- docs/content/guides/security/auth/extauth/passthrough_auth/_index.md
Backport sharing state and config docs
> Backport passthrough auth config doc

- .github/workflows/trivy-analysis.yaml
- Makefile
- changelog/v1.5.17/backport-trivy-workflow.yaml
Backport 1.5.x trivy scanner workflow.
> Backport trivy workflow 1.5

- changelog/v1.7.0-beta29/bump-solo-kit.yaml
- go.mod
- go.sum
Bump solo-kit dependency to point to a released version
> solo-kit:v0.18.2

- changelog/v1.7.0-beta30/bump-utility-deps.yaml
- go.mod
- go.sum
- projects/accesslogger/pkg/runner/run.go
- test/v1helpers/test_grpc_service/testgrpcservice.go
Upgrade internal utility libraries
> Upgrade go-utils and k8s-utils

- changelog/v1.7.0-beta31/bump-alpine.yaml
- docs/content/guides/security/tls/Dockerfile
- docs/examples/session-affinity/Dockerfile
- example/proxycontroller/Dockerfile
- jobs/certgen/cmd/Dockerfile
- projects/accesslogger/cmd/Dockerfile
- projects/discovery/cmd/Dockerfile
- projects/examples/services/sleeper/Dockerfile
- projects/gateway/cmd/Dockerfile
- projects/ingress/cmd/Dockerfile
- projects/sds/cmd/Dockerfile
bumping to latest alpine linux
> Bump alpine version

- Makefile
> Bump alpine

- changelog/v1.6.17/markdown-template-scan-report.yaml
- hack/utils/security_scan_report/markdown.tpl
Quick fix for: https://github.com/solo-io/gloo/issues/4453
> Markdown template

- changelog/v1.5.17/markdown-template-scan-report.yaml
- hack/utils/security_scan_report/markdown.tpl
> Markdown template backport 1.5

- changelog/v1.8.0-beta1/placeholder.yaml
> Add changelog

- docs/content/guides/security/auth/extauth/oauth/google/_index.md
> Update Google Oauth guide

- changelog/v1.8.0-beta4/fix-release-build.yaml
- cloudbuild.yaml
Add TAGGED_VERSION to the test step to fix the release build
> fix-release-build

- Makefile
- changelog/v1.6.23/bump-envoy-singleton-fix.yaml
Use solo-io/envoy-fork with bootstrap extension fix applied to 1.17
> bump envoy with singleton fix

- Makefile
- changelog/v1.8.0-beta10/bump-envoy-19.yaml
- changelog/v1.8.0-beta9/bump-envoy-19.yaml
> Bump envoy 1.19

- changelog/v1.6.24/fix-istio-mtls-sds-alpn.yaml
- projects/gloo/pkg/utils/ssl.go
Backport for: https://github.com/solo-io/gloo/pull/4647
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3994
> Fix: Istio mTLS not working in permissive mode (1.6)

- changelog/v1.7.5/fix-env-var-log-level.yaml
- docs/content/reference/values.txt
- go.mod
- go.sum
- install/helm/gloo/generate/values.go
Backport of https://github.com/solo-io/gloo/pull/4710
> Backport logger fix

- docs/content/guides/security/waf/_index.md
Docs to address: https://github.com/solo-io/gloo/issues/4671
> Add grpc section to waf docs

- changelog/v1.7.6/bump-jwt-go.yaml
- docs/content/guides/security/tls/Dockerfile
- docs/content/static/content/osa_provided.md
- docs/examples/session-affinity/Dockerfile
- example/proxycontroller/Dockerfile
- go.mod
- go.sum
- jobs/certgen/cmd/Dockerfile
- projects/accesslogger/cmd/Dockerfile
- projects/discovery/cmd/Dockerfile
- projects/examples/services/sleeper/Dockerfile
- projects/gateway/cmd/Dockerfile
- projects/ingress/cmd/Dockerfile
- projects/sds/cmd/Dockerfile
- test/e2e/aws_test.go
Backport: https://github.com/solo-io/gloo/pull/4723
> Bump alpine and jwt-go (#4723)

- changelog/v1.5.22/docker-compose-file-docs.yaml
- docs/content/installation/gateway/development/docker-compose-file/_index.md
- install/docker-compose-file/.gitignore
- install/docker-compose-file/data/config/gateways/gloo-system/gateway-proxy.yaml
- install/docker-compose-file/data/config/virtualservices/gloo-system/default.yaml
- install/docker-compose-file/data/envoy-config.yaml
- install/docker-compose-file/docker-compose.yaml
- install/docker-compose-file/prepare-directories.sh
Update the docker-compose-file docs to work with Gloo Edge 1.5
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4692
> Docker compose docs fix [1.5]

- changelog/v1.7.7/update-ipm.yaml
- docs/content/reference/cli/glooctl.md
- docs/content/reference/cli/glooctl_init-plugin-manager.md
- projects/gloo/cli/pkg/cmd/initpluginmanager/initpluginmanager.go
Backports the changes from https://github.com/solo-io/gloo/pull/4729
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4306
> Backport init-plugin-manager update

- changelog/v1.6.27/docker-compose-file-docs.yaml
- docs/content/installation/gateway/development/docker-compose-file/_index.md
- install/docker-compose-file/.gitignore
- install/docker-compose-file/data/config/gateways/gloo-system/gateway-proxy.yaml
- install/docker-compose-file/data/config/virtualservices/gloo-system/default.yaml
- install/docker-compose-file/data/envoy-config.yaml
- install/docker-compose-file/docker-compose.yaml
Update the docker-compose-file docs to work with Gloo Edge 1.6
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4692
> Docker compose docs fix [1.6]

- changelog/v1.7.7/docker-compose-file-docs.yaml
- docs/content/installation/gateway/development/docker-compose-file/_index.md
- docs/content/installation/glooctl_setup.md
- install/docker-compose-file/.gitignore
- install/docker-compose-file/data/config/gateways/gloo-system/gateway-proxy.yaml
- install/docker-compose-file/data/config/virtualservices/gloo-system/default.yaml
- install/docker-compose-file/data/envoy-config.yaml
- install/docker-compose-file/docker-compose.yaml
Update the docker-compose-file docs to work with Gloo Edge 1.7+
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4692
> Docker compose docs fix [1.7]

- changelog/v1.8.0-beta13/add-standard-deployment-k8s-fields.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/1-gloo-deployment.yaml
- install/helm/gloo/templates/10-ingress-deployment.yaml
- install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
- install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
- install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
- install/helm/gloo/templates/3-discovery-deployment.yaml
- install/helm/gloo/templates/5-gateway-deployment.yaml
- install/helm/gloo/templates/6-access-logger-deployment.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/templates/_helpers.tpl
- install/test/helm_test.go
Taking https://github.com/solo-io/gloo/pull/4484, https://github.com/solo-io/gloo/pull/4608, https://github.com/solo-io/gloo/pull/4607, https://github.com/solo-io/gloo/pull/2991 across the finish line.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1995
> Parametrize standard k8s values on Deployments and Jobs

- changelog/v1.8.0-beta15/helm-overrides.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4767
> fixed scoping on includes of enterprise named templates

- docs/content/reference/changelog/enterprise/_index.md
- docs/content/reference/changelog/open_source/_index.md
> Update page reference in open source and enterprise changelog pages

- docs/content/reference/changelog/enterprise/_index.md
- docs/content/reference/changelog/open_source/_index.md
> fixed docs

- changelog/v1.7.9/blank-changelog.yaml
> blank changelog

- changelog/v1.7.10/blank-changelog.yaml
- docs/content/reference/changelog/enterprise/_index.md
- docs/content/reference/changelog/open_source/_index.md
> Fix changelog docs 1.7

- changelog/v1.5.25/update-deps.yaml
- go.mod
- go.sum
- test/e2e/aws_test.go
Use form3tech-oss fork of jwt-go
> use jwt-go fork [1.5]

- .github/workflows/docs-gen.yaml
- .github/workflows/regression-tests-and-codegen.yaml
- .github/workflows/update-solo-apis.yaml
> free disk space in ci [1.7]

- .github/workflows/docs-gen.yaml
- .github/workflows/regression-tests-and-codegen.yaml
> free disk space in ci [1.6]

- .github/workflows/regression-tests-and-codegen.yaml
> free disk space in ci [1.5]

- .github/workflows/codegen.yaml
- .github/workflows/docs-gen.yaml
- .github/workflows/regression-tests.yaml
- .github/workflows/trivy-analysis-scheduled.yaml
- .github/workflows/update-solo-apis.yaml
> add a step to free disk space in ci

- docs/content/guides/traffic_management/request_processing/transformations/xslt_transformation/_index.md
> fix xslt guide

- changelog/v1.8.0-beta23/gloo-fed-docs.yaml
- docs/content/guides/gloo_federation/cluster_registration.md
- docs/content/guides/gloo_federation/federated_configuration.md
- docs/content/guides/gloo_federation/getting_started.md
- docs/content/guides/gloo_federation/multicluster_rbac.md
- docs/content/guides/gloo_federation/read_only_console.md
- docs/content/guides/gloo_federation/service_failover.md
- docs/content/installation/gloo_federation.md
Update gloo-fed installation docs to reflect glooctl and namespace changes.
> Gloo fed docs update

- changelog/v1.8.0-beta23/fix-docs-gen-ratelimit-issue.yaml
- docs/Makefile
- docs/cmd/generate_docs.go
- docs/content/reference/changelog/open_source/_index.md
- docs/content/static/content/osa_provided.md
- go.mod
- go.sum
> Cache Github releases during docgen

- docs/content/guides/gloo_federation/cluster_registration.md
- docs/content/guides/integrations/aws/_index.md
- docs/content/installation/advanced_configuration/extauth_custom_ca.md
- docs/content/installation/enterprise/_index.md
> fix cluster registration command for mac

- changelog/v1.7.12/fix-sec-scan.yaml
- changelog/v1.8.0-beta23/fix-sec-scan.yaml
- docs/cmd/securityscanutils/securityscan_utils.go
Backport
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4920
> 1.7 -- Fix `gloo-ee-envoy-wrapper` Security scan docs 

- docs/content/guides/security/waf/_index.md
A bit nitpicking, but use more inclusive language 
> chore: replace whitelist with allowlist

- docs/content/operations/upgrading/1.8.0.md
Add a note in upgrade guide about Gloo Fed cluster registration
> Add a note in upgrade guide about Gloo Fed cluster registration

- docs/content/operations/upgrading/1.8.0.md
> backport upgrade guide to 1.8

- docs/content/operations/upgrading/1.8.0.md
- docs/content/operations/upgrading/upgrade_steps.md
This PR fixes a couple of holes in the docs specific to 1.8.0 upgrades.
Closes #4951
> Fix 1.8.0 upgrade docs for new CRDs

- changelog/v1.8.1/proxy-service-extra-annotations.yaml
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/test/helm_test.go
Backport of: https://github.com/solo-io/gloo/pull/4953
> Do not mix extraAnnotations for gw-proxy service resources (#4953)

- .github/pull_request_template.md
- changelog/v1.9.0-beta3/pr-template.yaml
> update PR template

- test/README.md
- test/e2e/README.md
- test/kube2e/README.md
Update some of our test README's to make local development easier.
> Update Test READMEs

- .github/workflows/docs-gen-preview.yaml
skip the deploy to firebase step for community PRs
> docs gen preview: skip deploy to firebase for community PRs

- docs/content/installation/gateway/development/docker-compose-file/_index.md
- install/docker-compose-file/docker-compose.yaml
- install/docker-compose-file/prepare-directories.sh
> update docker-compose [1.8]

- docs/content/guides/traffic_management/destination_types/discovered_upstream/_index.md
- docs/content/installation/advanced_configuration/fds_mode.md
> docs: fix minor typo

- changelog/v1.8.2/fix-dup-route-names.yaml
- projects/gateway/pkg/translator/converter.go
- projects/gateway/pkg/translator/converter_test.go
- projects/gateway/pkg/translator/http.go
- projects/gateway/pkg/translator/tcp.go
- projects/gateway/pkg/translator/translator.go
- projects/gateway/pkg/translator/translator_test.go
backport of https://github.com/solo-io/gloo/pull/5029
> make route names more unique [1.8]

- changelog/v1.7.13/fix-dup-route-names.yaml
- projects/gateway/pkg/translator/converter.go
- projects/gateway/pkg/translator/converter_test.go
- projects/gateway/pkg/translator/http.go
- projects/gateway/pkg/translator/tcp.go
- projects/gateway/pkg/translator/translator.go
- projects/gateway/pkg/translator/translator_test.go
backport of https://github.com/solo-io/gloo/pull/5029
> make route names more unique [1.7]

- .github/workflows/regression-tests.yaml
- ci/deploy-to-kind-cluster.sh
- docs/content/installation/platform_configuration/cluster_setup.md
- hack/test.sh
- projects/gloo/cli/pkg/cmd/demo/federation.go
- test/kube2e/README.md
Backport of: https://github.com/solo-io/gloo/pull/5092
> Fix CI (1.8)

- changelog/v1.7.16/helm-gateway-options-fix.yaml
- install/helm/gloo/templates/8-default-gateways.yaml
Cherry-pick of https://github.com/solo-io/gloo/pull/5090
> Fix helm chart gatewaysettings options 1.7.x

- docs/content/guides/security/auth/extauth/ldap/_index.md
Ran through the guide, need this change for it to work
> Add scheme so LDAP guide works

- changelog/v1.9.0-beta9/fips-value.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
Add an entry in values.go for fips option for images.
> Fips installation option

- docs/active_versions.json
> Update docs active_versions

- .github/workflows/regression-tests-and-codegen.yaml
- docs/content/installation/platform_configuration/cluster_setup.md
- hack/test.sh
- projects/gloo/cli/pkg/cmd/demo/federation.go
> Fix ci (#5092)

- docs/content/installation/platform_configuration/cluster_setup.md
- hack/test.sh
- projects/gloo/cli/pkg/cmd/demo/federation.go
> Fix ci (#5092) v1.6

- changelog/v1.9.0-beta14/fips-install-docs.yaml
- docs/content/installation/advanced_configuration/fips.md
> Documentation for installing fips

- docs/content/guides/observability/prometheus/metrics.md
Follow up to https://github.com/solo-io/gloo/pull/5216, for https://github.com/solo-io/gloo/issues/5171
- N/A I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
> Edit note to show up

- Makefile
- changelog/v1.8.10/update-envoy.yaml
Update envoy-gloo to 1.19.0-patch2 for CVE-2021-32777, CVE-2021-32779, CVE-2021-32781, CVE-2021-32778, and CVE-2021-32780.
> [Gloo 1.8: Envoy 1.19] Update envoy dependency

- Makefile
- changelog/v1.7.20/update-envoy-dependency.yaml
Update envoy-gloo to  1.18.4-patch1 for CVE-2021-32777, CVE-2021-32779, CVE-2021-32781, CVE-2021-32778, and CVE-2021-32780.
> [Gloo 1.7: Envoy 1.18] Update envoy dependency

- changelog/v1.9.0-beta15/set-clusterspecifier.yaml
- projects/gloo/pkg/translator/route_config.go
- projects/gloo/pkg/translator/translator_test.go
This helps avoid potential NPEs.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5112
> Make sure clusterSpecifier always gets set during translation loop

- docs/active_versions.json
Bumping 1.8 docs version to latest.
> Bump latest doc version

- changelog/v1.8.17/duplicate-key-helm.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
Backporting https://github.com/solo-io/gloo/pull/5350
@sam-heilbron
> Backport helm fix #5350

- docs/content/guides/integrations/aws/_index.md
Fix typo in the ALBC target type annotation
> fix typo on the ALBC target type annotation

- docs/content/operations/production_deployment/_index.md
Move the "xDS-Relay" paragraph under "safeguarding the control-plane config"
Now looks like that:
--------
> doc - small reorg of the production deployment page

- changelog/v1.9.0-beta22/fix-glooctl-check-gloo-fed.yaml
- projects/gloo/cli/pkg/cmd/check/gloo_instances.go
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5386
> Fix typo in glooctl check

- docs/content/guides/traffic_management/request_processing/graphql/_index.md
Fix docs from https://www.apollographql.com/docs/intro/benefits/#graphql-provides-declarative-efficient-data-fetching
> Update graphql docs

- docs/content/operations/upgrading/1.9.0.md
Helm upgrade step was missing from 1.9 upgrade page
> Add upgrade step to 1.9.0 doc

- changelog/v1.10.0-beta5/tracing-docs-improvement.yaml
- docs/content/guides/observability/tracing.md
- docs/content/guides/traffic_management/listener_configuration/http_connection_manager.md
Formatting and clarification improvements for tracing docs
We found it difficult to navigate and use our documentation while working on #5368
> Tracing docs improvement

- changelog/v1.10.0-beta9/docs-openshift-fix.yaml
- docs/content/installation/enterprise/_index.md
- docs/content/installation/gateway/kubernetes/_index.md
- docs/content/installation/glooctl_setup.md
- docs/content/installation/platform_configuration/cluster_setup.md
Fixes OpenShift installation instructions.
- [N/A] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [N/A] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have added tests that prove my fix is effective or that my feature works
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5619
> Doc update for OpenShift installation settings

- projects/gloo/cli/pkg/cmd/create/upstream_test.go
> add test to demonstrate clone

- .gitignore
- changelog/v1.10.0-beta11/rt-route-replacement.yaml
- changelog/v1.9.6/route-table-selector-validation.yaml
- projects/gateway/pkg/translator/converter.go
- projects/gateway/pkg/translator/converter_test.go
- projects/gateway/pkg/translator/http.go
- projects/gateway/pkg/translator/merge_options.go
- projects/gateway/pkg/translator/merge_options_test.go
- projects/gateway/pkg/translator/translator.go
- projects/gateway/pkg/validation/validator.go
- projects/gateway/pkg/validation/validator_test.go
- test/kube2e/gateway/gateway_test.go
- test/samples/route_tables.go
- test/samples/sample_gloo_api_snapshot.go
Backport of https://github.com/solo-io/gloo/pull/5607 and https://github.com/solo-io/gloo/pull/5668
> Fix for rejected RT preventing updates [1.9]

- .gitignore
- changelog/v1.10.0-beta11/rt-route-replacement.yaml
- changelog/v1.8.24/route-table-selector-validation.yaml
- projects/gateway/pkg/translator/converter.go
- projects/gateway/pkg/translator/converter_test.go
- projects/gateway/pkg/translator/http.go
- projects/gateway/pkg/translator/merge_options.go
- projects/gateway/pkg/translator/merge_options_test.go
- projects/gateway/pkg/translator/translator.go
- projects/gateway/pkg/validation/validator.go
- projects/gateway/pkg/validation/validator_test.go
- test/kube2e/gateway/gateway_test.go
- test/samples/route_tables.go
- test/samples/sample_gloo_api_snapshot.go
> Fix for rejected RT preventing updates [1.8]

- .gitignore
- changelog/v1.10.0-beta11/rt-route-replacement.yaml
- changelog/v1.7.24/route-table-selector-validation.yaml
- projects/gateway/pkg/translator/converter.go
- projects/gateway/pkg/translator/converter_test.go
- projects/gateway/pkg/translator/merge_route_options.go
- projects/gateway/pkg/translator/merge_route_options_test.go
- projects/gateway/pkg/translator/translator.go
- projects/gateway/pkg/validation/validator.go
- projects/gateway/pkg/validation/validator_test.go
- test/kube2e/gateway/gateway_test.go
- test/samples/route_tables.go
- test/samples/sample_gloo_api_snapshot.go
> Fix for rejected RT preventing updates [1.7]

- Makefile
- changelog/v1.10.0-beta14/bump-envoy.yaml
> makefile: Bump envoy-gloo version to latest 1.19

- changelog/v1.10.0/release.yaml
Adds a changelog entry for the v1.10.0 release
> Add changelog entry for v1.10.0 release

- .github/ISSUE_TEMPLATE/BUG-ISSUE.yml
- .github/ISSUE_TEMPLATE/FEATURE-ISSUE.yml
Bump the version in the GH issue templates
> bump gloo edge versions

- changelog/v1.10.1/hybrid-gateway-panic.yaml
- projects/gloo/pkg/plugins/plugin_interface.go
- projects/gloo/pkg/plugins/registry/registry.go
- projects/gloo/pkg/translator/clusters.go
- projects/gloo/pkg/translator/endpoints.go
- projects/gloo/pkg/translator/filter_chain.go
- projects/gloo/pkg/translator/listener_subsystem.go
- projects/gloo/pkg/translator/route_config.go
- projects/gloo/pkg/translator/translator.go
- projects/gloo/pkg/translator/translator_test.go
Backport of: https://github.com/solo-io/gloo/pull/5786
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5785
> [1.10.x] Resolve HybridListener marshal panic (#5786)

- changelog/v1.11.0-beta7/hotfix-docs-gen.yaml
- docs/Makefile
- docs/build-docs.sh
- docs/content/reference/security-updates/enterprise/_index.md
- docs/content/reference/security-updates/open_source/_index.md
- docs/split-file-by-delimiter.sh
> feat(docs): split vulnerabillity scans to render in smaller chunks

- changelog/v1.11.0-beta9/clarify-admin-ui-installation.yaml
- docs/.gitignore
- docs/content/installation/enterprise/_index.md
update the doc on the installation of the admin UI
Doc only
> Doc - update the doc on the installation of the admin UI

- changelog/v1.10.6/fix-helm-indentation-https-gw.yaml
- changelog/v1.10.6/tls-secret-error-handling.yaml
- projects/gloo/pkg/translator/translator_test.go
- projects/gloo/pkg/utils/ssl.go
- projects/gloo/pkg/utils/ssl_test.go
- test/e2e/happypath_test.go
- test/samples/sample_gloo_api_snapshot.go
Backport https://github.com/solo-io/gloo/commit/ee2e1115631e36a6b6136101f5d330dde810be74 to v1.10.x
> Backport TLS Secret Validation to v1.10.x

- .github/ISSUE_TEMPLATE/FEATURE-ISSUE.yml
Updating Feature Request issue form to make version optional.
> Make version optional for feature request issues

- changelog/v1.10.10/fix-regex-route-short-circuiting.yaml
- projects/gateway/pkg/translator/http_translator.go
- projects/gateway/pkg/translator/http_translator_test.go
> fix regex route short circuiting check [1.10]

- changelog/v1.9.9/fix-regex-route-short-circuiting.yaml
- projects/gateway/pkg/translator/http.go
- projects/gateway/pkg/translator/translator_test.go
> fix regex route short circuiting check [1.9]

- changelog/v1.8.25/fix-regex-route-short-circuiting.yaml
- projects/gateway/pkg/translator/http.go
- projects/gateway/pkg/translator/translator_test.go
> fix regex route short circuiting check [1.8]

- Makefile
- changelog/v1.8.25/bump-envoy.yaml
Bump envoy gloo to 1.19.0-patch5
> Bump envoy gloo to 1.19.0-patch5

- Makefile
- changelog/v1.10.10/envoy-bump.yaml
> bump envoy-gloo to 1.20.0-patch4

- Makefile
- changelog/v1.9.9/envoy-bump.yaml
> [1.9] bump envoy-gloo to 1.20.0-patch4

- changelog/v1.10.12/fix-invalid-routes.yaml
- projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer.go
- projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer_test.go
- projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer.go
> Fix route replacement when service is missing [1.10]

- Makefile
- changelog/v1.10.17/bump-envoy.yaml
Aws sts race condition fix via envoy distroupdate
Should prevent intermittent 403
> makefile: Upgrade envoy-gloo version for aws fixes

- Makefile
- changelog/v1.8.26/docker-compose-repair.yaml
- install/docker-compose-file/docker-compose.yaml
* bump envoy version
related https://github.com/solo-io/gloo/issues/5980
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5980
> 8/feat(docker-compose): repair docker-compose launch script

- Makefile
- changelog/v1.9.10/docker-compose-repair.yaml
- install/docker-compose-file/docker-compose.yaml
* bump envoy version
related https://github.com/solo-io/gloo/issues/5980
> 9/feat(docker-compose): repair docker-compose launch script

- docs/content/guides/traffic_management/request_processing/append_remove_headers/_index.md
- projects/gloo/cli/pkg/printers/secret.go
- projects/gloo/pkg/api/converters/kube/header_secret.go
> docs/glooctl fixes for header secrets [1.10]

- Makefile
- changelog/v1.11.0-rc6/bump-envoy-1.21.yaml
Bump envoy version that we rely on to 1.21 from 1.20
> envoy: Bump to 1.21

- changelog/v1.10.20/doc-fixes.yaml
- docs/content/operations/upgrading/1.10.0.md
Small doc fixes for 1.10.x branch for the week of 04/04.
> Doc fixes 1.10.x

- changelog/v1.12.0-beta1/placeholder.yaml
Add placeholder for 1.12 changelog
> Add 1.12 placeholder

- changelog/v1.10.20/process-route-plugins-all-actions.yaml
- projects/gloo/pkg/plugins/basicroute/plugin.go
- projects/gloo/pkg/plugins/basicroute/plugin_test.go
- projects/gloo/pkg/translator/route_config.go
- projects/gloo/pkg/translator/translator_test.go
Backport https://github.com/solo-io/gloo/pull/6233 to v1.10.x
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5917
> v1.10.x: Process all route plugin config in direct and redirect actions

- changelog/v1.12.0-beta2/process-route-plugins-all-actions.yaml
- changelog/v1.9.12/process-route-plugins-all-actions.yaml
- projects/gloo/pkg/plugins/aws/plugin.go
- projects/gloo/pkg/plugins/azure/plugin.go
- projects/gloo/pkg/plugins/basicroute/plugin.go
- projects/gloo/pkg/plugins/basicroute/plugin_test.go
- projects/gloo/pkg/plugins/faultinjection/plugin.go
- projects/gloo/pkg/plugins/grpc/plugin.go
- projects/gloo/pkg/plugins/rest/rest.go
- projects/gloo/pkg/translator/route_config.go
- projects/gloo/pkg/translator/translator_test.go
Backport https://github.com/solo-io/gloo/pull/6233 to v1.9.x
>  v1.9.x: Process all route plugin config in direct and redirect actions

- changelog/v1.10.21/proxy-labels.yaml
- docs/content/guides/dev/example-proxy-controller.md
- projects/clusteringress/pkg/translator/translator_syncer.go
- projects/gateway/pkg/syncer/translator_syncer.go
- projects/ingress/pkg/translator/translator_syncer.go
Backporting to all LTS branches
BOT NOTES: 
resolves https://github.com/solo-io/solo-projects/issues/3380
> Backport to 1.10 Documentation for 'created-by' labels on proxies (#6254)

- changelog/v1.9.13/proxy-labels.yaml
- docs/content/guides/dev/example-proxy-controller.md
- projects/clusteringress/pkg/translator/translator_syncer.go
- projects/gateway/pkg/syncer/translator_syncer.go
- projects/ingress/pkg/translator/translator_syncer.go
Backporting this to all supported branches.
BOT NOTES: 
resolves https://github.com/solo-io/solo-projects/issues/3380
> Backport to 1.9 Documentation for 'created-by' labels on proxies (#6254)

- .github/ISSUE_TEMPLATE/BUG-ISSUE.yml
- .github/ISSUE_TEMPLATE/FEATURE-ISSUE.yml
update gloo edge versions in issue templates
> update gloo edge versions in issue templates

- changelog/v1.12.0-beta4/add-e2e-test-sanitizers.yaml
- test/kube2e/gateway/gateway_suite_test.go
- test/kube2e/gateway/robustness_test.go
Add k8s e2e test for https://github.com/solo-io/gloo/pull/6289#pullrequestreview-938372272 , basically equivalent to these steps: https://github.com/solo-io/gloo/issues/6115#issuecomment-1091856972
also ran the new test locally against gloo edge 1.12.0-beta2 and confirmed it fails before the changes aforementioned, and passes on version 1.12.0-beta3
> Add e2e test for sanitizers never error

- changelog/v1.11.5/datadog-and-prometheus-metrics.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
- install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
- install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
- install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
- install/helm/gloo/values-template.yaml
backport https://github.com/solo-io/gloo/pull/6306
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6272
> Additional helm configurable paths to envoy stats [1.11]

- changelog/v1.10.21/datadog-and-prometheus-metrics.yaml
- changelog/v1.12.0-beta4/datadog-and-prometheus-metrics.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
- install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
- install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
- install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
- install/helm/gloo/values-template.yaml
backport #6306
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6272
> Additional helm configurable paths to envoy stats [1.10]

- test/e2e/gateway_test.go
Reduce flakes in hybrid gateway tests, by ensuring that VirtualServices exist in the Snapshot, before Gateways are persisted.
Recent tests have been flaking with the following error:
```
Step #10 - "test": • Failure [1.041 seconds]
Step #10 - "test": Gateway in memory hybrid gateway http traffic ssl [It] should work with ssl if ssl config is present in matcher 
Step #10 - "test": /workspace/gloo/test/e2e/gateway_test.go:1086
Step #10 - "test": 
Step #10 - "test":   Unexpected error:
Step #10 - "test":       <*errors.resourceVersionErr | 0xc007236f80>: {
Step #10 - "test":           namespace: "gloo-system",
Step #10 - "test":           name: "gateway-proxy-hybrid",
Step #10 - "test":           given: "2",
Step #10 - "test":           expected: "3",
Step #10 - "test":       }
Step #10 - …
```
> Ensure Hybrid Gateway tests have VirtualService available

- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
docs updates that didn't make it into #6349
> helm docs updates

- .github/workflows/trivy-analysis-scheduled.yaml
- changelog/v1.12.0-beta13/go-utils-for-scans.yaml
- docs/cmd/securityscanutils/README.md
- go.mod
- go.sum
Bump go-utils to allow for cleaner security scans.
> mod: go-utils bump for scanning changes

- docs/content/introduction/architecture/_index.md
> fix broken xDS github link and point to correct new location

- changelog/v1.11.12/placeholder.yaml
> placeholder for 1.11.12

- docs/content/guides/observability/tracing.md
> fix-tracing

- docs/content/guides/observability/tracing.md
> Tracing fixes

- Makefile
- changelog/v1.11.14/envoy-cve-patch.yaml
> 11 | address 6.9 cve vulnerabilities

- Makefile
- changelog/v1.12.0-beta19/envoy-cve-patch.yaml
> master | address 6.9 cve vulnerabilities

- Makefile
- changelog/v1.10.27/envoy-cve-patch.yaml
> 10 | address 6.9 cve vulnerabilities

- changelog/v1.11.17/fix-validation-server-grpc-max-size-bytes.yaml
- docs/content/static/content/osa_provided.md
- go.mod
- go.sum
- projects/gateway/pkg/syncer/setup_syncer.go
- projects/gateway/pkg/translator/opts.go
- projects/gateway/pkg/validation/robust_client.go
- projects/gateway/pkg/validation/robust_client_test.go
- test/kube2e/gloo/setup_syncer_test.go
- test/services/gateway.go
> add MaxCallSendMsgSize option to Validate call (#6612)

- changelog/v1.11.20/helm-gateway-proxy-image.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
> Parameterize the gateway proxy sidecar image [1.11]

- docs/content/operations/production_deployment/_index.md
> add 'failurepolicy: Fail' to the production deployment tips

- changelog/v1.10.31/solo-kit-fixes.yaml
- go.mod
- go.sum
- projects/clusteringress/pkg/api/v1/translator_snapshot_emitter.sk.go
- projects/gateway/pkg/api/v1/api_snapshot_emitter.sk.go
- projects/gloo/pkg/api/v1/api_snapshot_emitter.sk.go
- projects/gloo/pkg/api/v1/discovery_snapshot_emitter.sk.go
- projects/gloo/pkg/api/v1/eds_snapshot_emitter.sk.go
- projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_snapshot_emitter.sk.go
- projects/gloo/pkg/api/v1/setup_snapshot_emitter.sk.go
- projects/ingress/pkg/api/v1/status_snapshot_emitter.sk.go
- projects/ingress/pkg/api/v1/translator_snapshot_emitter.sk.go
- projects/knative/pkg/api/v1/translator_snapshot_emitter.sk.go
Pull in the latest releases of solo-kit and go utils to get fixes for the snapshot emitter and logging endpoints.
> Dependency bumps for gloo v1.10

- changelog/v1.9.20/grpcmaxsize-default.yaml
- projects/gloo/pkg/syncer/setup/setup_syncer.go
> only set maxGrpcRecvSize if >= 0 (#6711)

- changelog/v1.10.32/handle-npe-markperfilerconfig.yaml
- projects/gloo/pkg/plugins/pluginutils/per_filter_config.go
- projects/gloo/pkg/plugins/pluginutils/per_filter_config_test.go
> v1.10.x - NPE

- changelog/v1.8.35/handle-npe-markperfilerconfig.yaml
- projects/gloo/pkg/plugins/pluginutils/per_filter_config.go
- projects/gloo/pkg/plugins/pluginutils/per_filter_config_test.go
> v1.8.x - NPE

- changelog/v1.11.24/fix-argo-hanging.yaml
- changelog/v1.11.24/http-connect-tls.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/5-resource-cleanup-job.yaml
- install/helm/gloo/templates/5-resource-migration-job.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/helm/gloo/values-template.yaml
Backport of https://github.com/solo-io/gloo/pull/6759
> helm: fix argocd hanging [1.11]

- changelog/v1.12.0-rc4/upgrade-docs-fixes.yaml
- changelog/v1.12.0-rc5/upgrade-docs-fixes.yaml
- docs/content/contributing/documentation/editing_locally.md
- docs/content/installation/enterprise/_index.md
- docs/content/installation/gateway/kubernetes/_index.md
- docs/content/installation/gloo_federation.md
- docs/content/installation/ingress/_index.md
- docs/content/operations/upgrading/v1.11.md
- docs/content/operations/upgrading/v1.12.md
- docs/content/static/content/upgrade-crd.md
- docs/content/static/content/upgrade-note.md
Add notes about helm changes, reapplying fed CRDs and re-registering clusters.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6732
> Upgrade doc fixes

- changelog/v1.10.34/sk-go-utils-bumps.yaml
- cloudbuild.yaml
- go.mod
- go.sum
- projects/gloo/api/external/solo/ratelimit/rate_limit_config.go
- projects/gloo/pkg/api/compress/compress.go
- projects/gloo/pkg/api/compress/compress_test.go
- test/kube2e/util.go
Updated solo-kit and go-utils to their latest versions
go-utils bump also fixes https://github.com/solo-io/go-utils/issues/475
Resolves https://github.com/solo-io/go-utils/pull/487 in v1.10.x
> v1.10.x: Solo-kit and go-utils update

- changelog/v1.12.0/placeholder.yaml
Prep 1.12.0
Add changelog directory for 1.12.0
> Placeholder changelog for 1.12.0

- changelog/v1.10.36/static-upstream-host-healthchecks.yaml
- projects/gloo/pkg/plugins/static/plugin.go
- projects/gloo/pkg/plugins/static/plugin_test.go
> 10 | fix(static/plugin.go): prevent auto-overwrite for host-level HC's

- changelog/v1.12.3/static-upstream-host-healthchecks.yaml
- projects/gloo/pkg/plugins/static/plugin.go
- projects/gloo/pkg/plugins/static/plugin_test.go
> 12 | fix(static/plugin.go): prevent auto-overwrite for host-level HC's

- changelog/v1.9.23/static-upstream-host-healthchecks.yaml
- projects/gloo/pkg/plugins/static/plugin.go
- projects/gloo/pkg/plugins/static/plugin_test.go
> 9 | fix(static/plugin.go): prevent auto-overwrite for host-level HC's

- changelog/v1.11.28/static-upstream-host-healthchecks.yaml
- projects/gloo/pkg/plugins/static/plugin.go
- projects/gloo/pkg/plugins/static/plugin_test.go
> 11 | fix(static/plugin.go): prevent auto-overwrite for host-level HC's

- changelog/v1.12.3/helm-job-customization.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/5-resource-cleanup-job.yaml
- install/helm/gloo/templates/5-resource-migration-job.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
Backport https://github.com/solo-io/gloo/pull/6902 and https://github.com/solo-io/gloo/pull/6822
BOT NOTES: 
> Helm customization for rollout/migration/cleanup jobs [1.12]

- changelog/v1.11.28/helm-job-customization.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/5-resource-cleanup-job.yaml
- install/helm/gloo/templates/5-resource-migration-job.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
Backport #6902 and #6822
BOT NOTES: 
> Helm customization for rollout/migration/cleanup jobs [1.11]

- changelog/v1.12.5/placeholder.yaml
Adding a changelog so we can re-release 1.12
> placeholder for release [1.12]

- changelog/v1.12.6/remove-default-activedeadline.yaml
- docs/content/reference/values.txt
- install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/5-resource-cleanup-job.yaml
- install/helm/gloo/templates/5-resource-migration-job.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
> Remove default activeDeadlineSeconds from jobs [1.12]

- changelog/v1.11.31/remove-default-activedeadline.yaml
- docs/content/reference/values.txt
- install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/5-resource-cleanup-job.yaml
- install/helm/gloo/templates/5-resource-migration-job.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
> Remove default activeDeadlineSeconds from jobs [1.11]

- changelog/v1.11.31/fix-fed-ns-check.yaml
- projects/gloo/cli/pkg/cmd/federation/register/register.go
> Fix namespace check when registering cluster [1.11]

- changelog/v1.12.7/fix-fed-ns-check.yaml
- projects/gloo/cli/pkg/cmd/federation/register/register.go
backport https://github.com/solo-io/gloo/pull/6962
> Fix namespace check when registering cluster [1.12]

- .github/ISSUE_TEMPLATE/BUG-ISSUE.yml
- .github/ISSUE_TEMPLATE/DOCS-ISSUE.yml
- .github/ISSUE_TEMPLATE/FEATURE-ISSUE.yml
> ISSUEFORM: Update for 1.12 release

- Makefile
- test/make/make_test.go
some of our tests don't work from a fork
> Update ci to pass from fork

- changelog/v1.12.9/vwh-accept-status-updates.yaml
- projects/gateway/pkg/services/k8sadmission/README.md
- projects/gateway/pkg/services/k8sadmission/validating_admission_webhook.go
- projects/gateway/pkg/services/k8sadmission/validating_admission_webhook_test.go
- test/kube2e/gateway/gateway_test.go
- test/kube2e/util.go
Backport of: https://github.com/solo-io/gloo/pull/7010
> [1.12]  Validation Webhook: Auto-Accept Status Updates

- changelog/v1.12.10/placeholder-gosum.yaml
> changelog: placeholder for release

- test/make/make_test.go
backport of https://github.com/solo-io/gloo/pull/7025
> Fix make tests for ci

- changelog/v1.9.25/placeholder.yaml
- changelog/v1.9.26/placeholder.yaml
Added a placeholder changelog in order to release 1.9.26.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6998
> 1.9.26 placeholder yaml

- changelog/v1.10.38/disable-istio-inject-jobs.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/test/helm_test.go
same changes as https://github.com/solo-io/gloo/pull/7082
> disable istio injection on jobs/cronjobs [1.10]

- changelog/v1.9.27/disable-istio-inject-jobs.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/test/helm_test.go
> disable istio injection on jobs [1.9]

- changelog/v1.11.36/cleanup-ignore-crd-errors.yaml
- install/helm/gloo/templates/5-resource-cleanup-job.yaml
> Fix gloo-resource-cleanup failure when CRD doesn't exist [1.11]

- Makefile
- changelog/v1.13.0-beta13/lambda-wrap.yaml
Bump envoy-gloo for new lambda features and fixes
> make: Update envoy version to 1.23.0-patch7

- Makefile
- changelog/v1.12.16/lambda-wrap.yaml
Bump envoy-gloo for new lambda features and fixes
> make: 1.12 Update envoy version to 1.23.0-patch7

- changelog/v1.12.20/placeholder.yaml
> changelog: Seems that 1.12.19 was previously tagged so push to 20

- changelog/v1.13.0-beta17/revert-breaking-api-change.yaml
- docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
- docs/data/ProtoMap.yaml
- install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
- projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
- projects/gloo/cli/pkg/cmd/create/authconfig/authconfig.go
- projects/gloo/cli/pkg/cmd/create/authconfig/authconfig_test.go
- projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
- projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
- projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
- projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Revert breaking changes in API definition introduced in https://github.com/solo-io/gloo/pull/6934
The previously removed fields have been added back, but currently do not affect anything under the hood.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7206
> Revert breaking api change

- Makefile
- changelog/v1.12.23/race-detector.yaml
- ci/extended-docker/extended-docker.sh
- projects/gloo/Dockerfile
We may do additional testing/optimizations on 1.12 and it will be helpful to have access to race detection images.
> Backport change to add targets for race images

- changelog/v1.12.25/truncate-status.yaml
- changelog/v1.13.0-beta19/truncate-status.yaml
- projects/gloo/pkg/api/external/solo/ratelimit/extensions.go
backport of https://github.com/solo-io/gloo/pull/7266
> Truncate rl status 1.12

- changelog/v1.13.0-beta19/helm-tweak.yaml
- install/helm/gloo/generate/values.go
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6581
> helm: standardized *Image as the default data type

- Makefile
- changelog/v1.12.29/base64_transformation_functions.yaml
- changelog/v1.13.0-beta20/base64_transformation_functions.yaml
- docs/content/guides/traffic_management/request_processing/transformations/_index.md
- docs/content/guides/traffic_management/request_processing/transformations/decode_and_modify_base64_headers/_index.md
- docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
- docs/content/static/content/setup_postman_echo.md
- projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
- projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
- test/e2e/staged_transformation_test.go
Backport #7255 to v1.12.x
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3597
> v1.12.x: Backport #7255 to add support for base64, substring Inja functions

- test/e2e/gateway_test.go
Backport a fix for another test flake
This was resolved on the main branch as part of: https://github.com/solo-io/gloo/pull/7327
Backporting this to 1.12 after encountering a test flake as part of https://github.com/solo-io/gloo/pull/7368
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=4a7df487-ace4-41c2-a2d6-385d0a09ac4c
I focused these two tests and ran them locally and they passed.
> [1.12] Deflake hybrid gateway e2e test

- changelog/v1.11.43/7096-downstream-protocol.yaml
- projects/gloo/pkg/plugins/protocoloptions/plugin.go
- projects/gloo/pkg/plugins/protocoloptions/plugin_test.go
- projects/gloo/pkg/plugins/upstreamconn/plugin.go
- projects/gloo/pkg/plugins/utils/httpprotocolhelpers/http1_utils.go
backport of https://github.com/solo-io/gloo/pull/7322
> 11/fix(Upstream): allow use_downstream_protocol when useHttp2 is set

- changelog/v1.13.0-beta26/cleanup-helm-tests.yaml
- test/kube2e/helm/helm_test.go
Combining helm tests to save compute time on prs
https://github.com/solo-io/solo-projects/issues/4246
> Helm cleanup

- changelog/v1.11.45/tunneling-upstream-tls.yaml
- projects/gloo/pkg/plugins/tunneling/plugin.go
- projects/gloo/pkg/plugins/tunneling/plugin_test.go
- test/e2e/http_tunneling_test.go
Backport of https://github.com/solo-io/gloo/pull/7397
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7313
> [1.11] Generate tunneling cluster once per upstream

- changelog/v1.12.35/tunneling-upstream-tls.yaml
- projects/gloo/pkg/plugins/tunneling/plugin.go
- projects/gloo/pkg/plugins/tunneling/plugin_test.go
- test/e2e/http_tunneling_test.go
Backport of https://github.com/solo-io/gloo/pull/7397
> [1.12] Generate tunneling cluster once per upstream

- changelog/v1.9.30/tunneling-upstream-tls.yaml
- projects/gloo/pkg/plugins/tunneling/tunneling.go
- projects/gloo/pkg/plugins/tunneling/tunneling_test.go
- test/e2e/http_tunneling_test.go
- test/v1helpers/test_upstream.go
Backport of https://github.com/solo-io/gloo/pull/7397
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7313
> [1.9] Generate tunneling cluster once per upstream

- projects/gloo/pkg/plugins/basicroute/plugin.go
base and max retry policy backoff CAN be equal
> removed the pesky alligator bracket

- docs/content/guides/dev/writing-upstream-plugins.md
> Docs upstream plugin

- docs/content/guides/dev/writing-upstream-plugins.md
backport of https://github.com/solo-io/gloo/pull/7443
> 12/Update writing-upstream-plugins.md

- docs/content/guides/dev/writing-upstream-plugins.md
backport of https://github.com/solo-io/gloo/pull/7443
> 10/Update writing-upstream-plugins.md

- docs/content/guides/dev/writing-upstream-plugins.md
backport of https://github.com/solo-io/gloo/pull/7443
> 9/Update writing-upstream-plugins.md

- changelog/v1.14.0-beta1/placeholder.yaml
Add 1.14 placeholder so that changelog-bot works
Without this, changelog-bot will fail
> Add 1.14.0-beta1 Changelog

- docs/content/guides/dev/writing-upstream-plugins.md
backport of https://github.com/solo-io/gloo/pull/7443
> 11/Update writing-upstream-plugins.md

- projects/gloo/cli/pkg/cmd/demo/federation.go
- test/kube2e/upgrade/upgrade_test.go
Previously tests would fail for the first release of a new minor
> Upgrade Tests: First patch of minor fix

- changelog/v1.12.38/skv2-bump.yaml
- go.mod
- go.sum
backport of https://github.com/solo-io/gloo/pull/7564
> upgrade skv2 for fed cluster reg fixes [1.12]

- ci/deploy-to-kind-cluster.sh
- docs/content/installation/platform_configuration/cluster_setup.md
missed one change from https://github.com/solo-io/gloo/pull/7571
> cluster config beta3

- .github/workflows/nightly-tests.yaml
- .github/workflows/regression-tests.yaml
- ci/deploy-to-kind-cluster.sh
- docs/content/installation/platform_configuration/cluster_setup.md
- hack/test.sh
- jobs/kubectl/Dockerfile
- projects/gloo/cli/pkg/cmd/demo/federation.go
- test/kube2e/README.md
- test/kube2e/helm/helm_test.go
more k8s 1.24 updates:
- ci
- docs
- kubectl image
> k8s 1.24 ci updates [1.13]

- .github/workflows/regression-tests.yaml
- changelog/v1.12.38/k8s-1.24.yaml
- ci/deploy-to-kind-cluster.sh
- docs/content/installation/platform_configuration/cluster_setup.md
- hack/test.sh
- jobs/kubectl/Dockerfile
- projects/gloo/cli/pkg/cmd/demo/federation.go
- test/kube2e/README.md
backport ci changes to support k8s 1.24
> use k8s 1.24 in ci [1.12]

- changelog/v1.13.1/extra-helm-containers.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/templates/_helpers.tpl
- install/test/helm_test.go
> v1.13-extra-containers

- docs/content/introduction/architecture/_index.md
- docs/content/introduction/architecture/concepts.md
- docs/content/introduction/architecture/custom_resources.md
- docs/content/introduction/architecture/deployment_arch.md
Fixing a couple of typos in the documentation
> fix typos in the docs

- changelog/v1.13.4/expose-kube-jobspec-fields.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/5-resource-cleanup-job.yaml
- install/helm/gloo/templates/5-resource-migration-job.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/templates/_helpers.tpl
- install/test/helm_test.go
Backport of https://github.com/solo-io/gloo/pull/7661 to v1.13
for issue
https://github.com/solo-io/gloo/issues/7112
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7112
> back port changes for issue 7112 to v1.13

- changelog/v1.12.42/expose-kube-jobspec-fields.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/5-resource-cleanup-job.yaml
- install/helm/gloo/templates/5-resource-migration-job.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/templates/_helpers.tpl
- install/test/helm_test.go
Backport of https://github.com/solo-io/gloo/pull/7661 to v1.12
for issue
https://github.com/solo-io/gloo/issues/7112
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7112
> back port changes for issue 7112 to v1.12

- changelog/v1.12.42/rollout-job-fix
- install/helm/gloo/templates/5-resource-configmap.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/test/helm_test.go
- test/kube2e/helm/helm_test.go
> Rollout job configmap [1.12]

- changelog/v1.11.50/rollout-job-fix
- install/helm/gloo/templates/5-resource-configmap.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/test/helm_test.go
- test/kube2e/helm/helm_test.go
> Rollout job configmap [1.11]

- changelog/v1.13.4/rollout-job-fix
- install/helm/gloo/templates/5-resource-configmap.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/test/helm_test.go
- test/kube2e/helm/helm_test.go
> Rollout job configmap [1.13]

- changelog/v1.12.42/goroutine-leak.yaml
- projects/gloo/cli/pkg/cmd/check/root.go
- test/kube2e/util.go
> fix glooctl goroutine leak [1.12]

- changelog/v1.11.50/goroutine-leak.yaml
- projects/gloo/cli/pkg/cmd/check/root.go
- test/kube2e/util.go
> fix glooctl goroutine leak [1.11]

- changelog/v1.11.52/fix-cloudbuild.yaml
- cloudbuild.yaml
same changes/rationale as #7832
> revert cloudbuild bumps [1.11]

- changelog/v1.14.0-beta16/alpine-bump.yaml
- projects/gloo/Dockerfile
Update gloo dockerfile. One of the missed alpine updates.
> gloo/docker: Missed alpine bump, now bumped

- .gitignore
- changelog/v1.12.48/reduce-dependency-footprint.yaml
- hack/dependency-hunter.py
- pkg/cliutil/install/kubernetes.go
- pkg/cliutil/testutil/testutil.go
- projects/gloo/cli/pkg/cmd/debug/debug_test.go
- projects/gloo/cli/pkg/cmd/install/knative.go
- projects/gloo/cli/pkg/cmd/install/uninstall_test.go
backport of https://github.com/solo-io/gloo/pull/7928
> 12/build(glooctl): removed ginkgo and gomega dependencies

- .gitignore
- changelog/v1.11.54/reduce-dependency-footprint.yaml
- hack/dependency-hunter.py
- pkg/cliutil/install/kubernetes.go
- pkg/cliutil/testutil/testutil.go
- projects/gloo/cli/pkg/cmd/debug/debug_test.go
- projects/gloo/cli/pkg/cmd/install/knative.go
- projects/gloo/cli/pkg/cmd/install/uninstall_test.go
backport of https://github.com/solo-io/gloo/pull/7928
> 11/build(glooctl): removed ginkgo and gomega dependencies

- .gitignore
- changelog/v1.13.10/reduce-dependency-footprint.yaml
- hack/dependency-hunter.py
- pkg/cliutil/install/kubernetes.go
- pkg/cliutil/testutil/testutil.go
- projects/gloo/cli/pkg/cmd/debug/debug_test.go
- projects/gloo/cli/pkg/cmd/install/knative.go
- projects/gloo/cli/pkg/cmd/install/uninstall_test.go
backport of https://github.com/solo-io/gloo/pull/7928
> 13/build(glooctl): removed ginkgo and gomega dependencies

- docs/content/guides/security/rate_limiting/simple/_index.md
- Update yaml keys from snake_case to camelCase
- Update bullet points to be the correct keywords
> Typo Fixes for RateLimitConfig in Security Docs

- changelog/v1.12.49/istio-plugin-speedup.yaml
- projects/gloo/pkg/plugins/istio_integration/istio_suite_test.go
- projects/gloo/pkg/plugins/istio_integration/plugin.go
- projects/gloo/pkg/plugins/istio_integration/plugin_test.go
- projects/gloo/pkg/plugins/registry/registry.go
> Improve istio plugin translation time [1.12]

- changelog/v1.13.11/istio-plugin-speedup.yaml
- projects/gloo/pkg/plugins/istio_integration/istio_suite_test.go
- projects/gloo/pkg/plugins/istio_integration/plugin.go
- projects/gloo/pkg/plugins/istio_integration/plugin_test.go
- projects/gloo/pkg/plugins/registry/registry.go
> Improve istio plugin translation time [1.13]

- Makefile
- changelog/v1.12.50/envoy-alpine-cve.yaml
- docs/content/guides/dev/writing_auth_plugins/_index.md
- docs/content/guides/security/tls/Dockerfile
- docs/examples/session-affinity/Dockerfile
- docs/examples/xslt-guide/Dockerfile
- example/proxycontroller/Dockerfile
- jobs/certgen/cmd/Dockerfile
- jobs/kubectl/Dockerfile
- projects/accesslogger/cmd/Dockerfile
- projects/discovery/cmd/Dockerfile
- projects/examples/services/sleeper/Dockerfile
- projects/gloo/Dockerfile
- projects/ingress/cmd/Dockerfile
- projects/sds/cmd/Dockerfile
Update envoy and alpine for upstream cves
BOT NOTES: 
resolves https://github.com/solo-io/envoy-gloo-ee/issues/543
resolves https://github.com/solo-io/gloo/issues/8039
> 1.12 make: Update envoy and alpine for cves

- Makefile
- changelog/v1.13.12/envoy-alpine-cve.yaml
- docs/content/guides/dev/writing_auth_plugins/_index.md
- docs/content/guides/security/tls/Dockerfile
- docs/examples/session-affinity/Dockerfile
- docs/examples/xslt-guide/Dockerfile
- example/proxycontroller/Dockerfile
- jobs/certgen/cmd/Dockerfile
- jobs/kubectl/Dockerfile
- projects/accesslogger/cmd/Dockerfile
- projects/discovery/cmd/Dockerfile
- projects/examples/services/sleeper/Dockerfile
- projects/gloo/Dockerfile
- projects/ingress/cmd/Dockerfile
- projects/sds/cmd/Dockerfile
Update envoy and alpine for cves found in scanners
BOT NOTES: 
resolves https://github.com/solo-io/envoy-gloo-ee/issues/543
resolves https://github.com/solo-io/gloo/issues/8039
> 1.13 make: Update envoy and alpine for cves

- docs/content/guides/security/access_logging/_index.md
Added a sample of how to enable File Based Standard logging(stdout/stderr)
#This bug fixes ... \ This new feature can be used to ...
Helps users add logging to a file, we only have docs for Access logging atm.
#Users ran into this bug doing ... \ Users needed this feature to ...
> Added File Based Standard Logging to docs.

- Makefile
Ensure that kind-reload always restarts the deployment
When you update the image and use the same image tag, the deployment spec doesn't change, and the new pods aren't rolled out.
This update annotates the pod template with a timestamp. This ensures that new pods will be rolled out, and it also makes developing easier because you can see on the pod when the last update was pulled in.
> Stability: Ensure kind-reload-% always updates deployment

- Makefile
- changelog/v1.13.16/bump-envoy-gloo-apr26.yaml
Bemp envoy-gloo to bring in April 26 FIPS compliance fix
> [1.13] bump envoy-gloo for april 26

- Makefile
- changelog/v1.12.53/bump-envoy-gloo-apr26.yaml
Bemp envoy-gloo to bring in April 26 FIPS compliance fix
> [1.12] bump envoy-gloo for april 26

- Makefile
- changelog/v1.15.0-beta5/bump-envoy-gloo-apr26.yaml
Bemp envoy-gloo to bring in April 26 FIPS compliance fix
> bump envoy-gloo for april 26

- changelog/v1.14.1/bump-bitnami-kubectl.yaml
- jobs/kubectl/Dockerfile
> [1.14] bump bitnami kubectl

- docs/content/guides/traffic_management/configuration_validation/admission_control.md
- docs/content/guides/traffic_management/destination_types/aws_lambda/cross-account.md
> Backport docs 1.14

- docs/content/guides/traffic_management/configuration_validation/admission_control.md
> Backport docs 1.13

- docs/content/guides/traffic_management/configuration_validation/admission_control.md
> Backport docs 1.12

- changelog/v1.14.6/webhook-skip-delete-validation.yaml
- docs/content/reference/values.txt
- docs/content/static/content/osa_provided.md
- go.mod
- go.sum
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
- install/helm/gloo/templates/_helpers.tpl
- install/test/5-gateway-validation-webhook-configuration_test.go
- install/test/helm_test.go
- pkg/utils/stringutils/stringutils.go
- pkg/utils/stringutils/stringutils_suite_test.go
- pkg/utils/stringutils/stringutils_test.go
Backport of https://github.com/solo-io/gloo/pull/8282
> V1.14.x webhook deletes

- .github/workflows/codegen.yaml
- .github/workflows/push-solo-apis-branch.yaml
- changelog/v1.13.20/arduino-dep-pin.yaml
Backport of https://github.com/solo-io/gloo/pull/8315
> v1.13 arduino-dep-pin

- changelog/v1.14.7/header-manipulation-validation.yaml
- docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/headers/headers.proto.sk.md
- projects/gloo/api/v1/options/headers/headers.proto
- projects/gloo/pkg/api/v1/options/headers/headers.pb.go
- projects/gloo/pkg/plugins/headers/plugin.go
- projects/gloo/pkg/plugins/headers/plugin_test.go
Backport of https://github.com/solo-io/gloo/pull/8326
> V1.14.x header validation manipulation

- changelog/v1.13.20/header-manipulation-validation.yaml
- docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/headers/headers.proto.sk.md
- projects/gloo/api/v1/options/headers/headers.proto
- projects/gloo/pkg/api/v1/options/headers/headers.pb.go
- projects/gloo/pkg/plugins/headers/plugin.go
- projects/gloo/pkg/plugins/headers/plugin_test.go
Backport of https://github.com/solo-io/gloo/pull/8326
> V1.13.x header manipulation validation

- changelog/v1.13.20/add-gwp-hpa-v2-support.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/8-gateway-proxy-horizontal-pod-autoscaler.yaml
- install/test/helm_test.go
- install/test/values/val_gwp_hpa_v2.yaml
Back-ports #7644 to 1.13
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7634
> Add support for GWP HPA autoscaling/V2

- changelog/v1.14.9/transformation-logging-global-settings-fix.yaml
- projects/gloo/pkg/plugins/transformation/plugin.go
- projects/gloo/pkg/plugins/transformation/plugin_test.go
- test/e2e/staged_transformation_test.go
> [v1.14.x] Fix Transformation Logging Global Setting

- changelog/v1.15.0-beta23/benchmark-matcher-tests.yaml
- test/gomega/matchers/benchmark_test.go
- Add unit tests for benchmark matchers
We have tests for our other matchers, so we should have tests for our benchmark matchers
The interesting percentile logic is [already tested](https://github.com/solo-io/gloo/blob/main/test/helpers/util_test.go) so these tests are quite simple
> Benchmark matcher tests

- changelog/v1.14.13/helm-gw-fix.yaml
- go.mod
- go.sum
- install/helm/gloo/templates/_8-default-gateways.tpl
- install/test/helm_suite_test.go
- install/test/helm_test.go
> helm test refactor and gw yaml fix [1.14]

- changelog/v1.13.23/helm-gw-fix.yaml
- go.mod
- go.sum
- install/helm/gloo/templates/_8-default-gateways.tpl
- install/test/helm_suite_test.go
- install/test/helm_test.go
backport https://github.com/solo-io/gloo/pull/8493
> helm test refactor and gw yaml fix [1.13]

- changelog/v1.15.0-beta25/deflake-connection-limit-e2e.yaml
- test/e2e/connection_limit_test.go
Fixes https://github.com/solo-io/gloo/issues/8531
https://github.com/solo-io/gloo/issues/8531
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8531
> Deflake connection limit e2e test

- changelog/v1.16.0-beta1/placeholder.yaml
Add changelog placeholder for 1.16
-
> 1.16 Placeholder

- .github/workflows/push-solo-apis-branch.yaml
- changelog/v1.15.0-rc4/rl-nil-checks.yaml
- changelog/v1.16.0-beta2/gha-fix.yaml
- projects/gloo/pkg/plugins/ratelimit/plugin.go
- projects/gloo/pkg/plugins/ratelimit/raw_util.go
- projects/gloo/pkg/plugins/ratelimit/raw_util_test.go
Original PRs: 
https://github.com/solo-io/gloo/pull/8575
https://github.com/solo-io/gloo/pull/8581/
> Backport fixes for missing fields in ratelimit configs and solo-apis PR action

- changelog/v1.15.2/call-set-logger.yaml
- docs/content/static/content/osa_provided.md
- go.mod
- go.sum
- pkg/utils/setuputils/main_setup.go
- projects/discovery/cmd/main.go
- projects/gloo/pkg/setup/setup.go
> Call SetLogger to prevent error logs [1.15]

- changelog/v1.13.26/fix-gateway-yaml.yaml
- go.mod
- go.sum
- install/helm/gloo/templates/_8-default-gateways.tpl
- install/test/helm_test.go
> Fix gateway yaml [1.13]

- install/helm/gloo/templates/_8-default-gateways.tpl
- install/test/helm_test.go
follow-up to https://github.com/solo-io/gloo/pull/8658, missed one
> fix failover gw

- changelog/v1.14.19/fix-gateway-yaml.yaml
- go.mod
- go.sum
- install/helm/gloo/templates/_8-default-gateways.tpl
- install/test/helm_test.go
> Fix gateway yaml [1.14]

- install/helm/gloo/templates/_8-default-gateways.tpl
- install/test/helm_test.go
> fix failover gw [1.13]

- changelog/v1.15.5/fix-failover-gw.yaml
- install/helm/gloo/templates/_8-default-gateways.tpl
- install/test/helm_test.go
backport https://github.com/solo-io/gloo/pull/8663
> fix failover gw [1.15]

- changelog/v1.15.5/doc-fixes.yaml
- changelog/v1.16.0-beta6/docs-tcp-connect
- docs/content/guides/security/limit-connection.md
- docs/content/guides/traffic_management/hello_world/_index.md
- docs/content/guides/traffic_management/listener_configuration/caching/_index.md
- docs/content/installation/enterprise/_index.md
- docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
- projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
- projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
> V1.15.x doc fixes

- changelog/v1.15.6/fix-helm-chart-hook-ttl.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/5-resource-cleanup-job.yaml
- install/helm/gloo/templates/5-resource-migration-job.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/templates/_helpers.tpl
- install/test/helm_test.go
Backport of #8601 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8500
> [1.15]: fix(helm): update chart hooks to allow for ttl on jobs when set (#8601)

- changelog/v1.14.20/fix-helm-chart-hook-ttl.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/5-resource-cleanup-job.yaml
- install/helm/gloo/templates/5-resource-migration-job.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/templates/_helpers.tpl
- install/test/helm_test.go
Backport of #8601 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8500
> [1.14]: fix(helm): update chart hooks to allow for ttl on jobs when set (#8601)

- changelog/v1.13.27/fix-helm-chart-hook-ttl.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/5-resource-cleanup-job.yaml
- install/helm/gloo/templates/5-resource-migration-job.yaml
- install/helm/gloo/templates/5-resource-rollout-job.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/templates/_helpers.tpl
- install/test/helm_test.go
Backport of #8601 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8500
> [1.13]: fix(helm): update chart hooks to allow for ttl on jobs when set (#8601)

- changelog/v1.16.0-beta16/docs-access-log-filter.yaml
- docs/content/guides/security/access_logging/_index.md
> Docs access log filter

- changelog/v1.16.0-beta16/fips-validation.yaml
- docs/content/installation/advanced_configuration/fips.md
Add user-facing documentation around FIPS validation
Enable users to follow the same steps that we take in CI
-
-
-
> Docs: FIPS Validation

- changelog/v1.14.26
- changelog/v1.14.26/renew-certs.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-cronjob.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
- jobs/certgen/cmd/main.go
- jobs/pkg/kube/secret.go
- jobs/pkg/kube/secret_test.go
- jobs/pkg/run/run.go
backport #8643
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5944
> Renew certs 1.14

- README.md
> Adding quickstart for Helm

- changelog/v1.16.0-beta27/doc-oidc-ms.yaml
- docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
- projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
- projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Part of https://github.com/solo-io/gloo-mesh-enterprise/issues/12078
Doc review of the Azure OIDC distributed claims proto fields.
> Doc updates for Azure OIDC distributed claims

- changelog/v1.16.0-beta27/docs-debug.yaml
- docs/content/operations/debugging_gloo/_index.md
> Docs: Debugging steps for data plane

- .github/workflows/static-analysis.yaml
- .golangci.yaml
- Makefile
- changelog/v1.17.0-beta2/linter-ginkgo-p2.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
- install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
- install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
- install/helm/gloo/templates/3-discovery-deployment.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_suite_test.go
- install/test/helm_test.go
- projects/gloo/cli/pkg/surveyutils/route_test.go
- projects/gloo/pkg/utils/aws/session_test.go
- test/kube2e/gateway/gateway_test.go
- test/kube2e/gateway/robustness_test.go
- test/kube2e/gloo/gloo_resources_test.go
Enable linting on tests as part of our CI check
We introduced a linter in: https://github.com/solo-io/gloo/pull/9005
There were known tests to not follow the lint requirements, so we ignored those in the first PR.
This PR aims to address those issues, fix the tests, and ensure that future commits all are required to fit the ginkgolinter standard.
Slack context: https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1703096096869749
We discovered that some tests weren't forming proper assertions against our helm templates, and fixing those assertions made us aware of an inconsistency in our templates.
Specifically, the tests which asserted that by default, we set `runAsUser` to `10101`, was broken for certain deployments. We opted to solve this minimally. The solution is self-explanatory.
We …
> Resolve Ginkgo Lint Errors

- docs/content/guides/security/rate_limiting/access_logs/_index.md
- docs/content/guides/traffic_management/request_processing/transformations/enrich_access_logs/_index.md
- docs/content/reference/support.md
- docs/content/support/about.md
* Update support.md
* rephrase distribution
* formatting
---------
- ...
- ...
- ...
- ...
This is a …
> Doc fixes 1.16

- docs/content/guides/security/rate_limiting/access_logs/_index.md
- docs/content/guides/traffic_management/request_processing/transformations/enrich_access_logs/_index.md
- docs/content/reference/support.md
weekly doc-fixes backport to 1.15
> Doc-fixes 1.15

- docs/content/guides/security/rate_limiting/access_logs/_index.md
- docs/content/guides/traffic_management/request_processing/transformations/enrich_access_logs/_index.md
- docs/content/reference/support.md
weekly doc-fixes backport to 1.13
> Doc fixes 1.13

- .githooks/pre-commit
- docs/content/guides/security/rate_limiting/access_logs/_index.md
- docs/content/guides/traffic_management/request_processing/transformations/enrich_access_logs/_index.md
- docs/content/reference/support.md
weekly doc-fixes backport to 1.14
> Doc fixes 1.14

- changelog/v1.17.0-beta5/docs-kick-off-1.16
- docs/content/guides/traffic_management/extproc/_index.md
> Kick off 1.16 doc build

- projects/gloo/pkg/translator/translator_test.go
The [translator tests](https://github.com/solo-io/gloo/blob/450739ee6726da0e2de503e7d8f59d3d321ce5c8/projects/gloo/pkg/translator/translator_test.go) fail locally (on a mac) when attempting to call the envoy binary for transformation validation:
```
[FAIL] Translator non route_routeaction routes [It] can process routeOptions properly
[FAIL] Translator non route_routeaction routes [It] does not affect envoy config when options only processed on routeActions are specified
```
To get around this, disable transformation validation, as we currently already do for the [e2e tests](https://github.com/solo-io/gloo/blob/450739ee6726da0e2de503e7d8f59d3d321ce5c8/test/services/gloo.go#L210)
This should be safe to do since the translator tests don't rely on transformation validation.
If testing for …
> disable transformation validation in translator test

- Makefile
- changelog/v1.15.23/envoy-gloo-cves.yaml
> [1.15] CVE 8feb24 patch

- Makefile
- changelog/v1.16.4/envoy-gloo-cves.yaml
> [1.16] CVE 8feb24 patch

- projects/gateway/pkg/validation/validator.go
Stop collecting errors and warnings separately for validation.
Merge target is feature branch
> (feature branch target) Sheidkamp/secret delete no warnings

- install/helm/gloo/templates/2-gloo-service.yaml
- install/helm/gloo/values-template.yaml
- projects/envoyinit/pkg/runner/run.go
- projects/gateway2/controller/controller.go
- projects/gateway2/controller/main.go
- projects/gateway2/deployer/builder.go
- projects/gateway2/deployer/deployer.go
- projects/gateway2/deployer/deployer_test.go
- projects/gateway2/examples/helm-install.yaml
- projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
- projects/gateway2/helm/gloo-gateway/values.yaml
- projects/gloo/pkg/bootstrap/opts.go
- projects/gloo/pkg/syncer/setup/setup_syncer.go
- projects/gloo/pkg/xds/cache.go
- projects/gloo/pkg/xds/cache_test.go
- projects/gloo/pkg/xds/node_hash.go
- projects/gloo/pkg/xds/node_hash_test.go
> gloo-gateway: re-use ControlPlane server and cache 

- .github/workflows/README.md
- .github/workflows/docs-gen.yaml
- .github/workflows/pr.yaml
- .github/workflows/regression-tests.yaml
- changelog/v1.17.0-beta9/update-pr-trigger.yaml
> Update github to trigger on ready for review

- .trivyignore
- changelog/v1.17.0-beta11/ignore-helm-bump.yaml
Updating Trivy ignore list because the impact of Helm upgrade is minimal, and does not impact the control and data planes of Gloo. Only glooctl can be impacted on installs / upgradese.
Fixes the CVEs in <=v1.15 in OSS and Enterprise :
https://github.com/solo-io/gloo/issues/9189
https://github.com/solo-io/gloo/issues/9187
https://github.com/solo-io/gloo/issues/9186
https://github.com/solo-io/solo-projects/issues/5822
https://github.com/solo-io/solo-projects/issues/5852
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/9186
> trivy: Ignore CVE-2024-26147 (helm)

- .github/ISSUE_TEMPLATE/DOCS-ISSUE.yml
- changelog/v1.17.0-beta14/docs-versions.yaml
Update docs issue template to reflect current beta and latest
> Update docs issue template for versions

- Makefile.ci
- changelog/v1.17.0-beta15/fix-glooctl-assets.yaml
Build glooctl assets with correct arch
`make build-cli` and run `file` on each output bin in `_output/glooctl*`
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/9295
> fix glooctl assets arch

- Makefile
- changelog/v1.17.0-beta16/distorless-comments.yaml
- projects/distroless/Dockerfile
- projects/envoyinit/cmd/Dockerfile.envoyinit.distroless
- projects/gloo/cmd/Dockerfile.distroless
- projects/sds/cmd/Dockerfile.distroless
Refactors the distroless dockerfiles adding comments about the files copied over from donor images as well as why they are needed
> Refactor distroless dockerfiles

- changelog/v1.15.25/doc-fixes.yaml
- docs/content/guides/integrations/service_mesh/istio.md
- docs/content/support/_index.md
- docs/content/support/about.md
- docs/content/support/support-info.md
- docs/content/support/support-ticket.md
> Doc fixes 1.15

- Makefile
- changelog/v1.17.0-beta16/envoy-sanitize-te-false.yaml
- changelog/v1.17.0-beta21/bump-envoy.yaml
- install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
- install/test/fixtures.go
- install/test/fixtures/envoy_config/bootstrap_extensions.yaml
- install/test/fixtures/envoy_config/custom_static_bootstrap.yaml
- install/test/fixtures/envoy_config/overload_manager.yaml
- install/test/fixtures/envoy_config/static_clusters.yaml
- install/test/fixtures/envoy_config/tcp_keepalive.yaml
- install/test/helm_test.go
Bump to the envoy-gloo which builds on the latest envoy v1.29.3
https://github.com/solo-io/solo-projects/issues/6008
> Bump envoy to 1.29.3-patch1

- Makefile
- changelog/v1.15.25/envoy-gloo-cves.yaml
- ci/cloudbuild/publish-artifacts.yaml
- ci/cloudbuild/run-tests.yaml
Description
Bumps envoy for upstream http2 cve continuation upstream changes.
> 1.15: Deps bump envoy and cloud builders

- changelog/v1.17.0-beta25/deleg-test-updates.yaml
- projects/gateway2/translator/gateway_translator_test.go
- test/kubernetes/e2e/features/route_delegation/suite.go
update translator test names and use WithHostHeader
> gateway2/delegation: update translator test names and use WithHostHeader

- changelog/v1.17.0-beta25/script-cleanup.yaml
- projects/gateway2/README.md
- projects/gateway2/install.sh
Update scripts that broke after recent changes (see [comment](https://github.com/solo-io/gloo/pull/9407#issuecomment-2088992740))
> update readme and install script

- changelog/v1.17.0-beta26/deleg-test-2.yaml
- projects/gateway2/translator/gateway_translator_test.go
- test/kubernetes/e2e/features/route_delegation/suite.go
Addresses follow-up changes suggested in 1c322ee25.
> gateway2/test: address follow-up changes from 1c322ee25

- Makefile
- changelog/v1.17.0-beta32/envoy-1.30-bump.yaml
envoy 1.30
Unblock common duration and several other features
> Envoy 1.30.bump

- changelog/v1.17.0-rc2/passthrough-json-to-proto.yaml
- projects/gloo/pkg/plugins/transformation/plugin.go
- projects/gloo/pkg/plugins/transformation/plugin_test.go
Pass through missed API value from transformation API.
> Ensure `json_to_proto` is passed through to envoy

- .github/workflows/regression-tests.yaml
Skip the Istio regression tests for now
- Skip the Istio regression tests
The Istio regression tests are failing as of #9582
See slack conversation [here](https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1718143649229349)
> skip istio regression tests

- changelog/v1.18.0-beta1/1-18-beta1.yaml
After cutting the 1.17.x LTS branch, create the placeholder changelog for the 1.18 beta releases
This is done as part of https://github.com/solo-io/solo-projects/issues/6264
-
-
-
> changelog: introduce 1.18 beta1 folder

- projects/gateway2/deployer/deployer_test.go
Stub a test for fully defined gwp to make sure we don't have any fields not being propagated without our intent/knowledge
> Test propagation of fully defined GatewayParameters

- changelog/v1.16.17/cve-24790.yaml
- ci/cloudbuild/publish-artifacts.yaml
- ci/cloudbuild/run-tests.yaml
- go.mod
- jobs/kubectl/Dockerfile
Bump pinned go version and bitnami/kubectl image to resolve CVEs
Routine Trivy scans identified CVE-2024-24790 in our images, with issues opened including #9669
I manually tested the latest released images as follows:
```
for service in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl; do trivy image --severity HIGH,CRITICAL "quay.io/solo-io/${service}:1.16.16"; done
```
<details>
<summary>
Results:
</summary>
```
2024-06-25T15:57:40-04:00	INFO	Vulnerability scanning is enabled
2024-06-25T15:57:40-04:00	INFO	Secret scanning is enabled
2024-06-25T15:57:40-04:00	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-06-25T15:57:40-04:00	INFO	Please see also https://aquasecurity.github.io/trivy/v0.52/docs/scanner/secret/#recommen …
```
> 1.16 - CVE bitnami/kubernetes and Go bump

- pkg/utils/kubeutils/kubectl/cli.go
- test/kubernetes/e2e/test.go
> test/kube: namespaces from kubectl

- Makefile
- changelog/v1.17.0/envoy-1.30.4.yaml
Update makefile with new envoy-gloo patch.
> make: bump envoy for 1.30.4

- changelog/v1.17.0/cors-regex-safety.yaml
- docs/content/guides/traffic_management/request_processing/transformations/_index.md
- pkg/utils/regexutils/regex.go
- projects/gloo/pkg/plugins/cors/plugin.go
- projects/gloo/pkg/plugins/cors/route_plugin_test.go
- projects/gloo/pkg/plugins/cors/vhost_plugin_test.go
Backport https://github.com/solo-io/gloo/pull/9735
Enforce cors regex validation
> 1.17: Fix/enforce regex inutils (#9735)

- changelog/v1.17.1/devmode-cancel-xds.yaml
- projects/gloo/pkg/syncer/envoy_translator_syncer.go
- projects/gloo/pkg/syncer/translator_syncer.go
- test/gomega/assertions/assertions_suite_test.go
- test/gomega/assertions/goroutines.go
- test/gomega/assertions/goroutines_test.go
- test/helpers/input_resources.go
- test/helpers/util.go
- test/helpers/util_test.go
- test/kube2e/helper/curl.go
- test/kube2e/helper/curl_test.go
Backports https://github.com/solo-io/gloo/pull/9771
> Backport 1.17: Test/xds snap ctx aware and leak detector (#9771)

- changelog/v1.17.1/docs-cloud-run.yaml
- docs/content/guides/traffic_management/destination_types/google-cloud-run.md
- docs/content/operations/upgrading/faq.md
From PR #9780
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/9474
> [v1.17.x] Backport Docs for Google Cloud Platform

- changelog/v1.17.1/glooctl-grpc-function-name-output.yaml
- projects/gloo/cli/pkg/cmd/create/upstream.go
- projects/gloo/cli/pkg/cmd/get/upstream.go
- projects/gloo/cli/pkg/common/create.go
- projects/gloo/cli/pkg/printers/upstream.go
- projects/gloo/cli/pkg/printers/upstream_test.go
> 1.17 - Glooctl grpc Upstream output in augmented status

- changelog/v1.18.0-beta11/deleg-fix-6621-2.yaml
- projects/gateway2/translator/gateway_translator_test.go
- projects/gateway2/translator/httproute/delegation_helpers.go
- projects/gateway2/translator/testutils/inputs/delegation/bug-6621.yaml
Resolves cosmetic comments from [739b0e950](https://github.com/solo-io/gloo/pull/9809)
> gateway2/delegation: resolve comments from 739b0e950

- changelog/v1.18.0-beta12/opentelemetry-status-code-documentation.yaml
- docs/content/guides/observability/tracing/otel.md
Explain how to interpret the opentelemetry status code in our user-facing documentation
> Update documentation with status code behaviour

- changelog/v1.18.0-beta12/remove-unneeded-cat.yaml
- docs/content/guides/dev/example-proxy-controller.txt
- docs/content/guides/graphql/getting_started/local_executor.md
- docs/content/guides/graphql/getting_started/remote_executor.md
- docs/content/guides/graphql/getting_started/secure_api.md
- docs/content/guides/graphql/getting_started/simple_discovery.md
- docs/content/guides/graphql/resolver_config.md
- docs/content/guides/integrations/cert_manager/_index.md
- docs/content/guides/integrations/ingress/_index.md
- docs/content/guides/security/csrf/_index.md
- docs/content/guides/security/rate_limiting/enterprise/_index.md
- docs/content/installation/advanced_configuration/session_affinity.md
- docs/content/installation/enterprise/_index.md
- docs/content/installation/gateway/kubernetes/_index.md
- docs/content/installation/platform_configuration/cluster_setup.md
- docs/content/installation/preparation.md
Removed [Useless use of cat](https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat) instances
> Remove unneeded cat calls from our docs

- .github/pull_request_template.md
- changelog/v1.18.0-beta16/update-pull-request-template.yaml
This commit updates the pull request template to improve the usability and clarity of the template. The changes involve converting the instructions and guidelines under each section into comment formatting (``).
This allows contributors to fill out the template without needing to delete instructional text, reducing friction and ensuring that the template remains clear and organized.
> .github: Update PR template to use comment formatting for instructions

- Makefile
- changelog/v1.18.0-beta17/update-conformance-project-name.yaml
Update the conformance project name to match the new project name.
Previously, the "gloo" project name was being used, which is inconsistent
our previous naming conventions.
See https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/reports/v1.0.0/gloo-gateway/v2.0.0-beta1-report.yaml#L9 for an example of a previously published conformance report.
> conformance: Specify 'gloo-gateway' as the project name

- .github/CODEOWNERS
- changelog/v1.18.0-beta17/exclude-generated-files-from-doc-codeowners.yaml
- docs/content/static/content/osa_provided.md
Exclude the generated osa_provided.md file from requiring approval from the doc codeowners. This file is updated anytime we modify the go.* dependencies.
> CODEOWNERS: Exclude generated osa_*.md files from docs group

- changelog/v1.18.0-beta17/docs-redirect-fixes.yaml
- docs/build-docs.sh
- docs/content/reference/support.md
> Doc redirect fixes

- changelog/v1.18.0-beta17/docs-redirects2.yaml
- docs/build-docs.sh
> Redirect fixes

- changelog/v1.18.0-beta17/doc-redirects2.yaml
- docs/build-docs.sh
> Docs redirects

- changelog/v1.14.32/doc-fixes.yaml
- docs/build-docs.sh
> Docs redirect 1.14

- changelog/v1.16.20/doc-redirects.yaml
- docs/build-docs.sh
> Docs redirect 1.16

- changelog/v1.15.31/doc-redirects.yaml
- docs/build-docs.sh
> Docs redirects 1.15

- changelog/v1.17.8/doc-backports1.yaml
- docs/content/guides/security/access_logging/_index.md
> Doc fixes 1.17

- changelog/v1.18.0-beta22/upgrade-go.yaml
- ci/cloudbuild/publish-artifacts.yaml
- ci/cloudbuild/run-tests.yaml
- cloudbuild-cache.yaml
- go.mod
Upgrade Go to 1.23.1
In https://github.com/solo-io/gloo/pull/10026 we attempted to do this in one large PR. We hit issues with some tests, and the easiest way to get to the bottom of those failures is to breakdown the changes into smaller PRs and merge them independently.
- All CI passes
> mod: upgrade go

- changelog/v1.17.8/new-fields-for-tap-filter.yaml
Fixed changelog for tap config backport
> Fixed changelog for tap config backport

- .github/workflows/composite-actions/kube-gateway-api-conformance-tests/action.yaml
- .github/workflows/conformance-tests.yaml
- .github/workflows/nightly-tests.yaml
- .github/workflows/regression-tests.yaml
- Makefile
- changelog/v1.18.0-beta23/support-gw-api-1.1-conformance.yaml
- changelog/v1.18.0-beta24/support-gw-api-1.1-conformance.yaml
- ci/kind/setup-kind.sh
- docs/content/static/content/osa_provided.md
- go.mod
- go.sum
Bump the sigs.k8s.io/gateway-api client and server versions to v1.1.0. This is the
initial step towards making Gloo conformant with the new(ish) OSS release.
In order to accomplish this, the existing conformance-related make targets needed
to be refactored:
- Reduces the length of the CONFORMANCE_ARGS variable. This helps
make the Makefile easier and more flexible for dev input.
- Removes the conformance-experimental target. This target is no
longer relevant as the v1.1 GW API release overhauled the
conformance suite and consolidated everything into a single
suite entrypoint.
Further work will be needed to add support for EndpointSlices to make Gloo fully
conformant with the 1.1 release. Without it, we're partially conformant as upstream
introduced a standard/core test that enforces …
> *: Bump the sigs.k8s.io/gateway-api dependency to v1.1.0

- .github/workflows/push-docs.yaml
- changelog/v1.17.11/doc-workflow-fix.yaml
Fixes an error in the push-docs workflow, after testing by calling it w a webhook from the solo-projects repo
> Docs workflow 1.17.x

- changelog/v1.18.0-beta25/issue_10115.yaml
- projects/gateway2/crds/gateway-crds.yaml
Updates the Gateway API CRDs yaml manifest from v1.0.0-rc1 to v1.0.0.
Fixes #10115
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/10115
> Updates Gateway API CRDs to v1.0.0

- projects/gloo/pkg/syncer/envoy_translator_syncer.go
- projects/gloo/pkg/translator/translator.go
> 1.17: add stopwatches for translator and envoy syncer (#10229)

- changelog/v1.17.16/glooctl-check-proxy-ns.yaml
- changelog/v1.18.0-beta31/glooctl-check-proxy-ns.yaml
- projects/gloo/cli/pkg/cmd/check/root.go
backport https://github.com/solo-io/gloo/pull/9939
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/9935
> glooctl: check only proxy ns [1.17]

- changelog/v1.18.0-beta34/exportto-destrule.yaml
- projects/gateway2/proxy_syncer/destrule.go
- projects/gateway2/proxy_syncer/upstreams.go
- projects/gateway2/setup/ggv2setup_test.go
- projects/gateway2/setup/testdata/failover-default-diffns-out.yaml
- projects/gateway2/setup/testdata/failover-default-diffns.yaml
- projects/gateway2/setup/testdata/failover.yaml
- projects/gateway2/setup/testdata/happypath.yaml
- projects/gateway2/setup/testdata/listeneropts.yaml
support destination rule export to field
> destinationrule: support exportTo

- changelog/v1.17.16/translator-stopwatches-1.17.x.yaml
Changelog entry to document [this pull request](https://github.com/solo-io/gloo/pull/10243) being merged into 1.17.x. That pull request lacked a changelog entry, so this pull request simply adds one for that work to support our version documentation.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/10278
> Translator stopwatches 1.17.x

- Makefile
Purges several Makefile targets that are no longer relevant. Quick follow-up to https://github.com/kgateway-dev/kgateway/pull/10514/.
Related to #10496.
> Makefile: Remove stale deploy targets

- .github/workflows/pr-unit-tests.yaml
- docs/content/static/content/osa_provided.md
- go.mod
- install/helm/gloo/templates/1-gloo-deployment.yaml
- install/helm/kgateway/templates/deployment.yaml
- pkg/utils/envoyutils/admincli/clusters.go
- pkg/utils/envoyutils/bootstrap/bootstrap_test.go
- pkg/utils/protoutils/utils.go
- pkg/utils/regexutils/regex.go
- projects/envoyinit/pkg/downward/transform.go
- projects/envoyinit/pkg/downward/transform_test.go
- projects/gateway2/endpoints/prioritize.go
- projects/gateway2/extensions2/plugins/istio/plugin.go
- projects/gateway2/extensions2/pluginutils/pluginutils.go
- projects/gateway2/plugins/stages.go
- projects/gateway2/translator/gateway/testutils/test_file_loader.go
- projects/gateway2/utils/any.go
> get rid of deprecated proto so we dont need GOLANG_PROTOBUF_REGISTRATION_CONFLICT

- .github/actions/kube-gateway-api-conformance-tests/action.yaml
- Tiltfile
- devel/tilt/tilt.md
- hack/kind/setup-kind.sh
- install/helm/kgateway/templates/deployment.yaml
- install/helm/kgateway/templates/gatewayparameters.yaml
- install/helm/kgateway/values.yaml
- internal/kgateway/krtcollections/setup.go
- internal/kgateway/translator/gateway/translator_case_test.go
- tilt-settings.yaml
made tilt work again. try it!
```
ctlptl create cluster kind --name kind-kgateway --registry=ctlptl-registry
VERSION=1.0.0-ci1 CLUSTER_NAME=kgateway IMAGE_VARIANT=standard make kind-build-and-load
tilt up
```
edit some code and save it; tilt should automatically update the deployment in the kind cluster
Also made tcprotues use a delayed informer so we will start if they are not there.
> dev: fix tilt.

- devel/architecture/istio-integration.md
- install/test/k8sgateway_test.go
- internal/kgateway/.gitignore
- internal/kgateway/README.md
- test/kubernetes/e2e/features/deployer/minimal_default_gatewayparameters_suite.go
- test/kubernetes/e2e/features/deployer/testdata/gateway-with-parameters.yaml
- test/kubernetes/e2e/features/deployer/testdata/gateway-without-parameters.yaml
- test/kubernetes/e2e/features/deployer/testdata/istio-gateway-parameters.yaml
- test/kubernetes/e2e/features/deployer/testdata/self-managed-gateway.yaml
- test/kubernetes/e2e/features/directresponse/testdata/gateway.yaml
- test/kubernetes/e2e/features/headless_svc/generate/generated_example/k8s_api.gen.yaml
- test/kubernetes/e2e/features/headless_svc/resources.go
- test/kubernetes/e2e/features/http_listener_options/testdata/gateway.yaml
- test/kubernetes/e2e/features/istio/testdata/k8s-routing-svc.yaml
- test/kubernetes/e2e/features/istio/testdata/k8s-routing-upstream.yaml
- test/kubernetes/e2e/features/listener_options/testdata/setup.yaml
- test/kubernetes/e2e/features/metrics/testdata/gateway-and-route-to-service.yaml
- test/kubernetes/e2e/features/metrics/testdata/gateway-and-route-to-upstream.yaml
- test/kubernetes/e2e/features/port_routing/testdata/gateway.yaml
- test/kubernetes/e2e/features/route_delegation/testdata/common.yaml
- test/kubernetes/e2e/features/route_delegation/testdata/invalid_child_valid_standalone.yaml
- test/kubernetes/e2e/features/route_options/testdata/setup.yaml
- test/kubernetes/e2e/features/services/httproute/testdata/route-with-service.yaml
- test/kubernetes/e2e/features/services/tcproute/testdata/cross-ns-gateway-and-client.yaml
- test/kubernetes/e2e/features/services/tcproute/testdata/cross-ns-no-refgrant-gateway-and-client.yaml
- test/kubernetes/e2e/features/services/tcproute/testdata/multi-listener-gateway-and-client.yaml
- test/kubernetes/e2e/features/services/tcproute/testdata/single-listener-gateway-and-client.yaml
- test/kubernetes/e2e/features/upstreams/inputs/route-with-upstream.yaml
- test/kubernetes/e2e/features/virtualhost_options/testdata/setup.yaml
- test/kubernetes/e2e/features/zero_downtime_rollout/testdata/route-with-service.yaml
Update the gatewayClassName in all tests to use `kgateway`
> update gatewayClassName used in tests

- internal/kgateway/krtcollections/uniqueclients_test.go
this commit will correctly assert the final state of UCCs being empty after all clients have disconnected
more fixes to this test are needed eventually to add tests for e.g. jitter
tested locally via:
```
% go test ./internal/kgateway/krtcollections/uniqueclients_test.go -count 2000 -failfast
ok  	command-line-arguments	68.877s
```
> fix ucc test flake

- go.mod
- hack/utils/oss_compliance/osa_included.md
- test/helpers/kube_dump.go
- test/testutils/requirements.go
it was only used in tests so minimal risk
fixes https://github.com/kgateway-dev/kgateway/issues/10643
> remove go multierror for stdlib. 

- internal/kgateway/extensions2/plugins/backend/plugin.go
- internal/kgateway/extensions2/plugins/directresponse/direct_response_plugin.go
- internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
- internal/kgateway/extensions2/plugins/listenerpolicy/listener_policy_plugin.go
- internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go
- internal/kgateway/ir/iface.go
- internal/kgateway/krtcollections/builtin.go
- internal/kgateway/translator/irtranslator/route.go
Also add UnimplementedProxyTranslationPass to allow plugins to embed and not need to update everytime a callback is added
> feat: add callback for route configurations.

- .golangci.yaml
- internal/kgateway/extensions2/plugins/backend/aws.go
- internal/kgateway/extensions2/plugins/istio/plugin.go
- internal/kgateway/proxy_syncer/xdswrapper.go
- internal/kgateway/proxy_syncer/xdswrapper_test.go
- internal/kgateway/translator/irtranslator/fc.go
- internal/kgateway/translator/utils/cluster.go
- pkg/utils/envoyutils/bootstrap/bootstrap.go
This PR has the following changes:
- Enable the forbidigo linter to prevent anypb.New usage
- *: Fix forbidigo linting violations
Related to #10720.
Closes #10693.
> *: Prevent anypb.New usage

- .github/workflows/release.yaml
There was an extra `kgateway-dev`
> Fix the release chart uri

- internal/kgateway/translator/irtranslator/route.go
Allow backend plugins for all backend types (not just Backend)
> route: don't use specific backend gvk here

- .github/actions/prep-go-runner/action.yaml
- .github/workflows/release.yaml
Call prep-go-runner which will clear out some disk space.
Latest run went from 21G -> 51G free
> Clear disk space before release

- .github/workflows/release.yaml
- .goreleaser.yaml
Update all references to new registry in release template
> fix release description

- internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go
- internal/kgateway/krtcollections/policy.go
- internal/kgateway/setup/setup_test.go
workaround https://github.com/istio/istio/issues/55503 by creating a spearte collection for policies target refs
added envtest that reproduced it.
> fix: policy extension ref updates

- Tiltfile
fix tilfile now that crds are separate chart
> Update Tiltfile for new crd chart

- internal/kgateway/deployer/merge_test.go
- internal/kgateway/deployer/values_helpers_test.go
Use stdlib testing instead of ginkgo. Related to #10831.
> deployer: Refactor several ginkgo unit tests

- .github/actions/kube-gateway-api-conformance-tests/action.yaml
This is no longer needed so lets remove it
> remove no longer needed logic per https://github.com/kgateway-dev/kgateway/pull/10861

- internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
Fixes godcs for inference extension EPP plugin.
cc: @lgadban
> Fixes epp plugin godocs

- internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster.go
- internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster_test.go
- internal/kgateway/extensions2/plugins/backend/plugin.go
- internal/kgateway/setup/testdata/ai-model-failover-out.yaml
- internal/kgateway/setup/testdata/ai-model-failover.yaml
- internal/kgateway/setup/testdata/ai-openai-moderation-promptguard-out.yaml
- Fixes missing secrets for Multi Pool AI backends
NONE
- Fixes plugin to use multi pool secret refs for MultiPool AI backends
NONE
NONE
Use the setup from the e2e tests:
```
k apply -f /Users/ninapolshakova/solo/kgateway/test/kubernetes/e2e/features/aiextension/testdata/routes-basic.yaml 
k apply -f /Users/ninapolshakova/solo/kgateway/test/kubernetes/e2e/features/aiextension/testdata/common.yaml 
```
Create secret:
```
kubectl create secret generic openai-secret -n ai-test \
--from-literal="Authorization=Bearer $OPENAI_API_KEY" \
--dry-run=client -oyaml | kubectl apply -f -
```
This backend config should now work: 
```
kubectl apply -f - <<EOF
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
labels:
app: kgateway
name: openai
namespace: ai-test
spec:
type: AI
ai: …
```
> Fix multi pool secrets

- install/helm/README.md
Quick cleanup PR to the nested helm README to reflect the current state.
> install/helm: Update README.md to reflect current state

- internal/kgateway/krtcollections/policy.go
reduce the chance of fetch cycles
> policies by GK

- api/v1alpha1/route_policy_types.go
- install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
- internal/kgateway/extensions2/plugins/routepolicy/local_rate_limit_plugin.go
- internal/kgateway/setup/testdata/local-rate-limit-route-disabled-out.yaml
- internal/kgateway/setup/testdata/local-rate-limit-route-disabled.yaml
- pkg/generated/openapi/zz_generated.openapi.go
- test/kubernetes/e2e/features/local_rate_limit/suite.go
- test/kubernetes/e2e/features/local_rate_limit/testdata/common.yaml
- test/kubernetes/e2e/features/local_rate_limit/testdata/extensionref-rl.yaml
- test/kubernetes/e2e/features/local_rate_limit/testdata/gw-local-rate-limit.yaml
- test/kubernetes/e2e/features/local_rate_limit/testdata/httproutes.yaml
- test/kubernetes/e2e/features/local_rate_limit/testdata/route-local-rate-limit-disabled.yaml
- test/kubernetes/e2e/features/local_rate_limit/testdata/route-local-rate-limit.yaml
- test/kubernetes/e2e/features/local_rate_limit/testdata/service.yaml
- test/kubernetes/e2e/features/local_rate_limit/types.go
- test/kubernetes/e2e/tests/kgateway_tests.go
This PR adds support for disabling a local rate limit on specific route by having empty local config:
```yaml
rateLimit:
local: {}
```
The PR also adds e2e tests that cover this PR feature as well as various scenarios of #10908
Resolves #10931
Resolves #10932
Resolves #10973
Change to allow empty `local` field in the `rateLimit` to disable.
If `local` is empty, we disable the local rate limit for the target by adding a local rate limit filter that has 0% enabled on requests. I.e. not rate limiting any request even if there is a higher level (GW) rate limit config.
This is also adding E2E tests to cover the various local rate limit scenario (including the disablement support in this PR).
Needs to be updated.
> Support disabling local rate limit + e2e tests

- internal/kgateway/controller/controller.go
- internal/kgateway/controller/gatewayclass_controller_test.go
- internal/kgateway/controller/start.go
Pulled out from the #10981.
Closes https://github.com/kgateway-dev/kgateway/issues/10974.
> controller: Use unique descriptions for the project's GatewayClasses

- internal/kgateway/controller/gatewayclass_controller_test.go
These tests were recently introduced with #10999 and flaked in https://github.com/kgateway-dev/kgateway/actions/runs/14202321897/job/39791902463?pr=11013.
The potential issue is that we check that the GCs are present in the cluster and then immediately
assert that the expected status condition types are present. This is problematic in the case that
the controller hasn't had the chance to update the provisioned GCs by the time the test assertions
are run. Instead, we can wrap the expected status condition type asserts in eventually handlers to
assert on the eventually consistent state.
> controller: Wait for expected GC status conditions to be present

- internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
- internal/kgateway/setup/testdata/inferencepool.yaml
- internal/kgateway/translator/httproute/translate_httproute_test.go
Backport of https://github.com/kgateway-dev/kgateway/pull/11035
> Removes port requirement from InferencePool backendRef (#11035)

- .github/actions/kube-gateway-api-conformance-tests/action.yaml
- .github/actions/kubernetes-e2e-tests/action.yaml
- .github/actions/performance-tests/action.yaml
- .github/actions/regression-tests/action.yaml
- .github/actions/upload-artifact/action.yaml
> Unique artifact names

- internal/kgateway/translator/irtranslator/route.go
> [v2.0.x] Timeout panic fix

- internal/kgateway/translator/irtranslator/route.go
Fixes https://github.com/kgateway-dev/kgateway/issues/11044
> nil check when applying timeout

- .github/workflows/pr-kubernetes-tests.yaml
- test/gomega/matchers/pod.go
- test/kubernetes/testutils/assertions/pods.go
backport https://github.com/kgateway-dev/kgateway/pull/11056
> [v2.0.x] e2e: check pods ready

- api/v1alpha1/gateway_parameters_types.go
- install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
> [v2.0.x] update gatewayparameters validation message

- internal/kgateway/extensions2/plugins/routepolicy/ai_policy.go
- internal/kgateway/setup/testdata/ai-anthropic-passthrough-out.yaml
- internal/kgateway/setup/testdata/ai-anthropic-passthrough.yaml
Fix a small bug in the override logic in the FieldDefaults feature.
NONE 
Small fix in ai policy plugin for default field logic
NONE
NONE
N/A
NONE
Confirmed with unit tests
N/A
> Fix AI policy field defaults bug

- .golangci.yaml
- internal/kgateway/admin/xds_snapshot.go
- internal/kgateway/extensions2/common/collections.go
- internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
- internal/kgateway/extensions2/plugins/routepolicy/extauth_policy.go
- internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go
- internal/kgateway/extensions2/plugins/sandwich/plugin.go
- internal/kgateway/extensions2/plugins/waypoint/waypointquery/service_model.go
- internal/kgateway/krtcollections/builtin.go
- internal/kgateway/krtcollections/endpoints_test.go
- internal/kgateway/krtcollections/pods_test.go
- internal/kgateway/query/query.go
- internal/kgateway/query/query_test.go
- test/kubernetes/e2e/features/extauth/suite.go
- test/kubernetes/e2e/features/transformation/suite.go
add linter to prevent duplicate imports
Signed-off-by: omar <omar.hammami@solo.io>
> remove duplicate imports and add linter

- test/kubernetes/e2e/defaults/testdata/nginx_pod.yaml
- test/kubernetes/e2e/features/services/httproute/suite.go
- test/kubernetes/e2e/features/services/httproute/testdata/route-with-service.yaml
- test/kubernetes/e2e/features/services/httproute/types.go
- test/kubernetes/e2e/tests/kgateway_test.go
> fix service routing test flakes

- install/helm/kgateway/templates/serviceaccount.yaml
> Use (hardcoded) ClusterRole name in binding

- internal/envoyinit/rustformations/src/http_simple_mutations.rs
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
I was working on implementing a Rust lint target here: https://github.com/kgateway-dev/kgateway/pull/11135
and found some lint errors, and separately fixed them in this PR.
Ran:
```shell
cargo fmt
cargo clippy --fix
```
and accepted the code changes.
Fixes warnings found when running:
```shell
cargo fmt --check
cargo clippy --all-targets -- -D warnings
```
> Fix rustfmt and clippy lint issues

- api/applyconfiguration/api/v1alpha1/extauthpolicy.go
- api/applyconfiguration/api/v1alpha1/extprocpolicy.go
- api/applyconfiguration/internal/internal.go
- api/v1alpha1/ext_proc_types.go
- api/v1alpha1/traffic_policy_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
- internal/kgateway/extensions2/plugin/plugin.go
- internal/kgateway/extensions2/plugins/routepolicy/ai_policy.go
- internal/kgateway/extensions2/plugins/routepolicy/ai_policy_test.go
- internal/kgateway/extensions2/plugins/routepolicy/extauth_policy.go
- internal/kgateway/extensions2/plugins/routepolicy/extauth_policy_test.go
- internal/kgateway/extensions2/plugins/routepolicy/extproc_policy.go
- internal/kgateway/extensions2/plugins/routepolicy/extproc_policy_test.go
- internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go
- internal/kgateway/ir/gw.go
- internal/kgateway/setup/testdata/extauth-gw-and-route-disable-out.yaml
- internal/kgateway/setup/testdata/extauth-gw-and-route-out.yaml
- internal/kgateway/setup/testdata/extauth-gw-only-out.yaml
- internal/kgateway/setup/testdata/extauth-route-only-out.yaml
- internal/kgateway/setup/testdata/extproc-backend-extref-out.yaml
- internal/kgateway/setup/testdata/extproc-routerule-out.yaml
- internal/kgateway/setup/testdata/extproc-targetref-out.yaml
- internal/kgateway/setup/testdata/failover-default-diffns-out.yaml
- internal/kgateway/setup/testdata/failover-out.yaml
- internal/kgateway/translator/gateway/testutils/outputs/delegation/traffic_policy_filter_override_merge.yaml
- internal/kgateway/translator/gateway/testutils/outputs/delegation/traffic_policy_multi_level_inheritance_override_ok.yaml
- pkg/generated/openapi/zz_generated.openapi.go
> fix ext-auth api: remove listener level fields

- examples/waypoint/README.md
Minor adjustment to the waypoint docs
n/a
n/a
n/a
- don't recommend 1.23 for ambient, it's buggy
- also minor md/spelling fixes
Was researching kgw waypoint and found we implicitly recommend 1.23 as OK for ambient. It's really not a good idea though since 1.23 is pre-release for the ambient feature. 1.24 is the GA for ambient mode and I think it should be our minimum recommendation.
> Waypoint Docs Update

- README.md
take some kgateway.dev front page updates and put them in the README.
> update README to include social accounts and highlight new features

- install/helm/kgateway/templates/deployment.yaml
This replica count value is under the controller in values.yaml.
```
controller:
replicaCount: 1
```
> fix: use correct controller replica count in deployment.yaml

- test/helpers/kube_dump.go
Updated the "kube dump on fail" used in e2e tests:
- updated solo/gloo references to kgateway
- updated list of resources to dump
- update the proxy label query (thanks to https://github.com/kgateway-dev/kgateway/pull/11241)
Fixes #10592
```
/kind cleanup
```
```release-note
NONE
```
> update kube dump on fail

- internal/kgateway/extensions2/plugins/waypoint/testdata/input/authz-gateway-ref-fakegw.yaml
- internal/kgateway/extensions2/plugins/waypoint/testdata/input/authz-gateway-ref.yaml
- internal/kgateway/extensions2/plugins/waypoint/testdata/input/authz-gatewayclass-ref-nonrootns.yaml
- internal/kgateway/extensions2/plugins/waypoint/testdata/input/authz-gatewayclass-ref.yaml
- internal/kgateway/extensions2/plugins/waypoint/testdata/input/authz-multi-service.yaml
- internal/kgateway/extensions2/plugins/waypoint/testdata/input/authz.yaml
- internal/kgateway/extensions2/plugins/waypoint/testdata/input/httproute-gateway.yaml
- internal/kgateway/extensions2/plugins/waypoint/testdata/input/httproute-svc.yaml
- internal/kgateway/extensions2/plugins/waypoint/testdata/input/ns-use-waypoint.yaml
this is a cosmetic change as selector is ignored by Waypoint tests
/kind cleanup
```release-note
NONE
```
> Fix typo in Waypoint Test yamls

- Makefile
Add a new Makefile target that provides a single entrypoint for bootstrapping a dev environment.
/kind cleanup
```release-note
NONE
```
> Makefile: Add run target to automate dev environment setup

- internal/kgateway/controller/gw_controller.go
Signed-off-by: Steven Landow <steven.landow@solo.io>
Addresses in the Spec should be surfaced in Status. Istio actually expects this for Waypoints
https://github.com/istio/istio/blob/7864675acb6d8da0d321f216d8f9e788bcea5aca/pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go#L248
```go
if len(gateway.Status.Addresses) == 0 {
// gateway.Status.Addresses should only be populated once the Waypoint's deployment has at least 1 ready pod, it should never be removed after going ready
// ignore Kubernetes Gateways which aren't waypoints
return nil
}
```
Eventually should adhere to that readiness bit as well. But this unblocks the ability to do self-managed waypoints (see [slack convo](https://cloud-native.slack.com/archives/C080D3PJMS4/p1748531641563139))
/kind bug_fix
```release-note …
```
> copy spec addresses to status

- internal/kgateway/extensions2/plugins/backend/plugin.go
- internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
- internal/kgateway/extensions2/plugins/kubernetes/k8s.go
- internal/kgateway/extensions2/plugins/serviceentry/backends.go
- internal/kgateway/krtcollections/endpoints_test.go
- internal/kgateway/krtcollections/grpc_route_test.go
- internal/kgateway/krtcollections/policy_test.go
- pkg/pluginsdk/ir/backend.go
- test/translator/test.go
Optimize things we saw in pprof.
Part of https://github.com/kgateway-dev/kgateway/issues/11293
```
/kind cleanup
```
-->
-->
```release-note
NONE
```
Should be no-op
> calculate backend name on ctor

- install/helm/kgateway/values.yaml
Signed-off-by: Hanh Vu <hanh.vu@solo.io>
- **Motivation:** provide quick access to relevant documentation on Inference extension
- **What changed:** 1 new line of comment in values.yml file
- **Related issues:** fixes https://github.com/kgateway-dev/kgateway/issues/11332
```release-note
NONE
```
> Docs: Added link to documentation on Inference Extension. 

- internal/kgateway/krtcollections/policy.go
- internal/kgateway/translator/gateway/gateway_translator_test.go
- internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/generation.yaml
- internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/generation.yaml
- internal/kgateway/translator/irtranslator/policy.go
- pkg/pluginsdk/reporter/types.go
- test/kubernetes/e2e/features/backendtls/suite.go
- test/kubernetes/e2e/features/transformation/suite.go
Set the observed generation status condition field for policy custom resources. Fixes #11386.
/kind fix
```release-note
NONE
```
> Set observed generation for policy status

- test/kubernetes/e2e/debugging.md
```
```
```release-note
NONE
```
> docs: enhance debugging guide with Tilt setup and usage instructions

- api/v1alpha1/backend_types.go
- design/10573.md
- pkg/generated/openapi/zz_generated.openapi.go
Clarifies the authentication method when no Auth is explicitly configured.
```
/kind cleanup
```
```release-note
None
```
> api/aws: clarify implicit authentication method

- internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
- internal/kgateway/extensions2/plugins/backendconfigpolicy/protocoloptions.go
/kind cleanup
```release-note
NONE
```
> refactor: Extract HTTP protocol options handling into separate file

- .github/workflows/action_lint.yaml
- .github/workflows/conformance-tests.yaml
- .github/workflows/lint-helm.yaml
- .github/workflows/lint-python.yaml
- .github/workflows/lint-rust.yaml
- .github/workflows/nightly-tests.yaml
- .github/workflows/pr-kubernetes-tests.yaml
- .github/workflows/pr-unit-tests.yaml
- .github/workflows/regression-tests.yaml
- .github/workflows/static-analysis.yaml
cancel existing workflow builds before runnning new
/kind cleanup
```release-note
NONE
```
> cancel existing builds before running new

- Makefile
Remove several stale or unused Makefile targets. A follow-up to the #11487 and #11434 PRs.
/kind cleanup
```release-note
NONE
```
> Makefile: Remove unused targets

- examples/plugin/main.go
- internal/kgateway/agentgatewaysyncer/syncer.go
- internal/kgateway/controller/controller.go
- internal/kgateway/controller/controller_suite_test.go
- internal/kgateway/controller/start.go
- internal/kgateway/deployer/gateway_parameters.go
- internal/kgateway/deployer/gateway_parameters_test.go
- internal/kgateway/extensions2/plugins/waypoint/plugin.go
- internal/kgateway/extensions2/registry/registry.go
- internal/kgateway/proxy_syncer/proxy_syncer.go
- internal/kgateway/reports/reporter_test.go
- internal/kgateway/setup/setup.go
- internal/kgateway/translator/gateway/gateway_translator_test.go
- internal/kgateway/translator/httproute/translate_httproute_test.go
- internal/kgateway/wellknown/controller.go
- pkg/deployer/deployer_test.go
- pkg/deployer/gateway_parameters.go
- pkg/setup/setup.go
- test/envtestutil/util.go
- test/translator/test.go
Refactor to use names from startup config
/kind cleanup
```release-note
NONE
```
Resolve #11509
> Refactor to use names from startup config

- api/v1alpha1/traffic_policy_types.go
- install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
- internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/buffer-gateway.yaml
- internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/buffer-route.yaml
add validation to ensure maxRequestSize is greater than 0.
fixes https://github.com/kgateway-dev/kgateway/issues/11561
also update test files to use string for maxRequestSize (otherwise cel validation fails). 
```
/kind bug_fix
```
```release-note
add validation to ensure maxRequestSize is greater than 0
```
> update validation for maxRequestSize in traffic policy

- cmd/sds/main.go
- internal/sds/pkg/run/run.go
- internal/sds/pkg/run/run_e2e_test.go
- pkg/sds/run.go
Refactor sds component so the run function is available in `pkg` for consistency with envoyinit.
/kind cleanup
```release-note
NONE
```
NONE
> refactor sds component

- internal/kgateway/controller/start.go
- pkg/logging/level.go
https://github.com/kgateway-dev/kgateway/issues/11691
- use lower case for log level
- use JSON format for krt logs to be consistent
with this change logs are now all json 
/kind bug_fix
```release-note
use lower case for log level and use JSON format for krt logs to be consistent
```
> logging fixes

- internal/kgateway/proxy_syncer/xdswrapper.go
- internal/kgateway/proxy_syncer/xdswrapper_test.go
Small bugfix for xds debug interface
```
/kind bug_fix
```
-->
```release-note
NONE
```
> fix: failed redact

- test/kubernetes/e2e/features/backendconfigpolicy/suite.go
The call to AssertEnvoyAdminApi was failing. Moved it into an Eventually
Fixes https://github.com/kgateway-dev/kgateway/issues/11909
/kind flake
```release-note
NONE
```
> Fix BackendConfigPolicy e2e flake

- internal/kgateway/helm/kgateway/templates/gateway/agent-gateway-deployment.yaml
A concise explanation of the change. You may include:
- **Motivation:** This PR is needed to add pod tolerations for agent gateway deployment template so that developers can deploy these pods with any tainted noded
- **What changed:** Added  a snippet for tolerations in agent-deployment.yaml template
Select one or more of the following by including the corresponding slash-command:
```
/kind bug_fix
```
```release-note
NONE
```
> Added tolerations for agent gateway deployment template

- go.mod
- hack/utils/applier/go.mod
- hack/utils/applier/go.sum
- test/mocks/mock-ai-provider-server/go.mod
- **Motivation:** Upgrade to the latest go version to receive software patches.
```
/kind cleanup
```
```release-note
NONE
```
> upgrade to go 1.24.6

- internal/kgateway/extensions2/plugins/backend/agentgateway/translate.go
Before we were overriding the filter instead of composing them
/kind bug_fix
```release-note
NONE
```
> agentgateway: fix MCP backend filter

- internal/kgateway/agentgatewaysyncer/README.md
Small README update to add bedrock example. 
```
```
```release-note
NONE
```
> Add bedrock example

- test/kubernetes/e2e/features/csrf/suite.go
- **What changed:** Adds wait for gateway and httproutes in csrf suite to be accepted
- **Related issues:** Fixes: https://github.com/kgateway-dev/kgateway/issues/11986
```
/kind flake
```
```release-note
NONE
```
> flake: add assertions gw and httproute accepted

- internal/kgateway/extensions2/plugins/backend/agentgateway/translate_test.go
Fixes https://github.com/kgateway-dev/kgateway/issues/11997
```
/kind flake
```
```release-note
NONE
```
```
go test -v ./internal/kgateway/extensions2/plugins/backend/agentgateway/... -shuffle=on -count=100
PASS
ok      github.com/kgateway-dev/kgateway/v2/internal/kgateway/extensions2/plugins/backend/agentgateway  0.795s
```
> deflake: agw backend translator test collections

- CONTRIBUTING.md
- README.md
- devel/contributing/README.md
Create a readme under `devel/contributing` that links to all the other guides.
Change the top-level readmes to point to the devel/contributing readme.
/kind cleanup
```release-note
NONE
```
> Contributing guide cleanup

- internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/ir.go
- internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
See https://github.com/kgateway-dev/kgateway/actions/runs/17079909371/job/48430835553?pr=12025#step:5:3732
/kind bug_fix
```release-note
NONE
```
Fixes https://github.com/kgateway-dev/kgateway/issues/12078
> Attempts to fix a data race.

- internal/kgateway/agentgatewaysyncer/workloads.go
this is was part of https://github.com/kgateway-dev/kgateway/commit/ab7ae92866481eb186731eac823315e360836521 that was addressing the `manual service` part of the conformance tests for `agentgateway`
```
/kind cleanup
```
```release-note
NONE
```
> agentgateway: restore workloads.go

- internal/sds/pkg/run/run_test.go
It is possible for the server to not shutdown before the next test resumes. This will result in `Run` failing because the server's listener hasn't shut down yet. This change waits for the server port to not be open before the test starts.
```
/kind flake
```
```release-note
NONE
```
Part of #11354
> test/sds: wait for server to shutdown between tests

- internal/kgateway/agentgatewaysyncer/nodes.go
- internal/kgateway/agentgatewaysyncer/service.go
- internal/kgateway/agentgatewaysyncer/syncer.go
- internal/kgateway/agentgatewaysyncer/testdata/outputs/backend/backend-tls.yaml
- internal/kgateway/agentgatewaysyncer/waypoint.go
- internal/kgateway/agentgatewaysyncer/workloads.go
- pkg/agentgateway/plugins/collection.go
This does not write any new code really, its just copying in Istio code from other Istio code we copied and removed.
Part of this PR is split out into https://github.com/kgateway-dev/kgateway/pull/12187
/kind bug_fix
-->
```release-note
NONE
```
> wds: bring more changes from Istio in

- devel/envoy/envoy-upgrade.md
Documented envoy upgrade procedure
```release-note
NONE
```
> Added envoy-gloo upgrade doc

- test/kubernetes/e2e/tests/manifests/agent-gateway-integration.yaml
Updates the agentgateway e2e test Helm values to include inference extension.
```
/kind cleanup
```
```release-note
Inference: Updates the agentgateway e2e test Helm values to include inference extension.
```
> Inference: Updates Agentgateway e2e Test Values

- internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
Rename solo -> kgateway
/kind cleanup
```release-note
NONE
```
> rename ai stats annotation

- internal/kgateway/agentgatewaysyncer/conversion.go
- internal/kgateway/translator/listener/validation.go
- internal/kgateway/translator/listener/validation_test.go
allow HBONE protocol
/kind cleanup
```release-note
NONE
```
> agentgateway: allow HBONE protocol

- internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
- internal/kgateway/agentgatewaysyncer/policy_collections.go
- internal/kgateway/agentgatewaysyncer/status_syncer.go
- internal/kgateway/agentgatewaysyncer/syncer.go
- internal/kgateway/agentgatewaysyncer/syncer_test.go
- internal/kgateway/setup/agentgateway_test.go
- pkg/agentgateway/translator/agw.go
- pkg/agentgateway/translator/builtin_helpers.go
- pkg/agentgateway/translator/conditions.go
- pkg/agentgateway/translator/const.go
- pkg/agentgateway/translator/conversion.go
- pkg/agentgateway/translator/gateway_collection.go
- pkg/agentgateway/translator/gatewayclass_collection.go
- pkg/agentgateway/translator/model.go
- pkg/agentgateway/translator/references_collection.go
- pkg/agentgateway/translator/resources.go
- pkg/agentgateway/translator/route_collections.go
- pkg/agentgateway/translator/route_collections_test.go
- pkg/agentgateway/translator/translator.go
Refactor translator logic outside of the internal package next to other translators. 
```
/kind cleanup
```
```release-note
NONE
```
> agentgateway: Refactor translator logic

- internal/kgateway/agentgatewaysyncer/syncer.go
Ensure auth policies generated for backends follow policy naming conventions. 
/kind bug_fix
```release-note
NONE
```
fixes https://github.com/kgateway-dev/kgateway/issues/12444
> agentgateway: ensure auth policies generated for backends follow policy naming conventions

- .golangci.yaml
- internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
- internal/kgateway/controller/controller_suite_test.go
- internal/kgateway/controller/start.go
- internal/kgateway/deployer/gateway_parameters_test.go
- internal/kgateway/extensions2/plugins/backendconfigpolicy/validate.go
- internal/kgateway/extensions2/plugins/backendconfigpolicy/validate_test.go
- internal/kgateway/extensions2/plugins/kubernetes/k8s.go
- internal/kgateway/extensions2/plugins/trafficpolicy/validate.go
- internal/kgateway/extensions2/plugins/waypoint/waypoint_translator.go
- internal/kgateway/extensions2/registry/registry.go
- internal/kgateway/krtcollections/endpoints.go
- internal/kgateway/krtcollections/grpc_route_test.go
- internal/kgateway/krtcollections/policy.go
- internal/kgateway/krtcollections/policy_test.go
- internal/kgateway/krtcollections/setup.go
- internal/kgateway/query/query_test.go
- internal/kgateway/setup/agentgateway_test.go
- internal/kgateway/setup/setup.go
- internal/kgateway/setup/setup_test.go
- internal/kgateway/translator/gateway/gateway_translator_test.go
- internal/kgateway/translator/irtranslator/backend.go
- internal/kgateway/translator/irtranslator/backend_test.go
- internal/kgateway/translator/irtranslator/gateway.go
- internal/kgateway/translator/irtranslator/route.go
- internal/kgateway/translator/irtranslator/validate.go
- pkg/pluginsdk/collections/collections.go
- test/deployer/testutils.go
- test/envtestutil/util.go
- test/translator/test.go
add imports entry for api/settings
resolves #12429 
/kind cleanup
```release-note
NONE
```
> refactor: add imports entry for api/settings

- devel/contributing/pull-request-reviews.md
- devel/testing/writing-tests.md
Fix 3 typos in 2 devel docs
```release-note
NONE
```
> fix typo in devel docs
