kgateway-dev/kgateway

docs/introduction/concepts.md

Small spelling error

---

docs/thetool/custom.md

Spelling change

---

Makefile
ci/Jenkinsfile
cmd/control-plane/Dockerfile.debug
cmd/function-discovery/Dockerfile
cmd/function-discovery/Dockerfile.debug
cmd/kube-ingress-controller/Dockerfile.debug
cmd/kube-upstream-discovery/Dockerfile.debug
install/helm/gloo/templates/control-plane.yaml
install/helm/gloo/templates/function-discovery.yaml
install/helm/gloo/templates/kube-ingress-controller.yaml
test/README.md
test/e2e/events_test.go
test/e2e/function_discovery_test.go
test/e2e/kube_resources/helm-values.yaml.tmpl
test/e2e/kubernetes_e2e_test.go
test/e2e/kubernetes_ingress_controller_test.go
test/e2e/kubernetes_suite_test.go
test/helpers/build_images.go
test/helpers/kubectl.go
test/helpers/vault.go

1. Use debug containers
2. Increase eventually polling time as the default 10ms is only suitable for channels
3. Use gibkgowriter everywhere to reduce verbosity
4. Add race detection

E2e updates

---

example/grpc/README.md
example/grpc/deploy.yaml

add example for grpc

---

pkg/plugins/rest/plugin.go

from some reason this commit from plugins didnt survive.

fix passthrough in rest plugin

---

docs/tutorials/openfaas.md

Please merge only after glooctl pull request is merged

use glooctl to create certificate secret

---

pkg/plugins/azure/plugin.go

Add TODO comments per code review comments for pull request #24.

azure: Add TODOs

---

internal/function-discovery/updater/gcf/get_google_funcs.go

@yuval-k please review; not urgent

prevent nil panic in google func discovery

---

install/openshift/install.yml

install yaml for openshift

---

internal/control-plane/translator/function_processor_plugin.go
internal/control-plane/translator/function_processor_plugin_test.go
internal/control-plane/translator/route_init_plugin.go
internal/control-plane/translator/route_init_plugin_test.go
internal/control-plane/translator/translator.go

split init plugin into a route init and function processor plugin
route init happens first
then regular plugins
then func processor plugin

fix order of translation loop

---

pkg/plugins/aws/spec.go
pkg/plugins/google/spec.go

make regions in aws and google public so that glooctl can use it

make regions public

---

Makefile
install/kube/install.yaml

new images, new flags, fun & sun for everyone
@yuval-k 
please testing once manually before approving

update install yaml

---

internal/control-plane/reporter/reporter.go
pkg/storage/base/base_client.go
pkg/storage/dependencies/file/filestorage_test.go
pkg/storage/dependencies/file/secretstorage_test.go

fix file storage tests, reduce reporter annoyingness

---

test/helpers/local/gloo.go
test/local_e2e/cloud_foundry_test.go
test/local_e2e/utils.go

the BeforeEach stuff is based mostly on the copilot integration tests.
To that I added a gloo config and upstream.
This test only tests endpoint discovery; will hopefully do upstream discovery test in a separate PR.

local e2e for gloo with copilot

---

Gopkg.lock
Gopkg.toml
internal/control-plane/translator/translator.go
test/e2e/kubernetes_e2e_test.go

fix issue where https listener was not listening on ipv4

---

pkg/bootstrap/flags/kube_flags.go

support client auth plugins in out-of-cluster auth

---

Dockerfile.site
docs/getting_started/aws/lambda.md
docs/getting_started/kubernetes/1.md
docs/installation/kubernetes.md
docs/tutorials/openfaas.md
docs/tutorials/refactor_monolith.md
docs/tutorials/source_events_from_github.md
example/demo/README.md
example/demo/demo.cast
example/source_events_from_github/README.md

update docs to point at new install

---

example/nomad/petstore.nomad
install/nomad/install.nomad
install/nomad/launch-consul-vault-nomad-dev.sh
internal/control-plane/install/install_plugins.go
internal/upstream-discovery/bootstrap/flags/upstream_discovery_flags.go
internal/upstream-discovery/bootstrap/options.go
internal/upstream-discovery/consul/consul_suite_test.go
internal/upstream-discovery/consul/upstream_controller.go
internal/upstream-discovery/consul/upstream_controller_test.go
internal/upstream-discovery/start.go
pkg/backoff/backoff.go

adds upstream discovery to consul
tests working! try it yourself

Consul upstream discovery

---

example/nomad/petstore.nomad
install/nomad/install.nomad
install/nomad/launch-consul-vault-nomad-dev.sh
internal/control-plane/install/install_plugins.go
internal/function-discovery/detector/detector.go
internal/function-discovery/detector/detector_test.go
internal/function-discovery/eventloop/event_loop.go
internal/function-discovery/resolver/resolve_upstream_address.go
internal/upstream-discovery/bootstrap/flags/upstream_discovery_flags.go
internal/upstream-discovery/bootstrap/options.go
internal/upstream-discovery/consul/consul_suite_test.go
internal/upstream-discovery/consul/upstream_controller.go
internal/upstream-discovery/consul/upstream_controller_test.go
internal/upstream-discovery/start.go
pkg/backoff/backoff.go

function discovery for consul (really just needs the resolver)
depends on #50

Consul function discovery

---

Gopkg.lock

this worked, dont blame me

---

Gopkg.lock
Gopkg.toml

the last time we will ever have dep problems

---

Makefile
install/helm/bootstrap.yaml
install/helm/gloo/Chart.yaml
install/helm/gloo/templates/NOTES.txt
install/helm/gloo/templates/ingress.yaml
install/helm/gloo/values.yaml
install/kube/install.yaml
test/helpers/kubectl.go
test/kube_e2e/kube_resources/helm-values.yaml.tmpl

hide admin port unless desired by user, make target for creating install.yaml

---

hack/run-local-docker.sh

updates the run local docker script
tested manually working

Update local script

---

Makefile
README.md
docs/getting_started/openshift/1.md
docs/getting_started/openshift/2.md
docs/index.md
docs/installation/openshift.md
mkdocs.yml

includes doc updates for openshift support
also add back in the Dockerfile.site that got lost when we moved to monorepo

Openshift install

---

pkg/plugins/nats-streaming/plugin.go

- make constants public so that glooctl can use them
- fixed but in setting cluster id

bug fix and public constants

---

docs/getting_started/kubernetes/2.md
docs/getting_started/openshift/1.md
docs/getting_started/openshift/2.md
docs/tutorials/refactor_monolith.md
example/demo/README.md

- install for openshift
- route update

updated docs to match latest glooctl

---

pkg/plugins/interface.go

Fix a typo in a comment and formatting.

Fix comment typo

---

docs/getting_started/docker/1.md
docs/getting_started/docker/2.md
docs/getting_started/kubernetes/2.md
docs/index.md
docs/installation/docker.md
install/docker-compose/README.md
mkdocs.yml

Using glooctl to install to Docker

---

docs/v1/role.md
docs/v1/virtualservice.md
mkdocs.yml

new theme for docs

---

docs/installation/openshift.md
install/README.md

Just some minor fixes to the links for Kubernetes and OpenShift apply semantics.
Signed-off-by: Tom Nguyen <tom81094@gmail.com>

Fixed links in apply semantics

---

internal/control-plane/snapshot/emitter_test.go
internal/function-discovery/detector/detector.go
internal/function-discovery/detector/detector_test.go
internal/function-discovery/eventloop/event_loop.go
internal/function-discovery/updater/updater.go

fix potential block on fn discovery loop; better names

---

pkg/config/desired_state.go

fix a nil pointer panic

---

internal/control-plane/translator/translator.go

remove an error check that was always nil

remove unused error

---

.gitignore
Makefile
build-envoy/README.md
build-envoy/build.sh
build-envoy/ci/build.sh
build-envoy/ci/run_envoy_docker.sh
build-envoy/run_tests.sh

1. update workspace file to use prebuilt dependencies and run tests.
2. use envoy scripts to prepare the build container
3. add an envoy-release make target

ci scripts to run in a docker container

---

api/README.md

this fixes a couple of broken links in the readme

fix plugin links and image

---

Gopkg.lock
Gopkg.toml
example/knative/README.md

update to tag v0.1.0
and add a readme

Knative readme

---

example/knative/README.md
pkg/plugins/knative/plugin.go

1. increase timeout for knative routes.
2. minor changes to readme

knative: increase timeouts

---

pkg/function-discovery/detector/detector.go
pkg/function-discovery/eventloop/event_loop.go

function-discovery: fix permanent caching of upstreams

---

pkg/function-discovery/updater/swagger/get_swagger_funcs.go

fix potential panic in swagger get funcs

---

projects/gloo/cli/install.sh

Fix script

---

docs/getting_started/kubernetes/1.md
example/petstore/petstore.yaml

Fix typos in service label

---

docs/cli.md

"or RBAC permissions" linked to https://github.com/solo-io/glooctl/issues/58.

fix permission spelling

---

Makefile
hack/create-release.sh
hack/upload-github-release-asset.sh

adds a release script for creating new gloo releases

Add release script

---

Gopkg.lock
Gopkg.toml
cloudbuild.yaml
projects/gateway/pkg/api/v1/api_snapshot_emitter_test.go
projects/gloo/pkg/api/v1/api_snapshot_emitter_test.go
projects/gloo/pkg/api/v1/discovery_snapshot_emitter_test.go
projects/gloo/pkg/api/v1/setup_snapshot_emitter_test.go
projects/gloo/pkg/plugins/kubernetes/kubernetes_test.go

Test step now runs `ginkgo -r`

---

Gopkg.lock
Gopkg.toml
test/e2e/happypath_test.go

This should fix some flakes seen in CI

Choose non local ip for e2e

---

Gopkg.lock
Gopkg.toml
pkg/utils/setuputils/setup_syncer.go
pkg/utils/setuputils/setup_syncer_test.go
projects/gateway/pkg/syncer/setup_syncer.go
projects/gloo/pkg/bootstrap/utils.go
projects/gloo/pkg/syncer/setup_syncer.go

Ran `dep ensure -update github.com/solo-io/solo-kit` to upgrade to the newest `solo-kit` version.

Update solo-kit dependency

---

Makefile
cloudbuild.yaml

Adds deploy-site to the automatic release process

Firebase release

---

Gopkg.lock
projects/clusteringress/pkg/api/clusteringress/clusteringress_suite_test.go
projects/clusteringress/pkg/api/clusteringress/resource_client.go
projects/clusteringress/pkg/api/clusteringress/resource_client_test.go

add custom resource client for knative clusteringress

---

Makefile

This PR has two effects:
* Optimizes CI build times for non-release builds. Skips building artifacts and docker images if they aren't going to be uploaded or pushed. 
* Trims the list of artifacts uploaded to Github to be just the CLIs. We don't currently support a simple binary install path, and these are confusing the release page. When we do want to add this back, we should probably add back as an archive of binaries.

Optimize non-release build times

---

projects/clusteringress/pkg/status/status_syncer_test.go
projects/clusteringress/pkg/translator/translate.go
projects/clusteringress/pkg/translator/translate_test.go
projects/clusteringress/pkg/translator/translator_suite_test.go
projects/clusteringress/pkg/translator/translator_syncer.go
projects/ingress/pkg/translator/translate.go

add translator for clusteringress (knative)

---

projects/gloo/pkg/plugins/kubernetes/uds.go
projects/hypergloo/main.go

fix case where uds assigns capital names

---

Makefile
install/README.md
install/helm/gloo/templates/1-namespace-clusterrole.yaml
install/helm/gloo/templates/10-ingress-deployment.yaml
install/helm/gloo/templates/13-ingress-proxy-service.yaml
install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
install/helm/gloo/templates/16-clusteringress-proxy-service.yaml
install/helm/gloo/templates/5-discovery-deployment.yaml
install/helm/gloo/templates/settings.yaml
install/helm/gloo/values-knative.yaml
install/kube-knative.yaml

add knative support to helm chart

---

projects/gloo/cli/install.sh

This makes the CLI check for the latest release that actually has a glooctl artifact. This fixes the issue where the script was broken during any release build, or if a release build failed. 
Also fixes the output to be more readable and less busy: 
After:
```
[08:23:25] rick@Ricks-MacBook-Pro-2:~/code/src/github.com/solo-io/gloo/projects/gloo/cli$ ./install.sh
Attempting to download glooctl version v0.6.1
Downloading glooctl-darwin-amd64...
Download complete!, validating checksum...
Checksum valid.
Gloo was successfully installed 🎉
Add the gloo CLI to your path with:
export PATH=$HOME/.gloo/bin:$PATH
Now run:
glooctl install kube        # install gloo into the 'gloo-system' namespace
Looking for more? Visit https://gloo.solo.io/installation/
```
Before:
```
[08:16:58] …
```

Clean up install script

---

install/helm/gloo/values.yaml

fix default gloo values

---

cloudbuild.yaml
projects/gateway/pkg/mocks/mock_gateway_client.go
projects/gateway/pkg/mocks/mock_virtual_service_client.go
projects/gloo/pkg/bootstrap/opts.go
projects/gloo/pkg/mocks/mock_artifact_client.go
projects/gloo/pkg/mocks/mock_endpoint_client.go
projects/gloo/pkg/mocks/mock_proxy_client.go
projects/gloo/pkg/mocks/mock_secret_client.go
projects/gloo/pkg/mocks/mock_settings_client.go
projects/gloo/pkg/mocks/mock_upstream_client.go
projects/gloo/pkg/syncer/setup_syncer.go
test/services/gateway.go

move Extensions to bootstrap.Opts, fix compile err

---

Makefile

tested with `make manifest TAGGED_VERSION=vfoo`

Fix make manifest for releases

---

Gopkg.lock
Gopkg.toml
test/helpers/build_test_images.go
test/helpers/install_helm_chart.go
test/helpers/testrunner.go
test/kube2e/artifacts/knative-hello-service.yaml
test/kube2e/artifacts/knative-no-istio-0.2.2.yaml
test/kube2e/artifacts/knative-no-istio-0.3.0.yaml
test/kube2e/artifacts/knative-no-istio.yaml
test/kube2e/knative_test.go
test/kube2e/kube2e_suite_test.go

add e2e test for knative

---

install/helm/gloo/generate.go
mkdocs.yml

Fix make generated code target, remove sqoop reference

---

projects/gloo/pkg/translator/route_config.go

Initial pass at https://github.com/solo-io/gloo/issues/306
Would love some guidance on this @ilackarms @yuval-k @rickducott 
I don't believe it's the right code, but it does solve my immediate problem. Would love to have eyes on it to make it suitable for long-term maintenance. 
Thanks!

initial stab at fixing auto_host_rewrite

---

Makefile
docs/getting_started/kubernetes/basic_routing.md
docs/getting_started/kubernetes/external_api_routing.md
docs/getting_started/kubernetes/function_routing.md
docs/installation/kubernetes.md
mkdocs.yml

So for this PR to work as described, we need this sorted out:
https://github.com/solo-io/gloo/issues/306
But assuming that'll happen soon, here's a guide for adding `static` upstreams to Gloo

add docs for external API example

---

docs/getting_started/kubernetes/basic_routing.md
docs/getting_started/kubernetes/external_api_routing.md
docs/getting_started/kubernetes/function_routing.md

the `glooctl gateway` command was renamed to `glooctl proxy`
this pr updates the docs with that change

fix updated command in docs

---

projects/clusteringress/pkg/api/clusteringress/resource_client_test.go

Make test not flake, fixes 328

---

Gopkg.lock
docs/cli.md
projects/gloo/cli/pkg/cmd/add/route.go
projects/gloo/cli/pkg/cmd/options/options.go
projects/gloo/cli/pkg/cmd/remove/remove_suite_test.go
projects/gloo/cli/pkg/cmd/remove/root.go
projects/gloo/cli/pkg/cmd/remove/route.go
projects/gloo/cli/pkg/cmd/remove/route_test.go
projects/gloo/cli/pkg/cmd/root.go
projects/gloo/cli/pkg/cmd/route/root.go
projects/gloo/cli/pkg/cmd/route/route_suite_test.go
projects/gloo/cli/pkg/cmd/route/sort.go
projects/gloo/cli/pkg/cmd/route/sort_test.go
projects/gloo/cli/pkg/flagutils/route.go
projects/gloo/cli/pkg/surveyutils/route.go
projects/gloo/pkg/plugins/grpc/plugin.go
projects/gloo/pkg/utils/paths.go
projects/gloo/pkg/utils/sort_routes.go
projects/gloo/pkg/utils/sort_routes_test.go
projects/gloo/pkg/utils/utils_suite_test.go
projects/gloo/pkg/utils/utils_test.go
test/helpers/routes.go

adds commands for [sorting | removing] routes on a virtual service

Route commands cli

---

projects/gloo/cli/pkg/cmd/create/upstream.go
projects/gloo/cli/pkg/cmd/create/upstream_test.go
projects/gloo/cli/pkg/cmd/create/virtualservice.go

make name flag work.

---

projects/gloo/pkg/discovery/discovery.go

just a nit

---

Makefile

Adds CLI for windows, this will be manually tested to start due to lack of automation against windows.

Update makefile for windows

---

projects/gateway/pkg/translator/translator.go
projects/gateway/pkg/translator/translator_suite_test.go
projects/gateway/pkg/translator/translator_test.go

a simpler version of https://github.com/solo-io/gloo/pull/385

make sure proxy has a constant name

---

projects/gloo/cli/pkg/argsutils/metadata.go
projects/gloo/cli/pkg/cmd/create/secret/aws.go
projects/gloo/cli/pkg/cmd/create/secret/azure.go
projects/gloo/cli/pkg/cmd/create/secret/root.go
projects/gloo/cli/pkg/cmd/create/secret/secret_interactive_test.go
projects/gloo/cli/pkg/cmd/create/secret/secret_test.go
projects/gloo/cli/pkg/cmd/create/secret/tls.go
projects/gloo/cli/pkg/cmd/create/upstream_test.go
projects/gloo/cli/pkg/cmd/options/secret.go

* Implements Azure secret in interactive and non-interactive modes for CLI
* Adds more tests for all secret paths
* Fixes an issue with metadata validation and error reporting for secret subcommands
* Refactors our a constant from upstream tests

Azure secret

---

Makefile
install/helm/gloo/values-gateway-template.yaml
install/helm/gloo/values-ingress-template.yaml
install/helm/gloo/values-knative-template.yaml

make creating a namespace default to false. fixes #399

---

docs/installation/install_with_helm.md
mkdocs.yml

add installation doc for helm

---

docs/dev/CONTRIBUTING.md
docs/index.md

-need to finish code review guideline section, would love feedback on what to include

contributor guide

---

projects/gloo/cli/install.sh

fixes https://github.com/solo-io/gloo/issues/415
@rickducott

Fix install.sh post install script

---

pkg/utils/namespaces.go
pkg/utils/namespaces_test.go
pkg/utils/utils_suite_test.go
projects/discovery/pkg/uds/syncer/setup_syncer.go
projects/gateway/pkg/syncer/setup_syncer.go
projects/gloo/pkg/plugins/kubernetes/uds.go
projects/gloo/pkg/syncer/setup_syncer.go
projects/ingress/pkg/setup/setup_syncer.go
test/e2e/happypath_test.go
test/services/envoy.go
test/services/gateway.go

watch all namespaces dynamically

---

Makefile
ci/push-docs.sh

Tested locally with `make release TAGGED_VERSION=v0.7.2`, produced https://github.com/solo-io/gloo-docs/pull/11. Expect when we actually release 0.7.2 that PR will get re-created.

Push docs2

---

Gopkg.lock
Gopkg.toml
test/e2e/happypath_test.go

https://github.com/solo-io/solo-kit/pull/87

test that eds works on all namespaces

---

cloudbuild.yaml

This was running after test, it should run in parallel, saving 3m
https://console.cloud.google.com/cloud-build/builds/656c1ebf-25e6-4528-b66e-0f19f73adcca?project=solo-public

Parallelize compile step

---

ci/push-docs.sh

To be merged in after @EItanya 's refactor for sqoop.

Update to use refactored repo

---

cloudbuild.yaml
install/helm/gloo/templates/10-ingress-deployment.yaml

This fixes the knative installation both via Helm and via `glooctl`.

Fix indentation in Helm template

---

projects/gloo/cli/pkg/cmd/create/upstream.go
projects/gloo/cli/pkg/cmd/create/upstream_test.go

this Wrapf with a nil error was causing a `return nil, nil`
this fixes it to return the error properly

fix wrapf which was suppressing error

---

install/helm/gloo/generate.go
projects/gloo/cli/pkg/cmd/install/util.go

Default values were not being copied over to sub-chart.

Fix gateway install

---

install/helm/gloo/generate/values.go
install/helm/gloo/templates/8-gateway-proxy-service.yaml
install/helm/gloo/values-gateway-template.yaml

Fixes https://github.com/solo-io/gloo/issues/448.

Ability to specify clusterIP and annotations for gateway service via Helm chart

---

install/helm/gloo/crds/templates/settings-crd.yaml

Add separator to manifest

---

Makefile
changelog/v0.10.2/deflake-regression.yaml
test/helpers/cmd_helpers.go
test/kube2e/README.md
test/kube2e/testrunner.go
test/kube2e/util.go

this pr tries to deflake e2e tests.
first step is to get them running locally.
i noticed test runner takes a lot of time to terminate - trying to understand why.

deflake e2e and regression

---

changelog/v0.11.2/external_traffic_policy.yaml
install/helm/gloo/generate/values.go
install/helm/gloo/templates/4-gloo-service.yaml
install/helm/gloo/values-gateway-template.yaml

Add ability to set ExternalTrafficPolicy.  Set default to Local for gateway.

Add ability to set ExternalTrafficPolicy. 

---

changelog/v0.11.2/sds_factory_name.yaml
projects/gloo/pkg/utils/ssl.go
projects/gloo/pkg/utils/ssl_test.go

add the crd factory name

---

changelog/v0.11.4/allow_creating_secrets.yaml
projects/gloo/pkg/api/converters/kube/secretconverter.go
projects/gloo/pkg/api/converters/kube/secretconverter_test.go

once https://github.com/solo-io/solo-kit/pull/110 is merged we can do some minor cleanup

allow creating secrets from secret converter

---

changelog/v0.13.2/propagate-exclusion-logic.yaml
projects/gloo/cli/pkg/cmd/install/installer.go

Propagate exclude resources

---

changelog/v0.13.6/fix-uds-start.yaml
projects/discovery/pkg/uds/syncer/discovery_syncer.go
projects/discovery/pkg/uds/syncer/setup_syncer.go
projects/gloo/pkg/discovery/discovery.go
test/kube2e/gateway/gateway_test.go

fix race when reconcile called more than once
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/631

uds only starts once and then gets kicked

---

changelog/v0.13.7/cleanup-cli-errors.yaml
docs/cli/glooctl.md
docs/cli/glooctl_add.md
docs/cli/glooctl_add_route.md
docs/cli/glooctl_create.md
docs/cli/glooctl_create_upstream.md
docs/cli/glooctl_create_upstream_aws.md
docs/cli/glooctl_create_upstream_azure.md
docs/cli/glooctl_create_upstream_consul.md
docs/cli/glooctl_create_upstream_kube.md
docs/cli/glooctl_create_upstream_static.md
docs/cli/glooctl_delete.md
docs/cli/glooctl_edit.md
docs/cli/glooctl_edit_upstream.md
docs/cli/glooctl_edit_virtualservice.md
projects/gloo/cli/pkg/cmd/add/root.go
projects/gloo/cli/pkg/cmd/add/root_test.go
projects/gloo/cli/pkg/cmd/create/root.go
projects/gloo/cli/pkg/cmd/create/root_test.go
projects/gloo/cli/pkg/cmd/create/secret/root.go
projects/gloo/cli/pkg/cmd/create/secret/secret_test.go
projects/gloo/cli/pkg/cmd/create/upstream.go
projects/gloo/cli/pkg/cmd/create/upstream_test.go
projects/gloo/cli/pkg/cmd/create/virtualservice_test.go
projects/gloo/cli/pkg/cmd/del/del_suite_test.go
projects/gloo/cli/pkg/cmd/del/root.go
projects/gloo/cli/pkg/cmd/del/root_test.go
projects/gloo/cli/pkg/cmd/edit/root.go

BOT NOTES: 
resolves https://github.com/solo-io/solo-projects/issues/404

Cleanup feedback

---

changelog/v0.13.7/add-proxy-address.yaml
docs/cli/glooctl_proxy.md
docs/cli/glooctl_proxy_address.md
projects/gloo/cli/pkg/cmd/gateway/root.go
projects/gloo/cli/pkg/cmd/gateway/url.go

resolve #643 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/643

add glooctl proxy address option

---

changelog/v0.13.7/upstream_group_all_roles.yaml
install/helm/gloo/templates/21-namespace-clusterrole-ingress.yaml
install/helm/gloo/templates/22-namespace-clusterrole-knative.yaml

add upstream groups to all roles

---

changelog/v0.13.10/completion.yaml
docs/cli/glooctl.md
docs/cli/glooctl_completion.md
projects/gloo/cli/pkg/cmd/completion.go
projects/gloo/cli/pkg/cmd/root.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/460

include shell completion in glooctl

---

changelog/v0.13.12/eds_ignore_host_network.yaml
projects/gloo/pkg/plugins/kubernetes/eds.go
projects/gloo/pkg/translator/translator.go

ignore file pods as they share the same IP. give different versions for resources in xds

snapshot improvments

---

README.md

adding link to the Gloo Enterprise trial on the READ ME

Add link to trial

---

changelog/v0.13.15/stats_for_envoy_snap.yaml
install/helm/gloo/templates/101-knative-crds-0.3.0.yaml
install/helm/gloo/templates/101-knative-crds-0.5.1.yaml
install/helm/gloo/templates/17-knative-no-istio-0.3.0.yaml
install/helm/gloo/templates/17-knative-no-istio-0.5.1.yaml
projects/gloo/cli/pkg/cmd/install/util.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/673

Update knative 0.5.1

---

changelog/v0.13.15/passthrough-content-type.yaml
projects/envoyinit/cmd/Dockerfile

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/682

upgrade envoy-gloo to 0.1.6

---

Gopkg.lock
Gopkg.toml
changelog/v0.13.18/package-management-update.yaml
ci/upload_github_release_assets.go

Waiting on merge of the following PR before progressing with this PR.
https://github.com/solo-io/supergloo/pull/367

Update package management formulas as part of release process

---

changelog/v0.13.22/keepalive.yaml
install/helm/gloo/templates/9-gateway-proxy-configmap.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/708

add tcp keepalive to prevent half open connections

---

changelog/v0.13.23/upstream_group_cli.yaml
docs/cli/glooctl_add_route.md
projects/gloo/cli/pkg/cmd/add/route.go
projects/gloo/cli/pkg/cmd/add/route_interactive_test.go
projects/gloo/cli/pkg/cmd/add/route_test.go
projects/gloo/cli/pkg/cmd/options/options.go
projects/gloo/cli/pkg/flagutils/route.go
projects/gloo/cli/pkg/helpers/clients.go
projects/gloo/cli/pkg/surveyutils/route.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/709

add upstream group to cli

---

changelog/v0.13.24/stats.yaml
install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
install/helm/gloo/values-gateway-template.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/710

port stats config from solo-projects

---

changelog/v0.13.25/annotation_quote.yaml
install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
install/helm/gloo/templates/8-gateway-proxy-service.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/711

Annotation quote

---

changelog/v0.13.27/alt_stat_name.yaml
install/helm/gloo/templates/9-gateway-proxy-configmap.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/713

Alt stat name

---

Gopkg.lock
Makefile
changelog/v0.13.28/fix_helm_var.yaml
install/helm/gloo/templates/8-gateway-proxy-service.yaml
install/test/helm_suite_test.go
install/test/helm_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/714

remove variable that doesn't exist

---

changelog/v0.13.29/admin_ipv4.yaml
install/helm/gloo/templates/9-gateway-proxy-configmap.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/716

only use ipv4 admin for now

---

changelog/v0.13.30/gloo-cpu.yaml
install/helm/gloo/templates/3-gloo-deployment.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/725

Reduce gloo cpu request

---

BUILD.md
Gopkg.lock
Gopkg.toml
Makefile
changelog/v0.13.31/relax-constraint-control-plane.yaml
projects/clusteringress/pkg/api/v1/translator_simple_event_loop.sk.go
projects/gateway/pkg/api/v1/api_simple_event_loop.sk.go
projects/gloo/pkg/api/v1/api_simple_event_loop.sk.go
projects/gloo/pkg/api/v1/discovery_simple_event_loop.sk.go
projects/gloo/pkg/api/v1/plugins/faultinjection/fault.pb.go
projects/gloo/pkg/api/v1/setup_simple_event_loop.sk.go
projects/gloo/pkg/plugins/aws/filter.pb.go
projects/gloo/pkg/plugins/aws/plugin.go
projects/ingress/pkg/api/v1/status_simple_event_loop.sk.go
projects/ingress/pkg/api/v1/translator_simple_event_loop.sk.go

needed new control plane and that means transition validate from lyft to envoyproxy

Relax control plane constraint

---

changelog/v0.14.1/appsv1.yaml
install/helm/gloo/templates/10-ingress-deployment.yaml
install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
install/helm/gloo/templates/3-gloo-deployment.yaml
install/helm/gloo/templates/5-discovery-deployment.yaml
install/helm/gloo/templates/6-gateway-deployment.yaml
install/helm/gloo/templates/7-gateway-proxy-deployment.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/767

change extensions/v1beta1 to apps/v1

---

Gopkg.lock
changelog/v0.14.1/fix-append.yaml
projects/gloo/pkg/upstreams/hybrid_client.go
projects/gloo/pkg/upstreams/snapshot.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/771

fix merged append on upstreams

---

changelog/v0.14.2/knative-helm-option.yaml
install/helm/gloo/generate/values.go
install/helm/gloo/templates/101-knative-crds-0.5.1.yaml
install/helm/gloo/templates/17-knative-no-istio-0.5.1.yaml
install/helm/gloo/values-knative-template.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/774

allow installing gloo in knative mode without knative

---

Makefile
changelog/v0.14.4/helm-race.yaml
cloudbuild.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/785

Fix race condition

---

Gopkg.lock
Gopkg.toml
changelog/v0.17.1/bump-sanitize-name.yaml
projects/gloo/pkg/plugins/aws/ec2/eds.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/817

update go-utils, use sanitizeNameV2

---

Gopkg.lock
Gopkg.toml
changelog/v0.17.1/fix-kube-eds.yaml
projects/gloo/pkg/plugins/kubernetes/eds.go
projects/gloo/pkg/plugins/kubernetes/kubernetes_test.go
test/kube2e/gateway/gateway_suite_test.go
test/kube2e/ingress/ingress_suite_test.go
test/kube2e/knative/knative_suite_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/816

fix kube eds bug

---

changelog/v0.17.4/grpc_no_path.yaml
projects/gloo/pkg/plugins/grpc/plugin.go
projects/gloo/pkg/plugins/grpc/plugin_test.go
projects/gloo/pkg/translator/route_config.go
projects/gloo/pkg/translator/translator_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/860

Fix grpc no path

---

changelog/v0.17.5/grpc-empty-path.yaml
projects/gloo/pkg/plugins/grpc/plugin.go
projects/gloo/pkg/translator/translator_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/860

handle missing path in grpc plugin

---

changelog/v0.17.7/partial_watch_hybrid_client.yaml
projects/gloo/pkg/upstreams/hybrid_client.go
projects/gloo/pkg/upstreams/hybrid_client_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/886

fixes a potential issue of a partial update from the hybrid client

---

Makefile
changelog/v0.17.7/tracing-manifest.yaml
install/helm/gloo/generate/values.go
install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
install/helm/gloo/values-gateway-template.yaml
install/helm/gloo/values-ingress-template.yaml
install/helm/gloo/values-knative-template.yaml
install/test/helm_suite_test.go
install/test/helm_test.go
install/test/test_values.yaml
projects/gloo/cli/pkg/cmd/install/install_suite_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/878

initial manifest update for tracing

---

changelog/v0.18.3/liveness-devnull.yaml
install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
install/test/helm_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/917

update liveness probe to not write anything

---

changelog/v0.18.4/vs-cli-edit.yaml
projects/gloo/cli/pkg/cmd/edit/virtualservice/root.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/921

vs cli edit fix

---

changelog/v0.18.4/liveness-revert.yaml
changelog/v0.18.5/liveness-off-bydefault.yaml
install/helm/gloo/generate/values.go
install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
install/helm/gloo/values-gateway-template.yaml
install/test/helm_test.go

Revert "Liveness revert"

---

changelog/v0.18.6/always_dev.yaml
install/helm/gloo/generate.go
install/helm/gloo/values-gateway-template.yaml
install/helm/gloo/values-ingress-template.yaml
install/helm/gloo/values-knative-template.yaml
install/test/helm_test.go

no need to always pull released images
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/942

pull policy: release - ifNotPresent; dev - always

---

changelog/v0.18.6/xds_client.yaml
docs/cli/glooctl_proxy.md
docs/cli/glooctl_proxy_served-config.md
hack/utils/xdsclient/main.go
pkg/utils/setuputils/main_setup.go
projects/gloo/cli/pkg/cmd/gateway/dump.go
projects/gloo/cli/pkg/cmd/gateway/root.go
projects/gloo/cli/pkg/cmd/gateway/served-config.go
projects/gloo/pkg/defaults/port.go

makes the `hack/utils/xdsclient.go` a command in glooctl
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/938

Xds client glooctl

---

changelog/v0.18.11/knative-ingress.yaml
projects/clusteringress/pkg/translator/translate.go
projects/clusteringress/pkg/translator/translate_test.go
projects/clusteringress/pkg/translator/translator_syncer.go
projects/clusteringress/pkg/translator/translator_syncer_test.go
projects/knative/pkg/translator/translate.go
projects/knative/pkg/translator/translate_test.go
projects/knative/pkg/translator/translator_syncer.go
projects/knative/pkg/translator/translator_syncer_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/971

fix knative unit test, status now always syncs generation

---

changelog/v0.18.11/alternate-aws-secret.yaml
projects/gloo/pkg/api/converters/kube/secretconverter.go
projects/gloo/pkg/api/converters/kube/secretconverter_test.go
projects/gloo/pkg/bootstrap/utils.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/990

kube secret converter chain and alternate aws secret input

---

Gopkg.lock
changelog/v0.18.14/default-ingress.yaml
install/helm/gloo/generate/values.go
install/helm/gloo/templates/10-ingress-deployment.yaml
projects/ingress/pkg/setup/opts.go
projects/ingress/pkg/setup/setup_syncer.go
projects/ingress/pkg/translator/translate.go
projects/ingress/pkg/translator/translate_test.go
projects/ingress/pkg/translator/translator_syncer.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/507

enable setting gloo as default ingress

---

changelog/v0.18.16/fix-knative-status-address.yaml
projects/ingress/pkg/setup/setup_syncer.go

fix a typo
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1017

Fix knative default addr

---

changelog/v0.18.16/testing.yaml
projects/gloo/cli/pkg/cmd/install/knative.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/996

fix knative install race

---

Gopkg.lock
changelog/v0.18.17/knative-create-settings.yaml
install/helm/gloo/templates/18-settings.yaml
install/helm/gloo/values-gateway-template.yaml
install/helm/gloo/values-knative-template.yaml
projects/gloo/cli/pkg/cmd/install/installer_test.go
projects/gloo/pkg/translator/functional_base.pb.go
projects/ingress/pkg/setup/setup_syncer.go
test/e2e/aws_credentials/ec2_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1023

add create to settings crd in helm chart

---

Gopkg.lock
Gopkg.toml
changelog/v0.18.17/optimize-hashes.yaml
projects/clusteringress/pkg/api/v1/translator_snapshot_emitter.sk.go
projects/clusteringress/pkg/api/v1/translator_snapshot_simple_emitter.sk.go
projects/gateway/pkg/api/v2/api_snapshot_emitter.sk.go
projects/gateway/pkg/api/v2/api_snapshot_simple_emitter.sk.go
projects/gloo/pkg/api/v1/api_snapshot_emitter.sk.go
projects/gloo/pkg/api/v1/api_snapshot_simple_emitter.sk.go
projects/gloo/pkg/api/v1/discovery_snapshot_emitter.sk.go
projects/gloo/pkg/api/v1/discovery_snapshot_simple_emitter.sk.go
projects/gloo/pkg/api/v1/eds_snapshot_emitter.sk.go
projects/gloo/pkg/api/v1/eds_snapshot_simple_emitter.sk.go
projects/gloo/pkg/api/v1/setup_snapshot_emitter.sk.go
projects/gloo/pkg/api/v1/setup_snapshot_simple_emitter.sk.go
projects/gloo/pkg/plugins/kubernetes/eds.go
projects/gloo/pkg/translator/functional_base.pb.go
projects/gloo/pkg/upstreams/hybrid_client.go
projects/gloo/pkg/upstreams/hybrid_client_test.go
projects/ingress/pkg/api/v1/status_snapshot_emitter.sk.go
projects/ingress/pkg/api/v1/status_snapshot_simple_emitter.sk.go
projects/ingress/pkg/api/v1/translator_snapshot_emitter.sk.go
projects/ingress/pkg/api/v1/translator_snapshot_simple_emitter.sk.go
projects/knative/pkg/api/v1/translator_snapshot_emitter.sk.go
projects/knative/pkg/api/v1/translator_snapshot_simple_emitter.sk.go
test/benchmark/benchmark_suite_test.go
test/benchmark/snapshot_benchmark_test.go
test/benchmark/upstream_list.json
test/e2e/aws_credentials/ec2_test.go
test/helpers/directories.go

reduces CPU overhead in gloo containers
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/706

Optimize hash strategy

---

changelog/v0.18.19/read-admin-and-label-gateway-proxy.yaml
projects/knative/pkg/translator/translate.go

…r ServerCertificate and PrivateKey
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1040

fix Knative Ingress' TLS configuration

---

changelog/v0.18.20/fix-glooctl-add-route.yaml
pkg/utils/selectionutils/virtual_service.go
pkg/utils/selectionutils/virtual_service_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1050

Fix select or create util

---

changelog/v0.18.20/autmnt_svc_accnt.yaml
install/helm/gloo/generate/values.go
install/helm/gloo/templates/8-gateway-proxy-service-account.yaml
install/helm/gloo/values-gateway-template.yaml
install/test/svc_accnt_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1057

Automount enable

---

changelog/v0.18.22/restore-namespaced-builds.yaml
test/kube2e/gateway/gateway_suite_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/1063

Restore namespaced builds

---

changelog/v0.18.22/no_net_bind.yaml
install/helm/gloo/generate/values.go
install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
install/test/helm_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1068

No net bind

---

changelog/v0.18.22/envoy_as_user.yaml
install/helm/gloo/generate/values.go
install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
install/test/helm_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1071

run envoy as regular user

---

Gopkg.lock
Gopkg.toml
changelog/v0.18.25/svc_account_for_job.yaml
install/helm/gloo/templates/6.5-gateway-conversion-job.yaml
install/test/helm_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1085

Assign a service account name to the gateway conversion job

---

changelog/v0.18.26/dodge-helm-bug.yaml
pkg/cliutil/install/chart.go

cc @rickducott 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1092

Dodge helm bug

---

Gopkg.lock
changelog/v0.18.38/vs-selector.yaml
docs/api/github.com/solo-io/gloo/projects/gateway/api/v2/gateway.proto.sk.md
projects/gateway/api/v2/gateway.proto
projects/gateway/pkg/api/v2/gateway.pb.go
projects/gateway/pkg/translator/http.go
projects/gateway/pkg/translator/translator_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/1143

implement virtualservice selector

---

changelog/v0.18.38/regen.yaml
projects/gateway/pkg/api/v1/virtual_service.pb.go
projects/gateway/pkg/api/v2/gateway.pb.go
projects/gloo/pkg/api/v1/enterprise/plugins/extauth/extauth.pb.go
projects/gloo/pkg/api/v1/enterprise/plugins/jwt/jwt.pb.go
projects/gloo/pkg/api/v1/enterprise/plugins/ratelimit/ratelimit.pb.go
projects/gloo/pkg/api/v1/enterprise/plugins/rbac/rbac.pb.go
projects/gloo/pkg/api/v1/enterprise/plugins/waf/waf.pb.go
projects/gloo/pkg/api/v1/load_balancer.pb.go
projects/gloo/pkg/api/v1/plugins.pb.go
projects/gloo/pkg/api/v1/plugins/als/als.pb.go
projects/gloo/pkg/api/v1/plugins/aws/ec2/aws_ec2.pb.go
projects/gloo/pkg/api/v1/plugins/hostrewrite/hostrewrite.pb.go
projects/gloo/pkg/api/v1/plugins/jwt/jwt.pb.go
projects/gloo/pkg/api/v1/plugins/lbhash/lbhash.pb.go
projects/gloo/pkg/api/v1/plugins/rbac/rbac.pb.go
projects/gloo/pkg/api/v1/plugins/rest/rest.pb.go
projects/gloo/pkg/api/v1/plugins/service_spec.pb.go
projects/gloo/pkg/api/v1/plugins/transformation/transformation.pb.go
projects/gloo/pkg/api/v1/proxy.pb.go
projects/gloo/pkg/api/v1/secret.pb.go
projects/gloo/pkg/api/v1/settings.pb.go
projects/gloo/pkg/api/v1/ssl.pb.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1147

regen protobuf code

---

projects/gloo/cli/pkg/cmd/install/uninstall.go

* uninstall -all with nonexistent namespace now uninstalls everything without error
* use kubeerrors.IsNotFound check instead
* Merge branch 'merge-cli' into uninstall-all-nonexistent-namespace

Uninstall all nonexistent namespace (#1162)

---

changelog/v0.18.45/eds_version_change.yaml
projects/gloo/pkg/translator/translator.go
projects/gloo/pkg/translator/translator_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1191

change eds versions wih clusters

---

changelog/v0.19.2/fix-glooctl-version-formatting.yaml
projects/gloo/cli/pkg/cmd/version/cmd.go
projects/gloo/cli/pkg/cmd/version/version_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1243

Clean up glooctl version formatting

---

Gopkg.lock
changelog/v0.19.2/filter-error-logs.yaml
projects/gloo/cli/pkg/cmd/debug/debug.go
projects/gloo/cli/pkg/cmd/debug/debug_test.go
projects/gloo/cli/pkg/cmd/debug/root.go
projects/gloo/pkg/utils/log_filtering.go
projects/gloo/pkg/utils/log_filtering_test.go
test/helpers/kube_dump.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1219

Filter error logs

---

Gopkg.lock
changelog/v0.20.1/fix-ui.yaml
pkg/cliutil/uri.go
projects/gloo/cli/pkg/cmd/install/install_test.go
projects/gloo/cli/pkg/cmd/install/util.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1278

Fix admin console

---

changelog/v0.20.2/gloo-validation-fixes.yaml
projects/gloo/pkg/bootstrap/opts.go
projects/gloo/pkg/defaults/port.go
projects/gloo/pkg/syncer/setup_syncer.go
projects/gloo/pkg/validation/server.go
projects/gloo/pkg/validation/server_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1296

fix issue where gloo validation server does not restart properly

---

changelog/v0.20.2/fix-ratelimit-tests.yaml
projects/gateway/pkg/translator/merge_route_plugins_test.go

Fix broken route merge tests due to ratelimit rename

---

.github/pull_request_template.md
changelog/v0.20.3/add-pr-template.yaml

Add PR template

---

Gopkg.lock
changelog/v0.21.0/glooctl-delegation.yaml
docs/cli/glooctl_add_route.md
docs/cli/glooctl_get_routetable.md
pkg/utils/selectionutils/mocks/mock_virtual_service.go
pkg/utils/selectionutils/route_table.go
pkg/utils/selectionutils/virtual_service.go
pkg/utils/selectionutils/virtual_service_test.go
projects/gloo/cli/pkg/cmd/add/route.go
projects/gloo/cli/pkg/cmd/add/route_test.go
projects/gloo/cli/pkg/cmd/get/root.go
projects/gloo/cli/pkg/cmd/get/route_table.go
projects/gloo/cli/pkg/cmd/get/route_table_test.go
projects/gloo/cli/pkg/cmd/options/options.go
projects/gloo/cli/pkg/common/get.go
projects/gloo/cli/pkg/constants/commands.go
projects/gloo/cli/pkg/flagutils/route.go
projects/gloo/cli/pkg/helpers/clients.go
projects/gloo/cli/pkg/printers/virtualservice.go
projects/gloo/cli/pkg/printers/virtualservice_test.go

Cherry-pick of https://github.com/solo-io/gloo/pull/1321 to `feature-rc1` branch
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1320
resolves https://github.com/solo-io/gloo/issues/1319
resolves https://github.com/solo-io/gloo/issues/1318

add glooctl commands for delegation (#1321)

---

changelog/v0.21.0/fix-petstore-manifest.yaml
example/petstore/petstore.yaml

Fix deployment apiVersion in petstore example manifest.

Fix petstore manifest

---

changelog/v0.21.0/fix-routeaction-glooctl.yaml
docs/cli/glooctl_get_virtualservice_route.md
projects/gloo/cli/pkg/cmd/get/virtualservice.go
projects/gloo/cli/pkg/cmd/get/virtualservice_test.go
projects/gloo/cli/pkg/printers/route.go

Fix glooctl interface conversion error panic trying to print route table
Still need to add tests
planning to cherrypick into master as well
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1350

Fix glooctl panic on printing route table

---

changelog/v0.20.4/envoy-1-11-2.yaml
projects/envoyinit/cmd/Dockerfile

port of https://github.com/solo-io/gloo/pull/1355 to `feature-rc1`

update envoy (#1355)

---

changelog/v0.21.0/kube2e-install-once-per-suite.yaml
test/e2e/access_log_test.go
test/kube2e/gateway/gateway_suite_test.go
test/kube2e/gateway/gateway_test.go
test/kube2e/gateway/robustness_test.go

port of https://github.com/solo-io/gloo/pull/1336 to `feature-rc1`

Install Gloo once per suite in gateway kube2e tests (#1336)

---

changelog/v0.20.7/dont-register-crds-with-glooctl.yaml
projects/gloo/cli/pkg/helpers/clients.go

Glooctl no longer registers CRDs when performing read/write operations
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1380

Don't register CRDs with glooctl

---

Gopkg.lock
changelog/v0.20.7/ext-authz-filter-builder.yaml
projects/gloo/pkg/plugins/extauth/extauth_suite_test.go
projects/gloo/pkg/plugins/extauth/filter.go
projects/gloo/pkg/plugins/extauth/filter_test.go
projects/gloo/pkg/plugins/extauth/plugin.go

Add utility function to build an `ext_authz` filter configuration from Gloo ExtAuth settings.

Ext auth listener filter builder

---

changelog/v0.20.7/fix-knative-manifest-parsing.yaml
projects/gloo/cli/pkg/cmd/install/install_test.go
projects/gloo/cli/pkg/cmd/install/knative.go

port of https://github.com/solo-io/gloo/pull/1371 to `feature-rc1`

fix-knative-manifest-parsing (#1371)

---

changelog/v0.20.8/fix-external-traffic-policy.yaml
install/helm/gloo/generate/values.go
install/helm/gloo/templates/2-gloo-service.yaml
install/helm/gloo/templates/8-gateway-proxy-service.yaml
install/test/helm_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1410

Set external traffic policy on gateway proxy service via helm

---

changelog/v0.20.8/fix-external-traffic-policy.yaml
install/helm/gloo/generate/values.go
install/helm/gloo/templates/2-gloo-service.yaml
install/helm/gloo/templates/8-gateway-proxy-service.yaml
install/test/helm_test.go

port of https://github.com/solo-io/gloo/pull/1412 to `feature-rc1`
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1410

Set external traffic policy on gateway proxy service via helm (#1412)

---

Gopkg.lock
changelog/v0.21.0/ext-authz-filter-builder.yaml
projects/gloo/pkg/plugins/extauth/extauth_suite_test.go
projects/gloo/pkg/plugins/extauth/filter.go
projects/gloo/pkg/plugins/extauth/filter_test.go
projects/gloo/pkg/plugins/extauth/plugin.go

Port custom auth filter builder

---

changelog/v0.21.0/process-custom-auth-configs.yaml
projects/gloo/pkg/plugins/extauth/plugin.go
projects/gloo/pkg/plugins/extauth/plugin_test.go

Process custom auth configurations

---

Gopkg.lock
changelog/v0.21.0/activate-custom-auth-plugin.yaml
projects/gloo/pkg/plugins/registry/registry.go
test/e2e/custom_auth_test.go
test/kube2e/gateway/gateway_test.go
test/services/gateway.go

Port of #1408 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1396

Port custom auth

---

Gopkg.lock
Gopkg.toml
changelog/v0.21.0/reporting-signatures.yaml
pkg/utils/setuputils/main_setup.go
pkg/utils/usage/instance_metadata.go

BOT NOTES: 
resolves https://github.com/solo-io/solo-projects/issues/1231

Send unique signature when reporting usage

---

Gopkg.lock
Gopkg.toml
changelog/v0.21.0/bump-go-utils.yaml
projects/gateway/pkg/conversion/gateway.go
projects/gateway/pkg/conversion/gateway_test.go
projects/gateway/pkg/translator/translator_test.go
test/consulvaulte2e/consul_vault_test.go
test/e2e/consul_test.go
test/e2e/gateway_test.go
test/e2e/happypath_test.go
test/kube2e/gateway/gateway_test.go
test/kube2e/gateway/robustness_test.go

Port of https://github.com/solo-io/gloo/pull/1430 to `feature-rc1` cc @marcogschmidt

Bump go-utils (#1430)

---

changelog/v0.20.9/remove-orphaned-rbac-role.yaml
install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml

Remove orphaned kube-crd-creator RBAC role from chart (#1493)

---

Gopkg.lock
Gopkg.toml
changelog/v0.20.9/skbump.yaml
projects/discovery/pkg/fds/updater.go
projects/gateway/pkg/api/v1/gateway.sk.go
projects/gateway/pkg/api/v1/route_table.sk.go
projects/gateway/pkg/api/v1/virtual_service.sk.go
projects/gateway/pkg/api/v2/gateway.sk.go
projects/gateway/pkg/syncer/translator_syncer.go
projects/gloo/pkg/api/v1/artifact.sk.go
projects/gloo/pkg/api/v1/endpoint.sk.go
projects/gloo/pkg/api/v1/enterprise/plugins/extauth/v1/auth_config.sk.go
projects/gloo/pkg/api/v1/proxy.sk.go
projects/gloo/pkg/api/v1/secret.sk.go
projects/gloo/pkg/api/v1/settings.sk.go
projects/gloo/pkg/api/v1/upstream.sk.go
projects/gloo/pkg/api/v1/upstream_group.sk.go
projects/gloo/pkg/upstreams/kubernetes/conversions.go
projects/ingress/pkg/api/v1/ingress.sk.go
projects/ingress/pkg/api/v1/kube_service.sk.go

port of https://github.com/solo-io/gloo/pull/1507

update solokit (#1507)

---

docs/content/gloo_routing/virtual_services/routes/matching_rules/header_matching/_index.md
docs/content/gloo_routing/virtual_services/routes/matching_rules/header_matching/virtual-service.yaml

port the invert match docs and add a fifth example
from https://github.com/solo-io/solo-docs/pull/634

port invertMatch docs and add 5th case

---

changelog/v1.0.0-rc1/mobile-docs-theme-fix.yaml
docs/Makefile
docs/content/changelog/_index.md

Improves docs theme for use on mobile (easier access to search)
Fixes links to product-specific changelogs

bump docs theme for mobile compat, fix changelog links

---

changelog/v0.20.10/export-filter-stage.yaml
projects/gloo/pkg/plugins/ratelimit/plugin.go

Export rate limiting filter stage info from gloo so solo-projects can consume it

Export rate limit filter stage from gloo

---

changelog/v0.20.10/generate-kube-types.yaml

fix changelog

---

docs/content/gloo_routing/tls/client_tls.md
docs/content/gloo_routing/tls/client_tls_service_annotations.md

Service annotation docs

---

changelog/v1.0.0-rc2/add-docs-custom-intervention-msg.yaml
docs/content/gloo_routing/gateway_configuration/waf/_index.md

update docs for new WAF feature
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1457

Docs for custom intervention message

---

changelog/v1.0.0-rc2/extauth-docs-details.yaml
docs/content/gloo_routing/virtual_services/security/_index.md

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1537

Clarify some ext auth deployment modes docs

---

changelog/v1.0.0-rc2/fix-install-docs-to-reference-global-overrrides.yaml
docs/content/installation/enterprise/_index.md
docs/content/installation/gateway/kubernetes/_index.md

the old format is still documented, fix

Update install docs to use correct rbac override

---

docs/content/gloo_routing/tls/_index.md
docs/content/gloo_routing/tls/client_tls.md
docs/content/gloo_routing/tls/client_tls_service_annotations.md
docs/content/gloo_routing/virtual_services/rate_limiting/envoy/_index.md
docs/content/gloo_routing/virtual_services/security/_index.md
docs/content/gloo_routing/virtual_services/security/apikey_auth/_index.md
docs/content/gloo_routing/virtual_services/security/basic_auth/_index.md
docs/content/gloo_routing/virtual_services/security/configuration_format_history/_index.md
docs/content/gloo_routing/virtual_services/security/plugin_auth/_index.md
docs/content/introduction/deployment_arch.md
docs/content/introduction/faq.md

Fix broken links in docs introduced by https://github.com/solo-io/gloo/pull/1335

Fix broken links related to doc-move and versioning changes

---

changelog/v1.0.0-rc2/add-docs-dlp.yaml
docs/content/gloo_routing/virtual_services/data_loss_prevention/_index.md
docs/content/gloo_routing/virtual_services/data_loss_prevention/us-echo-test.yaml
docs/content/gloo_routing/virtual_services/data_loss_prevention/vs-json-upstream.yaml

cc @EItanya 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1500

Add DLP docs

---

changelog/v1.0.0-rc2/warn2debug.yaml
projects/gloo/pkg/utils/sanitize.go

port of https://github.com/solo-io/gloo/pull/1605
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1604

fix log (#1605)

---

docs/content/gloo_routing/virtual_services/data_loss_prevention/_index.md

silly markdown error doesn't render bulleted list without newline after colon 🤦‍♂

Fix formatting

---

Gopkg.lock
Gopkg.toml
changelog/v1.0.0-rc2/role-suffix.yaml
install/helm/gloo/generate/values.go
install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
install/helm/gloo/templates/_helpers.tpl
install/test/rbac_test.go
test/kube2e/gateway/gateway_suite_test.go

port of https://github.com/solo-io/gloo/pull/1588
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1459

Allow role/role-binding names to take on unique suffixes (#1588)

---

changelog/v1.0.0-rc3/glooctl-dump-yaml.yaml
docs/cli/glooctl_debug_yaml.md
docs/content/cli/glooctl_debug.md
docs/content/cli/glooctl_debug_yaml.md
pkg/cliutil/install/kubernetes.go
projects/gloo/cli/pkg/cmd/debug/debug.go
projects/gloo/cli/pkg/cmd/debug/debug_suite_test.go
projects/gloo/cli/pkg/cmd/debug/debug_test.go
projects/gloo/cli/pkg/cmd/debug/root.go
projects/gloo/cli/pkg/cmd/install/uninstall_test.go
projects/gloo/cli/pkg/constants/commands.go

port of https://github.com/solo-io/gloo/pull/1649
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1650

Glooctl dump yaml (#1649)

---

changelog/v0.21.1/remove-logging.yaml
projects/clusteringress/pkg/translator/translator_syncer.go
projects/discovery/pkg/fds/syncer/discovery_syncer.go
projects/discovery/pkg/uds/syncer/discovery_syncer.go
projects/gateway/pkg/syncer/translator_syncer.go
projects/gloo/pkg/discovery/run.go
projects/gloo/pkg/syncer/envoy_translator_syncer.go
projects/ingress/pkg/status/status_syncer.go
projects/ingress/pkg/translator/translator_syncer.go
projects/knative/pkg/translator/translator_syncer.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1679

Remove overly verbose syncer logger

---

Gopkg.lock
changelog/v0.21.1/secret-redacter.yaml
pkg/utils/syncutil/log_redacter.go
pkg/utils/syncutil/log_redacter_test.go
pkg/utils/syncutil/syncutil_suite_test.go
projects/clusteringress/pkg/translator/translator_syncer.go
projects/discovery/pkg/fds/syncer/discovery_syncer.go
projects/discovery/pkg/uds/syncer/discovery_syncer.go
projects/gateway/pkg/syncer/translator_syncer.go
projects/gloo/pkg/discovery/run.go
projects/gloo/pkg/syncer/envoy_translator_syncer.go
projects/ingress/pkg/status/status_syncer.go
projects/ingress/pkg/translator/translator_syncer.go
projects/knative/pkg/translator/translator_syncer.go

Snapshot printed out during the consul end to end tests. Note the `[REDACTED]` text.
```
Artifacts:[]
Endpoints:[upstreams:<name:consul-svc:consul namespace:gloo-system > address:127.0.0.1 port:8300 metadata:<name:consul-consul namespace:gloo-system resource_version:12 labels:<key:dc_dc1 value:1 > >  upstreams:<name:consul-svc:my-svc namespace:gloo-system > address:10.0.0.115 port:60950 metadata:<name:my-svc-my-svc-1 namespace:gloo-system resource_version:14 labels:<key:dc_dc1 value:1 > labels:<key:tag_1 value:1 > labels:<key:tag_svc value:1 > >  upstreams:<name:consul-svc:petstore namespace:gloo-system > address:10.0.0.115 port:1234 metadata:<name:petstore-petstore-1 namespace:gloo-system resource_version:15 labels:<key:dc_dc1 value:1 > labels:<key:tag_petstore value:1 > …
```

Implement secret redacter for printing snapshots

---

Gopkg.lock
changelog/v1.0.0-rc3/remove-logging.yaml
changelog/v1.0.0-rc3/secret-redacter.yaml
pkg/utils/syncutil/log_redacter.go
pkg/utils/syncutil/log_redacter_test.go
pkg/utils/syncutil/syncutil_suite_test.go
projects/clusteringress/pkg/translator/translator_syncer.go
projects/discovery/pkg/fds/syncer/discovery_syncer.go
projects/discovery/pkg/uds/syncer/discovery_syncer.go
projects/gateway/pkg/syncer/translator_syncer.go
projects/gloo/pkg/discovery/run.go
projects/gloo/pkg/syncer/envoy_translator_syncer.go
projects/ingress/pkg/status/status_syncer.go
projects/ingress/pkg/translator/translator_syncer.go
projects/knative/pkg/translator/translator_syncer.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1679

Cherry pick secret redacter

---

changelog/v0.21.2/add-linkerd-helm-option.yaml
install/helm/gloo/generate/values.go
install/helm/gloo/templates/18-settings.yaml
install/helm/gloo/values-gateway-template.yaml
install/helm/gloo/values-knative-template.yaml

Cherry-pick of #1652 onto `master`.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1651

Cherry-pick: Linkerd Helm Chart Value

---

docs/content/getting_started/_index.md

Add a Getting Started section to the docs as requested.
We wanted to have a friendly starting place for users to make sure they had the necessary prerequisites to start using Gloo.

Adding getting started

---

docs/content/gloo_routing/_index.md
docs/content/gloo_routing/gateway_configuration/access_logging/_index.md
docs/content/gloo_routing/gateway_configuration/waf/_index.md
docs/content/gloo_routing/virtual_services/data_loss_prevention/_index.md
docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/_index.md
docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/add_headers_to_body/_index.md
docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/change_response_status/_index.md
docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/enrich_access_logs/_index.md
docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/extract_query_params/_index.md
docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/update_request_uri/_index.md
docs/content/gloo_routing/virtual_services/security/_index.md
docs/content/gloo_routing/virtual_services/security/apikey_auth/_index.md
docs/content/gloo_routing/virtual_services/security/ldap/_index.md
docs/content/gloo_routing/virtual_services/security/opa/_index.md
docs/content/gloo_routing/virtual_services/security/plugin_auth/_index.md
docs/content/introduction/deployment_arch.md

Revert "ww"

---

changelog/v1.1.1/anti-affinity.yaml
docs/content/installation/gateway/kubernetes/values.txt
install/helm/gloo/generate/values.go
install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
install/test/helm_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1775

Fix anti-affinity helm value

---

docs/content/upgrading/1.0.0.md
docs/content/upgrading/faq.md
docs/content/upgrading/upgrade_steps.md

The easiest thing may be to check out the branch and run it yourself 🤷‍♂

v1.0.0 Upgrade Guide

---

README.md

---
Notice: Development on `master` has slowed in favor of `feature-rc1`, which is under active development. 
Here's how to handle this.
Checklist
---
Explain your changes here
Why were these changes made? Alternatives considered? Any additional context to add?

added spacer to menu

---

docs/content/installation/gateway/kubernetes/_index.md
docs/content/installation/gateway/kubernetes/helm_chart_values.md
docs/content/installation/glooctl_setup.md

Solution
Update the glooctl and gloo gateway docs for clarity and accuracy.
Context
Add an intro section to the gloo gateway install page
Moved the helm values table to its own page
Updated the uninstall section to include removing namespace and CRDs
Need to add a helm uninstall section once helm 3 is working properly

updated docs for gateway install

---

docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/static_upstream/virtual-service.yaml

Fix static upstream tutorial

---

docs/content/_index.md

use versioned path for link

---

docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/grpc_to_rest/_index.md

fix tutorial yaml indent

---

Gopkg.lock
Gopkg.toml
Makefile
changelog/v1.2.0/helm-3.yaml
docs/content/installation/gateway/kubernetes/values.txt
go.mod
hack/utils/oss_compliance/third_party_licenses.txt
projects/clusteringress/api/external/knative/cluster_ingress.go
projects/clusteringress/pkg/api/custom/knative/cache.go
projects/clusteringress/pkg/api/custom/knative/knative_clusteringress_client.go
projects/clusteringress/pkg/translator/translate_test.go
projects/clusteringress/pkg/translator/translator_syncer.go
projects/clusteringress/pkg/translator/translator_syncer_test.go
projects/ingress/pkg/setup/setup_syncer.go
projects/knative/pkg/translator/translate.go

Knative 0.8.1 is not compatible with the kubernetes 1.16 libraries.

Use knative/serving 0.10.0

---

changelog/v1.2.4/enterprise-tag-fix.yaml
pkg/version/enterprise.go
projects/gloo/cli/pkg/cmd/install/installer.go

Readd version.EnterpriseTag for test overrides and future flag overrides.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1861

Enterprise tag fix

---

projects/gloo/pkg/upstreams/consul/upstream_client_test.go

https://github.com/solo-io/gloo/pull/1829/files should not have been merged until all PR comments were addressed.
namely, we need to re-enable this functioning test.

Re-enable consul test

---

docs/content/security/waf/_index.md

Update WAF docs for 1.x

---

docs/content/security/rate_limiting/_index.md
docs/content/security/rate_limiting/envoy/_index.md
docs/content/security/rate_limiting/rulepriority/_index.md
docs/content/security/rate_limiting/rulepriority/serverconfig.yaml
docs/content/security/rate_limiting/rulepriority/vsconfig.yaml
docs/content/security/rate_limiting/simple/_index.md

1. Update rate limit docs for 1.x (format changes and whatnot)
2. Add docs example for rate limit rule priority (tested against 1.0.0-rc4)

Ratelimit 1.x docs

---

docs/content/gloo_routing/virtual_services/https_redirect.md

https redirect docs
https://github.com/solo-io/gloo/issues/1908

Docs https redirect example

---

docs/content/installation/enterprise/_index.md

update link to Gloo enterprise trial

---

docs/content/security/auth/_index.md
docs/content/security/auth/apikey_auth/_index.md
docs/content/security/auth/apikey_auth/test-no-auth-vs.yaml
docs/content/security/auth/basic_auth/_index.md
docs/content/security/auth/basic_auth/test-no-auth-vs.yaml
docs/content/security/auth/configuration_format_history/_index.md
docs/content/security/auth/custom_auth/_index.md
docs/content/security/auth/jwt/access_control.md
docs/content/security/auth/jwt/claim_routing.md
docs/content/security/auth/ldap/_index.md
docs/content/security/auth/ldap/vs-auth-ldap.sh
docs/content/security/auth/ldap/vs-echo-no-auth.sh
docs/content/security/auth/oauth/_index.md
docs/content/security/auth/oauth/dex/_index.md
docs/content/security/auth/oauth/google/_index.md
docs/content/security/auth/opa/_index.md
docs/content/security/auth/plugin_auth/_index.md
docs/layouts/shortcodes/extauth_version_info_note

* updates extauth docs for breaking changes in Gloo 1.0
* updates petstore usages to petclinic, which functions the same but works on k8s 1.16+
* some cleanup to make examples more copy-pastable

Update Extauth docs for 1.0.0-rc5

---

changelog/v1.2.11/upgrades.yaml
projects/gloo/pkg/plugins/basicroute/plugin.go
projects/gloo/pkg/plugins/basicroute/plugin_test.go
projects/gloo/pkg/plugins/hcm/plugin.go
projects/gloo/pkg/plugins/hcm/plugin_test.go
projects/gloo/pkg/plugins/utils/upgradeconfig/upgradeconfig.go
projects/gloo/pkg/plugins/utils/upgradeconfig/upgradeconfig_suite_test.go
projects/gloo/pkg/plugins/utils/upgradeconfig/upgradeconfig_test.go

- always clear the upgrade configs list
- add server side validation
- make sure defaults are applied when settings are nil

modify upgrade related code to be more defensive

---

Makefile

gofmt and goimports on all your changed *.go files

Convenience fmt target

---

changelog/v1.2.13/dedupe-stats-config.yaml
go.mod
go.sum
projects/accesslogger/cmd/main.go
projects/accesslogger/pkg/runner/run.go
projects/discovery/cmd/main.go
projects/gateway/cmd/main.go
projects/gloo/cmd/main.go

Upgrade the stats server version to DRY out start up config
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1998

Ensure consistency of stats server startup config

---

changelog/v1.2.13/multiple-wasm-filters.yaml
docs/data/ProtoMap.yaml
projects/gloo/api/v1/options/wasm/wasm.proto
projects/gloo/pkg/api/v1/options/wasm/wasm.pb.go
projects/gloo/pkg/plugins/wasm/plugin.go
projects/gloo/pkg/plugins/wasm/plugin_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1956

Multiple wasm filters

---

Makefile
docs/content/installation/gateway/docker-compose-file/_index.md

cleanup from https://github.com/solo-io/gloo/issues/1843

Update feature-rc1 refs to master

---

changelog/v1.2.14/fix-outdated-ratelimit-docs.yaml
docs/content/security/rate_limiting/_index.md
docs/content/security/rate_limiting/envoy/_index.md
docs/content/security/rate_limiting/rulepriority/_index.md
docs/content/security/rate_limiting/simple/_index.md

@bdecoste https://github.com/solo-io/gloo/issues/2065
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2065

Fix some outdate ratelimit info and some syntax highlighting

---

docs/content/observability/metrics.md

Update docs to reflect changes made in https://github.com/solo-io/gloo/pull/2010

Update docs for recent changes to stats and metrics

---

Makefile
changelog/v1.2.15/assets-only-release.yaml

Don't create PRs against homebrew/fish during patch releases.

Fix release assets

---

docs/content/security/auth/_index.md
docs/content/security/auth/apikey_auth/_index.md
docs/content/security/auth/basic_auth/_index.md
docs/content/security/auth/configuration_format_history/_index.md
docs/content/security/auth/ldap/vs-auth-ldap.sh
docs/content/security/auth/oauth/dex/_index.md
docs/content/security/auth/oauth/google/_index.md
docs/content/security/auth/opa/_index.md

Fix example of how to disable extauth on a virtual service.

Fix extauth docs

---

changelog/v1.3.1/dlp-regex.yaml
docs/content/security/data_loss_prevention/_index.md

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2122

2122 correct regex in DLP doc

---

changelog/v1.3.1/correct-grpc-web-doc.yaml
docs/content/gloo_routing/gateway_configuration/grpc_web/_index.md

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2079

Correct grpc-web disable yaml in doc

---

changelog/v1.3.1/cert-manager-doc.yaml
docs/content/gloo_integrations/cert_manager/_index.md

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2081

2081 update cert-manager in doc to 0.12

---

docs/content/gloo_routing/virtual_services/routes/route_destinations/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/kubernetes_services/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/multiple_upstreams/multi_destination/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/multiple_upstreams/subsets/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/multiple_upstreams/upstream_groups/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/discovered_upstream/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/grpc_to_rest/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/static_upstream/_index.md

Minor changes to the route destination page and some of the subpages.

Update route destination main page

---

docs/content/gloo_routing/virtual_services/routes/matching_rules/query_parameter_matching/_index.md

Update the query parameter doc based on the style guide and add video content.  Ref issue #2186.

Add video and update structure

---

docs/content/gloo_routing/virtual_services/routes/matching_rules/http_method_matching/_index.md
docs/content/gloo_routing/virtual_services/routes/matching_rules/path_matching/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/kubernetes_services/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/multiple_upstreams/multi_destination/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/multiple_upstreams/subsets/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/multiple_upstreams/upstream_groups/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/discovered_upstream/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/grpc_to_rest/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/static_upstream/_index.md

Update the http method match doc based on the style guide and add video content. Ref issue #2190.

Add video to http method matching

---

changelog/v1.3.2/fix-notificaton-channel-close.yaml
projects/gateway/pkg/syncer/setup_syncer.go
projects/gateway/pkg/validation/notification_channel.go
projects/gateway/pkg/validation/notification_channel_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2070

gateway: retry connection to notification stream

---

changelog/v1.2.15/fix-notificaton-channel-close.yaml
projects/gateway/pkg/syncer/setup_syncer.go
projects/gateway/pkg/validation/notification_channel.go
projects/gateway/pkg/validation/notification_channel_test.go

* gateway: retry connection to notification stream
* fix test race
* fix comment

gateway: retry connection to notification stream (#2181)

---

docs/content/gloo_routing/gateway_configuration/http_connection_manager/_index.md
docs/content/gloo_routing/websockets.md

Related to https://github.com/solo-io/gloo/pull/1784 and fixes https://github.com/solo-io/gloo/issues/2143

Document websocket support and fine tuning. 

---

Makefile
changelog/v1.3.2/push-helm-chart-to-registry.yaml
cloudbuild.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2074

Push helm chart to solo-public image repository every CI build

---

changelog/v1.3.3/route-table-selector-docs.yaml
docs/content/gloo_routing/virtual_services/delegation/_index.md
docs/content/security/auth/custom_auth/_index.md

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2201
resolves https://github.com/solo-io/gloo/issues/2200
resolves https://github.com/solo-io/gloo/issues/2054

Route table selector docs

---

changelog/v1.3.3/fix-helm-hooks.yaml
install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
install/test/helm_test.go
projects/gloo/cli/pkg/cmd/install/installer_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2212

Remove unnecessary `pre-upgrade` Helm hooks to avoid failing on upgrades

---

changelog/v1.3.3/change-glooctl-ui-to-dashboard.yaml
docs/content/cli/glooctl.md
docs/content/cli/glooctl_dashboard.md
projects/gloo/cli/pkg/cmd/dashboard/root.go
projects/gloo/cli/pkg/cmd/root.go
projects/gloo/cli/pkg/constants/commands.go
projects/gloo/cli/pkg/flagutils/common.go

How would a changelog look for this? Should I link to the old issue? Is it a `FIX` even though it's kind of a breaking change?

change `glooctl ui` command to `glooctl dashboard` per Idit's request

---

changelog/v1.3.3/fix-more-helm-hooks.yaml
install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
projects/gloo/cli/pkg/cmd/install/installer_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2212

Remove unnecessary post-upgrade Helm hooks

---

docs/content/installation/ingress/_index.md
docs/content/installation/knative/_index.md

Update the knative and ingress installation docs to match the changes made to the Helm chart. This is in regards to issue #1997

Update knative and ingress install docs

---

changelog/v1.3.4/fix-docs-dropdown.yaml
docs/Makefile

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2322

Use new theme

---

changelog/v1.3.4/helm-value-to-disable-proxy-gc.yaml
docs/content/installation/gateway/kubernetes/values.txt
install/helm/gloo/generate/values.go
install/helm/gloo/templates/18-settings.yaml
install/helm/gloo/values-template.yaml
install/test/helm_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2323

Expose the `disableProxyGarbageCollection` settings field in Helm chart

---

changelog/v1.3.5/envoy-deprecated-fields.yaml
projects/gloo/pkg/plugins/ratelimit/raw_util.go
projects/gloo/pkg/plugins/ratelimit/raw_util_test.go
projects/gloo/pkg/translator/route_config.go
test/e2e/happypath_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2395

fix method regex

---

changelog/v1.3.6/docs.yaml
docs/content/advanced_configuration/consul_kv.md
docs/content/advanced_configuration/node_port.md
docs/content/dev/setting-up-dev-environment.md
docs/content/dev/writing-upstream-plugins.md
docs/content/gloo_routing/tls/client_tls.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/aws_lambda/_index.md
docs/content/installation/gateway/kubernetes/cluster_setup.md

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2369
resolves https://github.com/solo-io/gloo/issues/2360
resolves https://github.com/solo-io/gloo/issues/2154
resolves https://github.com/solo-io/gloo/issues/2125
resolves https://github.com/solo-io/gloo/issues/1519

Docs fixes

---

docs/content/getting_started/_index.md
docs/content/gloo_integrations/service_mesh/gloo_istio_mtls.md
docs/content/gloo_routing/gateway_configuration/access_logging/_index.md
docs/content/gloo_routing/tls/client_tls.md
docs/content/gloo_routing/tls/server_tls.md
docs/content/gloo_routing/virtual_services/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/consul_services/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/multiple_upstreams/upstream_groups/_index.md
docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/rest_endpoint/_index.md
docs/content/installation/enterprise/_index.md
docs/content/installation/gateway/kubernetes/helm_chart_values.md
docs/content/observability/grafana/deployment/_index.md
docs/content/observability/metrics.md
docs/content/observability/ports.md
docs/content/observability/prometheus/_index.md
docs/content/observability/tracing.md
docs/content/observability/usage_statistics.md
docs/content/security/auth/jwt/claim_routing.md
docs/content/security/rate_limiting/envoy/_index.md
docs/content/security/rate_limiting/simple/_index.md
docs/content/upgrading/faq.md
docs/content/upgrading/upgrade_steps.md

Switching out relative links to use versioned links per issue #1781

switch out links for shortcode

---

docs/content/gloo_routing/virtual_services/delegation/_index.md

Use less ambiguous example values in delegation doc

---

changelog/v1.3.6/readonly-ui.yaml
docs/content/advanced_configuration/gloo-readonly-ui.md
docs/content/installation/enterprise/_index.md

Add docs to explain how to install read-only UI in both open-source and enterprise.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2378

Docs readonly ui

---

docs/content/advanced_configuration/gloo-readonly-ui.md

simple docs update. add shortcut to open the UI for users

Add command to open gloo ui

---

docs/content/gloo_routing/virtual_services/routes/route_destinations/consul_services/_index.md

Fix error in consul doc: Links to the wrong proto, which is very confusing.

Fix error in consul doc

---

changelog/v1.3.6/docs-styles.yaml
docs/Makefile

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2351

bump docs version

---

docs/content/advanced_configuration/gateway-proxy-config.md
docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/_index.md
docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/add_headers_to_body/_index.md
docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/change_response_status/_index.md
docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/enrich_access_logs/_index.md
docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/extract_query_params/_index.md
docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/update_request_uri/_index.md
docs/content/introduction/faq.md
docs/content/security/auth/jwt/access_control.md
docs/content/security/auth/oauth/_index.md
docs/content/security/auth/opa/_index.md
docs/content/security/auth/plugin_auth/_index.md
docs/content/upgrading/1.0.0.md

After running the html-proofer tool, I found a number of broken links in the docs. This fixes all the bad links except what was found in the API.
Issue #2418

Fixing broken links

---

changelog/v1.3.6/served-config.yaml
projects/gloo/cli/pkg/xdsinspection/get_last_config.go
projects/gloo/pkg/defaults/port.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2381

Make 'glooctl proxy served-config' work in Gloo MTLS mode

---

changelog/v1.3.7/discover-vs-in-all-namespaces.yaml
docs/content/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk.md
projects/gateway/api/v1/gateway.proto
projects/gateway/pkg/api/v1/gateway.pb.go
projects/gateway/pkg/translator/http.go
projects/gateway/pkg/translator/translator_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2156

Discover vs in all namespaces

---

changelog/v1.3.7/fix-extauth-sidecar.yaml
install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
projects/envoyinit/cmd/Dockerfile.envoyinit

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2156

fix helm template for extauth sidecar

---

Makefile

Restores syntax highlighting in IDE

Fix syntax error in Makefile

---

changelog/v1.3.8/sds-envoy-helm-values.yaml
docs/content/installation/gateway/kubernetes/values.txt
install/helm/gloo/generate.go
install/helm/gloo/generate/values.go
install/helm/gloo/templates/1-gloo-deployment.yaml
install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
install/helm/gloo/values-template.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2134

add gloo MTLS sds and envoy image helm values

---

docs/content/security/auth/jwt/_index.md

See https://github.com/solo-io/gloo/issues/2495#issuecomment-590894850

Add enterprise-only disclaimer to JWT landing page

---

docs/content/gloo_routing/validation/partially_invalid_vs.yaml

Another small fix: routePlugins --> options

Fix route replacement docs

---

docs/content/operations/_index.md
docs/content/operations/debugging_gloo/_index.md
docs/content/operations/production_deployment/_index.md

TODO:
Fill out Production Lockdown doc a bit more
Add debugging the control plane to the debug doc
cc @lgadban @bdecoste

first pass operations doc

---

changelog/v1.3.14/gateway-ipv4-only.yaml
docs/content/reference/values.txt
docs/content/security/auth/plugin_auth/_index.md
install/helm/gloo/generate/values.go
install/helm/gloo/templates/8-default-gateways.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2425

Add ipv4Only helm value

---

changelog/v1.3.14/cors-regex.yaml
projects/gloo/pkg/plugins/cors/plugin.go
projects/gloo/pkg/plugins/cors/route_plugin_test.go
projects/gloo/pkg/plugins/cors/vhost_plugin_test.go
test/e2e/cors_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2614

fix cors regex

---

changelog/v1.3.13/downstream-mTLS-docs.yaml
docs/content/gloo_routing/tls/server_tls.md

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2598

Setting up downstream mTLS in virtual services docs

---

changelog/v1.3.15/glooctl-check-auth-configs.yaml
projects/gloo/cli/pkg/cmd/check/root.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2036

Add authconfigs to glooctl check

---

changelog/v1.3.15/helm.yaml
install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
install/test/helm_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2647

quote envoy extra args

---

changelog/v1.13.6/fix-title.yaml
docs/Makefile

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2613

Update docs theme

---

changelog/v1.13.6/fix-title.yaml
changelog/v1.3.16/glooctl-warnings.yaml
pkg/listers/mocks/mock_listers.go
pkg/utils/selectionutils/mocks/mock_virtual_service.go
projects/gloo/cli/pkg/cmd/check/root.go
projects/gloo/cli/pkg/cmd/install/mocks/mock_helm_client.go
projects/gloo/cli/pkg/cmd/install/mocks/mock_helm_installation.go
projects/gloo/cli/pkg/cmd/install/mocks/mock_helm_release_list.go
projects/gloo/cli/pkg/cmd/install/mocks/mock_helm_uninstallation.go
projects/gloo/cli/pkg/cmd/version/mocks/mock_watcher.go
projects/gloo/pkg/discovery/mocks/mock_discovery.go
projects/gloo/pkg/plugins/consul/mocks/dnsresolver_mock.go
projects/gloo/pkg/plugins/kubernetes/mocks/kubesharedfactory_mock.go
projects/gloo/pkg/plugins/wasm/mocks/mock_cache.go
projects/gloo/pkg/upstreams/consul/mocks/mock_consul_client.go
projects/gloo/pkg/upstreams/consul/mocks/mock_watcher.go
projects/metrics/pkg/metricsservice/mocks/mock_metrics_stream.go
projects/metrics/pkg/metricsservice/mocks/mock_storage.go
test/mocks/cache/corecache.go
test/mocks/gloo/validation_client.go
test/mocks/kubernetes/kubeinterface.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2613
resolves https://github.com/solo-io/gloo/issues/2659

report warnings in glooctl check

---

docs/content/guides/integrations/ingress/_index.md

Fix render of step 3 here: https://docs.solo.io/gloo/latest/guides/integrations/ingress/
Also, fix the numbering, as markdown repeated 1. list numbering doesn't work with our code blobs in the middle of the list

Fix docs render of ingress step 3

---

changelog/v1.3.16/glooctl-uninstall-prometheus-resources.yaml
projects/gloo/cli/pkg/cmd/install/util.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2419

Glooctl uninstall prometheus resources

---

docs/content/guides/security/auth/plugin_auth/_index.md

Updating plugin auth docs for 1.3.0, after testing against 1.3.0

Tested plugin auth for 1.3.0

---

docs/content/guides/observability/tracing.md

previous config was out-of-date, by default the zipkin
trace config uses a now deprecated `collector_endpoint_version`

fix zipkin tracing example

---

changelog/v1.4.0-beta1/consul-eds-err-race.yaml
projects/gloo/pkg/plugins/consul/eds.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2736

consul eds err chan race

---

changelog/v1.4.0-beta1/bump-envoy-fix-envoy-regression.yaml
changelog/v1.4.0-beta1/bump-envoy.yaml
projects/envoyinit/cmd/Dockerfile.envoyinit

Bumping gloo-envoy to pickup envoy dependency bump to address an envoy regression: https://github.com/envoyproxy/envoy/issues/10655

Fix envoy regression before release

---

docs/content/installation/advanced_configuration/gateway-proxy-config.md

Fix broken helm value example

---

docs/content/guides/traffic_management/destination_types/discovered_upstream/_index.md

clarify UDS

---

changelog/v1.3.19/translator-syncer-extension-reporter.yaml
projects/gloo/pkg/syncer/setup_syncer.go
projects/gloo/pkg/syncer/translator_syncer.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2719

translator syncer extension reporter

---

changelog/v1.4.0-beta2/gateway-ssl-ipv4.yaml
install/helm/gloo/templates/8-default-gateways.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2425

ipv4 gateway ssl

---

changelog/v1.4.0-beta3/fix-proxy-garbage-collection.yaml
projects/gloo/pkg/syncer/envoy_translator_syncer.go
projects/gloo/pkg/syncer/translator_syncer.go
projects/gloo/pkg/xds/envoy.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2721

fix proxy garbage collection

---

changelog/v1.4.0-beta4/fix-proxy-status-race.yaml

Forgot to update the changelog in https://github.com/solo-io/gloo/pull/2779 to list the actual changes to fix the race, rather than the initial solution

Make changelog more accurate

---

changelog/v1.4.0-beta4/fix-documented-helm-values.yaml
docs/content/reference/values.txt
install/helm/gloo/generate/values.go
install/helm/gloo/templates/10-ingress-deployment.yaml
install/helm/gloo/templates/6-access-logger-deployment.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2758

Fix documented helm values for gateway-proxy resources

---

changelog/v1.4.0-beta4/fix-glooctl-kubectl-timeouts.yaml
docs/content/operations/debugging_gloo/_index.md
pkg/cliutil/uri.go
projects/gloo/cli/pkg/cmd/check/proxy_prom_stats.go
projects/gloo/cli/pkg/cmd/gateway/dump.go
projects/gloo/cli/pkg/cmd/gateway/logs.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2771

fix glooctl kubectl timeouts

---

changelog/v1.3.21/fix-documented-helm-values.yaml
docs/content/reference/values.txt
install/helm/gloo/generate/values.go
install/helm/gloo/templates/10-ingress-deployment.yaml
install/helm/gloo/templates/6-access-logger-deployment.yaml

backport of https://github.com/solo-io/gloo/pull/2784
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2758

Fix documented helm values for gateway-proxy resources (#2784)

---

changelog/v1.4.0-beta4/upstream-status-service-dne.yaml
changelog/v1.4.0-beta5/upstream-status-service-dne.yaml
projects/gloo/pkg/plugins/kubernetes/plugin.go
projects/gloo/pkg/plugins/kubernetes/plugin_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2660

Upstream bad service

---

docs/content/guides/integrations/service_mesh/gloo_istio_mtls.md

fixing wrong documented docker image tag

Fix istio 1.5 docs

---

changelog/v1.4.0-beta5/fix-docs-releases.yaml
docs/Makefile
docs/README.md
docs/docs-staging.yaml

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2762

decouple docs makefile's TAGGED_VERSION and the docs url

---

docs/content/guides/security/opa/_index.md

fix rendering of OPA webhook docs

---

docs/content/guides/security/rate_limiting/envoy/_index.md
docs/content/guides/security/rate_limiting/envoy/serverconfig.yaml
docs/content/guides/security/rate_limiting/envoy/vsconfig.yaml

Clean up yaml examples

---

changelog/v1.3.23/fix-docs-releases.yaml
docs/Makefile
docs/README.md
docs/docs-staging.yaml

* decouple docs makefile's TAGGED_VERSION and the docs url
* Add instructions on how to test locally
* Update hugo-solo-io theme
* remove file
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2762

decouple docs makefile's TAGGED_VERSION and the docs url (#2819)

---

changelog/v1.4.0-beta6/clarify-upgrade-risks.yaml
docs/content/operations/upgrading/1.3.0.md

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2807

Clarify upgrade risk in adopting helm resources

---

docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/circuit_breaker.proto.sk.md
docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/retries/retries.proto.sk.md
projects/gloo/api/v1/circuit_breaker.proto
projects/gloo/api/v1/options/retries/retries.proto
projects/gloo/pkg/api/v1/circuit_breaker.pb.go
projects/gloo/pkg/api/v1/options/retries/retries.pb.go

resolves #2855 
resolves #2858

Fix docs links / descriptions

---

changelog/v1.4.0-beta7/fix-ssl-glooctl.yaml
projects/gloo/cli/pkg/cmd/create/secret/secret_test.go
projects/gloo/cli/pkg/cmd/options/secret.go
projects/gloo/pkg/utils/ssl.go
projects/gloo/pkg/utils/ssl_test.go

allow empty ssl config set on upstreams
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2823
resolves https://github.com/solo-io/gloo/issues/2871

suppor ssl with just ca in glooctl;

---

changelog/v1.4.0-beta7/ensure-hugo-version-matches.yaml
cloudbuild.yaml
docs/Makefile

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2856

Ensure docs build match ci

---

docs/content/installation/platform_configuration/cluster_setup.md

Initial documentation for installation to OCP

add openshift setup docs

---

docs/content/installation/platform_configuration/cluster_setup.md

fix broken link in openshift docs

---

changelog/v1.4.0-beta7/fix-listener-options.yaml
projects/gloo/pkg/plugins/registry/registry.go
projects/gloo/pkg/translator/translator_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2904

Register listener plugin

---

changelog/v1.3.25/fix-vs-recreation-race.yaml
go.mod
go.sum
projects/gloo/pkg/syncer/translator_syncer_test.go
test/e2e/gateway_test.go

* fix vs recreation race
* changelog
* fix test
* Merge remote-tracking branch 'origin/master' into fix-vs-recreation-race
* fix go.mod
* Adding changelog file to new location
* Deleting changelog file from old location
* go mod
* Merge branch 'fix-vs-recreation-race' of https://github.com/solo-io/gloo into fix-vs-recreation-race
* update solo-kit ref
* solo-kit update
* Remove unneeded test code
* Bump solo-kit version
* Unfocus test
* We did need this test code change
* Merge branch 'master' into fix-vs-recreation-race
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2900

Fix vs recreation race (#2908)

---

changelog/v1.4.0-beta8/fix-glooctl-check-rbac.yaml
projects/gloo/cli/pkg/cmd/check/root.go
projects/gloo/cli/pkg/helpers/clients.go
projects/gloo/cli/pkg/prerun/version_warning.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2820
resolves https://github.com/solo-io/gloo/issues/2375
resolves https://github.com/solo-io/gloo/issues/2581

Fix glooctl check

---

changelog/v1.3.25/fix-glooctl-check-rbac.yaml
projects/gloo/cli/pkg/cmd/check/root.go
projects/gloo/cli/pkg/helpers/clients.go
projects/gloo/cli/pkg/prerun/version_warning.go

* Fix connection and secrets checks for namespaced install
* CL
* github errors
* Fix cl
* Fix version check namespace use
* remove comment
* fmt
* Actually regen
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2820
resolves https://github.com/solo-io/gloo/issues/2375
resolves https://github.com/solo-io/gloo/issues/2581

Fix glooctl check (#2922)

---

Makefile
changelog/v1.3.25/validate-transformation-inja.yaml
cloudbuild.yaml
docs/content/guides/traffic_management/configuration_validation/_index.md
docs/content/guides/traffic_management/configuration_validation/admission_control.md
go.mod
go.sum
install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
install/test/helm_test.go
projects/envoyinit/cmd/Dockerfile.envoyinit
projects/envoyinit/cmd/README.md
projects/gloo/cmd/Dockerfile
projects/gloo/pkg/bootstrap/bootstrap_validation.go
projects/gloo/pkg/plugins/pluginutils/any.go
projects/gloo/pkg/plugins/transformation/plugin.go
test/kube2e/gateway/gateway_test.go

backport of https://github.com/solo-io/gloo/pull/2827

Validate inja in transformations (#2827)

---

changelog/v1.4.0-beta9/fix-helm-val.yaml
install/helm/gloo/templates/18-settings.yaml
install/test/helm_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2935

Fix helm val

---

docs/content/guides/dev_portal/api_reference/access_level.md
docs/content/guides/dev_portal/api_reference/apidoc.md
docs/content/guides/dev_portal/api_reference/common.md
docs/content/guides/dev_portal/api_reference/group.md
docs/content/guides/dev_portal/api_reference/portal.md
docs/content/guides/dev_portal/api_reference/user.md
docs/content/guides/security/auth/configuration_format_history/_index.md

This fixes the title of the dev portal API reference pages, and some typos on the auth config format page. 
resolves #2946 #2941

Minor fixes

---

changelog/v1.4.0-beta8/fix-routeAction-without-ns.yaml
changelog/v1.4.0-beta9/fix-routeAction-without-ns.yaml
projects/gateway/pkg/translator/converter.go
projects/gateway/pkg/translator/converter_test.go
projects/gloo/pkg/translator/translator_test.go
projects/gloo/pkg/translator/upstream_groups.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2730

Route action without ns

---

.github/workflows/check-code-and-docs-gen.yaml

This change succeeded in Service Mesh Hub:
https://github.com/solo-io/service-mesh-hub/pull/669

Update deprecated github action

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/pull_request_template.md

Small formatting changes to our PR template, and more explicit recommendations for additional context on bug reporting.

Small cleanups

---

docs/content/guides/security/waf/_index.md

Add docs for IP address whitelisting via WAF
Gap in documentation, see #2586
N/A

add ip addr whitelisting

---

Makefile
changelog/v1.4.0-beta11/fix-helm-race-release-process.yaml
cloudbuild.yaml

Our release process has a race between two simultaneous releases updating our hosted helm repo and the helm index.
When two builds were started at the same time (e.g., 1.4 and 1.3 releases off different branches) these builds would race to update the helm index. Previously, our release process downloaded the helm index at the beginning of the build, then packaged and uploaded the updated index later in CI (often 10+ minutes later). This adds a ten minute window where a second release build could download the old index and wipe the new release (that finished just prior) from the index.
This PR resolves this race by using GCS [versioning and concurrency control](https://cloud.google.com/storage/docs/gsutil/addlhelp/ObjectVersioningandConcurrencyControl) to ensure the version of the index we …

Fix helm index race in Gloo release process

---

Makefile
changelog/v1.3.27/fix-helm-race-release-process.yaml
cloudbuild.yaml

backport of https://github.com/solo-io/gloo/pull/2996
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2913

Fix helm index race in Gloo release process (#2996)

---

docs/content/guides/traffic_management/destination_types/grpc/_index.md

This guide describes how to present a gRPC service Upstream through a Virtual Service and interact using a gRPC client.  This is in reference to Issue #2372.

gRPC guide

---

docs/content/guides/integrations/cert_manager/_index.md
docs/content/guides/traffic_management/destination_types/rest_endpoint/_index.md
docs/content/guides/traffic_management/hello_world/_index.md

Following up on Issue #717. Made minor fixes to the docs. Most of the comments in the issue have already been resolved by other updates.

Minor fixes to docs for Issue 717

---

changelog/v1.4.0-beta11/glooctl-secret-docs.yaml
docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/secret.proto.sk.md
docs/content/reference/cli/glooctl_create_secret.md
docs/content/reference/cli/glooctl_create_secret_apikey.md
docs/content/reference/cli/glooctl_create_secret_aws.md
docs/content/reference/cli/glooctl_create_secret_azure.md
docs/content/reference/cli/glooctl_create_secret_oauth.md
docs/content/reference/cli/glooctl_create_secret_tls.md
projects/gloo/api/v1/secret.proto
projects/gloo/cli/pkg/cmd/create/secret/aws.go
projects/gloo/cli/pkg/cmd/create/secret/azure.go
projects/gloo/cli/pkg/cmd/create/secret/extauth_apikey.go
projects/gloo/cli/pkg/cmd/create/secret/extauth_oauth.go
projects/gloo/cli/pkg/cmd/create/secret/root.go
projects/gloo/cli/pkg/cmd/create/secret/tls.go
projects/gloo/pkg/api/v1/secret.pb.go

Add documentation about glooctl secret annotation requirement and secret data format
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2944

Glooctl secret docs

---

changelog/v1.3.27/add-helm-value-disable-vwh.yaml
docs/content/reference/values.txt
install/helm/gloo/generate/values.go
install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
install/helm/gloo/values-template.yaml

backport of https://github.com/solo-io/gloo/pull/3017
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3016

Allow disable validation webhook (#3017)

---

changelog/v1.3.27/glooctl-check-rl.yaml
projects/gloo/cli/pkg/cmd/check/check_suite_test.go
projects/gloo/cli/pkg/cmd/check/gloo_stats.go
projects/gloo/cli/pkg/cmd/check/gloo_stats_test.go
projects/gloo/cli/pkg/cmd/check/proxy_prom_stats.go
projects/gloo/cli/pkg/cmd/check/root.go
projects/gloo/pkg/defaults/port.go

Backport of new checks for out of sync resources and rate limit server in glooctl

1.3.x rl and xds checks

---

docs/content/introduction/_index.md
docs/content/introduction/faq.md

remove terraform from the docs for discovery
this support isn't currently implemented
N/A

remove terraform docs

---

docs/content/installation/_index.md

docs/content/installation: fix glooe link

---

docs/layouts/shortcodes/extauth_version_info_note

Another trivial docs change. :)

docs/extauth: fix config format history link

---

.github/workflows/check-code-and-docs-gen.yaml
changelog/v1.4.0-beta13/fix-codegen-gh-action.yaml
install/helm/gloo/generate/values.go

testing to see if we can repro https://github.com/solo-io/gloo/issues/3058
edit: successfully repro'ed the false positive (codegen github action succeeded when it should have failed); needs to be looked into further
edit: this PR now addresses the issue it was originally testing
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3058

Fix false positives in codegen github action

---

.github/workflows/regression-test.yaml
ci/kind.sh

This is a non-user-facing change, simply cleaning up some documentation for devs.

Some github action cleanup

---

docs/README.md
docs/docs-staging.yaml

Non-user-facing guide for devs to test a versioned Gloo docs locally.

Update docs staging guide

---

docs/content/guides/security/rate_limiting/envoy/_index.md

Add docs for method based rate limiting
Satisfying request on how to accomplish load shedding style rate limiting
N/A, docs change

add load shedding example to docs

---

changelog/v1.4.0-beta15/run-certgen-as-non-root.yaml
docs/content/reference/values.txt
install/helm/gloo/generate/values.go
install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
install/helm/gloo/values-template.yaml
install/test/helm_test.go

Certgen no root

---

README.md

update blog link off medium

---

changelog/v1.4.1/placeholder-for-1.4-patch.yaml

First changelog to setup changelog bot with the proper next expected version

Add changelog to set precedent for 1.4 patch releases

---

changelog/v1.5.0-beta1/placeholder-1.5.0-beta.yaml

First changelog to setup changelog bot with the proper next expected version

Add changelog to set precedent for 1.5.0-beta releases from master

---

docs/content/guides/security/access_logging/_index.md

docs/access_logging: fix "gRPC", fix markdown

---

changelog/v1.5.0-beta2/fix-formula-updater.yaml
go.mod
go.sum

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3178

Pick up fix for formula updater

---

changelog/v1.5.0-beta3/fix-formula-updater.yaml
go.mod
go.sum

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3178

Update formula_updater utility regexes

---

changelog/v1.5.0-beta4/fix-ingress-docs.yaml
docs/content/guides/integrations/ingress/_index.md

Ingress docs formatting was off and some text was written in white (on a white background!) which made for unusable docs. This PR fixes these formatting issues.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3222

Fix ingress docs formatting issues

---

changelog/v1.5.0-beta4/docs-fixes-doc-setup-and-typos.yaml
docs/content/contributing/documentation/editing_locally.md
docs/content/guides/security/rate_limiting/_index.md
docs/content/introduction/_index.md
docs/content/operations/debugging_gloo/_index.md

These changes fix a few minor typos across the Docs files, and corrects some information in the 'editing locally' section of documentation editing.
Among other things, this addresses the last under_score syntax variable referenced in this issue: https://github.com/solo-io/gloo/issues/3170
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3170

Docs changes docs init and misc

---

Makefile
changelog/v1.5.0-beta4/bump-envoy.yaml
docs/content/reference/values.txt
install/helm/gloo/generate/values.go
install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
install/helm/gloo/values-template.yaml
install/test/fixtures.go

Update envoy 07 2020 CVEs

---

changelog/v1.5.0-beta4/hello-world-git-bash-workaround.yaml
changelog/v1.5.0-beta5/hello-world-git-bash-workaround.yaml
docs/content/guides/traffic_management/hello_world/_index.md

Add a note to the Hello World doc about running it in Git Bash.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2731

Hello world git bash path rewrite

---

Makefile

vendor tools so that code regen doesn't clash with other projects

vendor tools so that code regen doesn't clash with other projects

---

docs/content/guides/traffic_management/destination_types/canary/_index.md

add more intro content and add links to the blogs and tutorials

update index.md - add content to canary releases

---

docs/content/operations/production_deployment/_index.md
docs/content/operations/upgrading/1.3.0.md

Add note for change of default behavior for NET_BIND
This is a changed default
N/A

add note regarding NET_BIND default value

---

docs/content/guides/traffic_management/listener_configuration/_index.md

Fix typos in the [**Listener Configuration** guide documentation](https://docs.solo.io/gloo/latest/guides/traffic_management/listener_configuration/). (resolve https://github.com/solo-io/gloo/issues/3411)
I was working my way through the _latest_ [Listener Configuration](https://docs.solo.io/gloo/latest/guides/traffic_management/listener_configuration/) guide and encountered the issue.

Update Listener Configuration guide documentation

---

.github/workflows/regression-test.yaml
changelog/v1.4.7/setup-protoc.yaml

Backport of https://github.com/solo-io/gloo/pull/3432/files

Use solo-io fork of setup-protoc (#3432)

---

changelog/v1.4.7/i3336-gateway-namespace-scoping.yaml
changelog/v1.4.7/validation-api-handles-yaml.yaml
projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook_test.go
projects/gateway/pkg/syncer/setup_syncer.go
projects/gateway/pkg/translator/opts.go
test/services/gateway.go

backport of https://github.com/solo-io/gloo/pull/3413 and https://github.com/solo-io/gloo/pull/3443

Handle yaml validation 1.4

---

docs/content/guides/observability/grafana/deployment/_index.md

Small docs fixes to observability commands

Fixing a couple of typos

---

changelog/v1.5.0-beta19/faster-sorting.yaml
projects/gloo/pkg/plugins/plugin_interface.go

suggestion to improve sort speed;
if ok will add changelog

suggestion: faster sort

---

docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md

Update istio version number in docs

---

changelog/v1.5.0-beta21/prom-stat-valid-config.yaml
docs/content/guides/traffic_management/configuration_validation/_index.md
pkg/utils/statsutils.go
projects/gateway/pkg/validation/validator.go
projects/gateway/pkg/validation/validator_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3408

Prometheus stat for valid config

---

test/e2e/aws_test.go

fix aws sts test

---

changelog/v1.4.12/gateway-update-status.yaml
go.mod
go.sum
projects/gateway/pkg/syncer/setup_syncer.go
projects/gateway/pkg/syncer/translator_syncer.go
projects/gateway/pkg/syncer/translator_syncer_integration_test.go
projects/gateway/pkg/syncer/translator_syncer_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3592

backport update gateway status

---

changelog/v1.5.0-beta22/remove-dev-portal-code.yaml
projects/gloo/cli/pkg/cmd/install/uninstall.go
projects/gloo/cli/pkg/cmd/install/uninstall_test.go
projects/gloo/cli/pkg/cmd/install/util.go

Remove Developer Portal related code from `glooctl`.

Remove Developer Portal related code from glooctl

---

changelog/v1.4.13/conflicting-empty-sni-domains.yaml
projects/gateway/pkg/translator/http.go
projects/gateway/pkg/translator/translator_test.go
projects/gloo/pkg/translator/listener.go
projects/gloo/pkg/translator/translator_test.go

1.4 backport for our changes to sni domain comparison, which is now a broader filter chain match comparison.
Original PR: https://github.com/solo-io/gloo/pull/3546
issue link: https://github.com/solo-io/gloo/issues/3459
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3459

Backport filter chain match comparison

---

Makefile
changelog/v1.4.15/bump-cve.yaml

handle CVEs CVE-2020-25017 and CVE-2020-25018
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3687

1.4 - handle CVEs CVE-2020-25017 and CVE-2020-25018

---

Makefile
changelog/v1.3.34/bump-cve.yaml

handle CVEs CVE-2020-25017 and CVE-2020-25018
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3687

1.3 - handle CVEs CVE-2020-25017 and CVE-2020-25018

---

Makefile
changelog/v1.5.0-beta28/bump-cve.yaml
docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
example/proxycontroller/go.sum
projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go

handle CVEs CVE-2020-25017 and CVE-2020-25018
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3687

handle CVEs CVE-2020-25017 and CVE-2020-25018

---

changelog/v1.5.0-beta28/transformation-doc-update.yaml
changelog/v1.5.0-beta29/transformation-doc-update.yaml
docs/content/guides/traffic_management/request_processing/transformations/_index.md

Adding a body parsing example to the docs
In reference to issue #3448 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3448

Transformation doc update

---

Makefile
changelog/v1.5.0-beta29/bump-envoy-v1.16.0-rc4.yaml

bump-envoy-v1.16.0-rc4

---

changelog/v1.5.1/gloo-1.5.1-placeholder.yaml

Placeholder changelog
Our bot doesn't know which version we expect next on this branch. By adding this changelog, we can help out our bot and it will enforce this branch as the 1.5 Gloo branch

1.5.1 changelog placeholder

---

Makefile
changelog/v1.6.0-beta3/bump-envoy.yaml
docs/content/installation/advanced_configuration/wasm.md
docs/content/reference/values.txt
install/helm/gloo/generate/values.go
install/helm/gloo/templates/1-gloo-deployment.yaml
install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
install/helm/gloo/templates/_helpers.tpl
install/test/helm_test.go
projects/gloo/pkg/plugins/wasm/plugin.go
projects/gloo/pkg/plugins/wasm/plugin_test.go
test/kube2e/wasm/wasm_suite_test.go

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3753

Use upstream envoy for wasm instead of envoy-wasm fork

---

.github/workflows/publish-docs.yaml
changelog/v1.6.0-beta10/fix-docs-push.yaml

fix-docs-push

---

.github/workflows/regression-tests-and-codegen.yaml
changelog/v1.6.0-beta11/use-upstream-setup-protoc.yaml

Prefer the upstream protoc setup GH action
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3810

Use upstream setup protoc in CI

---

docs/content/guides/traffic_management/configuration_validation/invalid_route_replacement.md

The old docs recommended enabling the feature with an incomplete route replacement configuration

Better route replacement docs

---

changelog/v1.6.0-beta11/grafana-namespaced-setting.yaml
docs/content/installation/advanced_configuration/multiple-gloo-installs.md

Update to namespaced Gloo installation doc to include the Grafana RBAC settings for helm values.
Resolves #1764

Grafana namespaced settings

---

docs/content/guides/security/auth/extauth/oauth/okta/_index.md

The newly added Okta integration guide omitted some advice about commonly encountered configuration issues with external security services.  This PR expands troubleshooting to include `requestTimeout`.

Enhance Okta troubleshooting with requestTimeout config

---

docs/content/guides/traffic_management/_index.md

Fixing a small type in the docs

Fixing a small typo in docs

---

Makefile
changelog/v1.5.12/bump-envoy-1.16.1.yaml
changelog/v1.5.13/bump-envoy-1.16.1.yaml

Bump envoy to latest patch release

Bump envoy v1.16.1 patch1

---

changelog/v1.6.0-beta14/set-rate-limiting-docs.yaml
docs/content/guides/security/rate_limiting/crds/_index.md
docs/content/guides/security/rate_limiting/set/_index.md

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2695

Add set rate limiting docs

---

docs/content/guides/traffic_management/destination_types/aws_lambda/_index.md

fixed small docs typo

---

changelog/v1.6.0-beta15/update-docker-compose-guides.yaml
install/docker-compose-consul/docker-compose.yaml
install/docker-compose-file/docker-compose.yaml
install/docker-compose-file/prepare-directories.sh

Updating the image version for Gloo Edge, Consul, and Vault in the Docker Compose guides. Resolves #3839 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3839

Issue 3839 docs

---

changelog/v1.6.0-beta17/enhance-prod-docs.yaml
docs/content/operations/production_deployment/_index.md

Enhance production deployment docs with additional pointers
Users have missed a few best practices before deploying to prod, this intends to help with that
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3952

Enhance production deployment docs

---

docs/content/guides/integrations/datadog/_index.md

add info on how to add annotations via helm for datadog users

add helm value to datadog docs

---

changelog/v1.6.0-beta26/docs-header-secret.yaml
docs/content/guides/traffic_management/request_processing/append_remove_headers/_index.md

Update the docs to include detail about the headerSecretRef capability in header manipulation.
Resolves issue #3865
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3865

Docs header secret

---

changelog/v1.7.0-beta1/placeholder.yaml

Placeholder to ensure the changelog bot has the next version.

Placeholder changelog

---

changelog/v1.7.0-beta1/update-docs.yaml
docs/active_versions.json

Update docs for 1.6 release

---

docs/content/guides/security/csrf/_index.md

Fix a broken internal docs link in the new CSRF guide.

Patch broken CSRF internal doc link

---

docs/Makefile

Update hugo theme to fix docs search bug

---

changelog/v1.5.15/gateway-validation-webhook-race-condition.yaml
projects/gateway/pkg/validation/validator.go
projects/gateway/pkg/validation/validator_test.go

Backport of: https://github.com/solo-io/gloo/pull/4128
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4136

Backport Validator Race Condition

---

changelog/v1.7.0-beta13/socket-options-docs.yaml
docs/content/guides/dev/configuring-socket-options.md
docs/content/guides/integrations/aws/_index.md

Add documentation for configuring socket options.
Follow up to allowing socket options: 
https://github.com/solo-io/gloo/issues/3758

Add docs for socket-options

---

changelog/v1.7.0-beta17/testrunner.yaml
go.mod
go.sum
test/kube2e/containers/testrunner/Dockerfile

Slim down testrunner container.

Testrunner

---

docs/active_versions.json

Update v1.6.x docs to reflect changes as of v1.6.7
They were previously reflecting v1.6.3

Docs use v1.6.7

---

docs/content/guides/gloo_federation/multicluster_rbac.md

Update the docs to include the new ratelimitconfig type.

rbac validating webhook ratelimitconfig docs

---

changelog/v1.7.0-beta21/add-pod-disruption-budget-helm-values.yaml
docs/content/reference/values.txt
install/helm/gloo/generate/values.go
install/helm/gloo/templates/8-gateway-proxy-pod-disruption-budget.yaml
install/test/helm_test.go

Added gateway-proxy PodDisruptionBudget, tests and changelog
Second PR to finish addressing https://github.com/solo-io/gloo/issues/2229
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2229

add gateway-proxy PodDisruptionBudget, tests and changelog

---

docs/content/introduction/gloo_federation.md

quick docs update

---

changelog/v1.7.0-beta19/remove-v2-envoy-server.yaml
projects/gloo/pkg/xds/envoy.go

This reverts commit ffe4178ae1d6ca06cd7b290ccf89e66bab7f45ae.

Revert "Remove v2 server creation (#4281)"

---

changelog/v1.7.0-beta23/revert-remove-v2-envoy-server.yaml

Unblock release by introducing a changelog
We just introduced a revert (https://github.com/solo-io/gloo/pull/4346). In order to release, we need a new changelog version. Add a changelog to allow this.

Changelog Placeholder to Enable Release
