kgateway-dev/kgateway

changelog/v1.9.18/grpcmaxvalidationbyte-refresh.yaml, projects/gloo/pkg/syncer/setup/setup_syncer.go, projects/gloo/pkg/syncer/setup/setup_syncer_test.go
Description
On settings update we check if grpc servers need a kick
Right now we only do it if the addr changes but we also need to set anything else that is passed in as a grpc opt. In this case the validation bytes.
Context
Users were confused when the settings change was not reflected in the validation server's behavior
=> [1.9] setup/settings: Update to allow for validationServerGrpcMaxSizeBytes to take effect without manual kick

.github/workflows/README.md, .github/workflows/docs-gen.yaml, .github/workflows/notify-on-regression-failure-list.json, .github/workflows/regression-tests.yaml, projects/envoyinit/cmd/main.go, projects/envoyinit/pkg/runner/run.go
A set of minor optimizations to our CI pipeline, and other related bug fixes
Gloo defines all of the code for running an instance of Envoy. Solo-Projects re-defines this logic verbatim. To enable this code to be imported, we move the logic into a Runner package, and out of the main package.
This is a non-functional change, but follows a good practice of keeping main as slim as possible.
Do not run the docs generation GitHub action on Draft PRs. This is a fairly expensive operation (20 minutes) that only needs to run once a PR is ready for review.
**As part of this, I also added support to trigger and skip this action based on a comment. Since the `on comment` trigger only applies from the default branch, I can't validate this trigger. However, I can validate (by modifying the script) that …
=> CI Improvements

changelog/v1.8.31/grpcmaxvalidationbyte-refresh.yaml, projects/gloo/pkg/syncer/setup/setup_syncer.go, projects/gloo/pkg/syncer/setup/setup_syncer_test.go
Description
On settings update we check if grpc servers need a kick
Right now we only do it if the addr changes but we also need to set anything else that is passed in as a grpc opt. In this case the validation bytes.
Context
Users were confused when the settings change was not reflected in the validation server's behavior
=> [1.8] setup/settings: Update to allow for validationServerGrpcMaxSizeBytes to take effect without manual kick

changelog/v1.10.29/grpcmaxvalidationbyte-refresh.yaml, projects/gloo/pkg/syncer/setup/setup_syncer.go, projects/gloo/pkg/syncer/setup/setup_syncer_test.go
Description
On settings update we check if grpc servers need a kick
Right now we only do it if the addr changes but we also need to set anything else that is passed in as a grpc opt. In this case the validation bytes.
Context
Users were confused when the settings change was not reflected in the validation server's behavior
=> [1.10] setup/settings: Update to allow for validationServerGrpcMaxSizeBytes to take effect without manual kick

.github/workflows/README.md, .github/workflows/regression-tests.yaml, changelog/v1.12.0-beta25/ci-updates.yaml
This commit removes the ability to trigger CI via comment.  While it was "working" before (started/matched a Github action trigger) it wasn't "working working".  A.K.A., a started job wasn't associated with the PR on which it was commented on.  ...effectively meaning we could trigger unit tests to run against `master` from any PR, just because.
Disabled the not-quite-working feature
=> build(regression-tests): revoke comment-triggers for CI

Makefile, changelog/v1.12.0-beta25/make-sec-scan.yaml
Update makefile for changes to trivy. 
We normally do not exercise this code path as we have a more robust scanning for existing vuln but this is a nice one to have for local dev.
Namely newer versions of trivy require the directive `image` when scanning images.
=> makefile: Local trivy runs outside of go-utils update

changelog/v1.8.33/weighted-cluster-validation.yaml, projects/gloo/pkg/translator/route_config.go, projects/gloo/pkg/translator/translator_test.go
Reject WeightedDestination when Total Weight < 1 
Follow-Up to: https://github.com/solo-io/gloo/pull/6567/
Original issue: https://github.com/solo-io/gloo/issues/6098
The issue calls out that before validation, Envoy would produce the following error:
```
[2022-03-16 00:29:39.279][8][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:127] gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[776]: embedded message failed validation | caused by VirtualHostValidationError.Routes[2]: embedded message failed validation | caused by RouteValidationError.Route: embedded message failed validation | caused by RouteActionValidationError.WeightedClusters: …
```
=> Reject WeightedDestination when Total Weight < 1 

changelog/v1.9.19/support-new-statuses.yaml, changelog/v1.9.19/unmarshal-status-never-errors-solo-kit-bump.yaml, go.mod, go.sum
- Bump solo-kit dependency
This brings in a change in behavior that prevents an error from being returned due to malformed status
In turn this prevents Gloo from crashing or getting stuck if a CR has a malformed status for any reason
The malformed status will be ignored and rewritten during the next reconcile of the resource
It has been manually verified in a local kind cluster that this branch behaves as expected in this regard
See #6642
=> Unmarshal status never error 1.9

docs/content/guides/graphql/stitching.md
There's a broken doc link [here](https://docs.solo.io/gloo-edge/latest/guides/graphql/stitching/#next-steps) due to updating the GraphQLApi custom resource from gloo apiVersion v1alpha1 to v1beta1 at v1.11.0. This PR fixes that. I couldn't find any other links that were similarly broken.
=> Fix broken stitching link in GraphQL API reference doc

docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md, projects/gloo/api/v1/proxy.proto, projects/gloo/pkg/api/v1/proxy.pb.go
Related issue: https://github.com/solo-io/gloo/issues/6098
Users are allowed to pass weights of 0 but we error if all weighted destinations have 0 or no weight. 
Documents updated to clarify the behavior of weighted destinations
=> docs : specify weight of 0 is allowed on weighted destination given other non zero destinations

docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md, projects/gloo/api/v1/proxy.proto, projects/gloo/pkg/api/v1/proxy.pb.go
Backport of https://github.com/solo-io/gloo/pull/6685
Related Issue: https://github.com/solo-io/gloo/issues/6098
=> Weighted Destination Document Updates backport - weight of 0 allowed 

docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md, projects/gloo/api/v1/proxy.proto, projects/gloo/pkg/api/v1/proxy.pb.go
Backport of https://github.com/solo-io/gloo/pull/6685
Related Issue: https://github.com/solo-io/gloo/issues/6098
=>  Weighted Destination Document Updates backport - weight of 0 allowed 

changelog/v1.12.0-beta29/weighted-destingation-test-updates.yaml, changelog/v1.12.0-beta30/weighted-destingation-test-updates.yaml, projects/gloo/pkg/translator/translator_test.go
Adding a new test to cover situations where users pass weighted destinations with 0 weight with weighted destinations with weights higher than 0
This also includes a name change to a previous test to reflect that we now check total weight and will only fail if all passed destinations have 0 weight
=> Weighted destination test updates

.github/workflows/issue_board.yaml, changelog/v1.12.0-beta31/automation_secret.yaml
The secret we originally used to automate adding issues to boards stopped working. This change updates to a new secret Jacob created for the automation. 
This was already tested in GME (https://github.com/solo-io/gloo-mesh-enterprise/pull/4406/files)
=> Update the secret used for Github automation

changelog/v1.11.23/handle-npe-markperfilerconfig.yaml, projects/gloo/pkg/plugins/pluginutils/per_filter_config.go, projects/gloo/pkg/plugins/pluginutils/per_filter_config_test.go
Fixes NPE
NPE when publishing Dynamic Proxy
=> v1.11.x - handles NPE (#6740)

changelog/v1.11.24/image-digest-pinning.yaml, docs/content/reference/values.txt, install/helm/gloo/generate/values.go, install/helm/gloo/templates/_helpers.tpl, install/test/helm_test.go
Backport of image digest pinning from v1.12 to v1.11
=> Image Digest Pinning #6581  (#6761)

changelog/v1.8.36/set-based-proxy-selection.yaml, projects/clusteringress/pkg/translator/translator_syncer.go, projects/gateway/pkg/syncer/translator_syncer.go, projects/ingress/pkg/translator/translator_syncer.go, test/kube2e/gateway/gateway_test.go
Write Proxies with proper label format 
Follow-Up to https://github.com/solo-io/gloo/pull/6728
In Gloo, we reconcile Proxy CRs. To determine which proxies to reconcile we only select resources with a particular label. In a later version of Gloo Edge the label used to identify Gloo-managed proxies changed, resulting in this bug: https://github.com/solo-io/gloo/issues/6406.
To resolve this, we changed our selection process to list both Proxies with the old and new label, but write the new label. This would allow customer upgrading, to do so seamlessly. 
However, since 1.8 is an older version, we should be writing the label using the old format. In https://github.com/solo-io/gloo/pull/6728/files we correctly read the old and new format, but we write the new format.
The effect of the bug is …
=> [1.8] Proxy Reconciliation is Forward and Backward Compatible

changelog/v1.13.0-beta1/changelog-compressor.yaml, hack/squash-changelogs.sh
When run, the script produces a changelog directory resembling:
This commit was made _without_ running, as the number of changes it generates, otherwise, is overwhelming to review
=> ci: added hack script to compress changelogs by minor version

changelog/v1.13.0-beta3/static-upstream-host-healthchecks.yaml, projects/gloo/pkg/plugins/static/plugin.go, projects/gloo/pkg/plugins/static/plugin_test.go
Removed an auto-created healthcheck which was preventing user-provided healthchecks from being reached
BOT NOTES: 
=> fix(static/plugin.go): prevent auto-overwrite for host-level HC's

changelog/v1.13.0-beta3/helm-job-customization.yaml, docs/content/reference/values.txt, install/helm/gloo/generate/values.go, install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml, install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml, install/helm/gloo/templates/5-resource-cleanup-job.yaml, install/helm/gloo/templates/5-resource-migration-job.yaml, install/helm/gloo/templates/5-resource-rollout-job.yaml, install/helm/gloo/templates/6.5-gateway-certgen-job.yaml, install/helm/gloo/values-template.yaml, install/test/helm_test.go
Add helm customization (pod spec fields, resource requirements, disabling istio injection) that was missing from the `gloo-resource-rollout`, `gloo-resource-migration`, and `gloo-resource-cleanup` jobs. 
Allow disabling the jobs (not recommended unless default Gateways/Upstreams are not needed).
=> Helm customization for rollout/migration/cleanup jobs

changelog/v1.13.0-beta6/remove-default-activedeadline.yaml, docs/content/reference/values.txt, install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml, install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml, install/helm/gloo/templates/5-resource-cleanup-job.yaml, install/helm/gloo/templates/5-resource-migration-job.yaml, install/helm/gloo/templates/5-resource-rollout-job.yaml, install/helm/gloo/templates/6.5-gateway-certgen-job.yaml, install/helm/gloo/values-template.yaml, install/test/helm_test.go
Only set the value if it's explicitly passed in through helm values.
BOT NOTES: 
=> Remove default activeDeadlineSeconds from jobs

changelog/v1.13.0-beta6/isolate-virtual-hosts-sharing.yaml, projects/gloo/pkg/plugins/tls_inspector/plugin.go, projects/gloo/pkg/plugins/tls_inspector/plugin_test.go
[envoy.filters.listener.tls_inspector](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/tls_inspector) is an essential [listener_filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/listener_filters) when attempting to use TLS.  For _most_ gateways, we would previously always consider logic on whether or not to add it based on the presence of a user-provided SslConfig field.  For the new [AggregateListener](https://github.com/solo-io/gloo/pull/6558/files#diff-2272a3c8b202d19594dd9a455396b8fd7504a83cdd5eeacc918cecca586f2375), we neglected to add support, originally.  This caused TLS to be unable to function when using the [isolateVirtualHostsBySslConfig](https://docs.solo.io/gloo-edge/latest/reference/api/github.com …
=> fix(tls_inspector): added AggregateListener support

changelog/v1.13.0-beta6/fix-fed-ns-check.yaml, projects/gloo/cli/pkg/cmd/federation/register/register.go
Use the correct namespace to check for gloo installation when registering clusters for Gloo Fed.
=> Fix namespace check when registering cluster

changelog/v1.13.0-beta6/bump-alpine.yaml, docs/content/guides/security/tls/Dockerfile, docs/examples/session-affinity/Dockerfile, docs/examples/xslt-guide/Dockerfile, example/proxycontroller/Dockerfile, jobs/certgen/cmd/Dockerfile, jobs/kubectl/Dockerfile, projects/accesslogger/cmd/Dockerfile, projects/discovery/cmd/Dockerfile, projects/examples/services/sleeper/Dockerfile, projects/ingress/cmd/Dockerfile, projects/sds/cmd/Dockerfile
=> bump alpine to 3.15.6

changelog/v1.12.7/bump-alpine.yaml, docs/content/guides/security/tls/Dockerfile, docs/examples/session-affinity/Dockerfile, docs/examples/xslt-guide/Dockerfile, example/proxycontroller/Dockerfile, jobs/certgen/cmd/Dockerfile, jobs/kubectl/Dockerfile, projects/accesslogger/cmd/Dockerfile, projects/discovery/cmd/Dockerfile, projects/examples/services/sleeper/Dockerfile, projects/ingress/cmd/Dockerfile, projects/sds/cmd/Dockerfile
=> bump alpine to 3.15.6 [1.12]

changelog/v1.11.31/bump-alpine.yaml, docs/content/guides/security/tls/Dockerfile, docs/examples/session-affinity/Dockerfile, docs/examples/xslt-guide/Dockerfile, example/proxycontroller/Dockerfile, jobs/certgen/cmd/Dockerfile, jobs/kubectl/Dockerfile, projects/accesslogger/cmd/Dockerfile, projects/discovery/cmd/Dockerfile, projects/examples/services/sleeper/Dockerfile, projects/gateway/cmd/Dockerfile, projects/ingress/cmd/Dockerfile, projects/sds/cmd/Dockerfile
=> bump alpine to 3.15.6 [1.11]

changelog/v1.10.37/bump-alpine.yaml, docs/content/guides/dev/writing_auth_plugins/_index.md, docs/content/guides/security/tls/Dockerfile, docs/examples/session-affinity/Dockerfile, docs/examples/xslt-guide/Dockerfile, example/proxycontroller/Dockerfile, jobs/certgen/cmd/Dockerfile, projects/accesslogger/cmd/Dockerfile, projects/discovery/cmd/Dockerfile, projects/examples/services/sleeper/Dockerfile, projects/gateway/cmd/Dockerfile, projects/ingress/cmd/Dockerfile, projects/sds/cmd/Dockerfile
=> bump alpine to 3.15.6 [1.10]

changelog/v1.9.24/bump-alpine.yaml, docs/content/guides/security/tls/Dockerfile, docs/examples/session-affinity/Dockerfile, docs/examples/xslt-guide/Dockerfile, example/proxycontroller/Dockerfile, jobs/certgen/cmd/Dockerfile, projects/accesslogger/cmd/Dockerfile, projects/discovery/cmd/Dockerfile, projects/examples/services/sleeper/Dockerfile, projects/gateway/cmd/Dockerfile, projects/ingress/cmd/Dockerfile, projects/sds/cmd/Dockerfile
=> bump alpine to 3.15.6 [1.9]

test/kube2e/gateway/gateway_suite_test.go
Use a single replica of the Gloo pod in the Gateway kube2e tests
We've noticed an increase in flakes with this test, after increasing the replica count. While we explore solutions to the flakes with multiple replicas, this should should allow CI to function more consistently in the meantime.
=> Use 1 Gloo Replica in Gateway Kube Test

changelog/v1.11.32/isolate-virtual-hosts-sharing.yaml, projects/gloo/pkg/plugins/tls_inspector/plugin.go, projects/gloo/pkg/plugins/tls_inspector/plugin_test.go
"envoy.filters.listener.tls_inspector" is an essential listener_filter when attempting to use TLS.  For _most_ gateways, we would previously always consider logic on whether or not to add it based on the presence of a user-provided SslConfig field.  For the new _AggregateListener_, we neglected to add support, originally.  This caused TLS to be unable to function when using the "isolateVirtualHostsBySslConfig" feature flag.
related https://github.com/solo-io/gloo/issues/6677
=> 11 | fix(tls_inspector): added AggregateListener support

.github/workflows/codegen.yaml, .github/workflows/do-not-submit.yaml, .github/workflows/docs-gen.yaml, .github/workflows/push-solo-apis-branch.yaml, .github/workflows/regression-tests.yaml, .github/workflows/trivy-analysis-scheduled.yaml, test/kube2e/containers/testrunner/Dockerfile
Upgrade builder images used in Github Actions
https://solo-io-corp.slack.com/archives/CDZ2L52DD/p1661175261432419
Github has deprecated the Ubuntu 18.04 images, and will be removing them entirely at end of year.
=> Upgrade GHA to use Ubuntu-22.04

.github/workflows/codegen.yaml, .github/workflows/do-not-submit.yaml, .github/workflows/docs-gen.yaml, .github/workflows/push-solo-apis-branch.yaml, .github/workflows/regression-tests.yaml, .github/workflows/trivy-analysis-scheduled.yaml, test/kube2e/containers/testrunner/Dockerfile
Backport of: https://github.com/solo-io/gloo/pull/7001
=> [1.10] Upgrade GHA to use Ubuntu-22.04

.github/workflows/codegen.yaml, .github/workflows/do-not-submit.yaml, .github/workflows/docs-gen.yaml, .github/workflows/push-solo-apis-branch.yaml, .github/workflows/regression-tests.yaml, .github/workflows/trivy-analysis-scheduled.yaml, test/kube2e/containers/testrunner/Dockerfile
Backport of: https://github.com/solo-io/gloo/pull/7001
=> [1.11] Upgrade GHA to use Ubuntu-22.04

test/make/make_test.go
ci make tests return different origin url string, related https://github.com/solo-io/gloo/pull/7018
=> Fix make tests for ci

test/e2e/gateway_test.go
Related https://github.com/solo-io/gloo/issues/7044
Test flakes happened because of resource version conflicts on update (e.g. status update race)
fixes errors of this kind:
```
• [SLOW TEST:13.031 seconds]
Gateway in memory http gateway traffic works when rapid virtual service creation and deletion causes no race conditions 
/workspace/gloo/test/e2e/gateway_test.go:402
------------------------------
••••Fail handler msg Unexpected error:
<*errors.resourceVersionErr | 0xc00486b700>: {
namespace: "gloo-system",
name: "gateway-tcp-ssl",
given: "2",
expected: "3",
}
invalid resource version gloo-system.gateway-tcp-ssl given 2, expected 3
occurred
------------------------------
• Failure [1.027 seconds]
Gateway in memory tcp gateway ssl [It] should work with ssl …
```
=> Fix gateway ssl test flakes

changelog/v1.13.0-beta12/hcm-0-value-overrides.yaml, projects/gateway/pkg/translator/hybrid_translator_test.go, projects/gateway/pkg/translator/merge.go
special care taken with `Duration` and `ResourceRef` object types.
* updated tests
When combining this `MatchableHttpGateway`
```yaml
apiVersion: gateway.solo.io/v1
kind: MatchableHttpGateway
metadata:
name: client-ip-reject-gateway
namespace: gloo-system
spec:
httpGateway:
options:
httpConnectionManagerSettings:
tracing:
verbose: false
virtualServices:
- name: client-ip-reject
namespace: gloo-system
matcher: {}
```
With this `Gateway`
```yaml
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
labels:
app: gloo
name: gateway-proxy
namespace: gloo-system
spec:
bindAddress: '::'
bindPort: 8080
hybridGateway:
delegatedHttpGateways:
httpConnectionManagerSettings:
tracing:
verbose: true
ref:
name: client-ip-reject-gateway
namespace: gloo-system
options: {}
proxyNames:
- gateway-proxy …
```
=> fix(hcm): 2nd passthrough of subfields to make nullable

changelog/v1.13.0-beta12/disable-istio-inject-jobs.yaml, install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml, install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml, install/helm/gloo/templates/5-resource-cleanup-job.yaml, install/helm/gloo/templates/5-resource-migration-job.yaml, install/helm/gloo/templates/5-resource-rollout-job.yaml, install/helm/gloo/templates/6.5-gateway-certgen-job.yaml, install/test/helm_test.go
Disable istio sidecar injection for Jobs and CronJobs (regardless of `global.istioIntegration.disableAutoinjection` value) as it causes jobs to hang.
=> disable istio injection on jobs/cronjobs

changelog/v1.13.0-beta12/glooctl-warnings.yaml, changelog/v1.13.0-beta13/glooctl-warnings.yaml, projects/gloo/cli/pkg/cmd/check/root.go
I noticed that when there was a single authconfig with an error, glooctl check returned a warning about missing authconfigs for every virtual service that used one. This was because when we make lists of resources to use in our checks, we return `nil, multiErr` if there are any errors.
This change updates the methods that make lists of resources to return the list even when there are some errors.
=> Fix incorrect warnings from glooctl check

changelog/v1.13.0-beta13/cleanup-ignore-crd-errors.yaml, install/helm/gloo/templates/5-resource-cleanup-job.yaml
Exit early from the `gloo-resource-cleanup` job (instead of erroring) if the Gloo Edge CRDs have already been deleted.
=> Fix gloo-resource-cleanup failure when CRD doesn't exist

changelog/v1.12.15/cleanup-ignore-crd-errors.yaml, install/helm/gloo/templates/5-resource-cleanup-job.yaml
backport https://github.com/solo-io/gloo/pull/7118
=> Fix gloo-resource-cleanup failure when CRD doesn't exist [1.12]

changelog/v1.13.0-beta13/ci-resource-version-error.yaml, test/kube2e/gateway/gateway_test.go, test/kube2e/util.go
Ensure that patch updates to resources in gateway tests are successful
When updating a resource, we read the existing resource, update it, and then overwrite the resource with a modified state. This should be successful. 
However, we have noticed the occasional flake in this behavior, and we have an issue tracking the behavior: https://github.com/solo-io/gloo/issues/7044.
I recently noticed, some infrequent test flakes:
- https://github.com/solo-io/gloo/runs/8272029770?check_suite_focus=true
where we see:
```
Fail handler msg Expected
<*errors.resourceVersionErr | 0xc00222c5c0>: {
namespace: "gloo-system",
name: "testrunner",
given: "",
expected: "4354",
}
to match error
<*matchers.ContainSubstringMatcher | 0xc002075d70>: {
Substr: "Failed to parse response template: Failed to parse …
```
=> CI Stability: Retry Patch Updates to Avoid ResourceVersionErr

changelog/v1.13.0-beta13/docs-licensing.yaml, docs/content/installation/preparation.md
Add a doc section for how to use license_secret_name. Coincides with https://github.com/solo-io/solo-projects/pull/4051
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5071
=> Docs: Add info about license_secret_name

changelog/v1.12.19/rate-limit-status-hotfix.yaml, projects/gloo/api/external/solo/ratelimit/rate_limit_config.go
Remove panic for now to restore operations.
Glooctl check will always pass as has been the case since namespaced statuses existed for rate limit configs.
=> ratelimit_config: Update to no longer panic and only add a todo

changelog/v1.13.0-beta16/ratelimit-status-impl.yaml, install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml, install/test/rbac_test.go, install/test/util.go, projects/gloo/pkg/api/external/solo/ratelimit/extensions.go, projects/gloo/pkg/syncer/extauth/extauth_translator_syncer.go, projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer.go, test/helpers/resource_clientset.go, test/helpers/snapshot_writer.go, test/kube2e/gateway/gateway_test.go, test/kube2e/resource_clientset.go
Update permissions and apply status logic for `RateLimitConfig` CRs (enterprise-only) so they are implemented and have the proper permissions as of the changes made in https://github.com/solo-io/gloo/pull/7133
Added k8s regression test per https://github.com/solo-io/solo-projects/issues/4076
- `kind create cluster --image kindest/node:v1.20.15@sha256:6f2d011dffe182bad80b85f6c00e8ca9d86b5b8922cdf433d53575c4c5212248`
- `VERSION=0.0.0-kdorosh make clean build-test-chart push-kind-images -B`
- `glooctl install gateway -f _test/gloo-0.0.0-kdorosh.tgz `
- apply some ratelimit configs / auth configs
see the following (note that statuses were successfully reported):
```yaml
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
name: ac-9
namespace: gloo-system
spec:
configs:
- oauth2: …
```
=> Fix ratelimit status reporting

changelog/v1.11.38/stable-filter-chain.yaml, projects/gateway/pkg/translator/aggregate_translator.go, projects/gateway/pkg/translator/aggregate_translator_test.go, projects/gateway/pkg/translator/ssl_configuration.go
Backport https://github.com/solo-io/gloo/pull/7180
=> [1.11] gateway/translator: Update grouping for ssl configs to emit stable order

changelog/v1.13.0-beta16/fix-liveness-probe.yaml, install/helm/gloo/templates/1-gloo-deployment.yaml, pkg/utils/probes/healthz.go, projects/gloo/cmd/main.go, test/kube2e/util.go
Updates the Gloo liveness probe to use a new http server that always returns http 200 "ok".
Gloo liveness probes are disabled by default, and are not generally recommended (as there is not a good way for us to signal we are in deadlock; rather prefer on healthchecks on the node and readiness).
Regardless, some organizations require liveness and readiness probes for all pods; these users opt into our liveness probe which is occasionally trigger-happy (particularly at scale). The old probe would wait for xds before signalling health, which in large environments could lag while EDS is warming. This could, in rare cases, cause the gloo pod to needless bounce while it was warming.
automated: added this flag to our integration tests to ensure liveness probe is being hit and passing
manual:
- …
=> Default Gloo Liveness Probe Shouldn't Wait for XDS

changelog/v1.12.21/fix-liveness-probe.yaml, install/helm/gloo/templates/1-gloo-deployment.yaml, pkg/utils/probes/healthz.go, projects/gloo/cmd/main.go, test/kube2e/util.go
backport of https://github.com/solo-io/gloo/pull/7199
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7197
=> [1.12.x] Default Gloo Liveness Probe Shouldn't Wait for XDS

.github/workflows/regression-tests.yaml, changelog/v1.13.0-beta18/deflake-glooctl-istio-tests.yaml, ci/deploy-to-kind-cluster.sh, test/kube2e/README.md, test/kube2e/glooctl/glooctl_suite_test.go, test/kube2e/glooctl/glooctl_test.go
Backport #7250 to v1.10.x
This removes a couple of flakes in the Glooctl Istio kube2e tests
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4428
=> V1.10.x: Deflake Glooctl Istio kube2e Tests (#7250)

changelog/v1.12.24/fix-ci.yaml, ci/extended-docker/extended-docker.sh
fix ci broken grep in extended docker due to https://github.com/solo-io/gloo/pull/7229
=> Fix ci 1.12.22

changelog/v1.13.0-beta19/truncate-status.yaml, projects/gloo/pkg/api/external/solo/ratelimit/extensions.go
Handles skv2 client statuses, related to https://github.com/solo-io/gloo/pull/7259
tested manually with:
- `kind create cluster --image kindest/node:v1.20.15@sha256:6f2d011dffe182bad80b85f6c00e8ca9d86b5b8922cdf433d53575c4c5212248`
- `glooctl install gateway --version 1.12.24`
- manually updating the line right before truncation to a very long message
- `VERSION=0.0.0-kdorosh make gloo-docker -B`
- `kind load docker-image quay.io/solo-io/gloo:0.0.0-kdorosh`
- `kubectl set image deployment gloo -n gloo-system gloo=quay.io/solo-io/gloo:0.0.0-kdorosh`
- apply yaml to cluster from clipboard: `xclip | kubectl apply -f -`
```yaml
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
name: my-rate-limit-policy
namespace: gloo-system
spec:
raw:
descriptors:
- key: generic_key …
```
=> Truncate rl status

changelog/v1.12.28/helm-tweak.yaml, install/helm/gloo/generate/values.go
backport of https://github.com/solo-io/gloo/pull/7268
=> 12 | helm: standardized *Image as the default data type

changelog/v1.13.0-beta22/upstream-load.yaml, projects/gloo/pkg/upstreams/hybrid_client.go, projects/gloo/pkg/upstreams/hybrid_client_test.go
This  fixes a big where upstream processing was delayed when a large amount of other resources is constantly being added to the gloo snapshot
BOT NOTES: 
resolves https://github.com/solo-io/solo-projects/issues/4120
=> fix: upstream processing priority for bulk updates

Makefile, changelog/v1.13.0-beta26/build-test-assets-removal.yaml, ci/extended-docker/README.md
UX improvements to our makefile.
Some of our make targets are not intended for developer use and are only used by the build system/CI, only make targets intended for developer use should have comments.
Fix for issue introduced in https://github.com/solo-io/gloo/pull/7312 which breaks build-test-assets make target: Instead of fixing this bug we removed build-test-assets due to it not being used anywhere and replicable by running make build-test-chart glooctl.
The changes can be proven safe by running them manually.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7301
=> `build-test-assets` make target removal and various UX improvements

Makefile, changelog/v1.13.0-beta26/always-push-images-makefile-m1-update.yaml
Remove conditional for architecture on push images. This would prevent m1 machines from pushing docker images when they are needed for use in kind cluster deployments
=> Makefile m1update

changelog/v1.13.0-beta26/http-protocol-options.yaml, projects/gloo/pkg/plugins/protocoloptions/plugin.go, projects/gloo/pkg/plugins/protocoloptions/plugin_test.go
Fix a bug in configuring Envoy upstreams where some http protocol options could not be specified when useHttp2 was enabled
This is a bugfix
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6983
=> 6983 http protocol options

.github/workflows/regression-tests.yaml, changelog/v1.13.0-beta27/xds-ci.yaml
We want run regression tests with and without  XDS relay enabled. We configure this with an environment variable that is checked by the test setup code. However the github actions were only setting this when we create the cluster, not when we install gloo and run the tests.
=> Fix for setting XDS_RELAY in regression matrix

docs/content/getting_started/_index.md, docs/content/guides/integrations/service_mesh/istio.md, docs/content/guides/observability/tracing.md, docs/content/installation/gloo_federation.md, docs/content/installation/ingress/_index.md, docs/content/installation/knative/_index.md
Small doc modification to remove one extra command when using `helm`. 
- [~] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [~] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [~] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [~] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [~] I have performed a self-review of my own code
- [~] I have commented my code, particularly in hard-to-understand areas
- [~] I have added tests that prove my fix is effective or that …
=> doc(helm): use --create-namespace parameter instead of separated `kubectl` command

.github/workflows/nightly-tests.yaml, changelog/v1.13.0-beta28/worflow-fixes.yaml
The formatting was off in the first iteration of the workflow for nightly runs. This change fixes that and removes and extra empty step that also was invalid. I realized while making this PR that github will spit out formatting errors for bad workflows on pushes and it stopped doing that once I made these fixes (see: https://github.com/solo-io/gloo/actions/workflows/nightly-tests.yaml)
=> Fix indentation in nightly build workflow

.github/workflows/regression-tests.yaml
Stop running broken xds relay tests on every commit. We already updated branch protection to allow us to merge without these tests and since we aren't planning to fix them this spring, we can stop running them until we do get around to fixing them.
=> Remove xds relay from regression test matrix

changelog/v1.14.0-beta1/vault-token-description-fix.yaml, docs/content/reference/cli/glooctl_create_secret.md, docs/content/reference/cli/glooctl_create_secret_apikey.md, docs/content/reference/cli/glooctl_create_secret_authcredentials.md, docs/content/reference/cli/glooctl_create_secret_aws.md, docs/content/reference/cli/glooctl_create_secret_azure.md, docs/content/reference/cli/glooctl_create_secret_header.md, docs/content/reference/cli/glooctl_create_secret_oauth.md, docs/content/reference/cli/glooctl_create_secret_tls.md, projects/gloo/cli/pkg/flagutils/common.go
The `--vault-token` flag incorrectly had the description associated with `--vault-address` but had correct behavior as we do use the value in vault-address (`&config.Address`)  for `vaultClient, err := vaultapi.NewClient(config)` and the value in vault-token (`&token`) for `vaultClient.SetToken(token)`.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7469
=>  `--vault-token` flag description

.github/workflows/nightly-tests.yaml, .github/workflows/regression-tests.yaml, changelog/v1.13.0/deps-and-release.yaml, changelog/v1.13.0/opencensus.yaml, ci/deploy-to-kind-cluster.sh, go.mod, go.sum
Update skv2 and bump changelog for release.
Enables gloo fed via glooctl registration.
Updates ci to use 1.24 throughout
=> mod: move to release-1.13.0 and update skv2

.github/ISSUE_TEMPLATE/BUG-ISSUE.yml, .github/workflows/nightly-tests.yaml, .github/workflows/regression-tests.yaml, changelog/v1.14.0-beta3/ci-1.24.yaml, ci/deploy-to-kind-cluster.sh, hack/test.sh, jobs/kubectl/Dockerfile, projects/gloo/cli/pkg/cmd/demo/federation.go, test/kube2e/README.md, test/kube2e/helm/helm_test.go
- forward-port of the ci changes that were merged into 1.13 in https://github.com/solo-io/gloo/pull/7571, plus some that were missed
- update issue template
=> update ci to use k8s 1.24

changelog/v1.14.0-beta4/glooctl-check-virtual-services, projects/gloo/cli/pkg/cmd/check/check_test.go, projects/gloo/cli/pkg/cmd/check/root.go
For some of our sub checks (checkResourceX functions), if we see that the status hasn’t been set on a given resource, we don’t add it to the list of known resources. This is an issue whenever resources exist in our cluster but Gloo hasn’t reported their status yet as these resources will not be listed as known for other checks that rely on them.
We want to append the resource to the list of known resources in any case, not just if resource.GetNamespacedStatuses() != nil. Also adding a new corresponding error message for the (resource.GetNamespacedStatuses() == nil) case.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7153
=> `glooctl check` virtual service reporting fixes/improvements

changelog/v1.14.0-beta5/glooctl-nightly.yaml, test/kube2e/glooctl/glooctl_test.go
The glooctl nightly tests have been failing to pull the helm chart to test checking crds because it tries to get a version that starts with 'v'. This change uses the value for the latest version that doesn't have a leading 'v'. 
Failed run: https://github.com/solo-io/gloo/actions/runs/3827002749/jobs/6511247290
I verified that this works by running the tests locally.
=> Fix for glooctl nightly tests

Makefile, changelog/v1.12.41/version-var-repair.yaml
Changed a _very heavily used_ Makefile variable, `VERSION`, from being always hardcoded to `0.0.1-fork` when doing local development
I was chasing a subtle bug when working on some EE actions, and found that I could not build arbitrary versions on the `1.12.x` OSS branch
(replaces PR https://github.com/solo-io/gloo/pull/7647 to test CI when running from a fork)
=> build: allow VERSION var to be set in local dev

.github/workflows/helpers/notify-from-json.go, .github/workflows/nightly-tests.yaml, changelog/v1.14.0-beta6/combine-nightly-logs.yaml
Added a data aggregation step prior to slack notification for nightly builds.  Enables slack posts to be prettier (and combined)
Performed with a simplified branch job: **Actions Testing**
* [workflow definition](https://github.com/solo-io/gloo/blob/cron-compression/.github/workflows/test-job.yaml)
* [example runs](https://github.com/solo-io/gloo/actions/workflows/test-job.yaml)
* slackbot posts (`#slack-integration-testing`)
necessary prep work for adding _even more_ slack posts based on CRON jobs
BOT NOTES: 
resolves https://github.com/solo-io/solo-projects/issues/4410
=> build(nightly-tests): combine/simplify slack alerts

changelog/v1.10.43/fix-gateway-proxy-config-and-tolerations.yaml, install/helm/gloo/templates/7-gateway-proxy-deployment.yaml, install/test/helm_test.go
- Moved pod-level options outside of container configuration.
- Essentially a backport of #5987, which also fixes the issue of istio being placed in the `tolerations` field.
- Backported test. It passes without this fix, although was added for extra guard-railing against(?) future changes.
- New test to verify istio-proxy gets set as a `container`, not a `toleration`.
When adding `tolerations` and enabling `istioSDS`, the `istio-proxy` container was being set in the `tolerations` field instead of `containers`. This fixes that issue.
1. `VERSION=<whatever> make build-test-chart`
2. `helm template gloo-fixed ~/go/src/github.com/solo-io/gloo/_test/gloo-<VERSION>.tgz 
--values ./values1.yaml --values ./values2.yaml > file`
- values file linked in issue …
=> Fix istio-proxy pod being placed inside `tolerations` in helm template

docs/content/guides/observability/grafana/dashboards/_index.md
Fix a bad CM reference to glooe-observability-config [here](https://docs.solo.io/gloo-edge/latest/guides/observability/grafana/dashboards/#dynamically-generated-dashboards).
A customer reported this while doing some initial Gloo Edge testing.
=> grafana docs: fix bad CM reference to glooe-observability-config

.github/actions/regression-tests/action.yaml, .github/workflows/helpers/notify-from-json.go, .github/workflows/nightly-tests.yaml, .github/workflows/regression-tests.yaml, changelog/v1.14.0-beta7/add-weekly-cron.yaml
In principal, there are only 2 _major_ changes done by this PR.
1) a refactor of the `regression-tests.yaml` workflow, in which most of its logic is extracted into a [local action](https://github.com/orgs/community/discussions/26245#discussioncomment-3250935)
2) heavy editing of the `nightly-tests.yaml` workflow to become a cron orchestrator
The choices I made for designing this Github Action scheduler came from a combination of...
* [There isn't a nice way to reference the outputs of all jobs in a github actions matrix](https://github.com/community/community/discussions/17245#discussioncomment-3814009)
* [Github Actions cron scheduling only works on the default branch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)
So!  Easy(ish) enough.  We …
=> build(regression-tests): refactor to support weekly LTS CRON

.github/workflows/nightly-tests.yaml, Makefile, changelog/v1.14.0-beta8/nightly-add-ginkgo-flags.yaml
Use Ginkgo's "-randomizeSuites -randomizeAllSpecs" flags when running cron builds
caveat:  [current Ginkgo docs](https://onsi.github.io/ginkgo/#running-multiple-suites) seem to indicate that the correct flags are titled `--randomize-all` and `--randomize-suites`, rather than the current usage.  This is because we are still using the (deprecated) v1
* [manual OSS run](https://github.com/solo-io/gloo/actions/runs/4047255584)
* drilling into https://github.com/solo-io/gloo/actions/runs/4047255584/jobs/6961060079#step:3:1597, for example, shows the specified flags being passed
=> build(regression): added randomize flags to ginkgo runners

changelog/v1.14.0-beta8/updating-dev-environment-docs.yaml, docs/content/guides/dev/setting-up-dev-environment.md
I have added a link for the new contributors trying to set up the gloo project locally to have a Kubernetes Cluster running before running this command `go run projects/gloo/cmd/main.go`
Related to issue #7758 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7758
=> docs: updating the setting-up-dev-environment

changelog/v1.14.0-beta8/secret-existing-failure.yaml, test/kube2e/gateway/gateway_test.go
Repaired test suite by always cleaning up secret after use.  (Previously, if this suite would run out-of-order, it would fail)
With the addition of https://github.com/solo-io/gloo/pull/7768, a new crop of flakes have presented themselves.  This PR is addressing _one_ such flake (possibly as an example to be referenced later)
=> test(gateway): clean up secrets after tests

changelog/v1.12.43/allow-query-parameters-on-re-writes.yaml, projects/gloo/pkg/translator/route_config.go, projects/gloo/pkg/translator/route_config_test.go
* allow QP on re writes
* unit tests on validate re-write
* Update changelog/v1.14.0-beta8/allow-query-parameters-on-re-writes.yaml
Co-authored-by: Nathan Fudenberg <nathan.fudenberg@solo.io>
---------
Co-authored-by: Nathan Fudenberg <nathan.fudenberg@solo.io>
=> allow QP on re-writes (#7771)

changelog/v1.13.6/cli-leak-hardening.yaml, projects/gloo/cli/pkg/helpers/clients.go, test/kube2e/upgrade/upgrade_utils.go
CLI calls as a library would not clean up after themselves. This led to a leak in goroutines which fails under race builds.
=> 1.13/cli safe testing

changelog/v1.14.0-beta9/cli-context-leak.yaml, projects/gloo/cli/pkg/helpers/clients.go
Clean up the last todos in the kube caches that were causing failures under race when using this code
=> cli: context todo cleanup for gleak

changelog/v1.10.45/fix-cloudbuild.yaml, cloudbuild.yaml
Revert the cloud-builders version bumps done in https://github.com/solo-io/gloo/pull/7721, except for the `e2e-go-mod-ginkgo` upgrade, which is still needed to fix the gke issue.
Bumping `go-mod-make` to 0.4.28 had caused our release assets to be built using go 1.18, which resulted in a glooctl cluster registration bug/panic. Building glooctl with go 1.16 (which our 1.10.x branch uses) resolves the panic.
=> revert cloudbuild bumps

.github/workflows/docs-gen.yaml, changelog/v1.14.0-beta15/ee-proto-docs-fix.yaml, docs/Makefile, docs/build-docs.sh
When generating docs for LTS branches copy the `changelog` dirs to allow generation to run correctly
When users consume our [enterprise helm reference](https://docs.solo.io/gloo-edge/1.11.52/reference/helm_chart_values/enterprise_helm_chart_values/), they were previously seeing _only_ the reference for the `latest` release, as opposed to the specific minor version of the site which was being viewed
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7887
=> docs: enterprise proto docs now generate based on minor version

.github/actions/regression-tests/action.yaml, .github/workflows/codegen.yaml, .github/workflows/docs-gen.yaml, .github/workflows/nightly-tests.yaml, .github/workflows/push-solo-apis-branch.yaml, .github/workflows/regression-tests.yaml, .github/workflows/trivy-analysis-scheduled.yaml, Makefile, changelog/v1.13.10/go-bump.yaml, changelog/v1.13.9/go-bump.yaml, cloudbuild-cache.yaml, cloudbuild.yaml
Bump cloud builders and github actions (might as well keep them in sync).
This prevents the possible denial of service to control plane http end points (stats end point) CVE-2022-27664
=> ci: bump go to 1.18.6 to prevent possible denial of service to control plane stats end point CVE-2022-27664

changelog/v1.14.0-beta16/kube2e-test-cleanup.yaml, test/kube2e/gloo/artifacts/helm.yaml, test/kube2e/gloo/gloo_suite_test.go, test/kube2e/glooctl/artifacts/helm.yaml, test/kube2e/glooctl/glooctl_suite_test.go, test/kube2e/istio/artifacts/helm.yaml, test/kube2e/istio/istio_suite_test.go
Attempt to fix the Istio kube2e test flake by disabling leader election explicitly
In [recent work](https://github.com/solo-io/gloo/pull/7882) we cleaned up the Gateway test suite, and clarified which helm values are being applied at install time, by defining them in an external file.
I updated the `gloo`, `istio` and `glooctl` suites to follow the same pattern. They also were updated to use the utilities for skipping install and tearing down, instead of redefining the same logic.
The istio flake, is it is documented on the issue is that a status is not reported on a resource when we expect one to be.
See https://github.com/solo-io/gloo/pull/7897 for details about how we de-flaked a similiar behavior in the Gateway tests.
The difference is just that those tests are validating the leader …
=> Stability: Fix Istio Kube2e Flake

changelog/v1.12.48/backport-upgrade-tests.yaml, test/kube2e/upgrade/README.md, test/kube2e/upgrade/artifacts/helm.yaml, test/kube2e/upgrade/upgrade_suite_test.go, test/kube2e/upgrade/upgrade_test.go, test/kube2e/upgrade/upgrade_utils.go, test/kube2e/util.go
Backporting updates to upgrade tests 
there is also a small backport of test/kube2e/utils methods
Most changes are represented in 
- https://github.com/solo-io/gloo/pull/7821
- https://github.com/solo-io/gloo/pull/7869
Corresponding 1.13 backport - https://github.com/solo-io/gloo/pull/7929
This is not a cherry-pick but a copy and paste as after minor updates over many PRs it made more sense to copy and paste the changes to older branches. 
This also undoes the changes made to enable ginkgo v2 on the current mainline branch of 1.14
=> 1.12 - backport upgrade tests

changelog/v1.14.0-beta16/istio-plugin-speedup.yaml, projects/gloo/pkg/plugins/istio_integration/istio_suite_test.go, projects/gloo/pkg/plugins/istio_integration/plugin.go, projects/gloo/pkg/plugins/istio_integration/plugin_test.go, projects/gloo/pkg/plugins/registry/registry.go
Speed up the Istio integration plugin's `ProcessRoute` by getting upstreams directly from the api snapshot, instead of using an upstream client to look them up. In local testing with 20 VirtualServices and 100 RouteTables (and istio integration enabled), this resulted in about a 100-200x speedup in translation time.
=> Improve istio plugin translation time

changelog/v1.14.0-beta18/oidc-docs.yaml, docs/content/guides/security/auth/extauth/oauth/dex/_index.md
Newer versions of Dex require extra configuration to install with a static list of users. The version in the `https://charts.helm.sh/stable` doesn't seem to work on newer versions of K8s.
In this change, start pulling dex from `dexidp.io` and update the config values so that it installs correctly. 
Ran into this while testing OIDC.
=> Fix instructions for installing OIDC with Dex 

.github/actions/regression-tests/action.yaml, .github/workflows/add-pr-label.yaml, .github/workflows/codegen.yaml, .github/workflows/nightly-tests.yaml, .github/workflows/push-solo-apis-branch.yaml, .github/workflows/regression-tests.yaml, .github/workflows/trivy-analysis-scheduled.yaml, changelog/v1.14.0-beta18/remove-gha-warnings.yaml
* updated instances of [set-output](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
* updated `cancel-actions` to `latest` to resolve "node 12 is not supported"
A couple of our GHA warnings were threatening to tick over into full-blown errors.  Resolved them, now, rather than waiting for CI to fail in a couple of months.
=> build: resolved GHA warnings

Makefile, changelog/v1.14.0-beta19/remove-race-ci.yaml
Follow-up to https://github.com/solo-io/gloo/pull/7979, remove the reference to the race image in the cloudbuild publish artifacts step.
BOT NOTES: 
resolves https://github.com/solo-io/solo-projects/issues/4649
=> remove race from cloudbuild step

.github/workflows/push-solo-apis-branch.yaml
we do the gloo checkout at path `gloo` so the go.mod should be at `gloo/go.mod`
this should fix the push solo-apis [failure](https://github.com/solo-io/gloo/actions/runs/4599755409) for next time
already fixed the latest push manually so don't need to do another release
=> fix go mod path for push solo-apis action

test/gomega/matchers/contain_headers.go, test/gomega/matchers/contain_headers_test.go, test/gomega/matchers/contain_substrings.go, test/gomega/matchers/contain_substrings_test.go, test/gomega/matchers/matchers_suite_test.go
We rely on custom matchers in our e2e tests, this PR adds some tests to improve confidence those matchers behave as we would expect
We've hit some response assertion panics in our aws tests and opened https://github.com/solo-io/gloo/issues/8003 as a result. One of them was the result of an update we needed to make to this custom matcher.
My hope was that if we added tests we might see what is causing the current (infrequent) panic. It didn't demonstrate this, but the side effect is now we have test to demonstrate these utilities work as expected.
=> Stability: Unit Test Custom Matchers

Makefile, changelog/v1.15.0-beta3/golang-version-location.yaml, cloudbuild-cache.yaml, go.mod
Whenever we upgrade Go in this repo, we have to update the version across multiple files. This PR aims to make some of the simplest changes that reduce the number of places we define our go version. Many of these hardcodings are impractical to change so they are left in with comments in the go.mod for future developers who upgrade go.
=> Centralize where go version is specified

Makefile, Makefile.ci, changelog/v1.15.0-beta3/suppress-ci-docker.yaml, ci/kind/setup-kind.sh
Add some `2> /dev/null` flags to docker builds on CI
_optimally_ this makes logs easier to use when tracking down flakes
=> build: reduce log burden by suppressing docker build logs

.github/workflows/push-solo-apis-branch.yaml, changelog/v1.13.14/update-mod-location.yaml
- the `go-version-file` field in the `Set up Go` step in the `Push API Changes to solo-apis` workflow was pointing to an invalid file path
- Gloo is checked out into the `gloo` directory, not at the root of the repo
- This PR updates the `go-version-file` field to point to `gloo/go.mod`, which is the correct path
=> [v1.13.x] Update go-version-file field in push-solo-apis-branch workflow

.github/workflows/push-solo-apis-branch.yaml, changelog/v1.12.52/update-mod-location.yaml
- the `go-version-file` field in the `Set up Go` step in the `Push API Changes to solo-apis` workflow was pointing to an invalid file path
- Gloo is checked out into the `gloo` directory, not at the root of the repo
- This PR updates the `go-version-file` field to point to `gloo/go.mod`, which is the correct path
=> [v1.12.x] Update go-version-file field in push-solo-apis-branch workflow

.github/workflows/push-solo-apis-branch.yaml, changelog/v1.11.57/update-mod-location.yaml
- the `go-version-file` field in the `Set up Go` step in the `Push API Changes to solo-apis` workflow was pointing to an invalid file path
- Gloo is checked out into the `gloo` directory, not at the root of the repo
- This PR updates the `go-version-file` field to point to `gloo/go.mod`, which is the correct path
=> [v1.11.x] Update go-version-file field in push-solo-apis-branch workflow

Makefile
Added alias to remedy the issue where the command `make kind-reload-gloo-envoy-wrapper` yielded the error
```log
kubectl rollout restart deployment/gloo-envoy-wrapper -n gloo-system
Error from server (NotFound): deployments.apps "gloo-envoy-wrapper" not found
make: *** [Makefile:788: kind-reload-gloo-envoy-wrapper] Error 1
```
This can be tested by running the command above, seeing the error, then running on the branch and observing the deployment restart
=> fix make target for kind-reload-gloo-envoy-wrapper

changelog/v1.15.0-beta4/upgrade-utils-refactor.yaml, test/kube2e/upgrade/upgrade_suite_test.go, test/kube2e/upgrade/upgrade_utils.go
Fixed a bug where `changelog` directory would always be dependent on `gloo` repository
_and_
offered a refactor of said method to make it easier to develop on
=> refactor(upgrade): simplify return branches of GetUpgradeVersions

.github/workflows/push-solo-apis-branch.yaml, changelog/v1.13.15/expand-release-branch-yaml
-  resolves issue in `push-solo-apis-branch` release job, in which the `RELEASE_BRANCH` environment variable was not being expanded correctly
=> [v1.13.x] Expand RELEASE_BRANCH properly in push-solo-apis-branch

.github/workflows/push-solo-apis-branch.yaml, changelog/v1.11.58/fix-release-branch
- Resolves an issue in the `push-solo-apis-branch` release workflow that caused the `RELEASE_BRANCH` environment variable to be unset
=> [v1.11.x] Ensure that RELEASE_BRANCH is set

.github/workflows/README.md, Makefile
Clarify kind-load behavior per recommendation from recent demo
Create a kind cluster
```
kind create cluster --name kind-demo
```
Install gloo
```
helm install -n gloo-system gloo gloo/gloo --create-namespace --version 1.14.0-rc1
````
Reload the gateway-proxy deployment
```
CLUSTER_NAME=kind-demo VERSION=1.0.0-sh make kind-reload-gloo-envoy-wrapper
```
Reload the gloo deployment
```
CLUSTER_NAME=kind-demo VERSION=1.0.0-sh make kind-reload-gloo
```
**Note: In the reload steps, version is no longer required**
=> Docs: Clarify Usage of kind-reload

.github/workflows/push-solo-apis-branch.yaml
Ensure the push-to-solo-apis GHA works properly
Slack context: https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1682360742297699?thread_ts=1682349377.057149&cid=G01EERAK3KJ
A bad find/replace was merged in https://github.com/solo-io/gloo/pull/8114
https://github.com/solo-io/gloo/blob/458fcc763ed3332b76554c9280874c27c811b951/.github/workflows/push-solo-apis-branch.yaml#L42 shows what this value was before the above PR
Create a manual run using:
Logs: https://github.com/solo-io/gloo/actions/runs/4789975107
Solo-Apis generated PR: https://github.com/solo-io/solo-apis/pull/810
This doesn't test everything, as where we failed was actually code that only runs on releases
=> Stability: Fix Push Solo-Apis GHA

.trivyignore, changelog/v1.15.0-beta4/go-graphql-bump.yaml, changelog/v1.15.0-beta5/go-graphql-bump.yaml
This CVE has been resolved by the `graphql-go/gaphql@v0.8.1` release.
=> Remove CVE-2022-37315 from trivyignore

Makefile, changelog/v1.15.0-beta5/envoy-gloo-cross-account-bump.yaml, test/e2e/aws_test.go
- Pulls in changes introduced in https://github.com/solo-io/envoy-gloo/pull/228 to fix the resource-based cross-account lambda scenario
- Prior to the PR linked above, envoy-gloo was not encoding fully-qualified ARNs properly in canonical requests sent to AWS. We only use a fully-qualified ARN when the `AwsAccountId` field is specified on a lambda upstream, which only occurs during the resource-based cross-account scenario, so this change effectively fixes that workflow
- See here -- `functionName` is only set to a fully-qualified ARN if `awsAccountId` is set https://github.com/solo-io/gloo/blob/44951547286262905c33d4ae5d5e24a51bb81a19/projects/gloo/pkg/plugins/aws/plugin.go#L386-L396
=> Pull in fix for resource-based cross-account lambda invocation

Makefile, changelog/v1.14.1/bump-envoy-gloo-apr26.yaml
Bemp envoy-gloo to bring in April 26 FIPS compliance fix
=> [1.14] bump envoy-gloo for april 26

Makefile, changelog/v1.11.58/cves.yaml, docs/content/guides/security/tls/Dockerfile, docs/examples/session-affinity/Dockerfile, docs/examples/xslt-guide/Dockerfile, example/proxycontroller/Dockerfile, jobs/certgen/cmd/Dockerfile, jobs/kubectl/Dockerfile, projects/accesslogger/cmd/Dockerfile, projects/discovery/cmd/Dockerfile, projects/examples/services/sleeper/Dockerfile, projects/gateway/cmd/Dockerfile, projects/gateway/pkg/api/v1/kube/generated_kube_types_test.go, projects/ingress/cmd/Dockerfile, projects/sds/cmd/Dockerfile
Bump Alpine dependency in the `kubectl` image for CVE-2023-0464.
Can be tested by running the following commands:
`docker run --rm alpine:3.17.2 apk info libssl3 libcrypto3`
`docker run --rm alpine:3.17.3 apk info libssl3 libcrypto3`
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8125
=> [1.11] CVE 2023 0464

changelog/v1.13.17/envoy-gloo-cross-account-bump.yaml, projects/gateway/pkg/api/v1/kube/generated_kube_types_test.go
Fix for https://github.com/solo-io/gloo/issues/8099
Backporting from https://github.com/solo-io/gloo/pull/8170
Constant flake blocking ci builds
=> Backport fix generated kube tests flake

changelog/v1.13.17/routeoptions-regex-validation.yaml, projects/gateway/pkg/translator/http_translator_test.go, projects/gateway/pkg/translator/virtual_service_translator.go
hand cherrypick changes from [PR: 8143](https://github.com/solo-io/gloo/pull/8143/files)
RouteOptions HostRewriteType_RewritePathRegex does not exist in 1.13 but does in 1.14 onwards so these changes had to be excluded
=> Regex Fixes 1.13

changelog/v1.15.0-beta6/cross-account-lambda-docs.yaml, docs/content/guides/traffic_management/destination_types/aws_lambda/cross-account.md, projects/gateway/pkg/api/v1/kube/generated_kube_types_test.go
- Adds a user guide for cross-account lambda functionality
- Includes details on Gloo and AWS configuration
- Includes two strategies for configuring cross-account lambda functionality -- IRSA and resource-based
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7965
=> Add user guide for cross-account lambda functionality

changelog/v1.14.4/grpc-migration.yaml, changelog/v1.15.0-beta6/grpc-migration.yaml, projects/discovery/pkg/fds/discoveries/grpc/grpc.go, projects/gloo/pkg/plugins/grpc/plugin.go, test/e2e/grpc_discovery_test.go, test/e2e/grpc_plugin_test.go
Original PR: https://github.com/solo-io/gloo/pull/8138#event-9192944019
This is work that was originally targeted for (and initially tested on) 1.14 but wasn't finished by the original release. The change is for users who have gRPC upstreams who are upgrading to 1.14.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8080
=> Backport change to allow migrating between grpc APIs without downtime

.github/workflows/nightly-tests.yaml, .github/workflows/regression-tests.yaml, changelog/v1.15.0-beta6/remove-upgrade-tests-from-prs.yaml
Upgrade Tests will run nightly on master branch
Upgrade Tests will run per pr for LTS branches 
Only run nightlies 1.13+
The idea was that upgrade tests run on every PR, but rarely do they test things that were introduced in PRs, so I made the argument that we could reduce cost by running them in our nightly tests and still keep our consistency. The downside is that IF someone introduces a change that would break the test, the PR can still merge. But with our nightly tests, we would see this in <24 hours and be able to revert
For nightlies, 1.13+ branches have the "most" stable tests. We want to get to a point where our weekly tests all pass. We have decided to run a subset first, and then future work will be to expand these tests should we want.
=> Upgrade tests not on prs

changelog/v1.15.0-beta6/healthcheck-docs.yaml, docs/content/guides/traffic_management/request_processing/upstream_health_checks/_index.md
Add a notice to the Upstream Health Check docs (https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/upstream_health_checks/) to call out the fact that envoy will not remove hosts with successful health checks unless the `ignoreHealthOnHostRemoval` field is set.
A customer ran into this when trying to use tags to determine which EC2 instances should be used. They expected that when they removed a tag from an instance, traffic wouldn't go to that instance. However, since those instances still looked "healthy" envoy continued sending traffic to them.
(doc only change)
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7996
=> Document behavior around removing hosts with valid health checks

changelog/v1.12.55/glooctl-proxy-fix.yaml, projects/gloo/cli/pkg/cmd/check/root.go, projects/gloo/cli/pkg/common/get.go
- Backport #8228 to 1.12.x
- Updates `glooctl check` to use the GPRC endpoint for proxy validation, ala `glooctl get proxies`.
- This fixes an issue where the check would report false-positives for invalid proxies that were not persisted.
- Prior to this change, glooctl check used a k8s client to obtain proxy resources
- Since 1.12.x, proxy resources are not persisted by default, so this k8s client failed to obtain proxies, and in turn failed to report errors on proxy resources
=> [1.12.x] Fix non-persisted proxy validation in glooctl check

changelog/v1.14.4/glooctl-proxy-fix.yaml, projects/gloo/cli/pkg/cmd/check/check_test.go, projects/gloo/cli/pkg/cmd/check/root.go, projects/gloo/cli/pkg/common/get.go
- Backport #8228 to 1.14.x
- Updates `glooctl check` to use the GPRC endpoint for proxy validation, ala `glooctl get proxies`.
- This fixes an issue where the check would report false-positives for invalid proxies that were not persisted.
- Prior to this change, glooctl check used a k8s client to obtain proxy resources
- Since 1.12.x, proxy resources are not persisted by default, so this k8s client failed to obtain proxies, and in turn failed to report errors on proxy resources
=> [1.14.x] Fix non-persisted proxy validation in glooctl check

changelog/v1.13.19/glooctl-proxy-fix.yaml, projects/gloo/cli/pkg/cmd/check/root.go, projects/gloo/cli/pkg/common/get.go
- Backport #8228 to 1.13.x
- Updates `glooctl check` to use the GPRC endpoint for proxy validation, ala `glooctl get proxies`.
- This fixes an issue where the check would report false-positives for invalid proxies that were not persisted.
- Prior to this change, glooctl check used a k8s client to obtain proxy resources
- Since 1.12.x, proxy resources are not persisted by default, so this k8s client failed to obtain proxies, and in turn failed to report errors on proxy resources
=> [1.13.x] Fix non-persisted proxy validation in glooctl check

.github/workflows/composite-actions/prep-go-runner/action.yaml, .github/workflows/push-solo-apis-branch.yaml, changelog/v1.15.0-beta8/cd-go-runner.yaml
The prior https://github.com/solo-io/gloo/pull/8229 PR had a flaw, in that it assumed that all workflows that called `prep-go-runner` were running from inside of a `gloo` repository.  Added a new `working-directory` arg (with a default value of `.`) to rectify this
Testing:
ran a [manual job of push-solo-apis-to-branch](https://github.com/solo-io/gloo/actions/runs/5014530230) with these args:
=> build(push-solo-apis): run setup steps from gloo directory

changelog/v1.15.0-beta8/replace-go-ps-with-gopsutil.yaml, docs/content/static/content/osa_provided.md, go.mod, go.sum, test/services/runner.go
The Keybase fork of go-ps (`github.com/keybase/go-ps`) appears to have been abandoned and left unmaintained for a long time. This PR replaces the usage of `github.com/keybase/go-ps` with `github.com/shirou/gopsutil/v3/process`. `gopsutil` offers the same set of functionalities.
=> refactor: replace go-ps with gopsutil/process

changelog/v1.15.0-beta8/listener_filter.yaml, projects/gloo/pkg/plugins/grpcjson/plugin.go, projects/gloo/pkg/plugins/grpcjson/plugin_test.go
This was supposed to be part of the 1.14 release but it wasn't finished in time.
Original PR: https://github.com/solo-io/gloo/pull/8213#event-9291888143
=> Backport change to put grpc transcoding filters on routes

changelog/v1.15.0-beta8/gateway-kube2e-reorder.yaml, test/kube2e/gateway/gateway_test.go
Place all tests which adjust the validation configuration of our Settings resource into the same context
**This just copies existing tests and moves them into a single context, and makes them Ordered**
When we change validation settings (or any setting), we must wait for the servers to start back up with the new configuration ([code](https://github.com/solo-io/gloo/blob/main/test/kube2e/util.go#L126)). There isn't an easy way to do this generically, so we add a sleep (3 seconds). 
For a lot of our tests in this space, we turn a setting on before the test, and off afterwards. This leads to a lot of flip-flopping of settings, when in reality, we're trying to test a set of behaviors when a setting is configured.
This work moves tests that are similar (ie validate the behavior of our …
=> Stability: Move Tests Which Adjust Validation Configuration to Same Context

changelog/v1.15.0-beta8/helm-indentation.yaml, install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
Fixes indentations in `20-namespace-clusterrole-gateway.yaml` file.
Mostly cosmetics as these do not change the resources' definition, however these were not playing well with some Tilt extensions used for local development.
When deploying Gloo edge locally using [Tilt](https://docs.tilt.dev/api.html) via the `helm_resource` extension, Tilt would effectively complain about the indentation issues fixed in this PR. Even though Tilt should handle them gracefully, fixing them is simpler than handling these in Tilt code.
=> refactor: fix indentation in RBAC resources

changelog/v1.13.20/helm-indentation.yaml, install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
backport of https://github.com/solo-io/gloo/commit/f0ee1d26fab8f3c9466d77a276ba788f1f25e781
=> v1.13.x -- refactor: fix indentation in RBAC resources (#8265)

Makefile, changelog/v1.15.0-beta9/repair-publish-glooctl.yaml, ci/upload_github_release_assets.go
when [attempting a test release](https://solo-io-corp.slack.com/archives/CFK0DQADU/p1685648551095939) for `v1.15.0-beta9`, we encountered a build error with `make publish-glooctl`.  The error was centered around an expected `TAGGED_VERSION` environment variable having been set
This PR resolves said issue and (locally) can run `PUBLISH_CONTEXT=RELEASE make publish-glooctl`
=> build(publish-glooctl): explicitly pass VERSION

.trivyignore, changelog/v1.14.8/cves.yaml, go.mod, go.sum, jobs/kubectl/Dockerfile
backport #8353
To verify locally:
Before fixes (on clean branch):
```
rm -rf _output
make VERSION=0.0.0-before docker-local
make VERSION=0.0.0-before scan-version
cat _output/scans/0.0.0-before/*  # shows CVEs for several images
```
After fixes (from this branch):
```
rm -rf _output
make VERSION=0.0.0-after docker
make VERSION=0.0.0-after scan-version
cat _output/scans/0.0.0-after/*  # comes out clean
```
=> Fix CVEs [1.14]

changelog/v1.12.56/cves.yaml, go.mod, go.sum, jobs/kubectl/Dockerfile
Same changes as #8355
To verify locally:
Before fixes (on clean branch):
```
rm -rf _output
make VERSION=0.0.0-before docker-local
for img in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl; do trivy image --severity HIGH,CRITICAL quay.io/solo-io/$img:0.0.0-before; done
```
After fixes (from this branch):
```
rm -rf _output
make VERSION=0.0.0-after docker-local
for img in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl; do trivy image --severity HIGH,CRITICAL quay.io/solo-io/$img:0.0.0-after; done
```
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8348
=> Fix CVEs [1.12]

changelog/v1.11.59/cves.yaml, go.mod, go.sum, jobs/kubectl/Dockerfile
Same changes as #8356
To verify locally:
Before fixes (on clean branch):
```
rm -rf _output
make VERSION=0.0.0-before discovery-docker gateway-docker gloo-docker \
gloo-envoy-wrapper-docker certgen-docker sds-docker \
ingress-docker access-logger-docker kubectl-docker
for img in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl gateway; do trivy image --severity HIGH,CRITICAL quay.io/solo-io/$img:0.0.0-before; done
```
After fixes (from this branch):
```
rm -rf _output
make VERSION=0.0.0-after discovery-docker gateway-docker gloo-docker \
gloo-envoy-wrapper-docker certgen-docker sds-docker \
ingress-docker access-logger-docker kubectl-docker
for img in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl gateway; do trivy image --severity …
```
=> Fix CVEs [1.11]

changelog/v1.13.20/cves.yaml, go.mod, go.sum, jobs/kubectl/Dockerfile
Note that this didn't require the .trivyignore update from #8353 and #8354 because the version of kubectl from this branch does not have the same vulnerability.
To verify locally:
Before fixes (on clean branch):
```
rm -rf _output
make VERSION=0.0.0-before docker-local
for img in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl; do trivy image --severity HIGH,CRITICAL quay.io/solo-io/$img:0.0.0-before; done
```
After fixes (from this branch):
```
rm -rf _output
make VERSION=0.0.0-after docker-local
for img in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl; do trivy image --severity HIGH,CRITICAL quay.io/solo-io/$img:0.0.0-after; done
```
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8347
=> Fix CVEs [1.13]

changelog/v1.15.0-beta11/correct-envoy-gloo-image-name.yaml, test/services/envoy/factory.go
- Resolves an error introduced in https://github.com/solo-io/gloo/pull/8365 that caused e2e tests to attempt to use `quay.io/solo-io/envoy-gloo-wrapper` instead of `quay.io/solo-io/gloo-envoy-wrapper` when running e2e tests
- I encountered this error when trying to run e2e tests using a locally built gloo-envoy-wrapper image
- The command I used was `ENVOY_IMAGE_TAG=<TAG> TEST_PKG=./test/e2e make test`
- see here: https://github.com/solo-io/gloo/blob/686422e2a33688ddd3cf95cb74f87a388f184f2c/Makefile#L515 the image should be called `gloo-envoy-wrapper`
=> Correct Envoy-Gloo image name in e2e tests

changelog/v1.15.0-beta12/refactor-docker-service-download.yaml, test/e2e/aws_test.go, test/services/consul.go, test/services/envoy/factory.go, test/services/utils/download.go, test/services/vault.go, test/testutils/env.go
Factor out the code for acquiring a test service binary. The behavior is unchanged, simply refactored. We first check for a specific environment variable specifying where to find the binary, then check the test executor's `$PATH`, then resort to running a docker container and extracting the binary from the running container. By using this docker method, we can leverage docker's local image cache to avoid downloading the dependency every time the tests are run without having to specify any additional environment variables when running locally and rapidly iterating.
=> Refactor test services download logic

changelog/v1.14.9/client-secret-api.yaml, docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md, install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml, projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto, projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go, projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go, projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go, projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
This adds the field `disableClientSecret` to the oauth2 APIs. This will enable configuring OKTA with PKCE.
=> Backport API to allow disabling the client secret

changelog/v1.15.0-beta15/add-xds-unit-tests.yaml, projects/gloo/pkg/xds/cache_test.go
Adds additional tests to the xds package
https://github.com/solo-io/solo-projects/issues/5113
BOT NOTES: 
resolves https://github.com/solo-io/solo-projects/issues/5113
=> Add unit tests for xds package

changelog/v1.15.0-beta17/add-raw-header-method-for-http-request.yaml, test/testutils/http_request.go
- Add new method `WithRawHeader` which sets the header at a specific key to the values provided afterward.
There may be instances where the header we are setting has `,` as part of their value - for example HMAC authorization headers are in the form `hmac username="", algorithm="", headers="", signature=""`. 
The existing way of adding headers using our http request builder uses `,` as a delimeter, so adding a new function that handles cases where we _don't_ want to split off a header based on that delimiter. Titled `RawHeader` as we are setting the header to those raw strings without any formating/work done on them.
- ~If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff~
- ~I have added tests that prove my …
=> Add withRawHeader method to http request builder

changelog/v1.15.0-beta18/docs-inheritance.yaml, docs/content/guides/traffic_management/request_processing/append_remove_headers/_index.md, docs/content/guides/traffic_management/request_processing/transformations/_index.md, docs/content/introduction/traffic_filter.md
Adding to the concepts page and linking to existing docs on transformation and auth config as examples
Based on discussion in [Slack](https://solo-io.slack.com/archives/G01MKQQ0Q3W/p1685051433746149).
=> Docs for inheritance

changelog/v1.15.0-beta18/gloohelpers-measure.yaml, test/helpers/benchmark_darwin.go, test/helpers/benchmark_linux.go, test/helpers/certs.go, test/helpers/util_test.go, test/testutils/env.go
- Add `Measure()` function to gloohelpers with darwin and linux implementations
- Undo dot-import of ginkgo in `helpers` package which causes conflict on re-declaration of `Measure()`
We don't always care about the `ignore` value returned by `MeasureIgnore0ns()`
That function returns `true` if the linux-compatible `benchmark.Measure()` returns an error due to recording 0ns as the duration for the given function's runtime
This is relatively common for cases where the function being measured runs very quickly (~100µs) and the measurement may round down
In cases where our expected runtimes are orders of magnitude higher we probably do want to error if we get a 0ns measurement
See [this conversation](https://github.com/solo-io/solo-projects/pull/5142#discussion_r1258931031) about a case where …
=> Gloohelpers measure

Makefile, changelog/v1.15.0-beta19/bump-envoy-gloo.yaml
- Bump envoy-gloo to v1.25.8-patch1, pulling in fixes which resolve CVE-2023-35945
=> [v1.15.x/main] Bump envoy-gloo to v1.25.8-patch1

Makefile, changelog/v1.12.57/bump-envoy-gloo.yaml
- Bump envoy-gloo to v1.23.11-patch1, pulling in fixes which resolve CVE-2023-35945
=> [v1.12.x] Bump envoy-gloo to v1.23.11-patch1

changelog/v1.15.0-beta21/envoy-test-service-data-race.yaml, test/services/envoy/factory.go
Resolve data race in test service used in e2e tests
The `envoy.Factory` is responsible for producing an `envoy.Instance` with necessary configuration. Historically, it also tracked each instance that was created, and when the Factory was cleaned up, it would go to each instance it was aware of and call instance.Clean  on that instance. Cleaning an Envoy instance amounts to tearing down the process that is running the service.
However, when an Envoy instance is Started, it is provided a context, and when that context is cancelled the service is auto-cleaned up (https://github.com/solo-io/gloo/blob/main/test/services/envoy/instance.go#L136). This way, we only have to worry about the test context, and all other resource lifecycles are tied to it.
The race occurred because the instances …
=> Stability: Resolve Envoy Test Service Data Race

docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
The doc for Http Passthrough Auth is creating a service with the wrong name for the example auth service. 
It uses example-grpc-auth-service instead of example-http-auth-service
=> Update Http Passthrough Auth Doc

Makefile, changelog/v1.12.58/bump-envoy-gloo.yaml
- Pulls in upstream Envoy v1.23.12, which includes fixes for
CVE-2023-35941, CVE-2023-35942, CVE-2023-35944, and CVE-2023-35945.
=> [v1.12.x] Bump envoy-gloo to v1.23.12-patch1

Makefile, changelog/v1.13.23/bump-envoy-gloo.yaml
- Pulls in upstream Envoy v1.23.12, which includes fixes for
CVE-2023-35941, CVE-2023-35942, CVE-2023-35944, and CVE-2023-35945.
=> [v1.13.x] Bump envoy-gloo to v1.23.12-patch1

changelog/v1.15.0-beta23/vs-labels.yaml, docs/content/static/content/osa_provided.md, go.mod, test/helpers/snapshot_writer.go, test/helpers/virtual_services.go, test/helpers/virtual_services_test.go, test/kube2e/gateway/gateway_test.go, test/kube2e/gateway/robustness_test.go, test/kube2e/gloo/gloo_resources_test.go, test/kube2e/gloo/snapshot_writer_test.go, test/kube2e/gloomtls/gloo_mtls_test.go, test/kube2e/istio/istio_integration_test.go, test/kube2e/util.go
Support setting the labels on a VS, using the VS builder
Setting the label is helpful for kube tests, to ensure we have unique resources across test cases
Added a wait to ensure that after deleting a proxy, we only proceed if they have been successfully removed
=> Stability: Port Kube2e Changes to Open Source

changelog/v1.15.0-beta23/env-err.yaml, projects/gloo/pkg/plugins/headers/plugin.go, projects/gloo/pkg/plugins/headers/plugin_test.go, projects/gloo/pkg/translator/translator.go
Error when the value of HEADER_SECRET_REF_NS_MATCHES_US is non-empty and can't be parsed as a boolean. 
Forward port of change that I made as a result of this comment: https://github.com/solo-io/gloo/pull/8522#pullrequestreview-1552196329
=> Check for malformed values in HEADER_SECRET_REF_NS_MATCHES_US env var

.github/workflows/cache.yaml, .github/workflows/codegen.yaml, changelog/v1.14.15/gha-cache.yaml
Run a job on push to branch, to ensure a go cache entry exists for the LTS branch
- Create a new cache job to run on pushes to LTS branches
https://github.com/solo-io/solo-apis/pull/847#issuecomment-1552915687
We need to introduce this "on push" trigger on the branch that is performing the action, not just on the main branch
I specified the branch regex, because otherwise, if you just use "on push", all pushes to all branches will re-run this. We only want to run this on a push to an LTS branch
There are 2 ways (as I see it) that we can have a job run on push to the branch:
1. Introduce a new job, that only runs on push
2. Re-use an existing job, and have it run on push
When deciding, I wanted to really focus on:
- Efficiency (let's avoid running jobs unnecessarily when we can)
- …
=> [1.14] Introduce GHA Go Cache on LTS

.github/workflows/cache-setup.yaml, .github/workflows/codegen.yaml, .github/workflows/composite-actions/prep-go-runner/action.yaml, .github/workflows/composite-actions/regression-tests/action.yaml, .github/workflows/push-solo-apis-branch.yaml, Makefile, changelog/v1.15.0-rc4/gha-cache.yaml, changelog/v1.16.0-beta1/gha-cache.yaml
Run a job on push to branch, to ensure a go cache entry exists for the main branch
**This is a forwardport of work introduced into 1.14**
- Create a new cache job to run on pushes to LTS branches
- Update existing jobs to use a composite-action
https://github.com/solo-io/solo-apis/pull/847#issuecomment-1552915687
The work that merged into 1.14 was introduced in the following segments:
- https://github.com/solo-io/gloo/pull/8535
- https://github.com/solo-io/gloo/pull/8538
- https://github.com/solo-io/gloo/pull/8545
I followed the same patterns/decisions as the changes in the 1.14 branch
Since this was tested for 1.14, we assume this will work, but it is good to verify. This can be done after this PR merges.
After this merges, we can then test this, and ensure PRs against this LTS branch …
=> [1.16] Introduce GHA Cache on Main

changelog/v1.15.0-rc4/set-logger-in-tests.yaml, go.mod, go.sum, test/kube2e/gloo/gloo_suite_test.go
Backport of https://github.com/solo-io/gloo/pull/8549
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8548
=> Backport to v1.15 - Fix "log.SetLogger(...) was never called"

changelog/v1.15.0-rc4/update-cloud-builders.yaml, ci/cloudbuild/publish-artifacts.yaml, ci/cloudbuild/run-tests.yaml
https://github.com/solo-io/gloo/pull/8557
Update builders for releases to match enterprise to have the newest 1.20 go patch release used in builds.
This should update all 0.6.2 references to solo cloud builder assets to 0.6.4
This can be tested by release and sanity checked by looking at ee code base.
=> ci: Update builders to match enterprise

.github/workflows/push-solo-apis-branch.yaml, changelog/v1.16.0-beta2/gha-fix.yaml, projects/gloo/pkg/plugins/ratelimit/raw_util.go
Use the correct path for the composite actions when actions have a different working directory.
Add a default case when translating ratelimit actions. In addition to missing fields, it's also possible to define config for an action that can't be cast. Without a default case, we give Envoy an empty action that makes it unhappy.
Failed solo-apis run: https://github.com/solo-io/gloo/actions/runs/5860985506
=> Fix solo-apis action and small addition to rlc translation fix.

changelog/v1.16.0-beta3/fix-check-skip-directives.yaml, ci/github-actions/process-skip-directives/script.sh
This fixes a bug in [process-skip-directives script](https://github.com/solo-io/gloo/blob/main/ci/github-actions/process-skip-directives/script.sh#L28) that checks the changelog from main instead of the base branch
This causes issues when raising PRs against older branches as this can result in including changelogs from main which may contain the skip directives that can lead to kube tests being skipped
=> ci: Fix check skip directives script

.github/workflows/push-solo-apis-branch.yaml, changelog/v1.13.26/indentation-fix.yaml
I accidentally introduced extra indentation when backporting the change to stop using the prep-go-runner action. I handled the solo-apis change for the last 1.13 release by running the action manually with the action defined on 1.14. This PR fixes the action so it will work on releases.
=> Fix push to solo-apis syntax

.github/workflows/push-solo-apis-branch.yaml, changelog/v1.16.0-beta3/push-solo-apis.yaml
Forward port of https://github.com/solo-io/gloo/pull/8585
Our cache action caches the results of gloo's `go mod download` but this action uses the go.mod from the solo-apis repo. The caching wasn't working and isn't useful.
https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1692130274771609
https://github.com/solo-io/gloo/actions/runs/5880803055
=> fp: Remove caching from action to push to solo-apis

.github/workflows/push-solo-apis-branch.yaml, changelog/v1.15.0-rc5/push-solo-apis.yaml
Forward port of https://github.com/solo-io/gloo/pull/8585
Our cache action caches the results of gloo's `go mod download` but this action uses the go.mod from the solo-apis repo. The caching wasn't working and isn't useful.
https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1692130274771609
https://github.com/solo-io/gloo/actions/runs/5880803055
=> [1.15] fp: Remove caching from action to push to solo-apis

Makefile, changelog/v1.16.0-beta6/version-no-tags.yaml
Ensure that a PR from a forked repository, can correctly version resources generated in the PR
- Provide a default VERSION, in case `git describe` returns nothing
The `VERSION` variable in the Makefile is used as the source of truth for identifying asset (docker images, helm charts) tags. On releases, this tag is supplied by the manual version that is supplied, but on PRs, we must determine the version dynamically. To do so, and to ensure that each PR has a unique version, we determine the value by the following:
- Use git describe to gather the latest tag
- Append a unique suffix that is provided by cloudbuild
And this ensures that versions on PRs tend to look like: `1.16.0-beta4-12345`, where 12345 is the `TEST_ASSET_ID`.
_This doesn't work however, when `git describe` returns no tags, …
=> Version Assets Properly from Forked Repositories

changelog/v1.16.0-beta6/update-testclient-docs.yaml, test/testutils/http_client.go
Add comments to testutils.DefaultHttpClient && testutils.DefaultClientBuilder detailing the consequences of it caching TCP connections and to instead create a new client everytime when testing network (L4) filters
=> Advise using HttpClientBuilder when testing network (L4) filters

.github/workflows/add-pr-label.yaml, .github/workflows/cache-eviction.yaml, .github/workflows/cache-setup.yaml, .github/workflows/codegen.yaml, .github/workflows/docs-gen.yaml, .github/workflows/issue_board.yaml, .github/workflows/nightly-tests.yaml, .github/workflows/push-solo-apis-branch.yaml, .github/workflows/regression-tests.yaml, .github/workflows/trivy-analysis-scheduled.yaml, changelog/v1.16.0-beta7/gha-timeouts.yaml
Add sensible timeouts to our GHA, overriding the default of 6 hours, and improve naming of certain actions
- Set `timeout-minutes` for most GHA jobs
- Update names for certain GHAs to align with EE and/or be more presentable
OSS follow-up for solo-io/solo-projects#5327
From that PR:
> Slack: https://solo-io-corp.slack.com/archives/C04CJMXAH7A/p1693566367155739
The nightly tests were unable to resolve the cache entry (likely due to network issues), and caused the job to spin for 6 hours. We should have failed sooner.
All timeouts are meant to be at least one order of magnitude (ie roughly double) what we expect based on recent runs, and no less than five minutes
The scheduled Trivy scan has run successfully taking as long as five hours recently, so we do not want to be any more restrictive …
=> GHA timeouts

.github/workflows/add-pr-label.yaml, .github/workflows/cache-setup.yaml, .github/workflows/codegen.yaml, .github/workflows/docs-gen.yaml, .github/workflows/issue_board.yaml, .github/workflows/nightly-tests.yaml, .github/workflows/push-solo-apis-branch.yaml, .github/workflows/regression-tests.yaml, .github/workflows/trivy-analysis-scheduled.yaml, changelog/v1.15.3/gha-timeouts.yaml
Backport #8637
- Set `timeout-minutes` for most GHA jobs
- Update names for certain GHAs to align with EE and/or be more presentable
Removed cache-eviction action, as it is run on main and does not need backporting.
=> GHA timeouts 1.15

.github/workflows/add-pr-label.yaml, .github/workflows/cache-setup.yaml, .github/workflows/codegen.yaml, .github/workflows/do-not-submit.yaml, .github/workflows/push-solo-apis-branch.yaml, .github/workflows/regression-tests.yaml, changelog/v1.14.19/gha-timeouts.yaml
Backport #8637
- Set `timeout-minutes` for most GHA jobs
- Update names for certain GHAs to align with EE and/or be more presentable
Removed cache-eviction action, as it is run on main and does not need backporting.
Also omitted docs-gen, issue_board, nightly-tests, and trivy-analysis-scheduled actions which were not previously present on this LTS branch
Added timeouts to jobs that are not present in more recent versions
=> GHA timeouts 1.14

.github/workflows/add-pr-label.yaml, .github/workflows/cache-setup.yaml, .github/workflows/codegen.yaml, .github/workflows/do-not-submit.yaml, .github/workflows/push-solo-apis-branch.yaml, .github/workflows/regression-tests.yaml, changelog/v1.13.26/gha-timeouts.yaml
Backport #8637
- Set `timeout-minutes` for most GHA jobs
- Update names for certain GHAs to align with EE and/or be more presentable
Removed cache-eviction action, as it is run on main and does not need backporting.
Also omitted docs-gen, issue_board, nightly-tests, and trivy-analysis-scheduled actions which were not previously present on this LTS branch
Added timeouts to jobs that are not present in more recent versions
=> GHA timeouts 1.13

Makefile, changelog/v1.16.0-beta8/fix-version-on-prs.yaml
Ensure that the VERSION variable, which corresponds to the tag for docker images that are built on the PR, includes the latest git tag, if one exists
This is follow up to https://github.com/solo-io/gloo/pull/8631. In that PR, we identified that forked repos, which do not contain git tags, were failing, because we did not properly identify when `git describe` returned an empty string. The testing steps included there worked on a local machine (mac) but did not verify the tag that our CI uses (linux). 
In a slack conversation (https://solo-io-corp.slack.com/archives/C03MFATU265/p1693594894391679?thread_ts=1693492511.156679&cid=C03MFATU265) the behavior of tagging in CI was identified. It did not break the behavior but was a confusing change.
This PR updates the logic to ensure that we abide …
=> Fix Version Tagging on PRs

Makefile, changelog/v1.16.0-beta10/restore-tag-regex.yaml
- Restore `tag_regex` variable in the top-level Makefile, which was accidentally removed in #8605
- That PR inadvertenly reverted some changes introduced in https://github.com/solo-io/gloo/pull/8653
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8578
=> Restore tag_regex in Makefile

.github/workflows/regression-tests.yaml, changelog/v1.15.6/docs-for-vault-aws-irsa-integration.yaml, docs/content/guides/integrations/vault/_index.md, docs/content/guides/integrations/vault/aws-irsa-auth/_index.md, test/e2e/vault_aws_test.go
_backport of #8647_
Adds user-facing documentation for Vault as a secret storage using AWS IRSA to handle credential fetching and secret access.
- Removed "STS" test in `test/e2e/vault_aws_test.go`.
- I originally added it when creating the first ticket, but was minsunderstanding, since we were working with IRSA and required kubernetes cluster(s).
- Added guide about feature vault integration with AWS IRSA
We recently removed the need to hard-code credentials when setting aws credentials for vault-as-secret-storage (#8622). This opened up the possibility for customers to make use of AWS IRSA which handles credential fetching. These are docs for said possibility.
=> [1.15] Add Vault + AWS IRSA Integration Docs

.github/ISSUE_TEMPLATE/DOCS-ISSUE.yml, .github/workflows/docs-gen.yaml, .github/workflows/trivy-analysis-scheduled.yaml, Makefile, changelog/v1.16.0-beta10/remove-1.11-scans.yaml, docs/Makefile
Stop doing security scans for 1.11 and make other cosmetic changes to reflect dropping of support for 1.11
- Add 1.15.x as an option for docs issue, remove 1.11.x
- Docs gen no longer runs on pushes to 1.11.x and does run on pushes to 1.15.x
- Trivy scans have a minimum version of 1.12.0
- Change default value for `MIN_SCANNED_VERSION`, used by `run-security-scans` target, to `v1.12.0`
- Bump minimum scanned version presented in docs to 1.12.0
A couple of issues were recently opened regarding a [CVE in 1.11](https://github.com/solo-io/solo-projects/issues/5361) and requesting a [release of 1.11](https://github.com/solo-io/solo-projects/issues/5362)
We no longer support 1.11, as of the release of 1.15.0, and …
=> remove 1.11 from scans, docs, issue template

changelog/v1.16.0-beta11/discovery-fips.yaml, install/helm/gloo/templates/_helpers.tpl, install/test/helm_test.go
When enabling FIPS images via Helm, include the discovery image in the list of images which will use the FIPS variant.
- Listed as non-user facing, since this only applies to Enterprise installs
- Includes a unit test to demonstrate the functionality
- Based off of https://github.com/solo-io/gloo/pull/5158, which is when this Helm API was initially introduced
This Helm adjustment is backed by the following enterprise PR: https://github.com/solo-io/solo-projects/pull/5368
- Run helm unit tests
```
TEST_PKG=./install/test/ make test
```
-
=> Helm support for FIPS Discovery image

changelog/v1.15.7/discovery-fips.yaml, install/helm/gloo/templates/_helpers.tpl, install/test/helm_test.go
Backport of: https://github.com/solo-io/gloo/pull/8708
When enabling FIPS images via Helm, include the discovery image in the list of images which will use the FIPS variant.
- Listed as non-user facing, since this only applies to Enterprise installs
- Includes a unit test to demonstrate the functionality
- Based off of https://github.com/solo-io/gloo/pull/5158, which is when this Helm API was initially introduced
This Helm adjustment will be backed by enterprise code. https://github.com/solo-io/solo-projects/pull/5368 is an example of what this looked like for another LTS branch.
- Run helm unit tests
```
TEST_PKG=./install/test/ make test
```
-
=> [1.15] Helm support for FIPS Discovery image

changelog/v1.16.0-beta12/unreleased-envoy-gloo-support.yaml, ci/cloudbuild/run-tests.yaml
- Update CI to better support unreleased assets from envoy-gloo CI builds
- envoy-gloo CI builds and tags assets with a commit SHA. This leads to issues when we test unreleased assets in gloo CI, as gloo CI assumes that envoy-gloo assets are tagged in major.minor.patch-label format.
- This PR introduces a try/except structure to the portion of CI that pulls envoy-gloo assets. First, we try to pull the asset using the major.minor.patch-label format. If that fails, we try to pull the asset using the commit SHA format.
- essentially a port of this PR from the closed-source repo: https://github.com/solo-io/solo-projects/pull/5257
=> Better support for unreleased envoy-gloo assets

Makefile, changelog/v1.16.0-beta12/envoy-change.yaml, ci/cloudbuild/run-tests.yaml, projects/envoyinit/cmd/Dockerfile.envoyinit, projects/gloo/cmd/Dockerfile
Move to an ubuntu based envoy image with plans to introduce distroless in 1.16. 
This is done to avoid cves in glibc that cannot be fixed with our current alpine setup
https://gitlab.alpinelinux.org/alpine/tsc/-/issues/43#note_306270
https://github.com/sgerrand/alpine-pkg-glibc/issues/207#issuecomment-1707209887
https://github.com/sgerrand/alpine-pkg-glibc/issues/176
update docker images for all things with 
glibc is sort of eol for alpine. or at least looks like it
We chose to do it this way to make normal gateway-proxy -> gateway-proxy-debug be a smaller change.
As we intend to backport this to lts branches we wanted the least potential problems and so opted not to go with only distroless to start.
Gateway-proxy comes up and can handle requests on http and https ports
Gloo pod comes up …
=> Move to ubuntu based envoy dockerfiles

changelog/v1.16.0-beta12/helm-wait.yaml, changelog/v1.16.0-beta13/helm-wait.yaml, install/helm/gloo/templates/0-namespace.yaml, install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml, test/kube2e/helm/helm_test.go, test/kube2e/upgrade/upgrade_test.go
Most CI tools wait until resources are ready to mark a release as successful. Eg. [ArgoCD](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/) and [Flux](https://fluxcd.io/flux/components/helm/helmreleases/#disabling-resource-waiting)
We can emulate this by passing the `--wait` flag to helm rather than individually adding support for every CD tool out there.
This PR adds this flag to the helm tests as well as some tweaks to support ArgoCD
This is a complex PR and may require …
=> Add --wait to helm tests and other improvements to support CD tools

changelog/v1.15.9/fix-check-skip-directives-again.yaml, ci/github-actions/process-skip-directives/script.sh
Fixes the failing https://github.com/solo-io/gloo/blob/1.15.x/ci/github-actions/process-skip-directives/script.sh when it runs if there is no changelog
- Fixed process-skip-directives/script.sh
Contributors ran into this issue when there is no changelog present in their PR and tests do not run
https://github.com/solo-io/gloo/actions/runs/6420660619/job/17433245951?pr=8751
https://github.com/solo-io/gloo/actions/runs/6420694824/job/17433357462?pr=8751
=> [1.15] fix: Skip directives script failing on no changelog

changelog/v1.15.9/reenable-probes.yaml, projects/envoyinit/cmd/Dockerfile.envoyinit, projects/gloo/cmd/Dockerfile, test/kube2e/helm/artifacts/helm.yaml
Add a failing test for noncustom readiness probes.
Add wget back to ourgloo and gateway-proxy pods
- New Test option
- Docker files get wget
We do not currently test our default probes. We should.
Ubuntu update broke non-custom probes. This is a quick fix.
Not needed for any alpine setups as it comes with wget by default https://pkgs.alpinelinux.org/package/edge/main/x86/wget 
We probably should consider if we want to update our probes to use curl in the future though.
We chose to do things this way because we dont test all of our helm install options fully.
I manually verified behavior by  checking for wget + sleep in our new docker files.
Added failing test as first commit  and then had it run here with changelog https://github.com/solo-io/gloo/actions/runs/6419883299/job/17430709129
=> 1.15: Add tests for non custom probes and add wget back

changelog/v1.16.0-beta14/configmap-checks.yaml, install/helm/gloo/templates/11-ingress-proxy-deployment.yaml, install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
Forward port of https://github.com/solo-io/gloo/pull/8745/commits/be1bff6a6a641dbfc7d46261e7d0439cc06e53e9
This ensures that the config maps are consistent across branches
In the [previous PR](https://github.com/solo-io/gloo/pull/8733) the redundant checks were not removed but addressed in the backports
https://github.com/solo-io/gloo/pull/8745#discussion_r1347355063
https://github.com/solo-io/gloo/pull/8745#pullrequestreview-1659752500
=> Removing redundant checks in configmaps

changelog/v1.16.0-beta15/do-not-log-envoy-cluster-on-computeCluster.yaml, projects/gloo/pkg/translator/clusters.go
Updated our error report during cluster computing + validation to not print the Envoy cluster.
This was added in [Gloo 0.5.0](https://github.com/solo-io/gloo/commit/68f091e58125110221cbfe8a2009a6a4c5f83b23), where it was imported from solo-projects. While it's hard to trace the historical _decisions_ for printing the cluster, it should be safe to remove because:
1. Users can view cluster information in config dumps 
2. The the error itself already prints the issue.
As part of a quick-follow, will be looking into other areas we log reports to see if they leak data.
- Removed the cluster (`out`) from being printed during validation error.
Users ran into this bug when misconfiguring an Upstream with validation on, where the secret inline data was printed in the error. …
=> Do not print full cluster information on cluster validation errors

changelog/v1.14.23/add-timeout-resource-rollout-job.yaml, docs/content/reference/values.txt, install/helm/gloo/generate/values.go, install/helm/gloo/templates/5-resource-rollout-job-check.yaml, install/helm/gloo/templates/5-resource-rollout-job.yaml, install/helm/gloo/values-template.yaml, install/test/helm_test.go
Adds a longer timeout (600s vs the default is 30s) for the resource rollout job to complete. This can handle cases of slow gloo installs
If the gloo installation is slow, the wait on the resource rollout && rollout check jobs can timeout and execute before the prior jobs have been completed
N/A
N/A
N/A
N/A
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8782
=> [1.14] helm: Adding a longer timeout for the resource rollout job to complete

changelog/v1.13.29/add-timeout-resource-rollout-job.yaml, docs/content/reference/values.txt, install/helm/gloo/generate/values.go, install/helm/gloo/templates/5-resource-rollout-job-check.yaml, install/helm/gloo/templates/5-resource-rollout-job.yaml, install/helm/gloo/values-template.yaml, install/test/helm_test.go
Adds a longer timeout (600s vs the default is 30s) for the resource rollout job to complete. This can handle cases of slow gloo installs
If the gloo installation is slow, the wait on the resource rollout check job can timeout and execute before the prior job has been completed
N/A
N/A
N/A
N/A
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8782
=> [1.13] helm: Adding a longer timeout for the resource rollout job to complete

changelog/v1.16.0-beta15/add-timeout-resource-rollout-job.yaml, docs/content/reference/values.txt, install/helm/gloo/generate/values.go, install/helm/gloo/templates/5-resource-rollout-job-check.yaml, install/helm/gloo/templates/5-resource-rollout-job.yaml, install/helm/gloo/values-template.yaml, install/test/helm_test.go
Adds a longer timeout (600s vs the default is 30s) for the resource rollout job to complete. This can handle cases of slow gloo installs
If the gloo installation is slow, the wait on the resource rollout && rollout check jobs can timeout and execute before the prior jobs have been completed
N/A
N/A
N/A
N/A
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/8782
=> helm: Adding a longer timeout for the resource rollout job to complete

changelog/v1.15.11/do-not-log-envoy-cluster-on-computeCluster.yaml, projects/gloo/pkg/translator/clusters.go
_backport of #8778_
Updated our error report during cluster computing + validation to not print the Envoy cluster.
This was added in [Gloo 0.5.0](https://github.com/solo-io/gloo/commit/68f091e58125110221cbfe8a2009a6a4c5f83b23), where it was imported from solo-projects. While it's hard to trace the historical _decisions_ for printing the cluster, it should be safe to remove because:
1. Users can view cluster information in config dumps 
2. The the error itself already prints the issue.
As part of a quick-follow, will be looking into other areas we log reports to see if they leak data.
- Removed the cluster (`out`) from being printed during validation error.
Users ran into this bug when misconfiguring an Upstream with validation on, where the secret inline data was printed in the error. …
=> [1.15] Do not print full cluster information on cluster validation errors

Makefile, changelog/v1.12.59/bump-envoy-gloo.yaml
- Bump envoy-gloo to 1.23.12-patch3
- This pulls in fixes for CVE-2023-44487
=> [1.12.x] Bump envoy-gloo to fix CVE-2023-44487

Makefile, changelog/v1.13.29/bump-envoy-gloo.yaml, cloudbuild.yaml
- Bump envoy-gloo to 1.23.12-patch3
- This pulls in fixes for CVE-2023-44487
- Bump cloudbuilders to 0.6.5 to pull in go CVE fixes
=> [1.13.x] Bump envoy-gloo to fix CVE-2023-44487

changelog/v1.15.13/fix-secret-deletion-validation-flake-gw-kube2e.yaml, test/helpers/certs.go, test/kube2e/gateway/gateway_test.go
_manual backport of #8795_
Fixing flakes seen by adding retries.
The `FlakeAttempt` is a general (hot)fix.
There are times during our CI tests when we _do not_ get a validation error when deleting a `Secret` that is referenced elsewhere. 
This was an issue I previously hit constantly in 1.14- for 1/2 of runs, but after ~20 runs, I haven't reproduced it locally. In the 1.14 tests, I saw that the VS/proxy did not have an error status until way after (~1 minute, plus I added an annotation to try and force an update). Something similar could be happening here?
My only hypothesis is that resources (specifically the Secret) are created and deleted _too fast_... maybe even _before_ the VS updates to reference it, which is why it deletes with no issue. If not, then more thorough investigation …
=> [1.15] Fix kube2e gateway_test flakes due to recent secret deletion validation

projects/gloo/cli/pkg/cmd/check-crds/root.go
This fixes a dropped `err` variable in the `projects/gloo/cli/pkg/cmd/check-crds` package.
=> projects/gloo/cli/pkg/cmd/check-crds: fix dropped error

changelog/v1.16.0-beta22/fix-nightly-tests.yaml, test/kube2e/upgrade/upgrade_test.go
With the [fix for custom readiness probe](https://github.com/solo-io/gloo/pull/8831), The resource rollout job is not longer in a post hook and the job ttl has changed from 60 t0 300. As a consequence the job is not automatically cleaned as part of the hook deletion policy or within the time between installing gloo and upgrading it in the test. So we wait until the job is deleted after the TTL expires.
Failure in nightly upgrade test : https://github.com/solo-io/gloo/actions/runs/6780225254/job/18428570372
```
[10:34:04] ~/lab/gloo ➦ main $ VERSION=1.0.0-ci WAIT_ON_FAIL=1 KUBE2E_TESTS=upgrade make run-kube-e2e-tests
GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore ACK_GINKGO_RC=true ACK_GINKGO_DEPRECATIONS=v2.9.5 /Users/djumani/lab/gloo/_output/.bin/ginkgo -ldflags="-X …
```
=> Fix nightly upgrade test failure (#8756)

projects/gloo/cli/pkg/cmd/root.go, projects/gloo/cli/pkg/flagutils/common.go
as version 2 focuses on the k8s gateway api, there will be no support for using consul as an api storage backend.
=> remove old flags from glooctl

changelog/v1.16.0-beta25/disable-extauth-sidecar.yaml, docs/content/reference/values.txt, install/helm/gloo/generate/values.go, install/helm/gloo/templates/7-gateway-proxy-deployment.yaml, install/helm/gloo/templates/8-gateway-proxy-horizontal-pod-autoscaler.yaml, install/helm/gloo/templates/8-gateway-proxy-pod-disruption-budget.yaml, install/helm/gloo/templates/9-gateway-proxy-configmap.yaml, install/helm/gloo/templates/_8-default-gateways.tpl, install/helm/gloo/templates/_helpers.tpl, install/helm/gloo/values-template.yaml
When multiple gateway proxies are defined as well as extauth enabled, a user might want to enable the sidecar for a subset of gateway proxies (since some of them do not require extauth) to reduce resource usage and unnecessary network calls to an unused sidecar.
This feature adds the new helm value `gatewayproxy.proxyName.disableExtauthSidecar` to disable the extauth sidecar on it
It also adds additional helper methods to merge resources while omitting keys in those resources which should not be overwritten if empty
- Added a new `gatewayproxy.proxyName.disableExtauthSidecar` value
N/A
N/A
N/A
https://github.com/solo-io/gloo/issues/8430
Had initially thought of the idea to omit fields in an overwrite based on keys as in ddc6774fe70399bdbbd37a870b3f777d9a63f9ab but decided against it as …
=> feat: Allow users to disable extauth sidecar on a per proxy basis

changelog/v1.16.0-beta25/fix-nightlies.yaml, install/helm/gloo/templates/5-resource-rollout-job-clusterrole.yaml, install/helm/gloo/templates/5-resource-rollout-job-clusterrolebinding.yaml, install/helm/gloo/templates/5-resource-rollout-job-role.yaml, install/helm/gloo/templates/5-resource-rollout-job-rolebinding.yaml, install/helm/gloo/templates/5-resource-rollout-job-service-account.yaml, test/kube2e/upgrade/upgrade_test.go
Fix upgrade issues from v1.15.16, v1.14.27 and v1.13.32 to v1.16.0-beta20+
The upgrade failure was caused due to 1.16 having the resource rollout RBAC as a pre-install hook while on 1.13-1.15, it is no longer a hook. 
Understanding the issue :
- When a non-hook resource is made into a pre-upgrade hook and the chart is upgraded, helm starts with deploying the pre-upgrade hook - all good.
- Once the pre-hook phase is complete, helm will decide whether or not to delete the hook based on the deletion policy. In this case, the policy is not to delete the hook on success.
- Next, when deploying the resources as part of the upgrade, helm identifies resources that belong to the chart and deletes all resources in the old chart which do not exist in the upgraded chart - this includes the resource …
=> Fix upgrade issues from v1.15.16, v1.14.27 and v1.13.32 to v1.16.0-beta20+

projects/gloo/cli/pkg/cmd/add/route_interactive_test.go, projects/gloo/cli/pkg/cmd/add/route_test.go
This fixes dropped test `err` variables in `pkg/cmd/add`.
=> pkg/cmd/add: fix dropped test errors

.github/workflows/docs-gen.yaml, changelog/v1.16.0-beta29/update-docs-gen-scanner-min-version-1.12.yaml
We run & publish security scans through `docs-gen.yaml`, and did not update the MIN_SCANNED_VERSION to our latest least-supported-version.
- We now only scan v1.12+ releases on pushes on our supported (v1.12+) branches.
Our security scans reported CVEs for v1.11 of Gloo OSS + EE. We should not be scanning these versions as they fall outside of our current support (N-3 -> 15-3 -> 12).
- https://github.com/solo-io/gloo/issues/8955
- https://github.com/solo-io/solo-projects/issues/5555
We [missed this](https://github.com/solo-io/gloo/pull/8703) when updating our scanner + docs.
=> Update MIN_SCANNED_VERSION version in docs-gen.yaml to v1.12

projects/gloo/pkg/plugins/transformation/plugin_test.go
This fixes a dropped `err` variable in the tests for `pkg/plugins/transformation`.
=> pkg/plugins/transformation: fix dropped test error

Makefile, changelog/v1.16.0-beta29/pin-alpine.yaml
- Update golang/alpine docker images to pin alpine to 3.18
=> [Main/1.16] Pin alpine to 3.18

Makefile, changelog/v1.13.34/kubectl-bump.yaml, cloudbuild.yaml, docs/content/guides/dev/writing_auth_plugins/_index.md, docs/content/guides/security/tls/Dockerfile, docs/examples/session-affinity/Dockerfile, docs/examples/xslt-guide/Dockerfile, example/proxycontroller/Dockerfile, jobs/certgen/cmd/Dockerfile, jobs/kubectl/Dockerfile, projects/accesslogger/cmd/Dockerfile, projects/discovery/cmd/Dockerfile, projects/examples/services/sleeper/Dockerfile, projects/gloo/Dockerfile, projects/ingress/cmd/Dockerfile, projects/sds/cmd/Dockerfile
Kubectl bump, alpine patch bump 
Alpine just as might as well.
Bitnami kubectl image to get security updates for [CVE-2023-39325](https://github.com/advisories/GHSA-4374-p667-p6c8)
go pin until fslibrary issue with alpine bump is resolved
Reviews:
- check that kubectl job has the right value
- check that alpine layer has the correct value
- run cloud build locally see the built images go version
This fixes the kubectl cve which as always can be checked by running a trivy scan before and after.
It should be run something like this for ease of use
` VERSION=1.13/kubectl-bump
make docker 
git checkout main
go run github.com/solo-io/go-utils/securityscanutils/cli scan-version -v \
-r quay.io/solo-io\
-t $(VERSION)\
--images gloo,gloo-envoy-wrapper,discovery,ingress,sds,certgen,access-logger,ku …
=> 1.13: mod: bump both kubectl and alpine

changelog/v1.16.0-beta29/glooctl-versioning.yaml, projects/gloo/cli/pkg/cmd/istio/inject.go, projects/gloo/cli/pkg/cmd/istio/sidecars/sds.go
When running `glooctl instio inject` the version detected needs to be without V so that the actual image can be found.
- Change `GetVersion` to `GetVersionWithoutV`
I run into that, when testing `glooctl istio inject`
Run in an non istio injected environment
`glooctl istio inject` and you will see ERR_IMAGE_PULL.
```
│   Normal   BackOff    9s                 kubelet            Back-off pulling image "quay.io/solo-io/sds:v1.15.17"                                                                               │
│   Warning  Failed     9s                 kubelet            Error: ImagePullBackOff
```
With that change, all is well.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/8983
=> When running `glooctl instio inject` the version detected needs to be without V

Makefile, changelog/v1.14.28/fix-dec-8-2023-cves.yaml, ci/cloudbuild/publish-artifacts.yaml, ci/cloudbuild/run-tests.yaml, cloudbuild-cache.yaml, docs/content/guides/dev/writing_auth_plugins/_index.md, docs/content/guides/security/tls/Dockerfile, docs/examples/session-affinity/Dockerfile, docs/examples/xslt-guide/Dockerfile, example/proxycontroller/Dockerfile, jobs/certgen/cmd/Dockerfile, jobs/kubectl/Dockerfile, projects/accesslogger/cmd/Dockerfile, projects/discovery/cmd/Dockerfile, projects/examples/services/sleeper/Dockerfile, projects/gloo/Dockerfile, projects/ingress/cmd/Dockerfile, projects/sds/cmd/Dockerfile
Fixing new CVEs caught
- Upgraded to alpine:3.17.6 to fix https://github.com/advisories/GHSA-xw78-pcr6-wrg8
- Bumped Go version + Cloudbuild for https://github.com/advisories/GHSA-9f76-wg39-x86h
While working on the 1.14 CVEs, I caught a new one regarding the `libssl` library in alpine `3.17.3`, which needed updating.
```bash
VERSION=<version> make docker -B
for service in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl; do trivy image --severity HIGH,CRITICAL "quay.io/solo-io/${service}:<version>"; done
```
```
quay.io/solo-io/gloo:v1.14.x-oss-prefix (alpine 3.17.5)
=======================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
quay.io/solo-io/gloo-envoy-wrapper:v1.14.x-oss-prefix (alpine 3.17.5) …
```
=> [1.14] Fix 12/8/2023 CVEs

.github/workflows/stalebot.yaml, changelog/v1.16.0-beta29/stalebot.yaml
Introduce a stalebot to actively manage the issues in this project.
Inspired by: https://github.com/solo-io/gloo-mesh-enterprise/blob/main/.github/workflows/stalebot.yaml
All I did was extend the window between when issues are labeled stale, and issues are closed.
-
-
- I reached out to the product team for confirmation (https://solo-io-corp.slack.com/archives/C03L190TQDA/p1701777887923179) and got buy in from @kcbabo @SantoDE @chrisgaun
=> Introduce Stalebot

changelog/v1.15.18/bump-alpine-3.17.6.yaml, cloudbuild-cache.yaml, docs/content/guides/dev/writing_auth_plugins/_index.md, docs/content/guides/security/tls/Dockerfile, docs/examples/session-affinity/Dockerfile, docs/examples/xslt-guide/Dockerfile, example/proxycontroller/Dockerfile, jobs/certgen/cmd/Dockerfile, jobs/kubectl/Dockerfile, projects/accesslogger/cmd/Dockerfile, projects/discovery/cmd/Dockerfile, projects/examples/services/sleeper/Dockerfile, projects/gloo/Dockerfile, projects/ingress/cmd/Dockerfile, projects/sds/cmd/Dockerfile
Bumping Alpine to latest patch release to fix CVEs.
- Bump `alpine` base image to 3.17.6
While working on other CVEs, I caught some on the Alpine image we use (3.17.3). Bumping to the latest release resolves them.
```
VERSION=<version> make docker -B
for service in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl; do trivy image --severity HIGH,CRITICAL "quay.io/solo-io/${service}:<version>"; done
```
```
quay.io/solo-io/gloo:1.15.x-prefix (ubuntu 20.04)
=================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
quay.io/solo-io/gloo-envoy-wrapper:1.15.x-prefix (ubuntu 20.04)
===============================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
quay.io/solo-io/discovery:1.15.x-prefix (alpine 3.17.3) …
```
=> [1.15] Bump Alpine to 3.17.6

changelog/v1.16.0-beta29/fix-dec-8-2023-cves.yaml, cloudbuild-cache.yaml, docs/content/guides/dev/writing_auth_plugins/_index.md, docs/content/guides/security/tls/Dockerfile, docs/examples/session-affinity/Dockerfile, docs/examples/xslt-guide/Dockerfile, example/proxycontroller/Dockerfile, jobs/certgen/cmd/Dockerfile, jobs/kubectl/Dockerfile, projects/accesslogger/cmd/Dockerfile, projects/discovery/cmd/Dockerfile, projects/examples/services/sleeper/Dockerfile, projects/gloo/Dockerfile, projects/ingress/cmd/Dockerfile, projects/sds/cmd/Dockerfile
Fixing new CVEs caught
- Update Go version to `1.21.5`
- Update Alpine to `3.17.6` to fix https://github.com/advisories/GHSA-xw78-pcr6-wrg8
```bash
VERSION=<version> make docker -B
for service in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl; do trivy image --severity HIGH,CRITICAL "quay.io/solo-io/${service}:<version>"; done
```
```
quay.io/solo-io/gloo:main-oss-prefix (ubuntu 20.04)
===================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
quay.io/solo-io/gloo-envoy-wrapper:main-oss-prefix (ubuntu 20.04)
=================================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
quay.io/solo-io/discovery:main-oss-prefix (alpine 3.17.3)
=========================================================
Total: 2 (HIGH: …
```
=> Fix 12/8/2023 CVEs

changelog/v1.16.0-rc2/expand-cli-gateway.yaml, projects/gloo/cli/pkg/cmd/gateway/dump.go, projects/gloo/pkg/utils/sort_routes_test.go, projects/gloo/pkg/utils/ssl.go, projects/gloo/pkg/utils/ssl_test.go, test/helpers/kube_dump.go, test/kube2e/gateway/gateway_suite_test.go, test/kube2e/gloo/gloo_suite_test.go, test/kube2e/glooctl/glooctl_suite_test.go, test/kube2e/gloomtls/gloo_mtls_suite_test.go, test/kube2e/helm/helm_suite_test.go, test/kube2e/helm/helm_test.go, test/kube2e/ingress/ingress_suite_test.go, test/kube2e/istio/istio_suite_test.go, test/kube2e/knative/knative_suite_test.go, test/kube2e/upgrade/upgrade_suite_test.go
Backport of https://github.com/solo-io/gloo/pull/8986
Refactor getting dumps from the proxy. Also export this new method which is quite useful in debugging failures, especially in CI.
This way the config dump, stats, cluster, listener, heap and other info can be dumped if tests fail in CI making debugging them easier
N/A
- Exposed `GetEnvoyDump` in gloo/cli/pkg/cmd/gateway
- Use the newly exposed method to dump data when kube2e tests fail
- Refactored tests in `utils` package to `utils_test` for consistency
N/A
N/A
At times failures are difficult to debug in CI as we do not know if there was an issue with the upstream cluster, etc. This way as part of the tests fail handler, the envoy dump can be fetched to make debugging easier
Backport of https://github.com/solo-io/gloo/pull/8986
N/A …
=> [1.16] Get dumps from envoy and log these dumps on test failures

.github/ISSUE_TEMPLATE/TECH_DEBT.yml, changelog/v1.17.0-beta2/tech-debt-issue-template.yaml
Add an issue template for tracking tech debt and code improvements akin to the one in Gloo Mesh Enterprise ([link](https://github.com/solo-io/gloo-mesh-enterprise/blob/main/.github/ISSUE_TEMPLATE/tech_debt.md?plain=1))
=> Add tech debt issue template

changelog/v1.17.0-beta2/vault-renewal-docs.yaml, changelog/v1.17.0-beta3/vault-renewal-docs.yaml, docs/content/guides/integrations/vault/aws-irsa-auth/_index.md
This guide was updated with https://github.com/solo-io/gloo/pull/9009, and I don't believe it has been through a review by the docs team.
Please review the entire document instead of just the changeset.
* Simplified the logic around the creation of the VAULT_AUTH_ROLE and VAULT_AUTH_POLICY. Previously we were checking if the role/policy existed already and returning the arn if it did.  This made the logic difficult to read and was also assuming the existing entity was properly configured for the purposes of the guide.
* Updated the troubleshooting section to use the command line instead of the console.
=> AWS IRSA Vault guide for Docs review

projects/gateway2/reports/reporter.go, projects/gateway2/reports/reporter_test.go, projects/gateway2/reports/status.go, projects/gateway2/translator/gateway_translator.go, projects/gateway2/translator/listener/gateway_listener_translator.go, projects/gateway2/translator/listener/validation.go, projects/gateway2/translator/plugins/headermodifier/header_modifier_plugin.go, projects/gateway2/translator/plugins/redirect/redirect_plugin.go, projects/gateway2/translator/plugins/urlrewrite/url_rewrite_plugin.go, projects/gateway2/xds/xds_syncer.go
In order to consistently report the Generation while updating statuses for `Gateways` and `HTTPRoutes`, we will track it as part of reporting.
There are differences with how the Gateways and Routes are retrieved for translation and reporting:
* Gateways are retrieved as a List and passed to translation, then the same list is passed for status syncing
* This means we could not track generation as part of reporting, but for consistency we will do so
* If we do not have a report for a translated Gateway, something is wrong, and we will dpanic
* Routes are retrieved via query engine inside translation, so another retrieval step occurs to sync their status
* So the generation could change or routes could be added in this window
* If we do not have a report for a route, we can't be sure if this …
=> track generation at report time

projects/gateway2/controller/controller.go, projects/gateway2/controller/scheme/scheme.go, projects/gateway2/examples/example-http-route-with-header-modifier.yaml, projects/gateway2/examples/example-http-route-with-route-options.yaml, projects/gateway2/helm/gloo-gateway/templates/rbac.yaml, projects/gateway2/kind.sh, projects/gateway2/query/query.go, projects/gateway2/translator/plugins/registry/plugin_registry.go, projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go, projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go, projects/gateway2/translator/plugins/routeoptions/route_options_suite_test.go, projects/gateway2/translator/plugins/utils/plugin_utils.go, projects/gateway2/translator/plugins/utils/plugin_utils_test.go, projects/gateway2/translator/plugins/utils/utils_test.go
Add support for watching and translating `RouteOptions`.
Controller now watches `RouteOptions` similar to other API types and will `Kick()` the reconciler when an event happens. I explored trying to make the controller updates generic, but there didn't seem like a straightforward way to do so that wasn't contrived. Given that the only other type which will follow this specific model is `VHostOptions`, while the rest of the policies will come from the Platform APIs, this method of adding to the controller seems to make sense to me.
New `RouteOptions` plugin added, along with util methods to handle the `ExtensionRef` filter along with the actual retrieval of the referenced object, which ultimately happens inside query engine.
Original PR: https://github.com/solo-io/gloo/pull/8984
=> add RouteOption route plugin

changelog/v1.16.0/bump-ga.yaml
Changelog only request to allow for 1.16 release now that the rcs have been soaked and tested for performance degredations.
=> 1.16/to ga

changelog/v1.15.20/fix-envoy-slow-start-agression.yaml, projects/gloo/pkg/plugins/loadbalancer/plugin.go, projects/gloo/pkg/plugins/loadbalancer/plugin_test.go
Backport slow aggression fix.
fix: slow start aggression
create changelog
update version for the changelog
update runtime key to be configurable per cluster
=> fix: slow start aggression (#9031)

.github/workflows/docs-gen.yaml, .github/workflows/trivy-analysis-scheduled.yaml, Makefile, changelog/v1.17.0-beta5/bump-security-scan-min-version.yaml, docs/Makefile
Update docs gen to reflect currently supported LTS branches
- Bump `MIN_SCANNED_VERSION` in all places to v1.13.0
- Remove v1.12.x and add v1.16.x as docs version to generate
This bump needs to occur whenever we drop support for an LTS branch
This change affects docsgen for both OSS and EE
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/9084
resolves https://github.com/solo-io/solo-projects/issues/5703
=> Bump min scanned version to v1.13.0

changelog/v1.14.29/doc-fixes.yaml, docs/content/guides/security/cors/_index.md, docs/content/reference/values.txt, install/helm/gloo/generate/values.go
=> Doc fixes 1.14

changelog/v1.16.3/move-resource-rollout-cleanup.yaml, install/helm/gloo/templates/5-resource-rollout-check-job.yaml, install/helm/gloo/templates/5-resource-rollout-cleanup-job.yaml
Backport of https://github.com/solo-io/gloo/pull/9094
Tilt supports Helm out-of-the-box via the helm and helm_resource [extension](https://docs.tilt.dev/helm.html#installing-existing-charts). The way helm_resource works is as follows
- It deploys the specified helm chart via helm upgrade --install
- Once installed, it verifies that all the resources in helm get manifest exist
Since the resource-rollout-job is no longer a hook, it needs to be deleted if it exists prior to an upgrade / install since it will not be re-created if it already exists (the default behaviour of helm). This is done as part of the [resource-rollout-check-job](https://github.com/solo-io/gloo/blob/main/install/helm/gloo/templates/5-resource-rollout-check-job.yaml#L104) as a post-install hook for simplicity.
As a …
=> [1.16] move resource rollout job cleanup to pre-upgrade hook

changelog/v1.15.22/move-resource-rollout-cleanup.yaml, install/helm/gloo/templates/5-resource-rollout-check-job.yaml, install/helm/gloo/templates/5-resource-rollout-cleanup-job.yaml
Backport of https://github.com/solo-io/gloo/pull/9094
Tilt supports Helm out-of-the-box via the helm and helm_resource [extension](https://docs.tilt.dev/helm.html#installing-existing-charts). The way helm_resource works is as follows
- It deploys the specified helm chart via helm upgrade --install
- Once installed, it verifies that all the resources in helm get manifest exist
Since the resource-rollout-job is no longer a hook, it needs to be deleted if it exists prior to an upgrade / install since it will not be re-created if it already exists (the default behaviour of helm). This is done as part of the [resource-rollout-check-job](https://github.com/solo-io/gloo/blob/main/install/helm/gloo/templates/5-resource-rollout-check-job.yaml#L104) as a post-install hook for simplicity.
As a …
=> [1.15] move resource rollout job cleanup to pre-upgrade hook

changelog/v1.17.0-beta6/validation-test-flake-fix.yaml, test/kube2e/gateway/gateway_suite_test.go, test/kube2e/gateway/gateway_test.go
- Add a wait for resources to be accepted and wrap an assertion in an `Eventually` to resolve a test flake
This test has been failing often on k8s 1.24 on nightlies
I was also able to reproduce this locally
It's not clear why it fails in k8s 1.24 but not 1.28 or what caused the test to start failing per se
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/9118
=> Gateway validation flake fix

Makefile, changelog/v1.17.0-beta7/fix-nightly-gw2.yaml
The nightly OSS performance test suite was [failing](https://github.com/solo-io/gloo/actions/runs/7751635213/job/21139853735) with:
```
There were failures detected in the following suites:
conformance ./projects/gateway2/tests/conformance [Compilation failure]
```
Since these tests are not part of the performance suite, just explicitly exclude them.
Output after adding the skip:
```
Will skip:
./projects/gateway2/controller
./projects/gateway2/deployer
./projects/gateway2/ports
./projects/gateway2/query
./projects/gateway2/reports
./projects/gateway2/tests/conformance
./projects/gateway2/translator
./projects/gateway2/translator/httproute
./projects/gateway2/translator/listener
./projects/gateway2/translator/plugins/headermodifier
./projects/gateway2/translator/plugins/mirror …
```
=> fix nightly compilation failure

changelog/v1.14.29/fix-envoy-slow-start-agression.yaml, projects/gloo/pkg/plugins/loadbalancer/plugin.go, projects/gloo/pkg/plugins/loadbalancer/plugin_test.go
* fix: slow start aggression
* create changelog
* update version for the changelog
* update runtime key to be configurable per cluster
=> 14 fix: slow start aggression (#9031) (#9087)

changelog/v1.17.0-beta9/docs-rm-wasm.yaml, docs/content/installation/advanced_configuration/wasm.md
* Removes references to WebAssembly Hub and `wasme` CLI.
* Updates the old WAH image to one stored in GCR.
=> Remove WasmHub and wasme from Edge docs

changelog/v1.16.5/add-sds-log-level.yaml, docs/content/reference/values.txt, install/helm/gloo/generate/values.go, install/helm/gloo/templates/7-gateway-proxy-deployment.yaml, install/helm/gloo/values-template.yaml, install/test/helm_test.go, projects/sds/pkg/run/run_main.go
Backport of https://github.com/solo-io/gloo/pull/9102/files helm values to set log level. Add helm flags for setting log level on sds container `.Values.global.glooMtls.sds.logLevel` and setting log level on istio-proxy container `global.glooMtls.istioProxy.logLevel`.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/9006
=> backport sds and envoy log helm value

changelog/v1.17.0-beta10/fix-xds-cache-key.yaml, projects/gloo/pkg/xds/node_hash.go, projects/gloo/pkg/xds/node_hash_test.go
Fix the implementation of node_hash to support the assumption that Enterprise services make when communicating with the control plane.
In classic Gloo Edge (1.16 and below), we only supported a single type of Proxy workload (data plane). This meant that when workloads started, they would identify themselves via the `node.metadata.role` property in the Node metadata. Our xDS cache used a node hash to inspect the value of the `node.metadata.role` and use that string value as the exact cache key.
Node Metadata:
```
node:
metadata:
role: gloo-system~gateway-proxy
```
In-Memory Cache:
```
gloo-system~gateway-proxy: <xDS Snapshot>
```
We relied on the same functionality for non-proxy workloads (like extauth). Node Metadata:
```
node:
metadata:
role: extauth
```
In-Memory Cache:
```
extauth: …
```
=> xds/hash: support non-proxy workload key generation

changelog/v1.15.25/secret-delete-flake.yaml, test/kube2e/gateway/gateway_test.go
Partial backport of https://github.com/solo-io/gloo/pull/9250
Added the call to `verifyGlooValidationWorks` and removed `FlakeAttempts`, but did not need the changes to restore the kube artifact dump as the changes that broke it did not get backported to 1.15. For the same reason, the robustness test fixes were not backported.
"spammed" CI run of gateway tests: https://github.com/solo-io/gloo/actions/runs/8392439465
=> [1.15.x] Delete secret flake mititgation

Makefile, changelog/v1.17.0-beta15/fix-github-release-script.yaml, ci/upload_github_release_assets.go
Publishing glooctl assets to github depends on fragile output of `glooctl version`. This was broken in https://github.com/solo-io/gloo/pull/9212. A more holistic fix to `glooctl version` is in progress in https://github.com/solo-io/gloo/pull/9285, but this PR should unblock releases
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/9288
=> fix github asset publish script, add dry run for PRs

Makefile, changelog/v1.17.0-beta16/remove-pkgmgmt.yaml, ci/README.md, ci/upload_github_release_assets.go, go.mod, go.sum
Following up the unblock PR for the GitHub release assets upload script, this PR removes confusing and antiquated dead code around updating package management systems homebrew and fishfood (archived). The codepath was never called, and it has been confirmed that `glooctl` is updated via autobump in the homebrew repo.
=> Cleanup assets upload script

changelog/v1.17.0-beta16/envoy-sanitize-te-false.yaml, install/helm/gloo/templates/9-gateway-proxy-configmap.yaml, install/test/fixtures.go, install/test/fixtures/envoy_config/bootstrap_extensions.yaml, install/test/fixtures/envoy_config/custom_static_bootstrap.yaml, install/test/fixtures/envoy_config/overload_manager.yaml, install/test/fixtures/envoy_config/static_clusters.yaml, install/test/fixtures/envoy_config/tcp_keepalive.yaml, install/test/helm_test.go
Envoy's change to remove hop-by-hop TE headers broke upstreams whose gRPC client libraries expect a `TE: trailers` header. This is fixed in Envoy 1.29.3, which is not yet released. In the interim we will disable the sanitization.
Implementation: https://github.com/envoyproxy/envoy/pull/30535
Upstream Fix: https://github.com/envoyproxy/envoy/pull/32255
Upstream Fix backport: https://github.com/envoyproxy/envoy/pull/33018 
See slack conversation [here](https://solo-io-corp.slack.com/archives/C03MFATU265/p1712070803092839)
We chose to do things this way in case 1.29.3 is not released at the time 1.17 goes GA or in case the bump is not made
Helm tests upgraded, could stand to test that before/after a grpc upstream did or did not receive the headers
=> hardcode envoy's runtime flag for sanitize TE to false

Makefile, changelog/v1.17.0-beta17/compiler-inlining.yaml
Remove GCflags by default. This should remove compiler inlining which will allow us to run faster. For debug builds that need to dive more deeply these can always be passed in to a build.
=> feat: no compiler inlining

Makefile, changelog/v1.16.10/envoy-gloo-cves.yaml, ci/cloudbuild/publish-artifacts.yaml, ci/cloudbuild/run-tests.yaml
Bumps cloud builders for golang and envoy for envoy upstream changes.
Deals with http2 cve cont in both places.
=> 1.16 bump: envoy-gloo and go (via cbuild) for http2 cont cve

changelog/v1.17.0-beta22/vhopts-rbac.yaml, changelog/v1.17.1/virtualhostoption-rbac.yaml.yaml, install/helm/gloo/templates/44-rbac.yaml
The original virtualhostoptions plugin for k8s gateway implementation missed adding the resource to rbac for the ClusterRole defined for K8s Gateway API.
=> Fix virtualhostoptions rbac for k8s gateway

Makefile, changelog/v1.17.0-beta22/fix-glooctl-istio-inject.yaml
The `glooctl istio inject` command always injects the standard sds image variant irrespective of the variant of edge installed. As tests run on the distroless variant, this PR ensures the standard sds image is built and loaded so the glooctl test passes while we fix the underlying issue
https://github.com/solo-io/gloo/actions/runs/8683582052/job/23826553002?pr=9358
https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1713193713670019
```
Back-off pulling image "quay.io/solo-io/sds:1.0.0-ci1"
Warning  Failed     30s (x3 over 56s)  kubelet            Error: ImagePullBackOff
Warning  Failed     15s (x3 over 59s)  kubelet            Error: ErrImagePull
Warning  Failed     15s (x3 over 59s)  kubelet            Failed to pull image "quay.io/solo-io/sds:1.0.0-ci1": rpc error: code = NotFound …
```
=> Always build and load sds standard image for tests

changelog/v1.15.26/validation-test-flake-fix.yaml, changelog/v1.17.0-beta6/validation-test-flake-fix.yaml, test/kube2e/gateway/gateway_test.go
Backport of https://github.com/solo-io/gloo/pull/9119
=> [1.15.x] Gateway validation flake fix (#9119)

changelog/v1.16.11/validation-test-flake-fix.yaml, changelog/v1.17.0-beta6/validation-test-flake-fix.yaml, test/kube2e/gateway/gateway_test.go
Backport of https://github.com/solo-io/gloo/pull/9119
=> [1.16.x] Gateway validation flake fix (#9119)

changelog/v1.17.0-beta23/skip-glooctl-istio-test-attempt2.yaml, test/kube2e/glooctl/istio_test.go
Fix for bad syntax I added to: https://github.com/solo-io/gloo/pull/9383
Fast follow to https://github.com/solo-io/gloo/pull/9383 which has more context
-
I skipped the tests in CI, but locally you can focus the `Describe` block in the `istio_test` run: 
```
VERSION=1.17.0-beta22 KUBE2E_TESTS=glooctl SKIP_INSTALL=true make run-kube-e2e-tests
```
```
Running Suite: Glooctl Suite - /Users/samheilbron/go/src/github.com/solo-io/gloo/test/kube2e/glooctl
====================================================================================================
Random Seed: 1713470015 - will randomize all specs
Will run 4 of 29 specs
"Thu, 18 Apr 2024 13:53:53 MDT: github.com/solo-io/gloo/test/kube2e/helper/install.go:294"      found Helm index file at: …
```
=> kube2e/glooctl: fix invalid syntax

.github/workflows/composite-actions/kubernetes-e2e-tests/action.yaml, .github/workflows/pr-kubernetes-tests.yaml, changelog/v1.17.0-beta23/cmd-data-race.yaml, pkg/utils/kubeutils/dns.go, pkg/utils/kubeutils/kubectl/cli.go, pkg/utils/kubeutils/names.go, projects/gloo/pkg/syncer/setup/controlplane.go, test/kubernetes/e2e/features/route_options/route_options.go, test/kubernetes/testutils/assertions/curl.go
Expand the utilities for the new kubernetes e2e tests
- I set the value of `--repeat` to 1 so that on PRs we run tests twice. The hope here is we are more aggressive about flakes, and thus can act on them more quickly
- I set the value of `--flake-attempts` to 0 to ensure that we do not retry flakes. My hope is that in other suites that are flakier we could increase that number, and so I'd rather be explicit in this suite.
I don't actually know if this will be resolved, which is why I set it to `resolvesIssue=false`. My hope is that by increasing the number of runs on a PR, we will see more frequently how problematic this is.
Instead of requiring callers to construct their own Kube CLI, we can rely on the one in the assertions provider
We have a number of places in code that construct the …
=> tests/kube/e2e: Expand utilities, run tests multiple times on PRs

changelog/v1.17.0-beta24/delegate-host.yaml, projects/gateway2/translator/httproute/delegation.go, projects/gateway2/translator/httproute/gateway_http_route_translator.go, projects/gateway2/translator/plugins/plugins.go
Sets Hostnames are explicitly in the RouteContext for plugins that handle delegatee (child) routes to associate them with their hostnames, as the hostnames are not set on these routes.
=> gateway v2: set hostnames in RouteContext for plugins

changelog/v1.17.0-beta25/deleg-mulitple-parents.yaml, projects/gateway2/translator/gateway_translator_test.go, projects/gateway2/translator/testutils/inputs/delegation/multiple_parents.yaml, projects/gateway2/translator/testutils/outputs/delegation/multiple_parents.yaml, test/kubernetes/e2e/features/route_delegation/inputs/multiple_parents.yaml, test/kubernetes/e2e/features/route_delegation/suite.go, test/kubernetes/e2e/features/route_delegation/types.go
Adds translator and e2e tests for the scenario where a child route is selected by multiple parents with different hostnames.
=> gateway2/delegation: add test for multiple parents scenario

changelog/v1.17.0-beta26/secret-delete-flake-fix-attempt.yaml, test/kube2e/gateway/gateway_test.go
Moving the `verifyGlooValidationWorks` call immediately before the secret is attempted to be deleted.
There are two validation steps at the beginning of the test, `EventuallyResourceAccepted` and `verifyGlooValidationWorks`
I don't have a good explanation of why this works, but here is the empirical evidence:
Before the update I was able to reproduce the error locally by focusing the context and running the tests with `-until-it-fails`
The tests failed on attempts 21, 111, 18 and 68, which amount to 4 failures in 218 tests, with a mean time to failure of ~55 runs.
After updating and re-running the tests, I was unable to replicate with runs of 84, 173, and 150 tests (all manually stopped), for a total of X runs without failure. If the MTF is 55 runs, it is extremely unlikely to have over …
=> Secret Delete Flake Fix

.gitignore, Makefile, changelog/v1.17.0-beta26/deleg-test-1.yaml, projects/gateway2/translator/backendref/types.go, projects/gateway2/translator/gateway_translator_test.go, projects/gateway2/translator/httproute/delegation.go, projects/gateway2/translator/testutils/inputs/delegation/invalid_child_valid_standalone.yaml, projects/gateway2/translator/testutils/outputs/delegation/invalid_child_valid_standalone.yaml, test/kubernetes/e2e/debugging.md, test/kubernetes/e2e/features/route_delegation/inputs/invalid_child_valid_standalone.yaml, test/kubernetes/e2e/features/route_delegation/inputs/unresolved_child.yaml, test/kubernetes/e2e/features/route_delegation/suite.go, test/kubernetes/e2e/features/route_delegation/types.go
- Reports an unresolved ref status when a parent route does not resolve to any child routes.
- Adds a test to confirm that a child route can work as a standalone route even if it is invalid in the context of route delegation from a parent.
=> gateway2/route-delegation: report child ref status and add more tests

changelog/v1.17.0-beta26/cve-kubctl-update.yaml, jobs/kubectl/Dockerfile
Updated bitnami/kubectl in the [kubectl Dockerfile](https://github.com/solo-io/gloo/blob/e05a5a0c1196fc770307738e117a13818fb4a606/jobs/kubectl/Dockerfile) from 1.28.4 to 1.28.9 to address [CVE-2023-45288](https://github.com/advisories/GHSA-4v7x-pqxf-cx7m)
The [changelog for the image](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md) was reviewed and nothing of concern was found, though it may be notable that the go version used to build Kubernetes went up a minor version from 1.20.13 to 1.21.7 at version 1.28.6.
Addressing a CVE
Existing versions:
```
for service in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl; do trivy image --severity HIGH,CRITICAL "quay.io/solo-io/${service}:1.17.0-beta25-9448"; done
```
<details> …
=> CVE fix bump bitnami/kubectl image

.trivyignore, changelog/v1.13.37/cve-kubctl-update.yaml, cloudbuild.yaml, jobs/kubectl/Dockerfile
Updated CloudBuilder version form `0.7.1` to `0.7.6`. This version is already in use in the EE 1.13 branch, added [here](https://github.com/solo-io/solo-projects/pull/6043)
This PR does not address the CVEs found on the `kubectl` image, as images with the fix are not available:
* [CVE-2023-39325](https://github.com/advisories/GHSA-4374-p667-p6c8) - HTTP/2 vulnerability, and kubectl is only used for jobs
* [CVE-2023-45283](https://github.com/advisories/GHSA-vvjp-q62m-2vph) - Windows filepath issue
* [CVE-2023-45288](https://github.com/advisories/GHSA-4v7x-pqxf-cx7m) - HTTP/2 vulnerability, and kubectl is only used for jobs
These CVEs have been added to the `.trivyignore` file, along with CVE-2024-26147, which is being ignored in later versions but had not yet surfaced in this one. This …
=> V1.13.x CVE 2023 45288

.trivyignore, changelog/v1.14.30/cve-kubctl-update.yaml, ci/cloudbuild/publish-artifacts.yaml, jobs/kubectl/Dockerfile
Updated bitnami/kubectl in the [kubectl Dockerfile](https://github.com/solo-io/gloo/blob/67d2bbfb8e5bb1018799bf8f2240972fae5a98b1/jobs/kubectl/Dockerfile) from 1.25.15 to 1.27.13 to address [CVE-2023-45288](https://github.com/advisories/GHSA-4v7x-pqxf-cx7m). This jump in minor versions was necessary to use images that no longer has CVEs. Kubectl is backwards-compatible 2 versions, so this should be compatible.
Updated CloudBuilder version form `0.7.1` to `0.7.6`. This version is already in use in the EE 1.13 branch, added [here](https://github.com/solo-io/solo-projects/pull/6043)
"Urgent" changelogs:
* https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md#urgent-upgrade-notes
* https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.26.md#urgen …
=> V1.14.x CVE 2023 45288

Makefile, changelog/v1.15.28/envoy-bump-and-test-multivalueheader-fix.yaml, devel/testing/aws-tests.md, test/e2e/aws_test.go, test/gomega/matchers/contain_headers.go
Backport #9455 using corresponding version of Envoy
=> Lambda non-string header tests 1.15

Makefile, changelog/v1.16.13/envoy-bump-and-test-multivalueheader-fix.yaml, devel/testing/aws-tests.md, test/e2e/aws_test.go, test/gomega/matchers/contain_headers.go
Backport #9455 using the appropriate Envoy version
=> Lambda non-string header tests 1.16

changelog/v1.17.0-beta26/test-framework-for-portal.yaml, changelog/v1.17.0-beta27/test-framework-for-portal.yaml, test/kubernetes/e2e/features/deployer/suite.go, test/kubernetes/e2e/features/glooctl/check_suite.go, test/kubernetes/e2e/features/route_delegation/suite.go, test/kubernetes/e2e/gloo_gateway_edge/gloo_gateway_api_test.go, test/kubernetes/e2e/k8sgateway/automtls_istio_test.go, test/kubernetes/e2e/k8sgateway/istio_test.go, test/kubernetes/e2e/k8sgateway/k8s_gw_test.go, test/kubernetes/e2e/test.go, test/kubernetes/e2e/tests/debug_logging_test.go, test/kubernetes/testutils/clients/clients.go, test/kubernetes/testutils/cluster/kind.go
Simplify our test framework further, and enable more dependency injection so we can re-use more of it in our Enterprise Portal e2e tests
After speaking with @jmhbh we decided to try to merge https://github.com/solo-io/gloo/pull/9448 first, as it will unblock portal efforts. That work will require some code duplication in Enterprise, and this PR will allow us to delete that duplication in a follow-up.
Originally our `TestCluster` had state on it, and it "managed" the TestInstallations running on it. We have inverted this relationship and TestInstallations just select a cluster and run against it. This means that we do not need an object that tracks the active installations on a cluster.
A side effect of this is that we remove the register/unregister functions. These were in essence …
=> test/kube/e2e: improved dependency injection

changelog/v1.17.0-beta28/deleg-extref.yaml, projects/gateway2/translator/gateway_translator_test.go, projects/gateway2/translator/httproute/delegation.go, projects/gateway2/translator/httproute/gateway_http_route_translator.go, projects/gateway2/translator/plugins/plugins.go, projects/gateway2/translator/plugins/routeoptions/query/query.go, projects/gateway2/translator/plugins/routeoptions/query/query_test.go, projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go, projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go, projects/gateway2/translator/plugins/utils/plugin_utils.go, projects/gateway2/translator/plugins/utils/plugin_utils_test.go, projects/gateway2/translator/testutils/inputs/delegation/route_options_filter_override_merge.yaml, projects/gateway2/translator/testutils/outputs/delegation/route_options_filter_override_merge.yaml, test/gomega/matchers/have_status.go
Implements merging of RouteOptions attached via ExtensionRef filter and targetRef based policy attachment. ExtensionRef based options have higher priority than targetRef based options, such that if the ExtensionRef based option sets a field, it cannot be overridden by a policy using targetRef. However, unset fields on a policy selected by ExtensionRef may be overridden by targetRef based options.
The merging semantics is already followed when policies are merged along a delegation chain, so this change is required for consistency.
The core of this change to merge policies in order of their priority within the query resolver itself because the resolver is responsible for recursively resolving the policies for delegated routes. Hence, existing lookup of ExtensionRef based options are moved …
=> gateway2/route-options: merge ExtensionRef override with targetRef attachment

changelog/v1.17.0-beta29/deleg-plugin.yaml, pkg/utils/env/env.go, projects/gateway/pkg/translator/converter.go, projects/gateway2/translator/httproute/delegation.go, projects/gateway2/translator/httproute/gateway_http_route_translator.go, projects/gateway2/translator/plugins/plugins.go, projects/gateway2/translator/plugins/routeoptions/query/query.go, projects/gateway2/translator/plugins/routeoptions/query/query_test.go, projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go, projects/gateway2/translator/routeutils/utils.go, projects/gateway2/translator/testutils/outputs/delegation/route_options_filter_override_merge.yaml, projects/gateway2/translator/testutils/outputs/delegation/route_options_inheritance_child_override_ok.yaml, projects/gateway2/translator/testutils/outputs/delegation/route_options_multi_level_inheritance_override_ok.yaml, projects/gloo/pkg/utils/merge.go, projects/gloo/pkg/utils/merge_test.go, test/kubernetes/e2e/tests/k8s_gw_test.go, test/testutils/env.go
This change simplifies how plugins may perform merging of policies in a delegation chain, particularly in the case of RouteOptions. It performs an in-place merge such that the policy on a child route may be overridden by by a subsequent call to the plugin with a different route context.
Further, it accurately tracks the source RouteOptions involved in the merge so that the statuses on them can be correctly reported.
Apply RouteOptions to routes similar to the configs in `projects/gateway2/translator/testutils/inputs/delegation/route_options*` and confirm the merging of policies works as expected.
BOT NOTES: 
resolves https://github.com/solo-io/solo-projects/issues/6204
=> gateway2: simplify how plugins handle delegated routes

changelog/v1.17.0-beta30/advance-port-safe.yaml, test/ginkgo/parallel/ports.go, test/ginkgo/parallel/ports_test.go
Add a test for the AdvancePortSafeListen logic
Slack: https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1716309405979209
We still are seeing some flakes with one particular test service that relies on this functionality. I decided to add these tests to verify that the logic works as expected.
```go
TEST_PKG=test/ginkgo/parallel make test
```
-
=> ginkgo/parallel: add tests for AdvancePortSafeListen

changelog/v1.17.0-beta31/append-missing-https-listener-data.yaml, projects/gateway2/translator/listener/gateway_listener_translator.go
Fixes issue seen (in portal) where the passed **routeCtx** to ApplyRoutePlugin had zero-valued listener information for HTTPS listeners.
- Pass missing HTTPS `listener` data to listener merger.
When using https gateway listener, in Portal the `listener` during the **ApplyRoutePlugin** was missing information.
Only verified [here](https://github.com/solo-io/solo-projects/pull/6229) with a Portal integration.
=> Fix missing listener data for HTTPS listeners during proxy translation

changelog/v1.17.0-beta34/persistproxy-false.yaml, test/kubernetes/e2e/tests/manifests/edge-gateway-test-helm.yaml, test/kubernetes/e2e/tests/manifests/istio-automtls-edge-gateway-test-helm.yaml, test/kubernetes/e2e/tests/manifests/istio-automtls-k8s-gateway-test-helm.yaml, test/kubernetes/e2e/tests/manifests/istio-edge-gateway-test-helm.yaml, test/kubernetes/e2e/tests/manifests/istio-k8s-gateway-test-helm.yaml, test/kubernetes/e2e/tests/manifests/k8s-gateway-no-webhook-validation-test-helm.yaml, test/kubernetes/e2e/tests/manifests/k8s-gateway-test-helm.yaml
Change `persistProxySpec` to false (which is the default) in the kubernetes e2e tests.
Keeping the proxies in memory rather than persisting to etcd is generally recommended for performance reasons.
=> Set persistProxySpec to false in kubernetes e2e tests

changelog/v1.17.0-beta34/glooctl-test-fixes.yaml, projects/gateway2/proxy_syncer/proxy_syncer.go, projects/gateway2/translator/gateway_translator.go, test/kubernetes/e2e/features/glooctl/get_proxy_suite.go
A couple of small updates to the glooctl get proxy test suite:
- Use DeleteFileSafe to fix test flake where VS deletion fails
- Make sure proxies are cleaned up at the end
=> glooctl test fixes

changelog/v1.13.38/docs-backport1.yaml, docs/content/guides/security/access_logging/_index.md, docs/content/introduction/faq.md
=> Doc fixes 1.13

Makefile, changelog/v1.16.15/envoy-bump.yaml
Bump envoy for cves scanners. 
We dont allow configuration of quic or really most any of these but it would still show up in scanners.
- [CVE-2024-34362: Crash (use-after-free) in EnvoyQuicServerStream](GHSA-hww5-43gv-35jv)
- [CVE-2024-34363: Crash due to uncaught nlohmann JSON exception](GHSA-g979-ph9j-5gg4)
- [CVE-2024-34364: Envoy OOM vector from HTTP async client with unbounded response buffer for mirror response, and other components](GHSA-xcj3-h7vf-fw26)
- [CVE-2024-32974: Crash in EnvoyQuicServerStream::OnInitialHeadersComplete()](GHSA-mgxp-7hhp-8299)
- [CVE-2024-32975: Crash in QuicheDataReader::PeekVarInt62Length()](GHSA-g9mq-6v96-cpqc)
- [CVE-2024-32976: Endless loop while decompressing Brotli data with extra input](GHSA-7wp5-c2vq-4f8m)
- [CVE-2024-23326: Envoy incorrectly …
=> make: bump envoy for 1.27.6 to address cve scanners

changelog/v1.17.0-rc3/fix-conformance-setup.yaml, ci/kind/setup-kind.sh
Uses jq to select specifically non-ipv6 ipam config when setting up MetalLB for kube gateway api conformance tests
error seen previously:
```log
Error from server (parsing address pool address-pool: invalid CIDR "fc00:f853:ccd:e793::/64.255.0-fc00:f853:ccd:e793::/64.255.231" in pool "address-pool": invalid IP range "fc00:f853:ccd:e793::/64.255.0-fc00:f853:ccd:e793::/64.255.231": invalid start IP "fc00:f853:ccd:e793::/64.255.0"): error when creating "STDIN": admission webhook "ipaddresspoolvalidationwebhook.metallb.io" denied the request: parsing address pool address-pool: invalid CIDR "fc00:f853:ccd:e793::/64.255.0-fc00:f853:ccd:e793::/64.255.231" in pool "address-pool": invalid IP range "fc00:f853:ccd:e793::/64.255.0-fc00:f853:ccd:e793::/64.255.231": invalid start IP …
```
=> Fix MetalLB setup for Kube GW API conformance tests

changelog/v1.17.0-rc4/test-dbg.yaml, test/kubernetes/testutils/assertions/curl.go
Prints the stdout and stderr of the curl command executed by the test. This is required to debug test failures when the curl request fails.
=> test: print stdout and stderr of Curl request

changelog/v1.17.0-rc4/glooctl-check-fix-prom-stats.yaml, projects/gloo/cli/pkg/cmd/check/proxy_prom_stats.go
During `glooctl check` we check prom stats for the gateway proxies. Currently if the default gateway proxy is disabled (which might be the case if you only want to use the kube gw api integration), glooctl check results in an error. Change it to a warning instead.
Manual testing steps:
```
helm install -n gloo-system gloo gloo/gloo --create-namespace --version 1.17.0-rc3 --set gatewayProxies.gatewayProxy.disabled=true
```
Before fix:
```
> glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking rate limit configs... OK
Checking VirtualHostOptions... OK
Checking RouteOptions... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... 1 Errors! …
```
=> fix `glooctl check` when default gateway proxy is disabled

.github/workflows/nightly-tests.yaml, changelog/v1.18.0-beta1/update-lts.yaml
Update our nightly tests to run against the newly created v1.17.x branch
We want to test our most recent stable branches 
- Change the frequency of our nightly tests from every weekday, to everyday: https://github.com/solo-io/gloo/pull/9620/files#r1638945969
- Allow the conformance tests to be run without the regression tests: https://github.com/solo-io/gloo/pull/9620/files#r1638943927
- Fix a bug in our 1.16 performance tests, which were actually running the 1.15 branch: https://github.com/solo-io/gloo/pull/9620/files#r1638944250
-
I invoked the nightly tests from this branch.
Logs: https://github.com/solo-io/gloo/actions/runs/9506754249
Slack result: https://solo-io-corp.slack.com/archives/C0314KESVNV/p1718315762628899
```
[Gloo OSS Manual run …
```
=> .github/workflows: update nightly tests to include 1.17

changelog/v1.17.0-rc5/dont-crash-on-failed-lease-renewal.yaml, ci/kind/cluster.yaml, ci/kind/setup-kind.sh, pkg/bootstrap/leaderelector/identity.go, pkg/bootstrap/leaderelector/kube/factory.go, pkg/utils/kubeutils/kubectl/cli.go, projects/gloo/pkg/setup/setup.go, test/kube2e/gloo/artifacts/block-gloo-apiserver.yaml, test/kube2e/gloo/artifacts/block-labels.yaml, test/kube2e/gloo/artifacts/helm.yaml, test/kube2e/gloo/bootstrap_clients_test.go, test/kube2e/gloo/gloo_suite_test.go, test/kube2e/gloo/setup_syncer_test.go, test/kube2e/helper/install.go, test/kube2e/helper/kube.go
Backport of https://github.com/solo-io/gloo/pull/9563
After a container has become a leader, any Kube API server unavailability results in the container crashing. This happens as the leader is unable to renew the lease. This is by design as outlined [here](https://github.com/solo-io/gloo/issues/8107#issuecomment-1516250478)
> if we allowed gloo to continue to function as a leader during kube apiserver outage, we risk having two leaders in other failure modes. we should remove the panic and allow gloo to continue to serve last-known xds as a follower (effectively having two followers until kube apiserver recovers). this idea is similar to the role xds relay could play for gloo edge
However, crashing the gloo pods can also lead to an outage during scaling as the gateway-proxy pods that come …
=> [1.17] Retry on leader lease renewal failure

.github/workflows/nightly-tests.yaml, .github/workflows/regression-tests.yaml, changelog/v1.18.0-beta1/disable-ingress-nightlies.yaml
Disables the ingress suite on 1.17 nightlies as it has been deprecated
Ref: https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1716389614777799
=> ci: disable ingress on 1.17 nightlies

.github/workflows/regression-tests.yaml, changelog/v1.17.0-rc6/disable-ingress.yaml
Disables the ingress suite on 1.17 regression tests as it has been deprecated
Ref: https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1716389614777799
=> [1.17] ci: Disable ingress suite on regression tests

changelog/v1.18.0-beta2/helm-repo-update-cilium.yaml, ci/kind/setup-kind.sh
In order to avert helm caching issues with folks who may have already had cilium repo on their machines, we add the repo under a separate name, make sure to update it, then delete the repo when we're done.
Additionally, since the affinity for the operator is set to disallow scheduling multiple pods on the same node, set our replica count to 1 ([ref](https://github.com/cilium/cilium/blob/v1.15.5/install/kubernetes/cilium/values.yaml#L2536))
=> setup kind fix for installing cilium

changelog/v1.18.0-beta2/optimize-glooctl-check.yaml, projects/gloo/cli/pkg/cmd/check/root.go, test/kube2e/glooctl/check_test.go
Optimize `glooctl check` by creating the resource client prior to iterating over namespaces.
This saves a considerable amount of time in large envs consisting of over 700 ns and cuts time by ~50%
See slack conversation [here](https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1718935489580349)
In an env of 700+ ns
glooctl version: `1.17.0-beta34(latest version)`
```
glooctl check  251.22s user 266.20s system 37% cpu 22:48.24 total
```
glooctl version: `1.0.0-ci1 (This PR)`
```
glooctl-darwin-arm64-david check  81.22s user 74.02s system 24% cpu 10:28.20 total
```
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/9673
=> glooctl: Improve performance of the check command by optimizing the creation of clients 

changelog/v1.17.0-rc8/remove-glooctl-init.yaml, projects/gloo/cli/pkg/cmd/check/gloo_instances.go, projects/gloo/cli/pkg/cmd/check/kube_gateway.go, projects/gloo/cli/pkg/cmd/check/root.go
Having the scheme registration for gloo fed APIs in the init causes issues when importing since importing code requires registering the same APIs from a different source. 
In this PR we revert registration to just before needed for an actual call. We also use a local scheme for the client that requires it, and remove the registration of kube gw APIs since we use the library client directly instead of controller-runtime.
- Do not register Kube GW APIs in scheme
- Do not use global scheme
See internal slack conversation [here](https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1719415728479849)
I manually verified behavior by importing this into the location in solo-projects where it was previously failing …
=> Remove glooctl init to not automatically register types to global scheme

changelog/v1.13.38/cve-24790.yaml, cloudbuild.yaml, jobs/kubectl/Dockerfile
Bump cloud-builders to use latest go1.21
Routine Trivy scans identified CVE-2024-24790 in our images, with issues opened including #9672
The CVE is also present in bitnami/kubectl however there is not a version of that image available with the CVE that is compatible with Gloo 1.13
An entry for the CVE is being added to the trivyignore in `main` explaining this
I manually tested the latest released images as follows:
```
for service in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl; do trivy image --severity HIGH,CRITICAL "quay.io/solo-io/${service}:1.13.37"; done
```
<details>
<summary>
Results:
</summary>
```
2024-06-26T17:00:33-04:00	INFO	Vulnerability scanning is enabled
2024-06-26T17:00:33-04:00	INFO	Secret scanning is enabled
2024-06-26T17:00:33-04:00 …
```
=> 1.13 - CVE Go bump

changelog/v1.14.31/cve-24790.yaml, ci/cloudbuild/publish-artifacts.yaml, ci/cloudbuild/run-tests.yaml, jobs/kubectl/Dockerfile
Bump bitnami/kubectl image to resolve CVEs and cloud-builders to use latest go1.21
Routine Trivy scans identified CVE-2024-24790 in our images, with issues opened including #9671
I manually tested the latest released images as follows:
```
for service in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl; do trivy image --severity HIGH,CRITICAL "quay.io/solo-io/${service}:1.14.30"; done
```
<details>
<summary>
Results:
</summary>
```
2024-06-26T15:29:52-04:00	INFO	Vulnerability scanning is enabled
2024-06-26T15:29:52-04:00	INFO	Secret scanning is enabled
2024-06-26T15:29:52-04:00	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-06-26T15:29:52-04:00	INFO	Please see also …
```
=> 1.14 - CVE bitnami/kubernetes and Go bump

changelog/v1.15.29/cve-24790.yaml, ci/cloudbuild/publish-artifacts.yaml, ci/cloudbuild/run-tests.yaml, jobs/kubectl/Dockerfile
Bump bitnami/kubectl image to resolve CVEs and cloud-builders to use latest go1.21
Routine Trivy scans identified CVE-2024-24790 in our images, with issues opened including #9670
I manually tested the latest released images as follows:
```
for service in gloo gloo-envoy-wrapper discovery ingress sds certgen access-logger kubectl; do trivy image --severity HIGH,CRITICAL "quay.io/solo-io/${service}:1.15.28"; done
```
<details>
<summary>
Results:
</summary>
```
2024-06-26T13:44:34-04:00	INFO	Vulnerability scanning is enabled
2024-06-26T13:44:34-04:00	INFO	Secret scanning is enabled
2024-06-26T13:44:34-04:00	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-06-26T13:44:34-04:00	INFO	Please see also …
```
=> 1.15 - CVE bitnami/kubectl and Go bump

changelog/v1.17.0-rc10/rename-ggv2-enablement-var.yaml, install/helm/gloo/templates/1-gloo-deployment.yaml, projects/gloo/cli/pkg/cmd/check/kube_gateway.go, projects/gloo/cli/pkg/kubegatewayutils/detect.go, projects/gloo/constants/gloo_gateway.go, projects/gloo/constants/istio.go
_backport of https://github.com/solo-io/gloo/pull/9708_
- Rename ggv2 enablement variable to remove `EXPERIMENTAL`.
As this is reaching GA, this is no longer an experimental feature.
Relying on CI (specifically gateway tests), as this just changes the envVar naming used to install ggv2 controller.
=> [1.17] Rename GGv2 env vars to remove `experimental` phrasing

changelog/v1.13.39/infer-gloo-deploy-name.yaml, projects/gloo/cli/pkg/cmd/check/gloo_stats.go, projects/gloo/cli/pkg/cmd/check/root.go, projects/gloo/cli/pkg/cmd/check/root_test.go, projects/gloo/cli/pkg/common/get.go, projects/gloo/cli/pkg/helpers/clients.go, projects/gloo/cli/pkg/xdsinspection/get_last_config.go
Infer the gloo deployment name in cases where the deployment name is not the default `gloo`. The gloo deployment is identified by the `gloo=gloo` label.
This will be forward ported
https://github.com/solo-io/gloo/issues/9163
Rather than adding another flag for the gloo deployment name which can soon ballon into a flag for the name of each deployment, I've decided to identify the deployment via the labels.
The following commands depend on the gloo deployment name :
- `glooctl check`
```
$ kg get deploy
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
discovery        1/1     1            1           5h33m
gateway-proxy    1/1     1            1           5h33m
gloo-deploy-v2   1/1     1            1           9m9s
$ ./_output/glooctl-darwin-amd64 check
Checking deployments... OK …
```
=> [1.13] cli: Infer gloo deploy name

changelog/v1.14.32/infer-gloo-deploy-name-114.yaml, projects/gloo/cli/pkg/cmd/check/gloo_stats.go, projects/gloo/cli/pkg/cmd/check/root.go, projects/gloo/cli/pkg/common/get.go, projects/gloo/cli/pkg/helpers/clients.go, projects/gloo/cli/pkg/printers/upstream.go, projects/gloo/cli/pkg/printers/upstream_test.go, projects/gloo/cli/pkg/xdsinspection/get_last_config.go
Infer the gloo deployment name in cases where the deployment name is not the default `gloo`. The gloo deployment is identified by the `gloo=gloo` label.
Forward port of https://github.com/solo-io/gloo/pull/9719
https://github.com/solo-io/gloo/issues/9163
Rather than adding another flag for the gloo deployment name which can soon ballon into a flag for the name of each deployment, I've decided to identify the deployment via the labels.
The following commands depend on the gloo deployment name :
- `glooctl check`
```
$ kg get deploy
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
discovery        1/1     1            1           5h33m
gateway-proxy    1/1     1            1           5h33m
gloo-deploy-v2   1/1     1            1           9m9s
$ ./_output/glooctl-darwin-amd64 check …
```
=> [1.14] cli: Infer gloo deploy name

changelog/v1.18.0-beta7/fix-self-managed.yaml, install/helm/gloo/crds/gateway.gloo.solo.io_gatewayparameters.yaml, projects/gateway2/api/v1alpha1/gateway_parameters_types.go
There was an [issue](https://github.com/solo-io/gloo/issues/9740) with creating GatewayParameters that had selfManaged set, when using Kubernetes versions older than 1.29.
We use an empty struct to indicate that the proxies will be self-managed (rather than auto-provisioned):
```
apiVersion: gateway.gloo.solo.io/v1alpha1
kind: GatewayParameters
metadata:
name: gw-params
spec:
selfManaged: {}
```
This worked fine in Kubernetes 1.29+ due to [this fix](https://github.com/kubernetes/kubernetes/pull/121459), but on older Kubernetes versions it was complaining with an error like `The GatewayParameters "gw-params" is invalid: spec: Invalid value: "object": invalid object type, expected either Properties or AdditionalProperties with Allows=true and non-empty Schema evaluating rule: only one of …
=> Fix GatewayParameters selfManaged

changelog/v1.17.0-rc12/listeners-reuse-ports.yaml, projects/gateway2/translator/gateway_translator_test.go, projects/gateway2/translator/listener/gateway_listener_translator.go, projects/gateway2/translator/testutils/inputs/multiple-listeners-http-routing/gateway.yaml, projects/gateway2/translator/testutils/inputs/multiple-listeners-https-routing/gateway.yaml, projects/gateway2/translator/testutils/outputs/multiple-listeners-http-routing-proxy.yaml, projects/gateway2/translator/testutils/outputs/multiple-listeners-https-routing-proxy.yaml
Backport of #9750 
HTTPS listeners on kube gateways were not aggregating properly due to translating away from privileged ports.
- Translate port before looking up if we already have listener
Users ran into this bug when applying a Gateway with multiple HTTPS listeners using the same port
See slack conversation [here](https://solo-io-corp.slack.com/archives/C07077NS0NP/p1720729966605369)
Translation unit tests added. Can be manually verified using the resource specified in the issue.
=> [1.17] Fix HTTPS listener aggregation with kube gateway

.github/workflows/trivy-analysis-scheduled.yaml, .trivyignore, Makefile, changelog/v1.18.0-beta8/1-17-ga.yaml, docs/active_versions.json
Include the 1.17.x branch in the docs and trivy scan versions.
1.17.0 was released yesterday, and thus the 1.17 branch should follow the pattern of our other LTS branches
-
-
-
=> docs: mark 1.17 as latest stable

.github/workflows/docs-gen.yaml, changelog/v1.18.0-beta8/update-docs-gen-scanner-min-version-1.14.yaml, changelog/v1.18.0-beta9/update-docs-gen-scanner-min-version-1.14.yaml
With the GA release of 1.17, our minimum supported version moved from 1.13 to 1.14.
- Updated `docs-gen.yaml` to scan from 1.14+.
- Scanning/publishing scans for 1.14+.
We did updates update the minimum version [here](https://github.com/solo-io/gloo/pull/9769), but missed this file.
=> Update `docs-gen.yaml` to scan from 1.14+

changelog/v1.18.0-beta11/deleg-fix-6621.yaml, projects/gateway2/translator/gateway_translator_test.go, projects/gateway2/translator/httproute/delegation_helpers.go, projects/gateway2/translator/testutils/inputs/delegation/bug-6621.yaml, projects/gateway2/translator/testutils/outputs/delegation/bug-6621.yaml
There's a bug where if a child route contains an invalid rule (rule not matching the parent matcher), then even though the matcher is discarded, the rule with an empty matcher but valid backendRef is returned by GetDelegatedRoutes(). The result is that a `/` route is programmed for such an invalid route rule. A more precise fix is to also prune the rules that do not have a valid matcher so that we do not rely on the translator to interpret a route without a valid matcher as '/', which could be an alternative fix though fragile.
The essence of this fix is to prune both the `rules` and `matches` field on the child route when we process it in the context of the parent matcher, so that:
1. invalid matchers on the child route are discarded
2. invalid rules (no valid child matchers) are also …
=> gateway2/delegation: fix extraneous route arising from invalid child rule

.trivyignore, changelog/v1.18.0-beta11/ignore-false-positive-istio-cve.yaml
This is a cherry-pick (of sorts) of the fix for some false positive CVE reports on solo-projects. While this repository is not affected by the CVE (because it does not actually contain this dependency), it serves as a point of documentation as to why trivy may falsely report this repository as having this CVE reported.
=> Ignore false positive istio cves

changelog/v1.18.0-beta12/extref-merge.yaml, projects/gateway2/translator/gateway_translator_test.go, projects/gateway2/translator/plugins/routeoptions/query/query.go, projects/gateway2/translator/plugins/routeoptions/query/query_test.go, projects/gateway2/translator/plugins/utils/plugin_utils.go, projects/gateway2/translator/plugins/utils/plugin_utils_test.go, projects/gateway2/translator/testutils/inputs/route_options/merge.yaml, projects/gateway2/translator/testutils/outputs/route_options/merge.yaml, test/kubernetes/e2e/features/route_options/suite.go, test/kubernetes/e2e/features/route_options/types.go
Enables merging of multiple ExtensionRef based RouteOption
attachments for a rule within an HTTPRoute.
Run the TestMerge test in the RouteOptions e2e suite, or try attaching 
multiple ExtensionRef based options to a rule and verifying they merge.
=> gateway2/route-options: merge extensionRef based attachments

changelog/v1.18.0-beta13/admin-server-p4.yaml, pkg/schemes/scheme.go, pkg/utils/glooadminutils/admincli/README.md, projects/gloo/pkg/servers/iosnapshot/history.go, projects/gloo/pkg/servers/iosnapshot/resources.go
Fast follow changes to incorporate feedback from  https://github.com/solo-io/gloo/pull/9844
The previous conversations can be found here:
- https://github.com/solo-io/gloo/pull/9844/files#r1702168427
- https://github.com/solo-io/gloo/pull/9844/files#r1702186289
- https://github.com/solo-io/gloo/pull/9844/#discussion_r1702211248
- https://github.com/solo-io/gloo/pull/9844/#discussion_r1702180013
-
These are not functional changes, so I relied on the existing CI tests to validate
-
=> admin/history: fast-follow PR feedback

changelog/v1.17.2/fix-image-digests.yaml, docs/content/reference/values.txt, install/helm/gloo/generate/values.go, install/helm/gloo/templates/_helpers.tpl, install/test/helm_suite_test.go, install/test/helm_test.go, test/makefile/make_suite_test.go, test/makefile/make_test.go, test/makefile/makefile.go
backport https://github.com/solo-io/gloo/pull/9869
=> Fix image digests [1.17]

changelog/v1.17.2/fix-eds-error.yaml, projects/gloo/pkg/plugins/kubernetes/eds.go, projects/gloo/pkg/plugins/kubernetes/eds_test.go, test/kube2e/helm/helm_test.go
Backport of https://github.com/solo-io/gloo/pull/9872
When following the [production recommendations](https://docs.solo.io/gloo-edge/latest/operations/production_deployment/), the following error is seen in the gloo pod
```
E1005 20:41:30.275565       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:gloo-system:gloo" cannot list resource "endpoints" in API group "" at the cluster scope
W1005 20:42:21.655454       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:gloo-system:gloo" cannot list resource "endpoints" in API group "" at …
```
=> [1.17] Ensure endpoints for upstreams are listed within watchNamespaces 

Makefile, changelog/v1.16.19/deallocate-tls-on-worker-thread.yaml
Bump Envoy to incorporate fix that allows thread-local slots to be deallocated on worker threads.
See slack conversation [here](https://solo-io-corp.slack.com/archives/C011H3TU17T/p1722369125146919)
The fix in our Envoy repositories includes the tests added by upstream which pass successfully
=> Deallocate TLS slots on worker threads - v1.16.x

Makefile, changelog/v1.17.4/update-envoy-gloo.yaml
Bump Envoy to incorporate fix that allows thread-local slots to be deallocated on worker threads.
See slack conversation [here](https://solo-io-corp.slack.com/archives/C011H3TU17T/p1722369125146919)
The fix in our Envoy repositories includes the tests added by upstream which pass successfully
=> Deallocate TLS slots on worker threads - v1.17.x

changelog/v1.18.0-beta16/helm-priority-class-name.yaml, docs/content/reference/values.txt, install/helm/gloo/generate/values.go, install/helm/gloo/templates/7-gateway-proxy-deployment.yaml, install/test/helm_test.go
Ensure that gateway-proxy deployments respect the  `gatewayProxy.NAME.kind.deployment.priorityClassName` field. This API allows you to set the PriorityClassName for gateway-proxy Pods. This is already supported on all other Gloo deployments.
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
This is an important Kubernetes feature, that is especially relevant for Pods (like the data plane) that customers want to assign high priorities to.
We have a `PodSpec` API, which was available under `kind.deployment`, but was not being used. I added a comment to clarify how this is confusing to developers.
I re-used an existing Helm field in our `PodSpec`. 
This allows us to expose the relevant APIs that caused users to rely on the `kubeResourceOverride`. When using …
=> helm: support PriorityClassName on gateway-proxy

changelog/v1.17.4/extref-merge.yaml, projects/gateway2/translator/gateway_translator_test.go, projects/gateway2/translator/plugins/routeoptions/query/query.go, projects/gateway2/translator/plugins/routeoptions/query/query_test.go, projects/gateway2/translator/plugins/utils/plugin_utils.go, projects/gateway2/translator/plugins/utils/plugin_utils_test.go, projects/gateway2/translator/testutils/inputs/route_options/merge.yaml, projects/gateway2/translator/testutils/outputs/route_options/merge.yaml, test/kubernetes/e2e/features/route_options/suite.go, test/kubernetes/e2e/features/route_options/types.go
Enables merging of multiple ExtensionRef based RouteOption attachments for a rule within an HTTPRoute.
=> [backport] gateway2/route-options: merge extensionRef based attachments (#9834)

changelog/v1.17.5/minor-reorg-and-rename.yaml, devel/contributing/conventions.md, projects/gateway/pkg/syncer/translator_syncer.go, projects/gateway/pkg/syncer/translator_syncer_integration_test.go, projects/gateway2/install.sh, projects/gloo/pkg/discovery/discovery.go, projects/gloo/pkg/discovery/run.go, projects/gloo/pkg/syncer/setup/setup_syncer.go, projects/gloo/pkg/syncer/translator_syncer.go
reorg and rename various components to be more readable
this commit contains no functional changes
note: backport of (#9883)
Reorg setup_syncer and rename various variables related to the core translator/syncer logic to be more 'correct' and readable.
These were all found while digging into syncers and translators and impeded my ability to read and grok the flow of data and control.
No functional changes
Introduces `MARK:` comments for help navigating via [VSCode minimap](https://code.visualstudio.com/docs/getstarted/userinterface#_minimap)
=> [v1.17.x] reorg and rename various components to be more readable

Makefile, changelog/v1.18.0-beta16/install-ginkgo-make-install-go-tools.yaml
This PR adds `ginkgo` as a installation requirement in the `_output/bin` directory when running `make install-go-tools`. `ginkgo` is a requirement of the test harness, and should be installed similar to other go tools.
=> Add ginkgo to make install-go-tools command

changelog/v1.16.20/fix-status-syncer-test.yaml, test/kube2e/ingress/status_syncer_test.go
Nightly tests were failing on [status_syncer_test.go:486](https://github.com/solo-io/gloo/blob/v1.16.x/test/kube2e/ingress/status_syncer_test.go#L486) on 1.16.x: 
```
Service "dusty" is invalid: status.loadBalancer.ingress: Forbidden: may only be used when `spec.type` is 'LoadBalancer'
{
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "Service \"dusty\" is invalid: status.loadBalancer.ingress: Forbidden: may only be used when `spec.type` is 'LoadBalancer'",
Reason: "Invalid",
Details: {
Name: "dusty",
Group: "",
Kind: "Service",
UID: "",
Causes: [
{
Type: "FieldValueForbidden",
Message: "Forbidden: may only be used when `spec.type` is 'LoadBalancer'",
Field: …
```
=> Fix 1.16.x ingress test

.github/workflows/composite-actions/prep-go-runner/action.yaml, changelog/v1.18.0-beta17/update-actions-cache-to-v4.yaml
Update `actions/cache` to v4 to use node 20.
Successful run:
https://github.com/solo-io/gloo/actions/runs/10562875616
Run from main with warnings:
https://github.com/solo-io/gloo/actions/runs/10555969742
=>  Update actions/cache to use v4/node20

changelog/v1.18.0-beta18/group-certgen-helm.yaml, install/helm/gloo/templates/6.5-gateway-certgen-cronjob.yaml, install/helm/gloo/templates/6.5-gateway-certgen-job-secret-create-role.yaml, install/helm/gloo/templates/6.5-gateway-certgen-job-secret-create-rolebinding.yaml, install/helm/gloo/templates/6.5-gateway-certgen-job-service-account.yaml, install/helm/gloo/templates/6.5-gateway-certgen-job-vwc-update-clusterrole.yaml, install/helm/gloo/templates/6.5-gateway-certgen-job-vwc-update-clusterrolebinding.yaml, install/helm/gloo/templates/6.5-gateway-certgen-job.yaml, install/test/helm_test.go, install/test/rbac_test.go
Introduces a `gloo.solo.io/component` label to group Helm resources that are associated with a given component. This is required by downstream projects that use Helm as a templating engine to be able to group resources associated with a component and customize their behavior. This change groups resources required by the certgen component using the new label.
Refer to https://github.com/solo-io/solo-projects/issues/6824
=> helm/gloo: introduce component label for grouping resources

Makefile, changelog/v1.18.0-beta18/fix-conformance-make-target.yaml
Fix the "conformance" and "conformance-%" targets in the Makefile
to run the "TestConformance" suite. Previously, both the "TestConformance"
and "TestExperimental" suites were run.
This was causing issues for me locally while I was trying to replicate the
downstream https://github.com/solo-io/solo-projects/issues/5838 issue
where the conformance suite cannot be run locally on macos hosts. As
we were silently running both suites, I was running into the experimental
suite failing as artifacts from the standard suite were still being GCd by kube.
=> Makefile: Fix the conformance-* targets

changelog/v1.17.8/strict-tls-validation.yaml, projects/gateway2/translator/sslutils/ssl_utils.go, projects/gloo/pkg/utils/ssl.go, projects/gloo/pkg/utils/ssl_test.go
In go pem decoding is intentionally spec compliant. This means that it is very permissive with its decoding and will skip un-parsable, possibly usable or just commented data.
This means that when we consume crt data we may pass along info that is rejected by envoy which can stall configuration and is generally something we try to avoid.
Rely on kubernetes cert encoding to check to see if anything was dropped in decoding from pem and then emit an error if anything was dropped.
Originally we attempted to go the route as seen in https://gist.github.com/anitgandhi/58b0618512fdb3caa89e86c8a6a536ab  from https://github.com/golang/go/issues/34069 
While this mostly worked and caught several issues we continued to find more edge cases such as with headers. Given this we decided to lean heavily on …
=> 1.17: projects/utils/ssl: Add a check for ssl secrets that will be rejected by envoy but not go

.trivyignore, changelog/v1.18.0-beta23/update-trivy0ignore-cve-2024-27289.yaml
Update trivignore to clarify when one entry can be removed and to add another entry
solo-io/go-utils#533 resolves CVE-2024-45258
That CVE does not impact Gateway, so there's no point expending the effort to backport it and bring it into LTS branches, however once all LTS branches have caught up with that PR, which is expected to be included in v0.27.0, the trivyignore entry for that CVE can be removed
More detail on why we're not resolving CVE-2024-27289 for 1.14 [here](https://github.com/solo-io/solo-projects/issues/6869#issuecomment-2362025363)
=> Trivyignore updates

changelog/v1.18.0-beta24/production-helm-profiles-in-tests-part2.yaml, pkg/utils/helmutils/unmarshal.go, test/kubernetes/e2e/test.go, test/kubernetes/testutils/gloogateway/context.go, test/testutils/helm_values.go
Adjust the way that the gloogateway.Context is validated for a given TestInstallation
Fast follow to https://github.com/solo-io/gloo/pull/10106
In the previous PR, we introduced a way to validate a file that contained Helm values for a given installation. Baked into that validation is an assumption that the file contains values for an open source installation of Gloo Gateway.
However, we want to make it so that the same functionality can be invoked for an Enterprise installation.
The proposed solution is two-fold:
- Adjust the constructor to not perform validation, and follow the "new is glue" motto
- Adjust the validation function to accept a validator, and inject an oss implementation for the oss tests
While I was working on an EE PR, I found some code that was duplicated and could just …
=> test/kubernetes/e2e: relax validation constraints for gloogateway.context

changelog/v1.17.11/discovery-watchlabels-bugfix.yaml, projects/gloo/pkg/discovery/discovery.go, test/kube2e/gateway/gateway_test.go, test/kubernetes/e2e/debugging.md, test/kubernetes/e2e/features/discovery_watchlabels/discovery_watchlabels_suite.go, test/kubernetes/e2e/features/discovery_watchlabels/testdata/service-with-labels.yaml, test/kubernetes/e2e/features/discovery_watchlabels/testdata/service-with-modified-labels.yaml, test/kubernetes/e2e/features/discovery_watchlabels/testdata/service-with-no-matching-labels.yaml, test/kubernetes/e2e/features/discovery_watchlabels/testdata/service-without-labels.yaml, test/kubernetes/e2e/features/discovery_watchlabels/types.go, test/kubernetes/e2e/tests/discovery_watchlabels_test.go, test/kubernetes/e2e/tests/discovery_watchlabels_tests.go, test/kubernetes/e2e/tests/manifests/discovery-watchlabels-test-helm.yaml
Backport #10118
This is a clean cherry-pick with no modifications
This branch will contain redundant Discovery tests, with functionality tested in both kube2e and kubernetes/e2e 
Earlier versions will only have kube2e while later versions will only have kubernetes/e2e
Manual testings has not been done for 1.17, however the kube2e and kubernetes/e2e tests running in CI should be sufficient to prove the bug has been fixed
=> 1.17 - Discovery resource version err (#10118)

changelog/v1.15.32/discovery-watchlabels-bugfix.yaml, projects/gloo/pkg/discovery/discovery.go, test/kube2e/gateway/gateway_test.go
Backport #10118 
This cherry-pick omits tests added in the kubernetes/e2e as that directory/framework is not present in 1.16
Manual testing has not been done for 1.16, however the kube2e test running in CI should be sufficient to prove the bug has been fixed
=> 1.15 - Discovery resource version err (#10118)

.trivyignore, changelog/v1.18.0-beta25/trivy-ignore-pgx.yaml
Follow-up to https://github.com/solo-io/gloo/pull/10087, there was another pgx CVE that falls into the same category and we will ignore it in 1.14 (fixed in 1.15+)
=> trivy ignore pgx cve

changelog/v1.17.12/production-helm-profiles-in-tests-part2.yaml, changelog/v1.17.13/production-helm-profiles-in-tests-part2.yaml, pkg/utils/helmutils/unmarshal.go, test/kubernetes/e2e/test.go, test/kubernetes/testutils/gloogateway/context.go, test/testutils/helm_values.go
Backport #10132
It is not possible to use OSS validation code from EE, and therefore we are backporting the PR that removed the validation requirement in main
See #10132 for additional context
=> 1.17 - Relax gloogateway.Context validation 

Makefile, changelog/v1.17.15/fix-watch-ns.yaml, test/kube2e/gloo/bootstrap_clients_test.go, test/kubernetes/e2e/features/watch_namespace_selector/suite.go, test/kubernetes/e2e/features/watch_namespace_selector/types.go
Backport of https://github.com/solo-io/gloo/pull/10160
Fixes the flaky TestMatchLabels that could be caused by not removing the label on a namespace after the test.
The presence of the label on the namespace (from the prior test even though the namespace was deleted???) could be present which causes the test to flake - maybe translation takes a bit of time to process the deleted namespace and its resources which is longer than it takes for the next test to begin ??
I've run this test ~20 times without flakes so it appears to be stable now
Fixes https://github.com/solo-io/gloo/pull/10160 once backported
=> [1.17] tests: Fix flaky TestWatchNamespaceSelector

.github/workflows/nightly-tests.yaml, changelog/v1.18.0-beta25/remove-helm-nightly.yaml
Followup to https://github.com/solo-io/gloo/pull/10165
Removes the helm tests from the nightly run
=> tests: Remove helm from nightly suite

.github/workflows/pr-kubernetes-tests.yaml, changelog/v1.18.0-beta25/fix-helm-test-path.yaml, test/kubernetes/e2e/features/helm_settings/suite.go
Fix wrong path in TestHelmSettings
```
--- PASS: TestHelmSettings (101.34s)
--- PASS: TestHelmSettings/HelmSettings (2.66s)
--- PASS: TestHelmSettings/HelmSettings/TestApplySettingsManifestsFromUnitTests (2.66s)
PASS
```
=> tests: Fix wrong path in TestHelmSettings

changelog/v1.18.0-beta26/issue_10099.yaml, projects/gateway2/controller/controller.go, test/kubernetes/e2e/features/deployer/istio_integration_suite.go, test/kubernetes/e2e/features/deployer/minimal_default_gatewayparameters_suite.go, test/kubernetes/e2e/features/deployer/suite.go, test/kubernetes/e2e/features/deployer/testdata/gateway-with-parameters.yaml, test/kubernetes/e2e/features/deployer/testdata/gatewayparameters-custom.yaml, test/kubernetes/e2e/features/deployer/types.go
Previously, the controller would only watch Gateway objects for `generation` field changes which is not updated when annotations change. Since Gateway reconciliation should be triggered when the `gateway.gloo.solo.io/gateway-parameters-name` annotation is added, removed, or modified, the predicate was updated to check for changes in either the generation field or the annotations.
Fixes #10099
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/10099
=> [gateway2] Updates Gateway Controller Watch Predicate

.github/workflows/pr-kubernetes-tests.yaml, changelog/v1.18.0-beta26/run-missing-tests.yaml, test/kubernetes/e2e/README.md
Add missing Kubernetes tests to PR runs. This brings parity between the PR runs and nightly runs except for upgrade tests since main is not an LTS branch
=> tests: Add missing Kubernetes tests to PR runs

changelog/v1.17.15/change-echo-server-image.yaml, test/kubernetes/e2e/defaults/testdata/http_echo.yaml
This is just a test to see if we can change the image used for our tests from kennship/http-echo to jmalloc/echo-server. See changelog for details.
CI passes successfully, so it doesn't seem like this change causes any harm. I was hoping that CI runs would be faster since this image is smaller than the previous one, but it does not appear to make any difference - compare to the times for CI to run on [this pull request](https://github.com/solo-io/gloo/actions/runs/11165938304/job/31041201811) as an example and you can see that the times to run do not change much at all.
However, this change does still provide an improvement in that the new image supports HTTP/2 while the other previous image does not:
```
ashish@laptop5 ~/go/src/github.com/solo-io/gloo/test/kubernetes/e2e/features/tracing/ …
```
=> Attempt to change http-echo image

Tiltfile, changelog/v1.18.0-beta29/tilt-fix.yaml, tilt-settings.yaml
`tilt up` is failing with `Error: open ./test/kube2e/helm/artifacts/helm.yaml: no such file or directory`. 
This PR updates the path to new location of the file.
=> Fixing issue with Tilt setup and a 'missing' file

changelog/v1.18.0-beta29/install-script-arm64.yaml, projects/gloo/cli/install.sh
On linux-aarch64 (or darwin), pull the correct published binary instead of the hardcoded one in the install script.
=> Install script - don't pull amd64 bin on arm64

changelog/v1.17.15/fix-unwatched-resource-npe.yaml, projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go, projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go, projects/gateway2/translator/plugins/virtualhostoptions/virtualhost_options_plugin.go, projects/gateway2/translator/plugins/virtualhostoptions/virtualhost_options_plugin_test.go
Backport of https://github.com/solo-io/gloo/pull/10230
This fixes a bug where the gloo pod segfaults when a Route / VirtualHost refers to a RouteOption / VirtualHostOption that is not in a watched namespace
https://github.com/solo-io/solo-projects/issues/7082#issuecomment-2427224411
The original investigation and fix by @jmhbh : https://github.com/solo-io/gloo/pull/10218
Added unit tests to catch this
=> [1.17] fix: Handle errors in ggv2 plugins when resource is not in a watched namespace

.github/workflows/pr-kubernetes-tests.yaml, changelog/v1.18.0-beta31/aws-sts-cluster-config.yaml, install/test/k8sgateway_test.go, projects/gateway2/controller/controller.go, projects/gateway2/controller/start.go, projects/gateway2/deployer/deployer.go, projects/gateway2/deployer/deployer_test.go, projects/gateway2/deployer/values.go, projects/gateway2/deployer/values_helpers.go, projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml, test/kubernetes/e2e/features/deployer/suite.go, test/kubernetes/e2e/tests/k8s_gw_aws_test.go, test/kubernetes/e2e/tests/k8s_gw_aws_tests.go, test/kubernetes/e2e/tests/manifests/aws-lambda-helm.yaml, test/kubernetes/testutils/gloogateway/context.go
As part of supporting [AWS Lambda with EKS ServiceAccounts](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/aws_lambda/eks-service-accounts/) with the Kubernetes Gateway API, the existing Helm values `settings.aws.enableServiceAccountCredentials` and `settings.aws.stsCredentialsRegion` are now respected when using Kubernetes Gateway API. 
The AWS options from Settings CR (which are configured at install time) are passed through to the kubernetes gateway controller. When `enableServiceAccountCredentials` is true, a `aws_sts_cluster` cluster, configured with the STS endpoint specified by `stsCredentialsRegion`, will automatically be added to dynamically provisioned proxies, so that Envoy can reach AWS to assume the role needed to access Lambdas.
The …
=> aws_sts_cluster static cluster config for kubernetes gateway api

changelog/v1.18.0-beta31/k8s-gw-svc-extra-anno.yaml, docs/content/reference/values.txt, install/helm/gloo/generate/values.go, install/helm/gloo/templates/43-gatewayparameters.yaml, install/test/k8sgateway_test.go, projects/gateway2/deployer/deployer_test.go, test/kubernetes/e2e/features/deployer/suite.go, test/kubernetes/e2e/features/deployer/testdata/gateway-with-parameters.yaml
For kubernetes gateway api: Add new helm values `kubeGateway.gatewayParameters.glooGateway.service.extraLabels` and `kubeGateway.gatewayParameters.glooGateway.service.extraAnnotations` to configure the proxy service's default labels/annotations. (Note that these values already existed on GatewayParameters via `spec.kube.service.extraLabels` and `spec.kube.service.extraAnnotations`; this PR just allows them to be set via helm values at install time)
=> Make k8s gateway Service labels/annotations configurable via helm

changelog/v1.18.0-beta34/oss-test.com-flake-fix.yaml, test/e2e/buffer_test.go, test/e2e/csrf_test.go, test/e2e/test_context.go, test/e2e/zipkin_test.go
"side port" of https://github.com/solo-io/solo-projects/pull/7163
Update the DefaultHost for the e2e testcontext to use jsonplaceholder.typicode.com with the HttpRequestBuilder instead of the inconsistent/not meant for testing test.com
A few tests required updating hardcoded references to "test.com"
=> Update test HttpRequestBuilder DefaultHost from test.com to jsonplaceholder.typicode.com/

changelog/v1.18.0-beta34/bump-go-1-23-3.yaml, ci/cloudbuild/publish-artifacts.yaml, ci/cloudbuild/run-tests.yaml, cloudbuild-cache.yaml, go.mod
Bump Go version to 1.23.3
The Go version in solo-projects is being bumped in https://github.com/solo-io/solo-projects/pull/7152 due to the same bump in ext-auth-service, and we'd like to keep solo-projects and gloo Go versions in sync.
Bump in cloudbuild as well
=> Bump Go version to 1.23.3

changelog/v1.18.0-beta34/issue_10323.yaml, install/helm/gloo/templates/44-rbac.yaml
Removes endpoints from the `44-rbac.yaml` Helm template since the gw API controller uses EndpointSlices instead of Endpoints due to https://github.com/solo-io/gloo/pull/10265.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/10323
=> Removes endpoints from the 44-rbac.yaml Helm template

changelog/v1.18.0-beta35/helm-doc-gen.yaml, docs/cmd/generate_docs.go, pkg/github-action-utils/version.go
When pulling in EE Helm docs, there are 2 steps:
1) Find the appropriate EE version
2) Use that version to pull in the Helm docs
Currently the first step is only looking at stable versions 
Update how docs generation pulls in Helm values from solo-projects:
* When pulling the latest Helm chart version, allow non-stable releases to be pulled
* In main branch, this allows the beta/rc versions to be used
* In LTS branches, the version constrains will prevent the main/unstable releases from being used
* When generating the docs
* Update from using the LTS branch itself to the latest tag identified when the version is pulled
* This will change how LTS docs are generated
* We are currently pulling ref for the LTS branch itself, which results in committed but unreleased changes being included
* …
=> Fix published Helm docs from main branch

.github/workflows/docs-gen.yaml, .github/workflows/nightly-tests.yaml, .github/workflows/push-docs.yaml, .github/workflows/trivy-analysis-scheduled.yaml, changelog/v1.18.0-beta35/fix-notification-urls.yaml
Fix slack url notification, remove old repo path. 
NONE
NONE
- Fixes slack notification URL 
NONE
=> Fix slack notification url

README.md
Adds a readme link to the community repo.
Fixes #10356
=> Adds link to community repo

.github/workflows/pr-kubernetes-tests.yaml, .github/workflows/regression-tests.yaml
Disables several permafailing GHA jobs. Re-enabling them is being tracked in https://github.com/k8sgateway/k8sgateway/issues/10447.
Closes https://github.com/k8sgateway/k8sgateway/issues/10454
=> .github: Disable permafailing jobs

README.md
fixup the README.md post-rename
n/a
n/a
n/a
n/a
We had to rename, this starts the process of fixing things up after the rename
=> fixup the README.md post-rename

install/helm/README.md, install/helm/kgateway/.helmignore, install/helm/kgateway/Chart.yaml, install/helm/kgateway/crds/gateway.gloo.solo.io_directresponses.yaml, install/helm/kgateway/crds/gateway.gloo.solo.io_gatewayparameters.yaml, install/helm/kgateway/crds/gateway.gloo.solo.io_httplistenerpolicies.yaml, install/helm/kgateway/crds/gateway.gloo.solo.io_listenerpolicies.yaml, install/helm/kgateway/crds/gateway.gloo.solo.io_routepolicies.yaml, install/helm/kgateway/crds/gateway.gloo.solo.io_upstreams.yaml, install/helm/kgateway/templates/NOTES.txt, install/helm/kgateway/templates/_helpers.tpl, install/helm/kgateway/templates/deployment.yaml, install/helm/kgateway/templates/hpa.yaml, install/helm/kgateway/templates/ingress.yaml, install/helm/kgateway/templates/rbac.yaml/role.yaml, install/helm/kgateway/templates/service.yaml, install/helm/kgateway/templates/serviceaccount.yaml, install/helm/kgateway/templates/tests/test-connection.yaml, install/helm/kgateway/values.yaml, projects/gateway2/generate.sh
This commit introduces an initial install/helm/kgateway chart via the `helm create` bootstrap command and updates the gateway2 codegen bash script to generate CRDs and RBAC for this chart along with the legacy chart. Note: this chart is not functional at this point. Future PRs will iterate on this effort, expand this chart values & templates, make sure it can be deployed correctly, passes the conformance suite, etc.
In the short term, the plan is to migrate away from the legacy chart + publish this chart with goreleaser to GHCR.io before we cut our first release in this new project. 
Related to https://github.com/kgateway-dev/kgateway/issues/10443. 
Initial task for the https://github.com/kgateway-dev/kgateway/issues/10423 tracker.
=> Bootstrap initial kgateway helm chart

.github/workflows/conformance-tests.yaml, .github/workflows/nightly-tests.yaml
Disables permafailing jobs in the nightly GHA workflow. See https://github.com/kgateway-dev/kgateway/issues/10472 for some context on the state of this workflow. This is a follow-up to https://github.com/kgateway-dev/kgateway/pull/10455 which disabled several jobs on main that haven't been migrated over yet. See https://github.com/k8sgateway/k8sgateway/issues/10447 for the tracker for that effort.
Closes #10472.
=> .github/workflows: Disable permafailing jobs on nightly workflow

.github/workflows/release.yaml, Makefile, install/helm/gloo/values-template.yaml, test/makefile/make_test.go
This commit is a follow-up to #10443 and #10470 and migrates away from the quay.io/solo-io container image registry in favor of the ghcr.io repository in the project.
Additional work around renaming the gloo component, binaries, etc. will be handled once we're closing the finish line with the https://github.com/kgateway-dev/kgateway/issues/10444 cleanup work.
Introducing automation to replace the quay container image expiration label is being tracked in the https://github.com/kgateway-dev/kgateway/issues/10441 epic.
=> *: Migrate container registry from quay.io to ghcr.io

projects/gateway2/admin/server.go, test/ginkgo/parallel/ports.go
Change to 9097 for now, so it won't conflict with existing ports used by the legacy admin server, until https://github.com/kgateway-dev/kgateway/issues/10501 is implemented
=> change admin server port to 9097

projects/gateway2/generate.sh
Quick PR for removing CRD and RBAC generation for the legacy chart. This is a quick follow-up to #10485.
=> Remove controller-gen generation for legacy chart

.github/workflows/release.yaml, .goreleaser.yaml, Makefile, projects/envoyinit/cmd/Dockerfile.envoyinit
Update the .goreleaser.yaml configuration and add the sds and envoy init containers to the release pipeline. See https://github.com/kgateway-dev/kgateway/issues/10441 for the high-level tracker for this stream of work.
Related to https://github.com/kgateway-dev/kgateway/issues/10423.
=> *: Add sds and envoyinit to the release pipeline

.goreleaser.yaml, Makefile, install/helm/kgateway/templates/deployment.yaml, install/helm/kgateway/templates/gatewayparameters.yaml, install/helm/kgateway/values.yaml, projects/gateway2/cmd/Dockerfile, projects/gateway2/cmd/Dockerfile.distroless
Rename the gloo -> kgateway container.
Rename gloo-envoy-init -> envoy-init container.
This commit renames the gloo container to kgateway now that #10514 and #10485 have merged.
Related to #10496 and #10510.
=> *: Rename gloo container to kgateway

.github/ISSUE_TEMPLATE/BUG-ISSUE.yml, .github/ISSUE_TEMPLATE/FEATURE-ISSUE.yml, .github/ISSUE_TEMPLATE/config.yml
Update the GitHub templates to use the correct project name.
=> fix product name in GitHub issue creation

ci/kind/cluster.yaml, ci/kind/setup-kind.sh
this was used for testing; not needed for now as we don't currently support leader election
=> remove cilium from setup-kind script

.github/workflows/release.yaml, .goreleaser.yaml, Makefile
This modifies the release.yaml workflow and adds the main branch push trigger to publish main branch images and the latest helm chart to ghcr.io.
Related to #10510.
=> release: Publish main branch images and charts

go.mod
These don't do anything, as seen by the go.sum not changing. They are an artifact of some problems that have been fixed from dependency updates
=> go.mod: drop redundant excludes

go.mod
This PR re-organizes the root go.mod. Previously, the first `require` directive had a mix of direct and indirect dependencies, which is a surprising organization for Go-based projects. Now, those indirect dependencies have been moved to the same require directive with the rest of the indirect dependencies.
Additionally, there were two `require` directives for the direct dependencies. While this isn't a big issue, there didn't seem to be a reason or theme that explains why these dependencies were separated.
Related to #10496.
=> go.mod: Re-organize dependencies

go.mod
Bumps go mod to the latest Go 1.23.x patch release.
=> Bumps gomod to 1.23.6

internal/kgateway/extensions2/common/krt.go, internal/kgateway/krtcollections/policy.go, internal/kgateway/krtcollections/policy_test.go, internal/kgateway/krtcollections/setup.go, internal/kgateway/proxy_syncer/proxy_syncer.go, internal/kgateway/query/query_test.go, internal/kgateway/translator/gateway/translator_case_test.go, internal/kgateway/translator/translator.go
Allow policies to get upstreams by placing the upstream index in the common collections.
these changes:
- Add the UpstreamIndex to the CommonCollections in proxy_syncer Init (before k8s client is started)
- Expose the `GetUpstreamFromRef` that return an upstream while doing reference grant checks.
=> internal change: policies can reference upstreams

internal/kgateway/setup/ggv2setup_test.go
add ability to alway dump krt debug, even on successful tests by setting KGW_DUMP_KRT_ON_SUCCESS=true
we can bike shed the var name, just wanted to get something out quick
add a helper for printing krt dbg stuff, add reading an env var during testing to dump
krt dbg is handy do make [these](https://mermaid.live/edit#pako:eNqNlVtr2zAUx79K8eNISiQ7jZOHwUi7bvRCSVo2lpSh2WosKkueJKeE0u8-ybMutlO2N-l3js75n0uc1yjjOY4W0RPlL1mBhDq5Xm3ZyQnTGKbj8UdzAHOLwMQi4LzOWgRnziuxXlOL4rhFceLQtEWOABvJAWgDTSyymrykuX3lfKAL5CIl_VxWtRMNrQv0om21sasW2HdgNkRegK0WgiDWaRsMDlkS9Ol9FIeNaRk4guJAmmVp0K8B0w2z7OwIS4ONaBmcB2O0LB2yOD7CJn7gFvk5tcQNAc422-gWlVhWKMNyGz26iIm2fCYM0YdKKoFRGVrBVFvzA_u5B4hWBQKn10QqzLC445Rkh9A11a6VoaSTAE40v6p_4Uuk8As6dGzxRhsFrxWW40KpatyeX4gqxpVN4cVC7b7klOJMEc42H_bg9BxLpeWb-6qmeJTru9CHvuGbQFWFxWOQPjHZHxj5XeMlZ …
=> always dump option for krt dbg info

test/kubernetes/e2e/features/client_tls/types.go, test/kubernetes/e2e/features/deployer/istio_integration_suite.go, test/kubernetes/e2e/features/deployer/testdata/self-managed-gateway.yaml, test/kubernetes/e2e/features/deployer/types.go, test/kubernetes/e2e/features/directresponse/suite.go, test/kubernetes/e2e/features/directresponse/types.go, test/kubernetes/e2e/features/headless_svc/types.go, test/kubernetes/e2e/features/http_listener_options/http_lis_opt_suite.go, test/kubernetes/e2e/features/http_listener_options/lis_opt_types.go, test/kubernetes/e2e/features/istio/k8s_gateway_auto_mtls_suite.go, test/kubernetes/e2e/features/istio/k8s_gateway_no_auto_mtls_suite.go, test/kubernetes/e2e/features/istio/types.go, test/kubernetes/e2e/features/listener_options/lis_opt_suite.go, test/kubernetes/e2e/features/listener_options/lis_opt_types.go, test/kubernetes/e2e/features/metrics/types.go, test/kubernetes/e2e/features/port_routing/k8s_gateway_suite.go, test/kubernetes/e2e/features/port_routing/types.go, test/kubernetes/e2e/features/route_delegation/types.go, test/kubernetes/e2e/features/route_options/suite.go, test/kubernetes/e2e/features/route_options/types.go, test/kubernetes/e2e/features/server_tls/types.go, test/kubernetes/e2e/features/services/httproute/types.go, test/kubernetes/e2e/features/services/tcproute/types.go, test/kubernetes/e2e/features/upstreams/types.go, test/kubernetes/e2e/features/virtualhost_options/types.go, test/kubernetes/e2e/features/virtualhost_options/vhost_opt_suite.go, test/kubernetes/e2e/features/zero_downtime_rollout/suite.go, test/kubernetes/e2e/features/zero_downtime_rollout/types.go
blanket removal of all gloo-proxy references in the e2e tests
=> remove gloo-proxy prefix from e2e tests

.github/workflows/pr-kubernetes-tests.yaml, test/kubernetes/e2e/debugging.md, test/kubernetes/e2e/tests/automtls_istio_test.go, test/kubernetes/e2e/tests/k8s_gw_aws_test.go, test/kubernetes/e2e/tests/k8s_gw_istio_test.go, test/kubernetes/e2e/tests/k8s_gw_minimal_default_gatewayparameters_test.go, test/kubernetes/e2e/tests/k8s_gw_no_validation_test.go, test/kubernetes/e2e/tests/k8s_gw_test.go, test/kubernetes/e2e/tests/revision_istio_k8s_gw_test.go
Addresses a [review comment](https://github.com/kgateway-dev/kgateway/pull/10519#discussion_r1960661809) from last PR
Also remove references to the already-deleted edge tests in the GH workflow file
=> e2e tests: rename TestK8sGateway to TestKgateway

test/kubernetes/e2e/features/basicrouting/suite.go, test/kubernetes/e2e/features/deployer/suite.go, test/kubernetes/e2e/features/metrics/suite.go, test/kubernetes/e2e/features/zero_downtime_rollout/suite.go, test/kubernetes/testutils/assertions/deployments.go, test/kubernetes/testutils/assertions/envoy.go, test/kubernetes/testutils/assertions/gloo.go, test/kubernetes/testutils/assertions/kgateway.go, test/kubernetes/testutils/assertions/pods.go
Fix basic routing test flake: wait for nginx, curl, proxy pods to be running before trying to curl
Also renamed `EventuallyRunningReplicas` to `EventuallyReadyReplicas` to accurately reflect that it waits for pods to have the `PodReady` condition
Fixes https://github.com/kgateway-dev/kgateway/issues/10661
=> Fix basicrouting flake

api/v1alpha1/direct_response_types.go, api/v1alpha1/gateway_parameters_types.go, api/v1alpha1/http_listener_policy_types.go, api/v1alpha1/listener_policy_types.go, api/v1alpha1/route_policy_types.go, api/v1alpha1/upstream_policy_types.go, install/helm/kgateway/crds/gateway.kgateway.dev_directresponses.yaml, install/helm/kgateway/crds/gateway.kgateway.dev_gatewayparameters.yaml, install/helm/kgateway/crds/gateway.kgateway.dev_httplistenerpolicies.yaml, install/helm/kgateway/crds/gateway.kgateway.dev_listenerpolicies.yaml, install/helm/kgateway/crds/gateway.kgateway.dev_routepolicies.yaml, install/helm/kgateway/crds/gateway.kgateway.dev_upstreams.yaml, pkg/generated/openapi/zz_generated.openapi.go
This commit updates the DRR and GWParams CRDs labels to be consistent with the rest of the project's CRDs.
A quick follow-up to #10597 and replaces the gloo-gateway labels being referenced in several CRDs.
Closes #10663.
=> *: Fix CRD metadata labels

.goreleaser.yaml
Avoid maintaining two sets of quickstart instructions and link out to the doc site instead.
Closes https://github.com/kgateway-dev/kgateway/issues/10695
=> Replace quickstart instructions in release template with doc site

.github/workflows/release.yaml
Ensures the v2.0.0-main release always points to the latest main branch commit by deleting the existing release and tag before goreleaser creates a new one. This prevents stale releases from persisting in the repository.
Closes https://github.com/kgateway-dev/kgateway/issues/10641
=> .github: Re-create the rolling main release

internal/kgateway/reports/reporter_test.go, internal/kgateway/reports/status.go
Crossport of https://github.com/solo-io/gloo/pull/10663
---
There is a requirement to allow external controllers to update the statuses on Gateway objects by writing Conditions that do not conflict with the Types owned by the Gateway. Currently, only condition.Types that are a part of the status reporter are set as the final list of conditions. This change allows external controllers to write Condition.Types that do not conflict.
=> gateway/status: preserve external conditions

.github/workflows/pr-kubernetes-tests.yaml, test/gomega/matchers/contain_substrings.go, test/kubernetes/e2e/features/services/httproute/suite.go, test/kubernetes/e2e/features/services/httproute/types.go, test/kubernetes/e2e/features/services/tcproute/suite.go, test/kubernetes/e2e/features/services/tcproute/types.go, test/kubernetes/e2e/tests/kgateway_tests.go, test/kubernetes/testutils/assertions/status.go
reenable TCPRoute and HTTPRoute e2e suite.
=> reenable TCPRoute e2e test

internal/kgateway/controller/start.go, internal/kgateway/ir/iface.go, internal/kgateway/krtcollections/uniqueclients_test.go, internal/kgateway/setup/controlplane.go, internal/kgateway/setup/ggv2setup.go, internal/kgateway/setup/ggv2setup_test.go, internal/kgateway/setup/testdata/setupyaml/setup.yaml
- add a test to cover 2 UCCs
- fix a rare flake in env test, where grpc server logs after test env is shutdown
- don't bind controll runtime ports in envtest - so they can be run in parallel
- fill in GW Params in envtest so that deployer doesnt log errors
- check policy ir in equals
=> minor test fixes + equals on policy ir

internal/kgateway/extensions2/plugins/directresponse/direct_response_plugin.go, internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go, internal/kgateway/extensions2/plugins/listenerpolicy/listener_policy_plugin.go, internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go, internal/kgateway/ir/iface.go, internal/kgateway/krtcollections/builtin.go, internal/kgateway/translator/irtranslator/fc.go
Remove the ability to set upstream filters on the router filter. upstream filters should go on clusters instead.
If filters are present on the cluster, envoy will use them instead of the router. so by exposing the ability to set them on the router filter, may lead to inconsistent behaviour with plugins that set them on the cluster (like aws for example). As we have no use case for setting them on the router, lets remove them.
=> remove upstream  filters on the router filter

test/kubernetes/e2e/defaults/testdata/curl_pod.yaml, test/kubernetes/e2e/defaults/testdata/http_echo.yaml, test/kubernetes/e2e/defaults/testdata/nginx_pod.yaml, test/kubernetes/e2e/defaults/testdata/tcp_echo.yaml
Add the `spec.terminationGracePeriodSeconds: 0` field to the test helper Pods that are used by various e2e suites. This helps reduce the time waiting for Pods to be deleted in CI.
Pulled out from #10720
=> test: Force delete helper Pods

Makefile
Add the GOLANGCI_LINT Makefile variable to allow the golangci-lint binary to be
overriden locally. Ex: `make analyze GOLANGCI_LINT="go tool github.com/golangci/golangci-lint/cmd/golangci-lint"`.
=> Makefile: Override the golangci-lint binary

Makefile, internal/kgateway/extensions2/plugins/kubernetes/k8s.go, internal/kgateway/ir/backend.go, internal/kgateway/setup/testdata/accesslog-filterhttp-httplisteneropt-out.yaml, internal/kgateway/setup/testdata/accesslog-filterhttp-httplisteneropt.yaml, internal/kgateway/translator/irtranslator/backend.go, internal/kgateway/translator/irtranslator/backend_test.go
i noticed we didn't have http2 set for grpc access log. so added support for app protocol for k8s service.
=> feat: support h2c app protocol

Makefile
Make target for golangci-lint was painful locally.
Since we didnt set a toolchain it would negotiate to the highest 1.23 setup
Therefore lets try to pass default GOTOOLCHAIN.
This ist the error you would see:
`go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5 run --fast --verbose ./...
go: github.com/golangci/golangci-lint@v1.64.5 requires go >= 1.23.0; switching to go1.23.7
INFO golangci-lint has version v1.64.5 built with go1.23.7 from (unknown, modified: ?, mod sum: "h1:5omC86XFBKXZgCrVdUWU+WNHKd+CWCxNx717KXnzKZY=") on (unknown)
INFO [config_reader] Config search paths: [./ /Users/nfudenberg/go/src/github.com/nfuden/k8sgateway /Users/nfudenberg/go/src/github.com/nfuden /Users/nfudenberg/go/src/github.com /Users/nfudenberg/go/src /Users/nfudenberg/go /Users/nfudenberg …
=> make: golangci-lint should use the current go mod version rather than negotiating down

.golangci.yaml, internal/sds/pkg/server/server_test.go
Add the https://golangci-lint.run/usage/linters/#ineffassign linter which is enabled by default
in golangci-lint.
=> Add the ineffassign linter

api/v1alpha1/backend_types.go, install/helm/kgateway/crds/gateway.kgateway.dev_backends.yaml
Add basic printer columns to the Backend CRD:
```bash
$ k get backend -A       
NAMESPACE     NAME             BACKEND TYPE   AGE
lambda-test   lambda-backend   aws            4m25s
```
Once #10555 is resolved and the Backend plugin is reporting status,
we can add another printer column that emits whether the CR is
in a good state or not.
=> api: Add basic Backend printer columns

.github/workflows/pr-kubernetes-tests.yaml
We ran into some issues where PRs failing the e2e suite merged to main, which led
to main branch CI permafailing. This was fixed in the #10759 PR. As a result, we
added the e2e suite as a required GHA check, but the problem is this suite doesn't
have the merge_group event triggered configured for the workflow, which leads to
PRs being stuck indefinitely in the MQ waiting for status to be reported.
=> .github: Add the merge_group trigger for the e2e suite

.github/actions/regression-tests/action.yaml, .github/pull_request_template.md, .gitignore, devel/README.md, devel/architecture/istio-integration.md, test/README.md, test/ginkgo/labels/labels.go, test/gomega/assertions/stats.go, test/helpers/resources.go, test/helpers/snapshot_writer.go, test/kube2e/README.md, test/kube2e/util.go, test/kubernetes/testutils/assertions/status.go, test/services/gloo.go, test/testutils/env.go
Replaced most of the references to Gloo Edge with kgateway across the codebase.
None
no code changes. Mostly text, some of comments and formatting.
None
Updated some text in READMEs
This is part of the ongoing effort to align terminology with kgateway.
none :-)
not required. Just search to return any references:
```
grep -r -i "gloo edge" --exclude-dir=".git" ../kgateway | wc -l
```
No functional changes—this is a purely textual update. Original discussion is [Slack](https://solo-io-corp.slack.com/archives/C085A044BHT/p1741394597734499)
=> Remove Gloo Edge references

internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml, internal/kgateway/setup/ggv2setup_test.go, internal/kgateway/setup/testdata/autodns/backend-out.yaml, internal/kgateway/setup/testdata/setupyaml/setup.yaml
Fix some issues with the setup tests:
- Use selfManaged gatewayparameters so that the deployer doesn't run (it isnt needed for these tests, and sometimes attempts to create extra resources causing tests to fail)
- Don't set env vars to initialize the Settings during the tests; instead, contruct the Settings directly. I found that env vars set in `TestScenarios` seemed to be interfering with tests in `TestWithAutoDns` (maybe they run in parallel?)
- Previous ggv2setup test flakes ran into a nil error in the proxy-deployment template where the sdsContainer was nil. Although this code path shouldn't get called anymore (since we're using selfManaged now), we should add nil checks to the helm template anyway
=> Fix some ggv2setup_test issues

internal/kgateway/ir/routes.go, internal/kgateway/setup/setup_test.go, internal/kgateway/setup/testdata/transformation-out.yaml, internal/kgateway/setup/testdata/transformation.yaml
Rule in an http route in general doesn't need its own equals, as it is covered by versionEquals to its parent. But attached object like policies and backends do need an equals.
=> fix: add equals for policies on rules

.github/workflows/release.yaml
This step should not be needed and increases the release workflow's time. Closes #10815.
=> .github: Remove the go-prep-runner step in the helm release job

.github/workflows/pr-kubernetes-tests.yaml, test/kubernetes/e2e/defaults/defaults.go, test/kubernetes/e2e/features/basicrouting/suite.go, test/kubernetes/e2e/features/route_delegation/suite.go, test/kubernetes/e2e/features/route_delegation/testdata/common.yaml, test/kubernetes/e2e/features/route_delegation/types.go
- Fix flakes in the route delegation e2e suite by setting up / tearing down the common stuff (curl, httpbin, proxy) just once for the suite
- Rebalance tests
Fixes https://github.com/kgateway-dev/kgateway/issues/10799
Fixes https://github.com/kgateway-dev/kgateway/issues/10814
Fixes https://github.com/kgateway-dev/kgateway/issues/10813
=> route delegation flakes

examples/plugin/main.go, internal/kgateway/controller/controller.go, internal/kgateway/controller/controller_suite_test.go, internal/kgateway/controller/gw_controller.go, internal/kgateway/controller/start.go, internal/kgateway/krtcollections/policy.go, internal/kgateway/krtcollections/setup.go, internal/kgateway/proxy_syncer/proxy_syncer.go, internal/kgateway/setup/setup.go, internal/kgateway/setup/setup_test.go, internal/kgateway/translator/gateway/gateway_translator_test.go, internal/kgateway/translator/gateway/testutils/inputs/custom-gateway-class/gateway.yaml, internal/kgateway/translator/gateway/testutils/outputs/custom-gateway-class.yaml, internal/kgateway/translator/gateway/testutils/test_file_loader.go, internal/kgateway/translator/gateway/translator_case_test.go, internal/kgateway/translator/translator.go
Split out from #10783
This PR addresses TODOs that were already expressed in the code, and is relevant for Waypoints which add a new GatewayClass. We will not need to maintain an internal list of relevant classes. 
The controllerName field on GatewayClass could theoretically trigger deployment and config gen for arbitrary GatewayClasses other than `kgateway`. 
* Remove `ExtraGatewayClasses`
* Remove `isOurGw` closure
* Add Watches(GatewayClass) to controller, add a filter on the GatewayClass.Spec.Controller name ot controller predicates
* Add a GatewayClasses collection used for filtering in Translator
Some form of multi-gatewayclass management is needed for waypoint
We had TODOs in the code; this is far simpler to maintain long term than having a list of static gatewayclasses. 
Updating …
=> use controller name to find relevant Gateways

api/v1alpha1/backend_types.go, install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml
We removed the implementation for the IRSA auth type in the initial lambda PR and forgot to remove some of the API fields. IRSA-based auth is still supported, but currently requires users to configure their GWP resource with the role arn service account annotation.
See https://cloud-native.slack.com/archives/C080D3PJMS4/p1741897619750649.
=> api,install: Remove the unused IRSA auth type

.github/actions/prep-go-runner/action.yaml, .github/workflows/release.yaml
The release workflow is the only workflow with write access to published artifacts, so make sure that all the actions in it and in actions it uses are pinned to a specific version. This helps with both build reproducibility and security.
=> workflow: pin actions on release

internal/kgateway/extensions2/plugins/waypoint/waypoint_translator.go
misc cleanups from https://github.com/kgateway-dev/kgateway/pull/10783 - mostly removing references to `gloo` and deleting unused constants.
=> misc cleanups in waypoint_translator

.github/workflows/pr-kubernetes-tests.yaml, test/kubernetes/e2e/features/transformation/suite.go, test/kubernetes/e2e/features/transformation/types.go, test/kubernetes/testutils/assertions/pods.go
Attempt to fix transformation e2e test flakes
- set up and tear down common resources once per suite
- wait for pods to be ready
- after patching kgateway deployment, wait for pods to reflect the env var
Fixes https://github.com/kgateway-dev/kgateway/issues/10826
=> transformation e2e flakes

hack/kind/setup-kind.sh
Align the GW API CRD version being installed in hack/kind/setup-kind.sh with the client version present in the root go.mod file. This matches the approach taken in the conformance composite action.
=> hack/kind: Bump CONFORMANCE_VERSION to v1.2.1

.github/workflows/release.yaml
The release workflow was incorrectly deleting the v2.0.0-main release during workflow_dispatch events. Add event type check to ensure deletion only occurs during push events to main branch.
=> .github: Restrict v2.0.0-main deletion to push events

install/helm/kgateway/values.yaml, internal/kgateway/controller/controller.go, internal/kgateway/deployer/deployer.go, internal/kgateway/deployer/deployer_test.go, internal/kgateway/wellknown/controller.go, test/kubernetes/e2e/features/aiextension/testdata/common.yaml, test/kubernetes/e2e/features/deployer/istio_integration_suite.go, test/kubernetes/e2e/features/deployer/minimal_default_gatewayparameters_suite.go, test/kubernetes/e2e/features/deployer/suite.go, test/kubernetes/e2e/features/deployer/testdata/gateway-with-parameters.yaml, test/kubernetes/e2e/features/deployer/testdata/istio-gateway-parameters.yaml, test/kubernetes/e2e/features/deployer/testdata/self-managed-gateway.yaml, test/kubernetes/e2e/features/lambda/testdata/setup.yaml
Add initial support for the spec.infrastructure field and handle GWP attachment from the parametersRef field. The current annotations-based attachment UX predates this field being introduced into the core GW API spec. Now, we check whether a GW has this configured, and fallback to the annotations-based approach if it's present. In the case that both are present, the spec field wins.
Support for the spec.infrastructure.[labels, annotations] fields is being tracked in #10821.
Closes https://github.com/kgateway-dev/kgateway/issues/10820.
=> internal/kgateway: Add initial support for the Gateway spec.infrastructure field

.goreleaser.yaml
Several users have been having issues pulling the kgateway-ai-extension manifest image for both beta2 and the main branch release. When inspecting the manifest image locally, we can see the following output:
```bash
$ docker manifest inspect cr.kgateway.dev/kgateway-dev/kgateway-ai-extension:v2.0.0-main
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 3875,
"digest": "sha256:ff48463a1511adf41158f5c5473e6231136edc07cea8685f7fc19ac1203d33ce",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 3875,
"digest": "sha256:ff48463a1511adf41158f5c5473e6231136edc07cea8685f7fc19 …
```
=> Add platform docker build parameter for AI images

api/v1alpha1/shared_types.go, pkg/generated/openapi/zz_generated.openapi.go
Now that the docs are automatically generated from the comments, replace TODO comment with descriptions.
Right now, it looks like [this](https://kgateway.dev/docs/reference/api/#localpolicytargetreference:~:text=perConnectionBufferLimitBytes%20integer-,LocalPolicyTargetReference,why%20i%20need%20to%20copy%20this%3B%20codegen%20fails%20if%20i%20dont,-Appears%20in%3A).
Just comments
Reported in Slack by an internal user
=> API docs for LocalPolicyTargetRef

Makefile
We've seen recent release workflows fail due to goreleaser timing out after 30m. This increase in runtime is largely due to #10883 in addition to the other images that have been onboarded to goreleaser the past month or so. In order to unblock v2.0.0-main releases we can bump this timeout to 60m and re-evaluate the current strategy to help decrease runtime in the short term.
=> Makefile: Bump goreleaser timeout to 60m

internal/kgateway/extensions2/plugin/plugin.go, internal/kgateway/extensions2/plugins/backendtlspolicy/plugin.go, internal/kgateway/proxy_syncer/proxy_syncer.go, internal/kgateway/proxy_syncer/status.go, internal/kgateway/proxy_syncer/status_test.go
The report used to generate backend policy status (introduced in https://github.com/kgateway-dev/kgateway/pull/10849) is a map keyed by `schema.GroupKind` which does not have a standard text marshaller.
This causes the krt DebugHandler to break as it cannot encode the collection as JSON.
This commit changes to report to be keyed by the GroupKind string to restore krt debug functionality.
=> use string key for policy report

.github/workflows/pr-unit-tests.yaml, api/applyconfiguration/api/v1alpha1/httplistenerpolicyspec.go, api/applyconfiguration/internal/internal.go, api/v1alpha1/http_listener_policy_types.go, install/helm/kgateway-crds/templates/gateway.kgateway.dev_httplistenerpolicies.yaml, internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go, pkg/generated/openapi/zz_generated.openapi.go
The compress field exposed on `HTTPListenerPolicy` was not functional and the API itself warranted further design.
This commit removes the field entirely.
=> remove compress field

internal/kgateway/extensions2/plugins/backend/ai/ai_backend.go
We were adding IR without cloning in the backend plugin to the typedfilterconfig map and then changing it later in the route policy plugin.
NONE
- Clone backend extproc IR before adding it to the map
NONE
NONE
=> Clone ir before adding it to typedfilterconfig map

install/helm/kgateway/templates/deployment.yaml, install/helm/kgateway/templates/hpa.yaml, install/helm/kgateway/templates/service.yaml
The Helm templates do not consistently set
`namespace: {{ .Release.Namespace }}` for namespaced resource templates.
If not set, helm template fails to render the Namespace set using --namespace, which would break tools like Argo and Operators that use Helm template to manage installations.
Resolves #10909
=> install/helm: use Release.Namespace for namespaced templates

internal/kgateway/extensions2/common/collections.go, internal/kgateway/extensions2/plugins/routepolicy/extauth_policy.go, internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go, internal/kgateway/extensions2/pluginutils/gatewayextensions.go, internal/kgateway/ir/gatewayextension.go, internal/kgateway/krtcollections/gateway_extensions.go, internal/kgateway/krtcollections/policy.go, internal/kgateway/krtcollections/setup.go
* move GwExt col outside of `policy.go` as it's not augmented with policies
* move GwExt to "standard" collection (as it doesn't need to be initialized after plugins are created)
* fix GetGatewayExtension helper to use correct ObjectSource key
* change GwExt col standard methods (ResourceName & Equals) to not be pointer receivers and thus satisfy the interface
* fully fill in GwExt IR on transformation
=> fix GwExt krt collection

internal/kgateway/helm/inference-extension/templates/endpoint-picker/resources.yaml
fixed kgateway epp integration
none
see diff
none
none
llm inference extension stopped working recently after the mode of communication with the extension changed to streaming.  the env var USE_STREAMING was still set to false.
none
try it out
none
=> fix epp integration

internal/kgateway/extensions2/plugins/routepolicy/extauth_policy.go, internal/kgateway/extensions2/plugins/routepolicy/extauth_policy_test.go, internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go
As we iterate to get e2e tests working for extauth this should fix up the cluster naming piece from backendrefs
=> extensions/routepolicy: extauth cluster naming

internal/kgateway/controller/controller_suite_test.go, internal/kgateway/controller/gatewayclass_provisioner.go, internal/kgateway/controller/gatewayclass_provisioner_test.go, internal/kgateway/controller/gw_controller_test.go, internal/kgateway/controller/inferencepool_controller_test.go
Fix a bug with the GC provisioner logic when existing GCs from other GW implementors are present on the cluster before kgateway has been installed. Previously, we relied on a simplistic check in the provisioner's runnable function to determine whether the initial reconciliation kick channel should be called when no GCs exist in the cluster.
This approach is too simplistic and interferred with aggressive event filters that filtered out non-Delete events. In this scenario, the Start method would see that there's GCs present on the cluster, and avoid kicking the initial reconcile channel, and the controller's event filters would filters out GCs from other projects.
Now, we improved the logic in the Start method to kick the initial reconciliation when no GCs exist in the cluster || when one …
=> controller: Improve GatewayClass provisioner reconciliation filtering

internal/kgateway/krtcollections/policy.go, internal/kgateway/proxy_syncer/proxy_syncer.go
to prevent circular deps, return backend with no policies when GetBackendForRef is called
=> no need to attach policies in most cases that an upstream is fetched

internal/kgateway/proxy_syncer/proxy_syncer.go, internal/kgateway/reports/reporter.go, internal/kgateway/reports/reporter_test.go, internal/kgateway/reports/status.go, internal/kgateway/setup/setup.go, internal/kgateway/translator/gateway/gateway_translator_test.go, internal/kgateway/translator/gateway/testutils/test_translator.go, internal/kgateway/translator/httproute/translate_httproute_test.go
* change Route status reporter to only report parents for parentRefs that were encountered during translation
this relies on a currently satisfied assumption that `RouteReport.ParentRefReport()` will be called for every route seen during translation
* when building the new status for a route, include all non-kgateway existing status from the resource
this prevents us from clobbering non kgateway parents
* sort route status for consistency with Equals() and to hopefully prevent thrashing with other controllers
=> fix route status interaction with other controllers

internal/kgateway/controller/gatewayclass_provisioner_test.go, internal/kgateway/controller/gw_controller_test.go, internal/kgateway/controller/inferencepool_controller_test.go
Wrap update client calls in an eventually block to help mitigate against flakes. Should fix the https://github.com/kgateway-dev/kgateway/issues/10969 test failure.
=> controller: Wrap client Update calls in Eventually block

api/v1alpha1/ai_policy.go, install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
Fix the kubebuilder marker used in the RouteType struct in the TrafficPolicy API.
Closes https://github.com/kgateway-dev/kgateway/issues/10972.
=> api,install: Fix invalid kubebuilder marker

install/helm/kgateway/values.yaml
The top-level image field provides the defaults for the controller and dataplane container images. However, the kgateway Deployment template first checks the controller.image.pullPolicy value and then falls back to the image.pullPolicy default:
https://github.com/kgateway-dev/kgateway/blob/2553feb9cbb08973ba20c39d933022a362d78880/install/helm/kgateway/templates/deployment.yaml#L34
This is problematic due to the way the controller.image.pullPolicy field is set:
https://github.com/kgateway-dev/kgateway/blob/2553feb9cbb08973ba20c39d933022a362d78880/install/helm/kgateway/values.yaml#L49-L53
In this scenario, we need to provide an empty default to get the desired behavior. This approach allows users to override the default value while achieving a consistent UX where the global image values …
=> install/helm: Fix the image.pullPolicy helm value

internal/kgateway/deployer/deployer_test.go, internal/kgateway/deployer/merge.go
The issue was that the merge logic was preventing valid GWP overrides because:
1. The in-memory default GatewayParameters always had these Istio fields set
2. The merge function used the in-memory parameters as the destination
3. The merge logic only copied from source if destination was nil
4. Therefore, valid overrides in user-provided GatewayParameters were being ignored
This effectively made these Istio configuration fields immutable once set in the default parameters, which was not the intended behavior.
Additionally, the GWP configuration outlined in the #11004 issue are configuring fields environment variables on the proxy deployment under-the-hood and the merging-related functions in the deployer suite did not assert on the expected envvars on the istio proxy container.
Closes …
=> deployer: Respect GWP overrides for Istio integration

test/kubernetes/e2e/features/local_rate_limit/suite.go, test/kubernetes/e2e/features/local_rate_limit/testdata/route-local-rate-limit.yaml
Minor update to the local rate limit e2e tests to verify that in case of both Gateway and HTTPRoute RL policies applied, the one of the route takes effect.
Specifically, while the Gateway has 1 req per 5m, the route one has 1 per 10s therefore after 10s a second request should return OK.
=> Update e2e test to verify the expected local rate limit is applied

.github/workflows/README.md, LICENSE, devel/contributing/pull-request-reviews.md, devel/debugging/envoy-segfault.md
Fixes #10954.
A full pass for `s/Gloo Gateway/kgateway/` needs to happen at a later date, by someone who knows things like whether we have an `envoy-wrapper-debug` image in kgateway. (I couldn't find a container of such so I just left that as was.)
=> docs: update some copyright/product names

.github/workflows/release.yaml, .goreleaser.yaml
Update the rolling main release name from v2.0.0-main -> v2.1.0-main now that v2.0.0 has been cut.
Tested this out in my fork: https://github.com/timflannagan/kgateway/actions/runs/14224168866/job/39859461695.
Closes https://github.com/kgateway-dev/kgateway/issues/11027
=> Update the rolling main release name to v2.1.0-main

.github/workflows/release.yaml
Add regex validation for the version workflow_dispatch input parameter in the release workflow. GH doesn't support a first-class approach for input validation right now (e.g. a `pattern` field would be useful here), so in lieu of that, we can implement our own validation logic that prevents the release pipeline from being run when invalid version overrides are provided.  
Tested this in my fork: https://github.com/timflannagan/kgateway/actions/runs/14269943102. Provided the "asdf" variable.
Tested this locally as well:
```bash
dev :: /work/kgateway ‹chore/add-release-override-tag-validation› » echo v2.1.0-rc.1 | grep -E '^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$' …
```
=> .github: Add version input validation in the release workflow

internal/kgateway/extensions2/plugins/waypoint/plugin.go, internal/kgateway/extensions2/plugins/waypoint/waypoint_translator.go, internal/kgateway/extensions2/settings/settings.go, internal/kgateway/extensions2/settings/settings_test.go
This adds an env to make waypoints bind their single inbound
listener to localhost. This is a security measure to prevent
bypassing the zTunnel by sending PROXY over plaintext. The
required changes in zTunnel just merged, so we won't have them in most releases of ztunnel, so this cannot be enabled by default. 
See:
https://github.com/solo-io/solo-projects/pull/8113
https://github.com/istio/ztunnel/pull/1501
=> waypoint: allow bind to localhost

.github/actions/kube-gateway-api-conformance-tests/action.yaml, .github/actions/kubernetes-e2e-tests/action.yaml, .github/actions/performance-tests/action.yaml, .github/actions/regression-tests/action.yaml
Incorrect path pulled in from other projects. 
introduced in https://github.com/kgateway-dev/kgateway/pull/11054
Show that upload on fail works via https://github.com/nfuden/k8sgateway/actions/runs/14334971559/job/40179564865?pr=3 where we specifically exercise it. We do not exercise upload on the happy path today
=> fix artifact upload on failure

api/annotations/delegation.go, internal/kgateway/translator/httproute/delegation_helpers.go, internal/kgateway/translator/httproute/delegation_test.go
- remove unused args in `isDelegatedRouteMatch ` (missed cleanup from https://github.com/kgateway-dev/kgateway/pull/11040)
- move annotation to `api/`
=> Delegation cleanup and move annotation

api/v1alpha1/gateway_parameters_types.go, install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
make the kubebuilder validation message more accurate - exactly one of `kube` or `selfManaged` must be set
=> update gatewayparameters validation message

api/labels/delegation.go, internal/kgateway/krtcollections/policy.go, internal/kgateway/query/httproute.go, internal/kgateway/translator/backendref/types.go, internal/kgateway/translator/backendref/types_test.go, internal/kgateway/translator/gateway/gateway_translator_test.go, internal/kgateway/translator/gateway/testutils/inputs/delegation/label_based.yaml, internal/kgateway/translator/gateway/testutils/outputs/delegation/label_based.yaml
Enables delegating to other HTTPRoutes using the label `delegation.kgateway.dev/label` that can be referenced as a BackendRef:
```
- group: delegation.kgateway.dev
kind: label
name: infra-routes
namespace: <empty>|all|<specific> # optional
```
Part of #10942
=> route-delegation: enable label-based delegation

internal/kgateway/extensions2/plugins/serviceentry/backendref.go, internal/kgateway/extensions2/plugins/serviceentry/collections.go
Signed-off-by: Steven Landow <steven.landow@solo.io>
https://github.com/istio/istio/issues/56036
After investigating this in Istio, I've audited our codebase and the only example we have that could trigger this undesired behavior is the serviceentry Backends collection being indexed by two different indexes. This consolidates to one index to avoid missing events. 
* Single index for hostport and object name when looking up the Backend generated by ServiceEntry
=> serviceentry: use a single index for backends

Makefile
add `HTTPRouteRequestTimeout` and `HTTPRouteBackendTimeout` conformance tests
=> add conformance tests for HTTPRoute timeout

internal/kgateway/proxy_syncer/proxy_syncer.go, internal/kgateway/proxy_syncer/proxy_syncer_test.go
When a route has multiple parentRefs, the exitsing status
merging code does not correctly merge parentRefs belonging
to different proxies. As a result, a route with multiple
parents does not have both parents in their status.
This change fixes it.
**Testing done:**
- Unit test added in commit 1 fails without the fixes in commit 2.
- Reproducible with the following config where a route with multiple parents does not have a status with both ancestors:
```
kubectl  apply -f- <<EOF
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
name: test-1
namespace: test
spec:
gatewayClassName: kgateway
listeners:
- protocol: HTTP
port: 80
name: http
allowedRoutes:
namespaces:
from: All
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
name: test-2
namespace: test
spec: …
```
=> status: correctly merge parentRefs for routes

internal/kgateway/extensions2/plugins/routepolicy/extauth_policy.go, internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go, internal/kgateway/setup/testdata/standard/extauth-gw-and-route-disable-out.yaml, internal/kgateway/setup/testdata/standard/extauth-gw-and-route-out.yaml, internal/kgateway/setup/testdata/standard/extauth-gw-only-out.yaml, internal/kgateway/setup/testdata/standard/extauth-route-only-out.yaml
removes the usage of transformation filter for this case, which will make it easier to maintain as we stop using it.
existing e2e test should validate this
=> use set_metadata for extauth global disable

internal/kgateway/endpoints/prioritize.go, internal/kgateway/extensions2/plugin/plugin.go, internal/kgateway/extensions2/plugins/destrule/destrule_plugin.go, internal/kgateway/proxy_syncer/cla_test.go, internal/kgateway/translator/irtranslator/backend.go, internal/kgateway/translator/translator.go
Signed-off-by: Steven Landow <steven.landow@solo.io>
Currently if multiple `PerClientProcessEndpoints` apply to the same backend, only one will win and we'll use that CLA. 
The only existing endpoint plugin is for DestinationRule. Effectively, it just adds `PriorityInfo` to the `PrioritizeEndpoints` call.
This change passes a mutable `EndpointsInputs` to endpoints plugins that allows mutation of:
* PriorityInfo
* EndpointsForBackend
Theoretically DR could set priority info, and another plugin could rearrange the `EndpointsForBackend` (for example, mapping multi-network endpoints to gateway IPs like Istio does for its sidecar multi-network).
Care should be taken when writing endpoint plugins, as ordering is not guaranteed. For the foreseeable future, we don't need to add a …
=> allow multiple endpoint plugins to apply on a single backend

README.md
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
Duplicate the content in the CONTRIBUTING.md file in README.md, to make it easier to find when browing the code at
https://github.com/kgateway-dev/kgateway/?tab=readme-ov-file#--------------------an-envoy-powered-kubernetes-native-api-gateway
=> docs: add pointer to contributing guide in README

internal/kgateway/ir/backend.go, internal/kgateway/ir/routes.go, internal/kgateway/ir/routes_test.go
Fixes https://github.com/kgateway-dev/kgateway/issues/11138
The issue was the TCP (and TLS) Route IR equals functions were not comparing the backend refs. So we would not update if a Ref Grant was created after route creation.
Apply refgrant after route creation. Before this change, route will have error "missing ref grant" and won't work. Now it will work.
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
name: tcp
namespace: kgateway-system
spec:
gatewayClassName: kgateway
listeners:
- name: httpbin
protocol: TCP
port: 8080
allowedRoutes:
kinds:
- kind: TCPRoute
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
name: tcp-httpbin
namespace: kgateway-system
spec:
parentRefs:
- name: tcp
sectionName: httpbin
rules:
- backendRefs:
- name: httpbin …
```
=> fix: compare backends of route ir

.github/workflows/lint-rust.yaml, internal/envoyinit/rustformations/Makefile
Inspired lint target in https://github.com/agentgateway/agentgateway
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
Add lint Makefile target and GitHub Action for Rust code.
This fixes https://github.com/kgateway-dev/kgateway/issues/10868
* I decided to put the lint target in a separate Makefile closer to the Rust code, for an initial try at this.  The top-level Makefile has quite a lot of stuff in there, so I didn't want to modify any of that.  If we want to move this logic into the top-level Makefile, I can do that.
* I decided to incorporate logic from http://github.com/agentgateway/agentgateway , since that is a new and active project.  Maybe @EItanya , who actively works on that project, can provide feedback here.
Added a new workflow for calling `make lint` for Rust.
* I …
=> Add lint Makefile target and GitHub Action for Rust code

go.mod, hack/utils/oss_compliance/osa_included.md, internal/kgateway/krtcollections/builtin.go, test/testutils/requirements.go
Stdlib supports multi-errors using errors.Join, so go-multierror is not required.
Bumps Go to 1.24.2.
=> Go: bump to 1.24.2 and use use errors.Join instead of go-multierror

.github/actions/prep-go-runner/action.yaml
When inspecting log messages from the prep-go-runner composite action, we see the following:
```
Done removing large packages
Error response from daemon: No such image: node:16
Error response from daemon: No such image: node:16-alpine
Untagged: node:18
Untagged: node@sha256:867be01f97d45cb7d89a8ef0b328d23e8207412ebec4564441ed8cabc8cc4ecd
Deleted: sha256:e56a6e3bc5724c51df0a1ad86c6e38aee233bb343457e98c943c3c7c1c9a2a84
Deleted: sha256:2520a921b445a127737d136c2826fc8c71b6473c22e8c19d16b9029b83afaf57
Deleted: sha256:36d39ffd22dec225fa298487ec57436c241338aa3c00bb542dd074253bda084b
Deleted: sha256:f1de0d0b1ff2b922dbcf85a1039bc6d0d120c0fbbf951d7bbaf6034ac4c5aae4
Deleted: sha256:1add6d7719c109667e3d96b[1611](https://github.com/kgateway-dev/kgateway/actions/runs/14885913016/job/41805346950#step:3:1 …
```
=> .github/actions: Remove docker rm node:16 command

internal/kgateway/deployer/deployer.go
Signed-off-by: Steven Landow <steven.landow@solo.io>
A service entry with the following should egress to `httpbin.org` externally
```
hosts:
- httpbin.org
ports:
- number: 80
name: http
protocol: HTTP
- number: 443
name: tls  
protocol: TLS
resolution: DNS
```
The path would be 
client -> httbin.org (ztunnel captures DNS, gives the SE VIP) -> ztunnel (we have a waypoint for SE VIP) -> waypoint
at this point, if we're DNS captured, the waypoint will send to that VIP and the ztunnel will send traffic back to the waypoint causing a loop
by opting out of DNS capture, we end up with the externally resolved DNS rather than the in-mesh DNS that includes ServiceEntry hosts. 
```
/kind bug_fix
```
```release-note
Turn off ambient DNS capture by default for kgateway-waypoint, fixing traffic loops …
```
=> turn off ambient DNS for waypoints by default

.github/workflows/README.md, .github/workflows/lint-helm.yaml, .github/workflows/release.yaml, install/helm/kgateway-crds/Chart.yaml, install/helm/kgateway/Chart.yaml
* Add helm chart linting to CI workflows (#10283)
* Fix missing icons on kgateway and kgateway-crd helm charts
```
/kind cleanup
```
```release-note
NONE
```
=> .github: Add helm chart linting to CI workflows (#10283)

internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml, test/kubernetes/e2e/features/deployer/suite.go
- Add the `kgateway` label to the data plane pod
/kind cleanup
```release-note
Add `kgateway` label to data plane pods
```
The omission of the `kgateway` label from the data plane pods is seemingly an oversight, and should be added for consistency, to allow selecting by labels for kgateway data plane pods to function as expected
I've manually verified e2e that kgateway pods are correctly created with the `kgateway: kube-gateway` label as of this change
=> Add kgateway label to data plane pod

install/helm/kgateway/templates/deployment.yaml, install/helm/kgateway/values.yaml
Allows users to set annotations on the `Deployment` when installing the `kgateway` Helm chart.
```
```
```release-note
Enables setting annotations on `Deployment` generated by `kgateway` Helm chart.
```
=> Enable annotations to be set on `Deployment` in `kgateway` Helm chart

test/kubernetes/e2e/features/services/tlsroute/suite.go
Attempt to fix TLSRoute e2e test flake by waiting for pods to be ready
Fixes #10812
```
/kind flake
```
```release-note
NONE
```
=> fix tlsroute flake

.github/workflows/pr-kubernetes-tests.yaml, test/kubernetes/e2e/features/rate_limit/testdata/common.yaml
Run the LocalRateLimit e2e tests in CI
Related to #11248
```
/kind cleanup
```
```release-note
NONE
```
- I tried enabling GlobalRateLimit but those tests were flaky, so left them out for now. We can keep the issue open to track it
=> enable local ratelimit test

.golangci.yaml, internal/kgateway/krtcollections/setup.go
Adds a linter rule to forbid the usage of kclient.New in favor of kclient.NewFiltered to honor the discoveryNamespaceSelectors ObjectFilter (added in 1bf1e2488) to filter out objects that are not relevant for discovery. This will prevent accidental usage of kclient.New on namespaced resources.
Although cluster scoped resources may use kclient.NewFiltered with an ObjectFilter since the filter rule does not apply to cluster scoped objects, it is acceptable to use kclient.New with a //nolint:forbidigo directive.
```
/kind cleanup
```
```release-note
NONE
```
Without //nolint:forbidgo 
```
internal/kgateway/krtcollections/setup.go:101:35: use of `kclient.New` forbidden because "use kclient.NewFiltered with discovery namespace ObjectFilter instead" (forbidigo)
gatewayClasses := …
```
=> linter: forbid usage of kclient.New to honor discoveryNamespaceSelectors

test/kubernetes/e2e/features/agentgateway/a2a-example/Dockerfile
The A2A example agent depends on a2a-samples from Google's A2A repository, which requires a2a-sdk>=0.2.1. The latest version of a2a-sdk requires Python 3.13, causing the Docker build to fail with Python 3.11.
Closes https://github.com/kgateway-dev/kgateway/issues/11254
/kind flake
```release-note
NONE
```
=> test: Update the Python base image in the A2A example image

go.mod, go.sum, hack/utils/oss_compliance/osa_provided.md, pkg/generated/openapi/zz_generated.openapi.go
Bumping the k8s api package to `v1.3.0`.
Main reason is to be able to support [HTTPRoute CORS](https://gateway-api.sigs.k8s.io/reference/spec/#httpcorsfilter) in https://github.com/kgateway-dev/kgateway/pull/11252.
/kind cleanup
Dependency bump (missing /kind).
```release-note
sigs.k8s.io/gateway-api bumped from v1.2.1 to 1.3.0
```
=> Bump gateway-api to v1.3.0

devel/debugging/local-controller.md, test/kubernetes/e2e/README.md
* Add an additional note to the instructions in local_controller.md about the IP address for the XDS service host when debugging a local build of kgateway using a local kind cluster for testing.
* Add additional steps to local_controller.md for testing a locally running build of kgateway using a local kind cluster and inspecting KRT and XDS snapshots.
* Fix a reference to Gloo found in the README.md in the test/kubernetes/e2e directory.
```
/kind cleanup
```
```release-note
NONE
```
=> docs: Add note about XDS service IP and steps for local debugging, README cleanup

api/applyconfiguration/api/v1alpha1/ratelimitprovider.go, api/applyconfiguration/api/v1alpha1/tokenbucket.go, api/v1alpha1/gateway_extensions_types.go, api/v1alpha1/traffic_policy_types.go, install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayextensions.yaml, install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml, internal/kgateway/extensions2/plugins/trafficpolicy/global_rate_limit_plugin.go, internal/kgateway/extensions2/plugins/trafficpolicy/global_rate_limit_plugin_test.go, internal/kgateway/extensions2/plugins/trafficpolicy/local_rate_limit_plugin.go, internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
Make sure CEL validation catches invalid durations in our CRDs
```
/kind feature
```
no functional changes.
```release-note
Invalid durations in our CRDs will now be rejected using CEL, before the CR is admitted.
```
=> cleanup: use gateway api duration for better CEL validation.

.github/workflows/release.yaml, .goreleaser.yaml
Updates the release pipeline to avoid publishing GH releases for pushes to main branch. Previously, both artifacts and a concrete GH release/tag would be published whenever a PR merged to main. Now, we publish artifacts but avoid publishing a concrete GH release for this event trigger.
/kind cleanup
```release-note
NONE
```
See https://github.com/kgateway-dev/kgateway/discussions/11286 for some context on this.
=> Avoid publishing GH releases for main branch pushes

api/applyconfiguration/api/v1alpha1/backendconfigpolicyspec.go, api/applyconfiguration/internal/internal.go, api/v1alpha1/backend_config_policy_types.go, api/v1alpha1/zz_generated.deepcopy.go, install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml, internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go, internal/kgateway/krtcollections/policy.go, internal/kgateway/setup/testdata/standard/backendconfigpolicy-alias-out.yaml, internal/kgateway/setup/testdata/standard/backendconfigpolicy-alias.yaml, internal/kgateway/setup/testdata/standard/backendconfigpolicy-label-out.yaml, internal/kgateway/setup/testdata/standard/backendconfigpolicy-label.yaml, pkg/generated/openapi/zz_generated.openapi.go, pkg/pluginsdk/ir/backend.go
- Introduced TargetSelectors field in BackendConfigPolicySpec to enable selection of resources with matchLabels.
Signed-off-by: omar <omar.hammami@solo.io>
```
```
```release-note
add TargetSelectors field in BackendConfigPolicySpec to enable selection of resources with matchLabels.
```
=> feat: add TargetSelectors to BackendConfigPolicy

internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy_test.go, internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go, internal/kgateway/extensions2/plugins/waypoint/waypoint_translator_test.go, internal/kgateway/krtcollections/builtin.go, internal/kgateway/krtcollections/policy.go, internal/kgateway/translator/gateway/gateway_translator_test.go, internal/kgateway/translator/irtranslator/fc.go, internal/kgateway/translator/irtranslator/gateway.go, internal/kgateway/translator/irtranslator/route.go, pkg/plugins/gwextbase/base.go, pkg/pluginsdk/ir/gw.go, pkg/pluginsdk/ir/gw_test.go, test/translator/file_loader.go, test/translator/test.go
- Exports MergeTrafficPolicies to make it possible to be consumed outside the pkg.
- Orders policy application such that built-in policies are applied last so that they can override other forms of attachments. Builtin policies are policies inlined within the targeted object's spec.
- Makes policy application consistent by merging policies by GroupKind (in order) before calling the Apply funcs on the TranslationPass. Not merging them can result in semantic differences when plugins support MergePolicies for a given GroupKind.
- Refactors the translator test to make it importable.
```
/kind cleanup
```
```release-note
NONE
```
=> plugins: export trafficpolicy merge, order plugin application

internal/kgateway/krtcollections/policy.go, internal/kgateway/translator/irtranslator/route.go
- Fixes a bug with ExtensionRef IR errors not being propagated to PolicyAtt.
- Fixes a regression introduced by 65aa25533 where the reporting must happen on indidual policies and not on the merged policy.
```
/kind cleanup
```
```release-note
NONE
```
=> policy: propagate ExtensionRef errors to PolicyAtt and fix reporting

internal/kgateway/extensions2/plugins/backend/plugin.go, internal/kgateway/extensions2/plugins/directresponse/direct_response_plugin.go, internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go, internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go, internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
The UnimplementedProxyTranslationPass type already provides default empty implementations for the ProxyTranslationPass interface. Some plugins were embedding this type while also providing their own empty method implementations, which is redundant.
This change removes the duplicate empty implementations, letting the embedded UnimplementedProxyTranslationPass handle the default behavior instead.
/kind cleanup
```release-note
NONE
```
=> plugins: Remove redundant empty method implementations

Makefile
The run Makefile target was introduced recently in an effort to automate dev environments without having to run the setup-kind.sh script, install the helm charts, etc.
Previously, this target was broken as it failed to install the GW API CRDs and used the vanity registry for deployment, which led to ImagePullBackOff in environments bootstrapped by this target.
This PR updates the target to install everything. There's some additional work that needs to be done to integrate it with CI that'll likely require some refactoring in how we manage these deployment and test related targets.
/kind cleanup
```release-note
NONE
```
=> Makefile: Fix the run target

.github/workflows/pr-unit-tests.yaml, Makefile, go.mod, go.sum, hack/utils/oss_compliance/osa_provided.md, internal/kgateway/setup/setup_test.go, pkg/envoyinit/run.go, pkg/utils/cmdutils/cmd.go, pkg/utils/cmdutils/local.go, pkg/utils/controllerutils/admincli/client_test.go, test/envtestutil/util.go
i suspect the cause is not having a separate t, so cleanup is not done properly.
Also added all of `internal` and `pkg` to unit test target
fixes https://github.com/kgateway-dev/kgateway/issues/11325
```
/kind flake
```
```release-note
NONE
```
=> deflake: try to deflake ipv6 setup tests.

install/test/fixtures.go, install/test/fixtures/envoy_config/bootstrap_extensions.yaml, install/test/fixtures/envoy_config/custom_static_bootstrap.yaml, install/test/fixtures/envoy_config/overload_manager.yaml, install/test/fixtures/envoy_config/static_clusters.yaml, install/test/fixtures/envoy_config/tcp_keepalive.yaml, install/test/k8sgateway_test.go, internal/kgateway/deployer/deployer.go, internal/kgateway/deployer/deployer_test.go
Switches to [Envoy's](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--stats?format=prometheus&usedonly) /stats/prometheus?usedonly endpoint "to only get statistics that Envoy has updated (counters incremented at least once, gauges changed at least once, and histograms added to at least once)".
This improves monitoring UX and resource usage.
```
/kind breaking_change
```
```release-note
Switching to Envoy's `/stats/prometheus?usedonly` endpoint to only get statistics that Envoy has updated (counters incremented at least once, gauges changed at least once, and histograms added to at least once).
```
=> Switch to exposing usedonly stats in StatsConfig

install/helm/kgateway/values.yaml
- **Motivation:** the helm-docs tool that generates the markdown can only take in a single line. As such, multi-line descriptions only included the last line
- **What changed:** changed descriptions to single line
- **Related issues:** followup to https://github.com/kgateway-dev/kgateway/pull/11350
```
```
```release-note
NONE
```
Since the discovery namespace selector example was too long, I added it to the docs in this commit and just linked out to that: https://github.com/kgateway-dev/kgateway.dev/pull/234/commits/615e4cb238b04c542ac975a79d6923a2d70a7074
=> docs: single-line Helm descriptions

internal/kgateway/extensions2/plugins/backend/ai/ai_backend.go, internal/kgateway/extensions2/plugins/backend/ai/ai_resources.go, internal/kgateway/extensions2/plugins/trafficpolicy/ai_env.go, internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go, internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy_test.go, test/testutils/env.go
Fixes #11366 
This PR centralizes the definition and documentation of AI Gateway's environment variables.
All AI-related environment variables are now defined in a single, well-documented location: `test/testutils/env.go`.
```
/kind cleanup
```
```release-note
NONE
```
=> refactor: Centralize AI plugin environment variable

go.mod, internal/kgateway/extensions2/plugins/backend/ai/ai_backend.go, internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster.go, internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster_test.go, internal/kgateway/extensions2/plugins/backend/aws.go, internal/kgateway/extensions2/plugins/backend/dfp.go, internal/kgateway/extensions2/plugins/backend/plugin.go, internal/kgateway/extensions2/plugins/backend/static.go, internal/kgateway/krtcollections/builtin.go, internal/kgateway/krtcollections/endpoints.go, internal/kgateway/krtcollections/endpoints_test.go, internal/kgateway/krtcollections/policy.go, internal/kgateway/krtcollections/setup.go
- Bumps Go to 1.24.2
- Fixes port lookup function. `break` was misused.
- Removes unused params
```
/kind cleanup
```
```release-note
NONE
```
=> internal: bump Go, fix port check, and remove unused param

internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go, internal/kgateway/setup/testdata/inference_api/inferencepool-basic-out.yaml, internal/kgateway/setup/testdata/inference_api/inferencepool-basic.yaml, internal/kgateway/setup/testdata/inference_api/inferencepool-multi-route-single-pool-out.yaml, internal/kgateway/setup/testdata/inference_api/inferencepool-multi-route-single-pool.yaml, internal/kgateway/setup/testdata/inference_api/inferencepool-single-route-multi-pool-out.yaml, internal/kgateway/setup/testdata/inference_api/inferencepool-single-route-multi-pool.yaml
Modifies `HttpFilters()` to register one well-known ext-proc filter regardless of InferencePool count and rely on the `typed_per_filter_config` overrides added in `ApplyForBackend()` to direct each request to the appropriate EPP cluster.
```
/kind bug_fix
```
Fixes #11389 
```release-note
NONE
```
- xref llm-d issue for add'l context: https://github.com/llm-d/llm-d-inference-scheduler/issues/158#issuecomment-2961262227
- https://github.com/kgateway-dev/kgateway/pull/11412 adds e2e test coverage for this change.
=> Inference Extension: Use a Single Shared ExtProc Filter for all InferencePools

.github/workflows/pr-unit-tests.yaml
Simplified job IDs in pr-unit-tests.yaml workflow from verbose names to concise language identifiers:
- kube_gateway_project -> go
- python_unit_tests -> python
The display names (Go Unit Tests, Python Unit Tests) remain unchanged. This change removes legacy naming artifacts from the 1.x project organization while keeping the workflow's functionality identical.
/kind cleanup
```release-note
NONE
```
Required changes to branch protection rules. Fixes https://github.com/kgateway-dev/kgateway/issues/10603.
=> .github/workflows: Simplify job names in unit test workflow

internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go, internal/kgateway/setup/testdata/inference_api/inferencepool-basic-out.yaml, internal/kgateway/setup/testdata/inference_api/inferencepool-basic.yaml, internal/kgateway/setup/testdata/inference_api/inferencepool-multi-route-single-pool-out.yaml, internal/kgateway/setup/testdata/inference_api/inferencepool-multi-route-single-pool.yaml, internal/kgateway/setup/testdata/inference_api/inferencepool-single-route-multi-pool-out.yaml, internal/kgateway/setup/testdata/inference_api/inferencepool-single-route-multi-pool.yaml
Backport of https://github.com/kgateway-dev/kgateway/pull/11390 and associated https://github.com/kgateway-dev/kgateway/pull/11444 (stabilizes setup tests).
```
/kind bug_fix
```
```release-note
NONE
```
xref upstream issue: https://github.com/llm-d/llm-d-inference-scheduler/issues/158
=> Inference Extension: Use single shared extproc filter

internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go, internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin_test.go, test/kubernetes/e2e/features/backendconfigpolicy/suite.go, test/kubernetes/e2e/features/backendconfigpolicy/testdata/setup.yaml
Previously, a user could specify http1 protocol options in a BackendConfigPolicy targeting an http2 backend, which would override the http2 configuration. This PR prevents this footgun.
also, follow up to https://github.com/kgateway-dev/kgateway/pull/11420 by adding additional assertions to the e2e test to ensure config is applied to envoy.
/kind fix
```release-note
prevent BackendConfigPolicy with http1protocoloptions set from overwriting an http2 backend
```
=> BackendConfigPolicy : dont apply http1 options to http2 backend

test/mocks/mock-ai-provider-server/main.go
Gin will not accept the `:param` in the middle of the path, and gemini has a weird api like `/gemini-1.5:generate`.
/kind cleanup
```release-note
NONE
```
=> ai mock: fix gemini endpoint

internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go, internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go, internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go, pkg/pluginsdk/utils/policy.go
Moves the TargetRefs conversion utils to an exported pkg to allow external plugins to use it.
```
/kind cleanup
```
```release-note
NONE
```
=> pluginsdk: move TargetRef util to exported pkg

internal/kgateway/extensions2/plugins/trafficpolicy/merge_test.go, internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
Previously, any errors in individual TrafficPolicy IR types were lost during
route translation due to the mergePolicies function not collecting errors from
individual policies. The function would create a new PolicyAtt with an empty
Errors slice, discarding all validation errors from the input policies.
This caused route.go line 310-311 to result in zero errors for attached
policies post-merge, even when individual policies had validation errors.
Invalid TrafficPolicy configurations would appear to be accepted during route
processing when they should have been rejected with appropriate error messages.
This change adds error aggregation to the mergePolicies function by iterating
through each policy and appending their Errors field to a combined slice in
the final merged result. Policy …
=> trafficpolicy: Preserve policy errors during route translation

Makefile, go.mod, go.sum
Remove the gettercheck tool dependency from the repository. With the migration away from protobuf-based APIs in favor of kubebuilder managed APIs, we no longer have a need for this type of tooling, and can remove some cruft from the repository. Additionally, this tool isn't actively maintained.
Note: this tool was originally carried over when we migrated to the Go 1.24 tool paradigm with an open question on whether it still served this project any value.
/kind cleanup
```release-note
NONE
```
=> Remove the github.com/saiskee/gettercheck tool

api/annotations/gateway.go, internal/kgateway/krtcollections/policy.go, internal/kgateway/translator/gateway/gateway_translator.go, internal/kgateway/translator/gateway/gateway_translator_test.go, internal/kgateway/translator/gateway/testutils/inputs/gateway-per-conn-buf-lim/gateway.yaml, internal/kgateway/translator/gateway/testutils/outputs/gateway-per-conn-buf-lim/proxy.yaml, internal/kgateway/translator/irtranslator/gateway.go, pkg/pluginsdk/ir/backend.go, pkg/pluginsdk/ir/gw2.go
https://github.com/kgateway-dev/kgateway/issues/11387
Allow setting listener-level perConnectionBufferLimitBytes. 
```release-note
Allow setting listener-level perConnectionBufferLimitBytes by setting the `kgateway.dev/per-connection-buffer-limit` annotation on the gateway. 
```
We discussed several options for setting perConnectionBufferLimitBytes.
- Creating new policy for listener options
-  decided against this since it was overkill to create a new policy for one field, and we're unlikely to have other listener level fields even in future
- adding this option to GatewayParameters
- while this makes sense, it will require a lot of up front work to refactor it out of deployer and into krt collections
We decided using an annotation on the gateway made sense and was …
=> allow setting per connection buffer limit on Gateway with annotation

api/v1alpha1/backend_config_policy_types.go, install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml, pkg/generated/openapi/zz_generated.openapi.go, test/kubernetes/e2e/tests/api_validation_test.go
This is a follow-up to the https://github.com/kgateway-dev/kgateway/pull/11455/ PR which introduced support for HTTP2 protocol options on the BCP API.
Update the CEL validation used to enforce that http1 & http2 protocol options cannot be defined together via the new AtMostOneOf marker.
/kind cleanup
```release-note
NONE
```
=> api: Replace CEL validation with AtMostOneOf marker for HTTP protocol options

api/v1alpha1/gateway_extensions_types.go, install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayextensions.yaml
- Remove 'Extended' from GatewayExtensionType enum validation as it was never implemented
- Only ExtAuth, ExtProc, and RateLimit are actually supported types
- No corresponding provider struct or validation rules exist for Extended type
/kind cleanup
```release-note
NONE
```
Noticed this locally while looking into an unrelated issue.
=> api: Remove unused Extended enum value from GatewayExtensionType

internal/kgateway/crds/inferencemodels.yaml, internal/kgateway/crds/inferencepools.yaml
Bumps the InferencePool and InferenceModel CRDs to consume recent upstream changes.
Needed to pass inference extension conformance tests.
```
/kind cleanup
```
```release-note
Bumps the inference extension CRDs to sync with upstream commit 842603b.
```
Fixes #11531
=> Inference: Bumps CRDs

design/11387.md
Design doc for https://github.com/kgateway-dev/kgateway/issues/11387 (well, part of it). Allow setting listener-level perConnectionBufferLimitBytes.
/kind design
```release-note
NONE
```
=> EP-11387 Listener-level perConnectionBufferLimitBytes.

Makefile
- This target is a subset of the run target and does everything outside of helm chart deployment
- Useful in the context of running the e2e suite locally
/kind cleanup
```release-note
NONE
```
=> Makefile: Add dedicated 'setup' target

design/11466.md, design/11584.md, internal/kgateway/deployer/gateway_parameters_test.go, internal/kgateway/krtcollections/grpc_route_test.go, internal/kgateway/krtcollections/metrics_test.go, internal/kgateway/krtcollections/policy.go, internal/kgateway/krtcollections/policy_test.go, internal/kgateway/krtcollections/setup.go, internal/kgateway/query/query_test.go, internal/kgateway/translator/gateway/gateway_translator_test.go, internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/label_based.yaml, internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/label_based_global_policy.yaml, pkg/deployer/deployer_test.go, pkg/settings/settings.go, pkg/settings/settings_test.go, test/kubernetes/e2e/defaults/defaults.go, test/kubernetes/e2e/defaults/testdata/httpbin.yaml, test/kubernetes/e2e/features/policyselector/suite.go, test/kubernetes/e2e/features/policyselector/testdata/label_selector.yaml, test/kubernetes/e2e/features/policyselector/types.go, test/kubernetes/e2e/test.go, test/kubernetes/e2e/tests/kgateway_test.go, test/kubernetes/testutils/install/context.go
Enables the ability to define policies in a well known namespace controlled by Settings.GlobalPolicyNamespace that resources in any namespace can attach to if they match the selected labels.
Resolves #11584
```
```
```release-note
Adds the ability for resources to attach to policies defined
in the global policy namespace when using targetSelectors.
```
=> policy: enable global cross-namespace targetSelector attachment

test/kubernetes/e2e/features/accesslog/suite.go, test/kubernetes/e2e/features/accesslog/testdata/otel.yaml, test/kubernetes/e2e/features/tracing/suite.go, test/kubernetes/e2e/features/tracing/testdata/tracing-policy.yaml, test/kubernetes/testutils/assertions/status.go
Fix a flake caused by the test running before the HTTPListenerPolicy is accepted
Ref: https://github.com/kgateway-dev/kgateway/actions/runs/16053044429/job/45300367457?pr=11483
```
/kind flake
```
```release-note
NONE
```
=> fix: ensure HTTPListenerPolicy is accepted before running tests

internal/kgateway/translator/gateway/gateway_translator_test.go, internal/kgateway/translator/gateway/testutils/inputs/delegation/unresolved_ref.yaml, internal/kgateway/translator/gateway/testutils/outputs/delegation/basic_parentref_mismatch.yaml, internal/kgateway/translator/gateway/testutils/outputs/delegation/child_rule_matcher.yaml, internal/kgateway/translator/gateway/testutils/outputs/delegation/cyclic1.yaml, internal/kgateway/translator/gateway/testutils/outputs/delegation/cyclic2.yaml, internal/kgateway/translator/gateway/testutils/outputs/delegation/invalid_child_valid_standalone.yaml, internal/kgateway/translator/gateway/testutils/outputs/delegation/multiple_parents.yaml, internal/kgateway/translator/gateway/testutils/outputs/delegation/unresolved_ref.yaml, internal/kgateway/translator/gateway/testutils/outputs/discovery-namespace-selector/base_select_infra.yaml, internal/kgateway/translator/httproute/delegation.go, internal/kgateway/translator/httproute/gateway_http_route_translator.go, internal/kgateway/translator/irtranslator/route.go, pkg/pluginsdk/ir/gw2.go, test/kubernetes/e2e/features/route_delegation/suite.go, test/translator/test.go
When a parent route's backendRefs is unresolved, return a 500 direct response to explicitly drop the rule and prevent unintentional matches against less specific routes.
```
/kind bug_fix
```
```release-note
Parent HTTPRoutes with unresolved child routes will
return a 500 direct response.
```
Resolves #11549
=> route-delegation: return 500 on unresolved backendRefs

.github/workflows/release.yaml, .goreleaser.yaml
Correct set the commit that will be used for releases.
This should not have a direct impact on releases from `main` but it is explicitly correct and prepares us for the next 2.1.x branch cut.
Forward port of https://github.com/kgateway-dev/kgateway/pull/11201
Fixes https://github.com/kgateway-dev/kgateway/issues/11176
```
/kind cleanup
```
```release-note
NONE
```
=> use correct commit for release

.github/workflows/pr-kubernetes-tests.yaml, test/kubernetes/e2e/features/path_matching/suite.go, test/kubernetes/e2e/features/path_matching/testdata/exact.yaml, test/kubernetes/e2e/features/path_matching/testdata/prefix-rewrite.yaml, test/kubernetes/e2e/features/path_matching/testdata/prefix.yaml, test/kubernetes/e2e/features/path_matching/testdata/regex.yaml, test/kubernetes/e2e/features/path_matching/testdata/setup.yaml, test/kubernetes/e2e/features/path_matching/types.go, test/kubernetes/e2e/tests/kgateway_tests.go
This PR adds e2e testing for HTTPRoute path matching using the `spec.rules.matches.path` field.
It also includes testing for simple prefix rewrites, trimming a prefix using the `PathPrefix` match type alongside setting `spec.rules.filters.urlRewrite.path.replacePrefixMatch` to `/`
/kind cleanup
```release-note
NONE
```
=> Add e2e testing for HTTPRoute path matching and simple prefix rewrites

internal/kgateway/krtcollections/builtin.go, internal/kgateway/translator/gateway/testutils/outputs/session-persistence/cookie.yaml, internal/kgateway/translator/gateway/testutils/outputs/session-persistence/header.yaml
While working on implementing session persistence via BackendTrafficPolicies for https://github.com/kgateway-dev/kgateway/issues/11162 on a local kind cluster I ran into some issues when testing the existing  HTTPRoute implementation where it appeared session persistence was not working.
Envoy’s log repeatedly showed:
```
gRPC config … rejected: Unable to unpack as … StatefulSessionPerRoute:
[type.googleapis.com/envoy.extensions.filters.http.stateful_session.v3.StatefulSession] { … }
```
for an HTTPRoute that looks like:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"gateway.networking.k8s.io/v1","kind":"HTTPRoute","metadata":{"annotations":{},"name":"echo","namespace":"default"},"sp …
```
=> fix: output per route config for SessionPersistence on RouteRules

test/kubernetes/e2e/file.go, test/kubernetes/e2e/tests/agent_gateway_test.go, test/kubernetes/e2e/tests/ai_extension_test.go, test/kubernetes/e2e/tests/inference_extension_test.go
Inside file.go, there were three variables — AIValuesManifestPath, InfExtValuesManifestPath, and AgentGatewayIntegrationValuesPath — which were only used in one test file, so I have moved them to their individual files, as suggested in Fixes #11375.
```
/kind cleanup
```
```release-note
NONE
```
=> refactor: Three variables from file.go have been moved to their individual files.

pkg/pluginsdk/ir/backend.go
Fixes https://github.com/kgateway-dev/kgateway/issues/11625
the Equals func must compare the PerConnectionBufferLimitBytes so that changing the value will update the gateway proxy.
Additionally, the Equals func was missing comparison for the Listeners, so added that
/kind bug_fix
```release-note
fix: handle changing the value of the PerConnectionBufferLimitBytes annotation on the gateway
```
=> fix: handle PerConnectionBufferLimitBytes in Gateway Equals

.github/workflows/pr-kubernetes-tests.yaml, internal/kgateway/translator/gateway/testutils/inputs/session-persistence/cookie.yaml, test/kubernetes/e2e/features/session_persistence/suite.go, test/kubernetes/e2e/features/session_persistence/testdata/cookie-session-persistence.yaml, test/kubernetes/e2e/features/session_persistence/testdata/echo-service.yaml, test/kubernetes/e2e/features/session_persistence/testdata/header-session-persistence.yaml, test/kubernetes/e2e/features/session_persistence/types.go, test/kubernetes/e2e/tests/kgateway_tests.go
The session persistence feature was missing e2e testing and had some translator test inputs that were failing CEL validation when applied directly. I've added a basic e2e test suite that validates both cookie-based and header-based session persistence functionality on httproutes. The tests create echo services with multiple replicas and verify that requests with the same session consistently hit the same backend pod.
I also fixed the CEL validation issues in the translator test inputs by adding the missing `absoluteTimeout` fields that are required when `lifetimeType` is set to `Permanent`.
fixes :
- https://github.com/kgateway-dev/kgateway/issues/11620
- https://github.com/kgateway-dev/kgateway/issues/11622
/kind cleanup
```release-note
NONE
```
=> Add session persistence e2e tests

pkg/validator/validator.go, pkg/validator/validator_test.go
Avoid hardcoding the envoy docker image and executable path with functional options. The primary benefit with this change is being able to perform xDS validation using the upstream Envoy image until we're able to migrate off the envoy-gloo dependency later in the 2.1 cycle, in 2.2, etc.
One of the follow-up(s) to the https://github.com/kgateway-dev/kgateway/issues/11535 PR.
/kind cleanup
```release-note
NONE
```
=> pkg/validator: Add functional options for envoy configuration

internal/kgateway/deployer/gateway_parameters.go
Part of https://github.com/kgateway-dev/kgateway/issues/11650, introduced by https://github.com/kgateway-dev/kgateway/pull/11508
UpdateSecurityContexts was introduced to add 
```
sysctls:
- name: net.ipv4.ip_unprivileged_port_start
value: "0"
```
To the `PodSecurityContext` in the `PodTemplate`. However, in the original PR, the [PodTemplate was assigned to a local var ](https://github.com/sheidkamp/kgateway/blob/main/internal/kgateway/deployer/gateway_parameters.go#L281) before the UpdateSecurityContexts was called.
In the case that the `PodTemplate` is null, a function called UpdateSecurityContexts [creates a PodTemplate](https://github.com/kgateway-dev/kgateway/blob/main/pkg/deployer/gateway_parameters.go#L59-L61) in order to have a place to set `PodSecurityContext` values. When this …
=> Port-mapping Security Context fix

internal/kgateway/controller/controller_suite_test.go, internal/kgateway/controller/gw_controller.go
- **Motivation:** I noticed that gw_controller ignores "Not Found" errors returned when deployer attempts to render gw chart. These can happen when kube client fails to fetch GatewayClass or GatewayParameter resources (for w/e reason) and result in chart not being rendered (an empty list of objects to sync to cluster).  There's no error recorded, and the only symptom is a missing gateway pod. The same issue doesn't exist in the inference extension controller.
- **What changed:** "Not Found" returned when the deployer renders the gateway chart are no longer ignored. 
/kind bug_fix
```release-note
NONE
```
=> Do not ignore 'not found errors' from Deployer

test/kubernetes/e2e/features/inferenceextension/testdata/epp.yaml
Updates the e2e inference extension EPP manifest to use plugin conf file due to breaking changes introduced by https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1151
Fixes #11686 
```
/kind flake
```
```release-note
e2e: Updates the inference extension EPP manifest to use the scheduler plugin config file.
```
N/A
=> e2e: Updates Inference Extension EPP Manifest

internal/kgateway/extensions2/plugins/trafficpolicy/gateway_extension.go, pkg/pluginsdk/ir/gw.go, pkg/pluginsdk/ir/iface.go
`PolicyAtt` and `PolicyWrapper` types did not consider their errors in their `Equals` impl
```
/kind bug_fix
```
```release-note
Correctly report status for attached policies and gatewayExtensions when only errors change
```
=> fix Equals for PolicyAtt and PolicyWrapper

internal/kgateway/controller/controller_suite_test.go, internal/kgateway/deployer/gateway_parameters_test.go, pkg/deployer/deployer_test.go, pkg/schemes/extended_scheme.go
Replaces the deprecated `AddToScheme()` with `Install()` to install the Inference Extension v1alpha2 scheme.
```
/kind cleanup
```
```release-note
Inference: Replaces deprecated AddToScheme() with Install() to install the Inference Extension v1alpha2 scheme.
```
See https://github.com/solo-io/gloo-gateway/pull/449#event-18709492492 and https://github.com/solo-io/gloo-gateway/actions/runs/16395469284/job/46327182858?pr=449 where this issue surfaces.
=> Inference: Replace Deprecated AddToScheme() with Install()

test/kubernetes/e2e/test.go, test/kubernetes/testutils/helper/install.go
**Motivation:** 
The test helper function `GetLocalChartPath` previously hardcoded the test asset directory (_test), making it difficult to override the asset location in different environments (e.g., when using a custom Makefile variable). This limited test flexibility and maintainability.
**What changed:**
- Refactored `GetLocalChartPath` to accept an optional `assetDir` parameter (variadic), allowing the test asset directory to be injected.
- If `assetDir` is not provided, the function defaults to using "_test" for backward compatibility.
**Related issues:**
Fixes: #11655 
/kind cleanup
```release-note
NONE
```
NONE
=> refactor: Update GetLocalChartPath to accept optional assetDir parameter

pkg/utils/helmutils/client.go
Related issues: Fixes #11658
**What changed:**
* Added a `helmPath` field to `helmutils.Client` to store the path to the helm executable.
* Introduced a `WithHelmPath` method to allow consumers to configure the executable path.
/kind cleanup
```release-note
NONE
```
=> feat: Add helmPath configuration to Client for customizable helm executable path

.github/actions/kube-inference-extension-conformance-tests/action.yaml, .github/workflows/regression-tests.yaml, .github/workflows/release.yaml, Makefile, hack/kind/setup-kind.sh
Updates CI and Make workflows to support running the Gateway API Inference Extension conformance tests.
```
```
```release-note
CI: Adds support for running Gateway API Inference Extension conformance tests.
```
Only review commit 824967d7018e5af35488b3838cefdf431a46d8ef since this PR requires commit f73fe0dce7b3c0d13b48949d2ad6ecfeebb0a319 from #11621 to pass CI.
=> Adds Support for Gateway API Inference Extension Conformance

test/kubernetes/e2e/tests/api_validation_test.go
**Motivation:**  
When an API validation test case does not expect an error (`wantErrors` is empty or nil) but the apiserver rejects the configuration, the test fails with a generic `exit status 1`. This makes it difficult to debug why the resource was rejected.
**What changed:**  
This change improves test feedback by logging the full output of `kubectl apply` (i.e., `out.String()`) when an unexpected error occurs. This provides better visibility into the underlying validation failure.
**Related issues:**  
Fixes #11751
/kind bug_fix
/kind cleanup
```release-note
API validation tests now log the output from `kubectl apply` when an unexpected error occurs, making it easier to debug failing test cases.
```
=> test: log apply output when unexpected error occurs in APIValidation

internal/kgateway/controller/gw_controller.go, internal/kgateway/proxy_syncer/proxy_syncer.go, pkg/reports/status.go
Adds retries to gateway controller and proxy syncer when updating Gateway status.
Fixes #11696 
```
/kind bug_fix
```
```release-note
Adds retries to gateway controller and proxy syncer when updating Gateway status.
```
N/A
=> Adds Retries to Updating Gateway Status

go.mod, go.sum, hack/utils/oss_compliance/osa_provided.md, test/kubernetes/e2e/features/inferenceextension/testdata/epp.yaml
**Description:**
Update `sigs.k8s.io/gateway-api-inference-extension` from `v0.5.0-rc.2` to stable `v0.5.0` in `go.mod` and test config, ensuring latest stable dependency.
**Change Type:**
```
/kind cleanup
```
**Changelog:**
```release-note
NONE
```
**Additional Notes:**
Fixes #11765.
=> Update gateway-api-inference-extension to v0.5.0 (Fixes #11765)

internal/kgateway/query/httproute.go, internal/kgateway/translator/gateway/gateway_translator_test.go, internal/kgateway/translator/httproute/gateway_http_route_translator.go, internal/kgateway/translator/irtranslator/route.go, pkg/pluginsdk/ir/gw2.go, pkg/pluginsdk/reporter/types.go, test/translator/test.go
PartiallyInvalid condition has several problems:
1. It must be set only when PartiallyInvalid=True. This requires extra logic to invalidate an existing condition when there should be no PartiallyInvalid condition on an updated route status.
2. PartiallyInvalid must only be set when the route is partially invalid and not fully invalid. This requires post processing as translation merges routes with the same hostname and tracking whether a route is only partially invalid needs to group translated route rules by their parent route and check the rules for validity.
This change drops the usage of PartiallyInvalid=True in favor of Accepted=False with Reason=RouteRuleDropped. A replaced route rule will have this condition set. A route is replaced in case there are processing errors or errors on …
=> status: use Accepted=False,Reason=RouteRuleDropped for replaced rule

internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go, internal/kgateway/extensions2/plugins/trafficpolicy/auto_host_rewrite.go, internal/kgateway/extensions2/plugins/trafficpolicy/buffer.go, internal/kgateway/extensions2/plugins/trafficpolicy/buffer_test.go, internal/kgateway/extensions2/plugins/trafficpolicy/constructor.go, internal/kgateway/extensions2/plugins/trafficpolicy/cors_policy.go, internal/kgateway/extensions2/plugins/trafficpolicy/csrf_policy.go, internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy.go, internal/kgateway/extensions2/plugins/trafficpolicy/extproc_policy.go, internal/kgateway/extensions2/plugins/trafficpolicy/global_rate_limit_plugin.go, internal/kgateway/extensions2/plugins/trafficpolicy/hash_policy.go, internal/kgateway/extensions2/plugins/trafficpolicy/hash_policy_test.go, internal/kgateway/extensions2/plugins/trafficpolicy/local_rate_limit_plugin.go, internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go, internal/kgateway/extensions2/plugins/trafficpolicy/transformation_plugin.go, pkg/plugins/gwextbase/base.go
The current TrafficPolicy implementation has a naming conflict between two distinct
phases in the plugin lifecycle that both use "apply" terminology:
- Phase 1: Spec -> IR conversion. Currently implemented via applyX() functions
- Phase 2: IR -> xDS application. There's are the existing ApplyForX() methods
The current naming created confusion since both phases used "apply"
terminology, and "builder" didn't match the actual construction pattern.
This commit refactors the builder.go file, renames it to constructor.go,
updates the type and the Translate method naming to better reflect the
responsibility for this type, etc. Additionally, it makes a breaking
changes to the pkg/ public surface for the alias'd type.
This change provides better semantic clarity consumption while avoiding …
=> plugins/tp: Rename TrafficPolicyBuilder to TrafficPolicyConstructor

devel/contributing/conventions.md, internal/kgateway/krtcollections/policy.go, internal/kgateway/translator/httproute/delegation_helpers.go, pkg/pluginsdk/ir/gw.go, pkg/pluginsdk/ir/gw_test.go, pkg/pluginsdk/ir/routes.go, pkg/pluginsdk/ir/routes_test.go
Fixes Equals check so that configuration derived
from annotations are reconciled on updates.
- HTTPRoutes with relevant annotation updates were not triggering translation. PrecedenceWeight changes and DelegationInheritParentMatcher are considered in the Equals check now. Both these fields are derived from annotations on the HTTPRoute.
- PolicyAtt.Equals needs to consider InheritedPolicyPriority to update the policies when a route's inherited policy priority is updated using the corresponding annotation.
```
/kind bug_fix
```
```release-note
NONE
```
Resolves #11789
=> ir: fix Equals for HttpRouteIr and PolicyAtt

test/kubernetes/e2e/features/csrf/suite.go
Looking at recent flake tests I noticed that they fail with a connection refused and on the first test in the suite.
I believe it's because the destination service wasn't ready yet.
This should fix it.
Fixes https://github.com/kgateway-dev/kgateway/issues/11644
/kind flake
```release-note
NONE
```
=> Attempt to fix flake CSRF tests

.github/workflows/pr-kubernetes-tests.yaml, test/kubernetes/e2e/defaults/defaults.go, test/kubernetes/e2e/defaults/testdata/httpbin.yaml, test/kubernetes/e2e/features/routereplacement/suite.go, test/kubernetes/e2e/features/routereplacement/testdata/setup.yaml, test/kubernetes/e2e/features/routereplacement/testdata/strict-mode-invalid-policy.yaml, test/kubernetes/e2e/features/routereplacement/types.go, test/kubernetes/e2e/tests/kgateway_tests.go, test/kubernetes/testutils/assertions/objects.go
Introduces a dedicated e2e suite for the route replacement safeguard functionality.
Fixes #11630. Introduces a basic functional suite for the route replacement functionality.
I considered a couple of different approaches:
- Update the common-recommendations.yaml manifest and enable STRICT mode by default for all suites. Dedicated feature suite would then validate invalid routes or valid routes with invalid policy attached to them, etc
- Dedicated route replacement test, enable STRICT mode by default, and keep this feature outside of the TestKgateway test
This suite is intentionally brief. The #11795 and #11766 trackers will expand it with more targeted test cases.
/kind cleanup
```release-note
NONE
```
=> Add basic route replacement e2e suite

internal/kgateway/extensions2/plugins/trafficpolicy/constructor.go, internal/kgateway/translator/gateway/gateway_translator_test.go
When there is an invalid extensionRef, print the ref in the resource status, to help with debugging.
/kind cleanup
```release-note
NONE
```
=> add gwext name to error message

internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go, internal/kgateway/translator/gateway/testutils/outputs/httplistenerpolicy/merge.yaml, internal/kgateway/translator/gateway/testutils/outputs/httplistenerpolicy/route-and-pol.yaml
https://github.com/kgateway-dev/kgateway/issues/11891
replace deprecated ExactMatch with StringMatch 
```
type HeaderMatcher_ExactMatch struct {
// If specified, header match will be performed based on the value of the header.
// This field is deprecated. Please use :ref:`string_match <envoy_v3_api_field_config.route.v3.HeaderMatcher.string_match>`.
```
/kind bug_fix
```release-note
NONE
```
=> httplistenerpolicy: replace deprecated ExactMatch with StringMatch

internal/kgateway/setup/agentgateway_test.go, internal/kgateway/setup/setup_test.go
Race condition occurred when accessing the test context.
It was actually setting the same context (parentT=t) which is redundant. Setting the context to nil under write lock makes sure the Write() function will see a nil and won't try to log after cleanup.
Fixes https://github.com/kgateway-dev/kgateway/issues/11886
/kind flake
```release-note
NONE
```
=> Fix data race with writer trying to log after test cleanup

internal/sds/pkg/run/run_e2e_test.go
This isn't a fix.
The purpose is to log the error if a test fails to start an SDS server.
This is to help tracking the flaky tests of: https://github.com/kgateway-dev/kgateway/issues/11870
/kind flake
```release-note
NONE
```
=> Log error if failed to start a test SDS server

devel/contributing/releasing.md
Updates the release guide to include an optional step to bump the GW API version.
```
```
```release-note
NONE
```
N/A
=> Docs: Update Releasing Guide for GW API Bump

hack/utils/applier/go.mod, test/mocks/mock-ai-provider-server/go.mod
Follow-up to https://github.com/kgateway-dev/kgateway/pull/11973
I was getting errors running `make generate-all`:
```
go: downloading go1.24 (darwin/arm64)
go: download go1.24 for darwin/arm64: toolchain not available
```
To fix it, changed the submodules to also use the patch version (1.24.6).
/kind cleanup
```release-note
NONE
```
=> use Go patch version in submodules

internal/kgateway/translator/gateway/gateway_translator_test.go, internal/kgateway/translator/irtranslator/route.go, pkg/pluginsdk/reporter/types.go, test/translator/assertions.go
Previously, both dropped and replaced route rules used a single custom reason "RouteRuleDropped". Now the route translator uses distinct reasons based on the actual action taken:
- RouteRuleDropped: When routes are dropped entirely (invalid matchers or legacy mode)
- RouteRuleReplaced: When routes are replaced with direct responses (standard/strict mode)
This provides clearer status reporting for users to understand whether their invalid routes were dropped or replaced with error responses.
Resolves #11977
/kind fix
/kind cleanup
```release-note
NONE
```
No need imo - the custom RouteRuleDropped condition reason was introduced in the 2.1 cycle.
=> translator: Add separate reasons for dropping vs replacing invalid routes

test/kubernetes/e2e/features/route_delegation/suite.go
Adds route status checks to TestMatcherInheritance test
**Related issues:** 
Hopefully fixes https://github.com/kgateway-dev/kgateway/issues/10814 
```
/kind flake
```
```release-note
NONE
```
TODO: still working on validating locally 
Test flakes on curl assertion:
```
2025-08-13T22:39:48.4462824Z HttpResponse{StatusCode: 200, Body: &matchers.ContainSubstringMatcher{Substr:"/anything/baz/child", Args:[]interface {}(nil)}, Headers: map[], NotHeaders: [], Custom: <nil>}
2025-08-13T22:39:48.4463119Z stdout:
2025-08-13T22:39:48.4463415Z upstream connect error or disconnect/reset before headers. reset reason: connection termination
2025-08-13T22:39:48.4463702Z stderr:  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2025-08-13T22:39:48.4464321Z …
```
=> flake: Add accepted route checks to TestMatcherInheritance test

test/kubernetes/e2e/features/deployer/suite.go
Match timeout in https://github.com/kgateway-dev/kgateway/blob/main/test/kubernetes/e2e/features/services/tlsroute/types.go#L88 
Should make https://github.com/kgateway-dev/kgateway/issues/11884 less painful. Should still investigate more why the self managed gateway status is taking longer to update than regular managed gateways.
```
/kind flake
```
```release-note
NONE
```
=> flake: bump timeout self managed gw test

.github/workflows/static-analysis.yaml
Increases Github Actions linter timeout to account for glacial prep-go-runner times.
/kind flake
```release-note
NONE
```
See https://github.com/kgateway-dev/kgateway/actions/runs/16994335597/job/48182096254
=> flake: bump timeout for linter

api/v1alpha1/backend_types.go, api/v1alpha1/mcp_backend.go, install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml, internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go, internal/kgateway/agentgatewaysyncer/agentgateway_translator_test.go, internal/kgateway/agentgatewaysyncer/testdata/inputs/backend-protocol/mcp-backend-selector.yaml, internal/kgateway/agentgatewaysyncer/testdata/outputs/backend-protocol/mcp-backend-selector.yaml, internal/kgateway/extensions2/plugins/backend/agentgateway/mcp.go, internal/kgateway/extensions2/plugins/backend/agentgateway/translate.go
- Defaults to Streamable HTTP for MCP services with `appProtocol: kgateway.dev/mcp`.
- Uses legacy SSE for MCP services with `appProtocol: kgateway.dev/mcp-sse`.
- Removes the Undefined Enum for Static MCP backends.
Drops Gingko in favor of Go stdlib for translator tests.
```
/kind cleanup
```
```release-note
NONE
```
Resolves #12036
=> agentgateway: fix MCP protocol for selector-based Backends

internal/kgateway/translator/listener/validation.go
Follow-up to https://github.com/kgateway-dev/kgateway/pull/12091
Updates the listenerset validation with an example flow
```
/kind cleanup
```
```release-note
NONE
```
=> Update listenerset validation with example workflow

pkg/deployer/agentgateway_version.go, pkg/deployer/agentgateway_version_test.go, pkg/deployer/gateway_parameters.go, pkg/deployer/wellknown.go
Dynamically extract agentgateway version from go.mod instead of using hardcoded value . This ensures the deployed container version matches the go.mod dependency.
Fixes #11967
```release-note
NONE
```
=> feat: dynamically extract agentgateway version from go.mod

go.mod, go.sum, hack/utils/oss_compliance/osa_provided.md, internal/kgateway/crds/inference-crds.yaml, internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/backends_test.go, internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/ir.go, internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/ir_test.go, internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go, internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/validation.go, internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/validation_test.go, internal/kgateway/setup/testdata/agentgateway/inferencepool.yaml, internal/kgateway/setup/testdata/inference_api/inferencepool-basic.yaml, pkg/agentgateway/plugins/inference_plugin.go, test/kubernetes/e2e/features/inferenceextension/testdata/epp.yaml, test/kubernetes/e2e/features/inferenceextension/testdata/pool.yaml
Bumps InferencePool to v1.0.0-rc.2. In this version, `inferencePool.spec.endpointPickerRef.portNumber` field has been replaced with `inferencePool.spec.endpointPickerRef.port.number`. The `inferencePool.spec.endpointPickerRef.port` field is a non-pointer and required when `inferencePool.spec.endpointPickerRef.kind` is unset or "Service". The port number `9002` is no longer inferred.
```
/kind cleanup
```
```release-note
Bumps InferencePool to v1.0.0-rc.2. `inferencePool.spec.endpointPickerRef.portNumber` field has been replaced with `inferencePool.spec.endpointPickerRef.port.number`.
```
N/A
=> Inference: Bump to v1.0.0-rc.2

internal/kgateway/krtcollections/policy.go, internal/kgateway/krtcollections/policy_test.go, internal/kgateway/query/utils.go, internal/kgateway/translator/gateway/gateway_translator_test.go, internal/kgateway/translator/gateway/testutils/inputs/backends/backend-ref-port-error.yaml, internal/kgateway/translator/gateway/testutils/outputs/backends/backend-ref-port-error.yaml
When specifying a port in the backend ref, although [doc warns users that they shouldn't](https://kgateway.dev/docs/traffic-management/destination-types/backends/#routing), we ended up with a generic `Backend "ext-httpbin" not found` error message in the HTTPRoute status condition.
E.g. for:
```yaml
backendRefs:
- name: ext-httpbin
kind: Backend
group: gateway.kgateway.dev
port: 443
```
This PR is modifying the error message in this case to be a little more descriptive and hint the actual error rather than backend not found.
E.g.:
```yaml
- conditions:
- lastTransitionTime: "2025-09-03T12:16:14Z"
message: BackendRef to "ext-httpbin" includes a port. Do not specify a port
when referencing a Backend resource, as it defines its own port configuration
observedGeneration: 1
reason: …
```
=> More descriptive error message about unexpected port in backendref

api/v1alpha1/traffic_policy_types.go, install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml, test/kubernetes/e2e/tests/api_validation_test.go
fix cel validation for TrafficPolicy buffer MaxRequestSize.
This was fixed in backendconfigpolicy for similar values of type `resource.Quantity` but missed here. See https://github.com/kgateway-dev/kgateway/issues/11611
Now the cel validation properly handles int or string values.
/kind bug_fix
```release-note
NONE
```
=> fix cel validation for TrafficPolicy buffer MaxRequestSize

Makefile, internal/envoyinit/rustformations/Cargo.lock, internal/envoyinit/rustformations/Cargo.toml
- bump envoy-gloo to latest v1.34 version
- update rust sdk hash to match the envoy release v1.34.6
envoy release note:
- https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.34/v1.34.2
- https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.34/v1.34.3
- https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.34/v1.34.4
- https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.34/v1.34.5
- https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.34/v1.34.6 (envoy has not update their doc yet. See https://github.com/envoyproxy/envoy/releases/v1.34.6 for now)
envoy-gloo release note:
- https://github.com/solo-io/envoy-gloo/releases/tag/v1.34.1-patch4
- https://github.com/solo-io/envoy-gloo/releases/tag/v1.34.5-patch1
- …
=> bump envoy-gloo to v1.34.6-patch1

test/kubernetes/e2e/features/routereplacement/suite.go, test/kubernetes/e2e/features/routereplacement/types.go
A couple changes that will hopefully help with flakes:
- convert the route replacement suite to use the BaseTestingSuite
- restore original deployment just once at the end
Fixes https://github.com/kgateway-dev/kgateway/issues/12208
/kind flake
```release-note
NONE
```
=> e2e route replacement flake fix

test/gomega/matchers/json_contains.go
Fixes https://github.com/kgateway-dev/kgateway/issues/12177
See the [issue comment](https://github.com/kgateway-dev/kgateway/issues/12177#issuecomment-3264591315) for an explanation of this fix. Removing the `evaluated` check so that JSONContains can be called more than once within an Eventually block.
/kind flake
```release-note
NONE
```
=> e2e headermodifiers flake fix

test/kubernetes/e2e/features/agentgateway/extauth/suite.go, test/kubernetes/e2e/features/agentgateway/local-rate-limit/suite.go, test/kubernetes/e2e/features/watch_namespace_selector/suite.go, test/kubernetes/e2e/tests/base/base_suite.go
Removed the non-functional / commented out upgrade code in the base testing suite to make the code more readable. (We can always add it back later if needed)
Related to https://github.com/kgateway-dev/kgateway/issues/10609
/kind cleanup
```release-note
NONE
```
=> e2e: Remove the upgrade-related code from the base suite

api/v1alpha1/traffic_policy_types.go, install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
Rejects invalid fillInterval values.
Based on:
https://github.com/envoyproxy/envoy/blob/e15295f2319133a0fd4b1df0ca94868fd378a9bb/source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc#L104
Resolves #11560
```
/kind cleanup
```
```release-note
NONE
```
=> api/rate-limit: reject invalid fillInterval value

test/kubernetes/e2e/features/routereplacement/suite.go, test/kubernetes/e2e/features/routereplacement/testdata/gateway-wide-invalid-policy.yaml, test/kubernetes/e2e/features/routereplacement/testdata/listener-merge-blast-radius.yaml, test/kubernetes/e2e/features/routereplacement/testdata/listener-specific-invalid-policy.yaml, test/kubernetes/e2e/features/routereplacement/types.go
Follow-up to the #12199 PR, which updated the route translator to handle invalid policy attached listener-and-gateway-wide.
This commit introduces several new functional tests to validate the new behavior and compliment existing route-level coverage in the route replacement e2e suite.
Partially fixes #11937.
/kind cleanup
```release-note
NONE
```
=> e2e: Extend route replacement policy tests

internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
Fix a flake caused by waiting for the secrets collection in the wrong place 🤦‍♂️ 
/kind flake
```release-note
NONE
```
=> agentgateway: wait for secrets sync in translator tests before building adp resources.

internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/mcp-backend-selector.yaml, internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/multipool-inline-auth.yaml, internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/multipool-priority-levels.yaml, internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/multipool-secret-auth.yaml, internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/ai/route-level-bearer.yaml, internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/ai/route-level.yaml, internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/rbac/mcp-rbac.yaml, internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/ai/route-level-bearer.yaml, internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/ai/route-level.yaml, internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/extproc-full-config.yaml, internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/rate-limit-full-config.yaml, internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/extproc-full-config.yaml, internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/rate-limit-full-config.yaml, test/translator/crd.go, test/translator/file_loader.go
- Fixes defaulting so that fields with omitempty are not dropped while applying the defaults.
- Errors on unknown fields in the input.
- Uses structurual pruning similar to k8s API server flow.
- Removes workaround for rate-limit's failOpen.
- Fixes agentgateway tests to use correct field names, indentation, and removes unsupported fields.
```
/kind cleanup
```
```release-note
NONE
```
Resolves #12264
=> test/translator: fix defaulting and detect unknown fields

Makefile
The manifests being deployed in the gie-crds target do not rely on the Gateway API CRDs. Additionally, having the gw-api-crds as a prerequisite breaks deploying a dev environment with the `CONFORMANCE_CHANNEL="standard"` Gateway API channel locally.
/kind cleanup
```release-note
NONE
```
=> Makefile: Remove prerequisite from the gie-crds target

Makefile
Fixes #11485. Refactors the conformance suite reporting to ensure we report
the correct conformance profiles that the default gateway class supports. This
was previously a gap in reporting where we supported TLS/GRPC profiles, but
the generated report didn't reflect that.
Note: I attempted to shadow the Makefile variables related to the agw-conformance,
but there's some skew between what the ingress & agw classes support right now.
As a result, I kept these profiles distinct for now.
Partially related to #12258, but we need to supply the -supported-features CLI
flag until we migrate to the 1.4 conformance suite implementation. Follow-up work
may implement this feature before 1.4 is adopted and we may need to maintain two
sets of lists in the interim.
See the following on the new …
=> Makefile: Refactor conformance reporting

api/applyconfiguration/api/v1alpha1/proxydeployment.go, api/applyconfiguration/internal/internal.go, api/v1alpha1/gateway_parameters_types.go, api/v1alpha1/zz_generated.deepcopy.go, hack/generate.sh, hack/helm/dev.yaml, install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml, install/helm/kgateway/templates/deployment.yaml, install/helm/kgateway/values.yaml, internal/kgateway/deployer/gateway_parameters.go, internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml, internal/kgateway/helm/kgateway/values.yaml, pkg/deployer/merge.go, pkg/deployer/values.go, pkg/generated/openapi/zz_generated.openapi.go, test/kubernetes/e2e/features/deployer/suite.go, test/kubernetes/e2e/features/deployer/testdata/gateway-with-parameters.yaml, test/kubernetes/e2e/tests/api_validation_test.go
Allows for modifying controller and Envoy rollout strategies, which gives flexibility for faster rollouts (see 'maxSurge') and rollouts that consume fewer resources (saving the cluster the time and expense of adding new Karpenter nodes, e.g., with 'Recreate'). See https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy for more information, including the harm to availability of modifying the Kubernetes defaults.
Test plan for control plane changes:
One e2e test uses strategy 'Recreate' but I didn't verify that the Deployment respects it. It simply does not crash.
Manually I did this with various values in `hack/helm/dev.yaml` to exercise Recreate and RollingUpdate:
- delete all kind clusters
- `make kind-create package-kgateway-charts deploy-kgateway-chart`
- …
=> Allows for specifying rollout strategies

.github/workflows/pr-kubernetes-tests.yaml, test/kubernetes/e2e/features/routereplacement/suite.go, test/kubernetes/e2e/features/routereplacement/testdata/invalid-matcher.yaml, test/kubernetes/e2e/features/routereplacement/testdata/invalid-route-rule-filter.yaml, test/kubernetes/e2e/features/routereplacement/testdata/route-attached-invalid-policy.yaml, test/kubernetes/e2e/features/routereplacement/types.go, test/kubernetes/e2e/tests/kgateway_tests.go, test/kubernetes/e2e/tests/route_replacement_test.go, test/kubernetes/e2e/tests/route_replacement_tests.go
Refactor route replacement e2e tests from nested TestKgateway suite to standalone TestRouteReplacement suite with strict mode enabled by default via helm values. This eliminates the complex runtime deployment patching logic that was previously used to switch between standard and strict modes during test execution.
All standard mode testing has been removed to focus exclusively on strict mode behavior. Additionally, test naming has been updated to remove mode-specific language and better reflect the actual attachment patterns being tested.
This refactoring provides proper test isolation with correct configuration from the start, improves test reliability by eliminating deployment restarts during execution, and simplifies the test logic by removing mode management complexity.
The …
=> e2e: Refactor route replacement tests to standalone suite

internal/kgateway/translator/irtranslator/backend_test.go, internal/kgateway/translator/irtranslator/fc_test.go, internal/kgateway/translator/irtranslator/route_test.go
A light refactor for the backend_test.go to remove any gomega-based assertions in favor of testify.
This was the only unit test in the irtranslator directory that imported any gomega/ginkgo dependencies.
Additionally, several unrelated changes that fix import grouping if we ever adopted the gci linter for
this repository.
Related to #11766 while implementing it locally.
/kind cleanup
```release-note
NONE
```
=> irtranslator: Remove gomega assertions from unit tests

.github/workflows/stalebot.yaml
Update the stalebot configuration to include PRs as well:
- Mark PRs stale after 30 days of inactivity
- Close stale PRs after 5 additional days
- Use separate job to avoid affecting existing issue stalebot
- Maintain same exemption system with 'no stalebot' label
/kind cleanup
```release-note
NONE
```
=> .github/workflows: Add stalebot for open PRs

examples/plugin/main.go, internal/kgateway/extensions2/plugins/backend/ai/ai_resources.go, internal/kgateway/extensions2/plugins/backend/plugin.go, internal/kgateway/extensions2/plugins/directresponse/direct_response_plugin.go, internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go, internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go, internal/kgateway/extensions2/plugins/sandwich/plugin.go, internal/kgateway/extensions2/plugins/trafficpolicy/auto_host_rewrite_test.go, internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy_test.go, internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go, internal/kgateway/extensions2/plugins/trafficpolicy/validate.go, internal/kgateway/krtcollections/builtin.go, internal/kgateway/translator/irtranslator/fc.go, internal/kgateway/translator/irtranslator/fc_test.go, internal/kgateway/translator/irtranslator/gateway.go, internal/kgateway/translator/irtranslator/route.go, pkg/plugins/gwextbase/base.go, pkg/pluginsdk/ir/iface.go, pkg/pluginsdk/types.go
Fixes #12212. Removes the no longer needed context.Context parameter for methods that implement a proxy translation pass. This was previously needed for logging before we migrated away from contextutils in favor of the slog logging library we maintain in-tree.
/kind cleanup
```release-note
NONE
```
=> *: Remove ctx parameter from ProxyTranslationPass methods

internal/kgateway/controller/gw_controller.go, internal/kgateway/deployer/gateway_parameters.go, internal/kgateway/deployer/gateway_parameters_test.go, internal/kgateway/translator/gateway/gateway_translator_test.go, internal/kgateway/translator/gateway/testutils/inputs/validation/gateway-reserved-port.yaml, internal/kgateway/translator/gateway/testutils/inputs/validation/xlistenerset-reserved-port.yaml, internal/kgateway/translator/gateway/testutils/outputs/validation/gateway-reserved-port.yaml, internal/kgateway/translator/gateway/testutils/outputs/validation/xlistenerset-reserved-port.yaml, internal/kgateway/translator/listener/validation.go, internal/kgateway/validate/gateway.go, pkg/deployer/deployer_test.go, pkg/deployer/values_helpers.go, test/translator/test.go
Detects reserved port usage (currently only metrics port) on Listener/XListenerSet, report error status, and skip Gateway deployment.
```
/kind bug_fix
```
```release-note
NONE
```
Resolves #12196
=> gateway: detect reserved port usage and report status

internal/kgateway/extensions2/plugins/backendconfigpolicy/lb.go, internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go, internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin_test.go, internal/kgateway/extensions2/plugins/backendconfigpolicy/protocoloptions.go, internal/kgateway/extensions2/plugins/backendconfigpolicy/validate.go, internal/kgateway/extensions2/plugins/backendconfigpolicy/validate_test.go, internal/kgateway/extensions2/registry/registry.go, internal/kgateway/proxy_syncer/backends.go, internal/kgateway/proxy_syncer/perclient.go, internal/kgateway/proxy_syncer/proxy_syncer.go, internal/kgateway/translator/gateway/gateway_translator_test.go, internal/kgateway/translator/gateway/testutils/inputs/route-replacement/backendconfigpolicy/invalid-cipher-suites.yaml, internal/kgateway/translator/gateway/testutils/inputs/route-replacement/backendconfigpolicy/invalid-missing-secret.yaml, internal/kgateway/translator/gateway/testutils/inputs/route-replacement/backendconfigpolicy/invalid-outlier-detection-zero-interval.yaml, internal/kgateway/translator/gateway/testutils/inputs/route-replacement/backendconfigpolicy/invalid-tlsfiles-nonexistent.yaml, internal/kgateway/translator/gateway/testutils/outputs/route-replacement/standard/backendconfigpolicy/invalid-cipher-suites-out.yaml, internal/kgateway/translator/gateway/testutils/outputs/route-replacement/standard/backendconfigpolicy/invalid-missing-secret-out.yaml, internal/kgateway/translator/gateway/testutils/outputs/route-replacement/standard/backendconfigpolicy/invalid-outlier-detection-zero-interval-out.yaml, internal/kgateway/translator/gateway/testutils/outputs/route-replacement/standard/backendconfigpolicy/invalid-tlsfiles-nonexistent-out.yaml, internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/backendconfigpolicy/invalid-cipher-suites-out.yaml, internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/backendconfigpolicy/invalid-missing-secret-out.yaml, internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/backendconfigpolicy/invalid-outlier-detection-zero-interval-out.yaml, internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/backendconfigpolicy/invalid-tlsfiles-nonexistent-out.yaml, internal/kgateway/translator/irtranslator/backend.go, internal/kgateway/translator/irtranslator/backend_test.go, internal/kgateway/translator/translator.go, test/translator/test.go
Follow-up to the https://github.com/kgateway-dev/kgateway/pull/11939 PR that introduces RDS support to the
route config translation. This commit updates the backend
translator to additionally ensure the computed Envoy cluster
passes xDS validation when the controller is running in
strict mode.
This implies that envoy mode validate is being run twice during
a translation pass, and then per-IR event update for the
BackendConfigPolicy and TrafficPolicy plugins.
Implement xDS validation for the BackendConfigPolicy plugin to
act as a safety net between valid user configuration but invalid
xDS configuration that degrades the dataplane.
Note: While BackendTLSPolicy can contribute policy to the backend
being computed and that policy can lead to NACKs, then current
implementation needs more work …
=> translator: Implement CDS validation

internal/kgateway/validate/gateway.go
follow up to https://github.com/kgateway-dev/kgateway/pull/12382
We additionally reserve port 8082 (readiness) and 19000 (envoy admin). These are hardcoded in internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
/kind bug_fix
```release-note
NONE
```
=> complete set of reserved ports

Makefile
Fixes #12426. Confirmed locally that the ingress class is conformant for both the 1.3 and 1.4 versions of the GW API.
/kind cleanup
```release-note
NONE
```
=> Makefile: Enable several unsupported conformance tests

pkg/deployer/merge.go
pkg/deployer now exports more routines.
- DeepMergeImage
- DeepMergeSecurityContext
```release-note
pkg/deployer now exports DeepMergeImage and DeepMergeSecurityContext
```
=> pkg/deployer now exports more routines.

internal/kgateway/deployer/gateway_parameters.go, internal/kgateway/helm/kgateway/templates/_helpers.tpl, internal/kgateway/helm/kgateway/templates/gateway/agent-gateway-deployment.yaml, internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml, internal/kgateway/wellknown/controller.go, pkg/deployer/values.go, test/deployer/testdata/agentgateway-out.yaml, test/deployer/testdata/base-gateway-out.yaml, test/deployer/testdata/omit-default-security-context-out.yaml
This was added upstream. The primary purpose is to be able to identify all pods owned by kgateway for things like monitoring etc
```release-note
The new `gateway.networking.k8s.io/gateway-class-name` label is added to all resources created by Kgateway to represent which `GatewayClass` was responsible for creating the resource.
```
=> deployer: add new standard `gateway-class-name` label

api/applyconfiguration/internal/internal.go, api/v1alpha1/ai_backend.go, api/v1alpha1/zz_generated.deepcopy.go, install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml, internal/kgateway/agentgatewaysyncer/backend/translate.go, internal/kgateway/agentgatewaysyncer/backend/translate_test.go, internal/kgateway/extensions2/plugins/backend/ai/ai_backend.go, pkg/generated/openapi/zz_generated.openapi.go
Makes the Bedrock `model` field optional in the Backend CRD, allowing users to specify any Bedrock model in their requests rather than being forced to configure a single model at the Backend level.
This aligns the kgateway API with the agentgateway data plane behavior, which already supports optional model override (uses backend model if set, otherwise uses the model from the request).
**Before:**
```yaml
spec:
type: AI
ai:
llm:
bedrock:
model: "anthropic.claude-3-5-sonnet-20241022-v2:0"  # REQUIRED
region: us-east-1
```
**After:**
```yaml
spec:
type: AI
ai:
llm:
bedrock:
region: us-east-1
```
This matches the behavior of OpenAI and Anthropic providers, which also have optional `model` fields.
/kind bug_fix
```release-note
Make Bedrock model field optional to allow user-specified models, …
```
=> Make Bedrock model field optional to allow user-specified models

internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
This fixes an issue where the volumemounts were rendered in the proxy deployment when no volume mounts are defined
Select one or more of the following by including the corresponding slash-command:
```
/kind bug_fix
```
```release-note
Fix a bug where the volumeMounts were rendered in the proxy deployment when no volume mounts are defined
```
=> fix: always rendering volumemounts in proxy-deployment

pkg/deployer/merge.go, pkg/deployer/merge_test.go
Fixes an issue where a dst && src have different probe actions, resulting in an invalid podTemplate with multiple probe actions
```
spec.template.spec.containers[0].readinessProbe.httpGet: Forbidden: may not specify more than 1 handler type]
```
Select one or more of the following by including the corresponding slash-command:
```
/kind bug_fix
```
```release-note
Fixes a bug where a user-defined GatewayParameters has a different probe from the default one, resulting in an invalid podTemplate with multiple probe actions for the given probe
```
=> fix: Merge probeHandler to ensure only one action is returned

Makefile, pkg/validator/validator.go, pkg/validator/validator_test.go
- bumped envoy gloo to v1.35.2-patch4. This is an update to the transformation filter in envoy-gloo, no upstream envoy change is brought in. 
- envoy-gloo release note: https://github.com/solo-io/envoy-gloo/releases/tag/v1.35.2-patch4
/kind cleanup
```release-note
NONE
```
=> bump envoy-gloo to v1.35.2-patch4

pkg/utils/kubeutils/kubectl/cli.go, pkg/utils/kubeutils/kubectl/logs_options.go, pkg/utils/kubeutils/kubectl/logs_options_test.go
I am using the kubeutils as a library in another repo, and would like to be able to pass options (specifically `since-time`) to  GetContainerLogs.
While implementing the changes, added a few more options that may be useful in a testing context:
* -c/--container
* --since
* --since-time
* --tail
Select one or more of the following by including the corresponding slash-command:
```
/kind cleanup
```
```release-note
NONE
```
=> Add options to GetContainerLogs

test/kubernetes/e2e/tests/agent_gateway_tests.go
A concise explanation of the change. You may include:
- **Related issues:** https://github.com/kgateway-dev/kgateway/issues/12537
```
/kind flake
```
```release-note
NONE
```
=> agentgateway: disable a2a tests run in the suite due flakiness
