- docs/introduction/introduction.md
The existing internal links were broken, at least in GitHub preview :link:
> Fix introduction outline links

- internal/control-plane/install/install_plugins.go
- pkg/plugins/azure/plugin.go
- pkg/plugins/azure/plugin_test.go
- test/local_e2e/azure_functions_test.go
1. Populate the Azure Function App hostname in the upstream metadata
rather than in the function metadata of each function.
2. Update the Envoy filter submodule to a commit that supports this
modification.
> plugins/azure: refactor metadata structure and add local_e2e test

- Gopkg.lock
- Makefile
1. 1. add debug build to make: now you can do `make debug-build`
2. fix go dep lock file with new dep
> add debug build to make; fix lockfile

- internal/function-discovery/updater/swagger/get_swagger_funcs.go
@yuval a while ago we changed function discovery to generate templates
that use default values if the user doesn't provide them
(so we don't get that "JSON element not found" error
from the transformation filter)
> set default values for path and header templates in swagger fn discovery

- pkg/plugins/kubernetes/endpoint_controller.go
> kube eds: fall back to service port if target port is not specified

- .circleci/Dockerfile
- Makefile
- cmd/control-plane/main.go
- internal/control-plane/configwatcher/config_watcher.go
- internal/control-plane/endpointswatcher/endpoints_watcher_test.go
- internal/control-plane/endpointswatcher/endpointswatcher_suite_test.go
- internal/control-plane/eventloop/eventloop.go
- internal/control-plane/snapshot/cache.go
- internal/control-plane/snapshot/cache_test.go
- internal/control-plane/snapshot/emitter.go
- internal/control-plane/snapshot/emitter_test.go
- internal/control-plane/snapshot/snapshot_suite_test.go
- internal/control-plane/translator/translator.go
- internal/control-plane/translator/translator_test.go
- internal/upstream-discovery/kube/kube_upstream_controller.go
- test/kube_e2e/containers/event-emitter/main.go
- test/kube_e2e/containers/upstream-for-events/main.go
isolate the logic that handles "gloo snapshots" (all of the inputs from the different watchers, hashing, caching, etc) from the core event loop.
change `translator.Inputs` -> `snapshot.Cache`
based on #79
> eventloop: gloo snapshots

- docs/tutorials/openfaas.md
This commit is updating typo in the OpenFaaS guide
Signed-off-by: Alex Ellis <alexellis2@gmail.com>
> Update typo in OpenFaaS guide

- pkg/storage/consul/client_template.go.tmpl
- pkg/storage/consul/roles.go
- pkg/storage/consul/upstreams.go
- pkg/storage/consul/virtual_services.go
- pkg/storage/file/roles.go
- pkg/storage/file/upstreams.go
- pkg/storage/file/virtual_services.go
generated code wasn't committed
> Storage change

- internal/control-plane/snapshot/cache.go
we were ignoring roles in the snapshot cache; i.e. if roles changed we ignored them. no more!
> eventloop: don't ignore role in snapshot hash

- cmd/kube-ingress-controller/main.go
- pkg/bootstrap/artifactstorage/bootstrap.go
- pkg/bootstrap/configstorage/bootstrap.go
- pkg/bootstrap/secretstorage/bootstrap.go
- pkg/function-discovery/eventloop/event_loop.go
- pkg/function-discovery/updater/fission/imported/client.go
- pkg/plugins/kubernetes/kube_discovery.go
- pkg/storage/crd/crd_storage_client.go
- pkg/upstream-discovery/start.go
- pkg/utils/kube/config.go
- pkg/utils/kube/config_test.go
- pkg/utils/kube/kube_suite_test.go
This change respects the usage of the environment variable KUBECONFIG
when loading the kubeconfig. It also supports the default behavior of
setting multiple kubeconfig paths inside the KUBECONFIG variable.
Signed-off-by: Ken Fukuyama <kenfdev@gmail.com>
Related issue: https://github.com/solo-io/glooctl/issues/53
---
**This change hasn't been tested.**
I wanted to test what I have changed and also test this with `glooctl` but had no luck so far in building on my Mac. I wonder if this can be tested on a Mac in the first place (as documented, maybe this only works on Linux?).
I've tried following https://gloo.solo.io/dev/README/ but this didn't work either.
I'm more than happy to be able to contribute, but am stuck for now.
> Support the use of the env-var KUBECONFIG

- docs/introduction/introduction.md
Fix a broken link and a minor grammar mistake in `introduction.md`.
> docs: fix broken link in introduction.md

- pkg/control-plane/endpointswatcher/endpoints_watcher.go
- pkg/control-plane/endpointswatcher/endpoints_watcher_test.go
- pkg/control-plane/eventloop/eventloop.go
- pkg/control-plane/snapshot/emitter_test.go
- pkg/control-plane/translator/function_processor_plugin.go
- pkg/control-plane/translator/route_init_plugin.go
- pkg/control-plane/translator/translator.go
- pkg/coreplugins/matcher/plugin.go
- pkg/coreplugins/routing/plugin.go
- pkg/coreplugins/static/plugin.go
- pkg/plugins/aws/plugin.go
- pkg/plugins/azure/plugin.go
- pkg/plugins/cloudfoundry/plugin.go
- pkg/plugins/connect/plugin.go
- pkg/plugins/consul/plugin.go
- pkg/plugins/fake/plugin.go
- pkg/plugins/google/plugin.go
- pkg/plugins/grpc/plugin.go
- pkg/plugins/interface.go
- pkg/plugins/kubernetes/plugin.go
- pkg/plugins/nats/plugin.go
- pkg/plugins/rest/plugin.go
change the plugin interface to use Init() instead of GetDependencies
this allows us to not pass Opts to the endpoitndiscovery method
> init-for-plugins

- docs/tutorials/refactor_monolith.md
Fix instructions to start minikube with RBAC. The currently used option name causes `minikube start` to time out. See [here](https://github.com/kubernetes/website/commit/cb8aae1b0dbeb6a75e7f735dceb4e762232ffa45/) for more info.
> Update "Refactoring monolith" tutorial

- projects/gloo/cli/pkg/cmd/create/upstream.go
- projects/gloo/cli/pkg/flagutils/upstream.go
fixes #205 
`LocalFlags` don't get propagated here, need to use `PersistentFlags`
> fix persistentflags issue on cli upstream create

- Makefile
- hack/recompile.sh
- install/kube.yaml
- pkg/cliutil/input.go
- projects/envoyinit/cmd/main.go
- projects/gloo/cli/pkg/cmd/gateway/logs.go
a few fixes for the CLI as well as disabling hot restarts on envoy, which otherwise causes a conflict when both our envoy and their envoy create the shared memory file for hot restarts
> Istio fixes

- pkg/utils/proto/any.go
- pkg/utils/proto/any_test.go
allow the user to know if GetMessage didn't find a value, or had a different error
change the name of GetMessage to UnmarshalAnyFromMap
make it use an output param to make usage less verbose.
> any GetMessage error handling

- Gopkg.lock
- Gopkg.toml
a breaking change for `make glooctl` was introduced to master
this pr contains a fix to `Gopkg.toml` which requires version `aed107e26498b88eb641f3e9a794dd1ddeda6a10` of `go-utils`
> update dep with new go-utils

- projects/gloo/cli/pkg/cmd/install/kube.go
Fixes:
Error: creating image pull seret: creating installation namespace: No Auth Provider found for name "gcp"
When using gcp
> Fix issue of not being able to login to gcp

- Gopkg.lock
- Gopkg.toml
- projects/gloo/cli/pkg/cmd/create/root.go
- projects/gloo/cli/pkg/cmd/create/secret/root.go
- projects/gloo/cli/pkg/cmd/create/upstream.go
- projects/gloo/cli/pkg/cmd/create/virtualservice.go
- projects/gloo/cli/pkg/cmd/del/proxy.go
- projects/gloo/cli/pkg/cmd/del/root.go
- projects/gloo/cli/pkg/cmd/del/upstream.go
- projects/gloo/cli/pkg/cmd/del/virtualservice.go
- projects/gloo/cli/pkg/cmd/gateway/root.go
- projects/gloo/cli/pkg/cmd/get/proxy.go
- projects/gloo/cli/pkg/cmd/get/root.go
- projects/gloo/cli/pkg/cmd/get/upstream.go
- projects/gloo/cli/pkg/cmd/get/virtualservice.go
- projects/gloo/cli/pkg/cmd/install/root.go
- projects/gloo/cli/pkg/cmd/upgrade/cmd.go
- projects/gloo/cli/pkg/constants/commands.go
created a file of "const" names for all of the commands.
This is important for a couple of reasons:
1) these values are re-used across this repo and it is important to maintain uniformity
2) these values can be used to swap commands in and out using the new options funcs, and go-utils
> Const commands

- pkg/utils/setuputils/main_setup.go
- projects/discovery/pkg/fds/setup/setup.go
- projects/discovery/pkg/uds/setup/setup.go
- projects/gateway/pkg/setup/setup.go
- projects/gloo/pkg/setup/setup.go
- projects/ingress/pkg/setup/setup.go
this changes the util method `setuputils.Main` to accept a single `Opts` parameter. Opts parameter exposes a flag `ExitOnError` telling the setup method to `exit 1` if the setup function fails
the current behavior (probably not desirable) is the error wil be logged but the pod will not crash/be restarted (making it harder to detect setup failures)
> exit on error if setup fails

- cloudbuild.yaml
v0.6.7 release build failed because the release target pushes yaml artifacts that are produced by the manifest target.
> Manifest needs to happen before release target

- test/e2e/happypath_test.go
Currently this test occasionally flakes out (see #264). Trying to see if the
frequency of flakes is reduced by giving discovery longer to work.
> Increasing the timeout for happy path test

- projects/gloo/cli/pkg/argsutils/metadata.go
- projects/gloo/cli/pkg/cmd/add/add_suite_test.go
- projects/gloo/cli/pkg/cmd/add/route.go
- projects/gloo/cli/pkg/cmd/add/route_test.go
- projects/gloo/cli/pkg/cmd/create/create_suite_test.go
- projects/gloo/cli/pkg/cmd/create/upstream_test.go
- projects/gloo/cli/pkg/helpers/clients.go
- projects/gloo/cli/pkg/testutils/utils.go
need to move Glooctl helper function to a proper place
As part of the cli for ext auth I created a way to test the cli in unit tests (as per @rickducott's idea)
I did a sanity and added a static upstream according to here:
https://gloo.solo.io/getting_started/kubernetes/external_api_routing/
but the test seems to fail. @ilackarms can you take a loog?
> initial tests for glooctl

- docs/v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/grpc/grpc.proto.sk.md
- projects/gloo/api/v1/plugins/grpc/grpc.proto
- projects/gloo/pkg/api/v1/plugins/grpc/grpc.pb.go
- projects/gloo/pkg/plugins/grpc/plugin.go
- projects/gloo/pkg/plugins/grpc/plugin_test.go
The purpose of this change is to allow marking upstreams as grpc so that envoy is configured correctly.
i think this might be needed for exauth purposes.
> allow empty grpc service spec

- projects/gloo/cli/pkg/cmd/upgrade/cmd.go
Unfortunately this has no tests, we may end up wanting to delete the command. But this is better than the status quo, in which the upgrade command would just error out whenever a release was building
> Fix upgrade command

- Gopkg.lock
- Gopkg.toml
- pkg/cliutil/nsselect/setup.go
- pkg/utils/setuputils/main_setup.go
- pkg/utils/setuputils/setup_syncer.go
- projects/clusteringress/pkg/api/v1/translator_snapshot_emitter_test.go
- projects/gateway/pkg/api/v1/api_snapshot_emitter_test.go
- projects/gloo/cli/pkg/cmd/install/util.go
- projects/gloo/cli/pkg/helpers/clients.go
- projects/gloo/pkg/api/v1/api_snapshot_emitter_test.go
- projects/gloo/pkg/api/v1/discovery_snapshot_emitter_test.go
- projects/gloo/pkg/api/v1/setup_snapshot_emitter_test.go
- projects/ingress/pkg/api/v1/translator_snapshot_emitter_test.go
- test/kube2e/gateway_test.go
currently kubecache is shared across "soft" restarts (when settings crd gets updated)
this PR updates with new solo kit where we have replaced 
`context.TODO()` in the KubeCache with a constructor that accepts a context.
when the context is cancelled, the goroutines running for the cache will be terminated.
we use this feature to create a new kubecache on a new SetupSync, where the previous 
cache will have been cancelled by the Setup Event Loop
> fix panic on new SetupSync

- projects/gloo/cli/pkg/cmd/gateway/gateway_suite_test.go
- projects/gloo/cli/pkg/cmd/gateway/url.go
- projects/gloo/cli/pkg/cmd/gateway/url_test.go
- projects/gloo/cli/pkg/testutils/utils.go
fixes `glooctl proxy url` command for the case when minikube is running in virtualbox with a NAT network
currently the command returns the NAT ip which is internal / not accessible from the host computer
> Fix url for virtualboxminikube

- projects/discovery/pkg/fds/discoveries/grpc/grpc.go
we were never closing client connection in grpc, so every attempt to DiscoverFunctionsOnce was leaving open grpc connections
saw a very large number of goroutines caused by:
number of upstreams x exponential backoff x number of syncs
> ensure grpc client connection is closed in func discovery

- docs/operator_guide/understanding_gloo_configuration.md
In particular, it explains the relationship between Gloo resources and Kubernetes CRDs.
I found it hard to abstract away from Kubernetes as storage and still come up with something that wasn't too generic (and with examples). When we have a stand-alone version of Gloo we'll have more material to flesh this out.
Please be brutally honest in your feedback.
> Add docs page explaining Gloo resources storage

- projects/gloo/pkg/bootstrap/utils.go
- projects/gloo/pkg/syncer/setup_syncer.go
- projects/ingress/pkg/setup/setup_syncer.go
solo kit v0.2.25 introduced a breaking change to the configmap and secret client factories.
this change fixes them by initializing a `KubeCoreCache` in the `utils.SecretFactoryForSettings` and `utils.ConfigMapFactoryForSettings` helper functions in the same way that rest configs are initialized and then shared there.
tested by running `hyperkube` without any init error
> fix constructors for artifact and secret client constructors

- projects/gloo/cli/pkg/helpers/clients.go
fixes a regression in the cli caused by a bump of the version of solo-kit we're using
> fix constructor for secret client in kube

- pkg/cliutil/cliutil_suite_test.go
- pkg/cliutil/input.go
- pkg/cliutil/input_test.go
it was an unused function so we never detected this issue
> fix GetBoolInput in cliutils

- projects/gloo/pkg/utils/ssl.go
- projects/gloo/pkg/utils/ssl_test.go
it seems that setting alpn on the upstream is not a good idea if the upstream doesnt support it.
> ALPN only for listeners

- changelog/v0.8.4/3.yaml
- projects/ingress/pkg/api/ingress/resource_client.go
- projects/ingress/pkg/api/service/resource_client.go
An empty namespace was being defaulted to `default` in the ingress resource client list & watch functions.
Fixes #476
> Fix ingress namespace bug

- changelog/v0.10.2/fix-artifact-version.yaml
- ci/upload_github_release_assets.go
- cloudbuild.yaml
Currently the CLI is built by the regression testing step, which does not set the version.
> Make sure version is set when building CLI

- Gopkg.toml
- Makefile
- changelog/v0.12.1/generalize-install-for-glooe.yaml
- changelog/v0.13.0/generalize-install-for-glooe.yaml
- cloudbuild.yaml
- install/helm/gloo/templates/0-namespace.yaml
- pkg/cliutil/install/chart.go
- pkg/cliutil/install/filters.go
- pkg/cliutil/install/kubernetes.go
- projects/gloo/cli/pkg/cmd/install/install_suite_test.go
- projects/gloo/cli/pkg/cmd/install/install_test.go
- projects/gloo/cli/pkg/cmd/install/installer.go
- projects/gloo/cli/pkg/cmd/install/installer_test.go
- projects/gloo/cli/pkg/cmd/install/uninstall.go
- projects/gloo/cli/pkg/cmd/install/uninstall_test.go
- projects/gloo/cli/pkg/cmd/install/util.go
A few changes that enable more general installs (for now just targeting gloo + glooe), including:
- Customizing allowed CRDs
- Customizing types allowed during pre-install and install phases
- Customizing expected labels
- Supporting final post-filtering logic (i.e. for Glooe to filter out PVCs that already exist)
> Generalize

- changelog/v0.13.16/fix-knative-flake.yaml
- install/helm/gloo/templates/17-knative-no-istio-0.5.1.yaml
fixes the failure to teardown knative namespace after installation
BOT NOTES: 
resolves https://github.com/solo-io/gloo/685
> fix missing label

- changelog/v0.13.16/uds_grpc.yaml
- hack/utils/xdsclient/main.go
- projects/gloo/pkg/plugins/consul/plugin.go
- projects/gloo/pkg/plugins/kubernetes/plugin.go
- projects/gloo/pkg/plugins/kubernetes/uds_convert.go
- projects/gloo/pkg/plugins/kubernetes/uds_convert_test.go
- projects/gloo/pkg/plugins/static/plugin.go
- projects/gloo/pkg/translator/clusters.go
- projects/gloo/pkg/translator/translator_test.go
- projects/gloo/pkg/xds/utils.go
To solves #688, we allow now to upstream discovery to know in advance if the upstream is a grpc upstream.
This is done by reading the port name or an annotation on the service.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/688
> UDS discovery for GRPC services

- changelog/v0.13.18/fix-settings-helm-template.yaml
- install/helm/gloo/templates/18-settings.yaml
Fix bug that caused gloo to always watch all namespace regardless of the value set on thr settings CRD.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/694
> Fix settings CRD template

- changelog/v0.13.26/udnerscore.yaml
- projects/gloo/pkg/translator/utils.go
otherwise promethues stats are not parsed correctly by envoy.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/712
> use underscore instead of dot for cluster name.

- changelog/v0.13.30/disable-fds.yaml
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/5-discovery-deployment.yaml
- projects/discovery/cmd/main.go
Function discovery can create noise on the network as it queries various endpoints. 
This adds an opt-in option to disable it if it is not in use.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/729
> allow disabling function discovery

- changelog/v0.13.30/keepalive-all.yaml
- install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
- install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
#708 added tcp keepalive for gateway, this adds it also to knative and ingress.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/728
> Keepalive for all

- changelog/v0.13.31/allow_identical_sslconfig.yaml
- changelog/v0.13.32/allow_identical_sslconfig.yaml
- projects/gateway/pkg/translator/translator.go
- projects/gateway/pkg/translator/translator_test.go
This addresses one of the issues raised in https://github.com/solo-io/gloo/issues/731, that virtual services with non-conflicting SslConfigs for the same virtual host are not allowed to be merged.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/731
> Allow routes from different virtual services with same SslConfig.

- changelog/v0.17.1/sanitize-uds-upstreams.yaml
- projects/gloo/pkg/plugins/kubernetes/uds_convert.go
- projects/gloo/pkg/plugins/kubernetes/uds_convert_test.go
more aggressively sanitize uds upstream names provided to the kubernetes API; remove duplicated logic
Will open a separate issue regarding concerns in the current implementation of `SanitizeNameV2`:
1. possibly-duplicate names after sanitization
2. frailty w.r.t. future naming regex changes in future versions of kubernetes.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/289
> Sanitize uds upstream names

- Gopkg.lock
- changelog/v0.17.2/helm-naming-convention.yaml
- install/helm/gloo/generate.go
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
- install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
- install/helm/gloo/templates/3-gloo-deployment.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
- install/helm/gloo/values-gateway-template.yaml
- install/test/helm_suite_test.go
- install/test/helm_test.go
- projects/gloo/cli/pkg/cmd/gateway/root.go
- projects/gloo/pkg/syncer/translator_syncer_test.go
- test/e2e/gateway_test.go
- test/e2e/happypath_test.go
- test/kube2e/gateway/gateway_test.go
- test/kube2e/gateway/robustness_test.go
Updates our template gateway proxy helm values file to use proper helm naming conventions, so once `generate.go` renders our values files then they will match helm naming conventions as well.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/827
> Fix helm naming convention

- Gopkg.lock
- Gopkg.toml
- changelog/v0.17.4/fix-for-kubernetes-1-10.yaml
Bump solo-kit to get CRD registration fix from https://github.com/solo-io/solo-kit/pull/221
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/828
> bump solo-kit to fix runtime CRD registration for Kubernetes 1.10

- changelog/v0.17.4/gateway-proxy-kebab-case.yaml
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
- install/helm/gloo/values-gateway-template.yaml
- install/test/helm_suite_test.go
- install/test/helm_test.go
Moves our `gatewayProxies` yaml back to using a map for easy overrides, but this time we leverage the `kebabcase` sprig function to abide by proper helm naming conventions without changing the name of our kube resources.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/857
> Move to kebab case so we can keep gateway proxies as a map

- changelog/v0.17.6/fix-ec2-default-port.yaml
- projects/gloo/cli/pkg/printers/upstream.go
- projects/gloo/pkg/plugins/aws/ec2/credential_batched_instances.go
- projects/gloo/pkg/plugins/aws/ec2/ec2_test.go
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/873
resolves https://github.com/solo-io/gloo/issues/874
> fix default port for EC2 upstream

- changelog/v0.18.0/summary.md
Add changelog summary for v0.18.0, in light of https://github.com/solo-io/gloo/pull/808 and https://github.com/solo-io/solo-docs/pull/401
(cherry picked from commit 84def3163eac06efaa650885e62885f33d6517e0)
> Take advantage of this seldom-used changelog feature

- changelog/v0.18.12/gloo-debug-log-fail-handler.yaml
- install/test/helm_suite_test.go
- pkg/cliutil/logger_test_util.go
- projects/gloo/cli/pkg/cmd/install/install_suite_test.go
- projects/gloo/pkg/plugins/aws/ec2/ec2_suite_test.go
- projects/gloo/pkg/plugins/shadowing/shadowing_suite_test.go
- test/consulvaulte2e/e2e_suite_test.go
- test/e2e/e2e_suite_test.go
- test/helpers/glooctl_debug_dump.go
- test/kube2e/gateway/gateway_suite_test.go
- test/kube2e/ingress/ingress_suite_test.go
- test/kube2e/knative/knative_suite_test.go
Allows test code to register the gloo debug log print fail handler easily using:
```golang
cliutil.RegisterGlooDebugLogPrintHandlerAndClearLogs()
```
Which will generally be preferable to the `cliutil.RegisterGlooDebugLogPrintHandler()` invocation.
This will be particularly helpful in regression/e2e tests that run against live k8s clusters, and useful `kubectl` error messages have been swallowed by `glooctl` debug logging.
Tested against gloo-ee with a branch revision, looks good 👍
> Allow gloo tests to print debug logs during pre fail handling

- Makefile
- changelog/v0.18.14/knative-ingress.yaml
- docs/cli/glooctl_install_knative.md
- install/helm/gloo/generate.go
- install/helm/gloo/values-knative-template.yaml
- projects/gloo/cli/pkg/cmd/install/knative.go
- projects/gloo/cli/pkg/cmd/install/knative_test.go
- projects/gloo/cli/pkg/cmd/install/knative_test_yaml.yaml
- projects/gloo/cli/pkg/cmd/options/options.go
- projects/gloo/cli/pkg/flagutils/install.go
- projects/ingress/pkg/setup/setup_syncer.go
- test/kube2e/knative/knative_test.go
default the knative install version to 0.8.0
also
- update the knative e2e test to run against 0.8.0
- set image pull policy to `Always` when building the helm chart for tests (with `make build-test-assets`)
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1006
> Knative install 0.8.0

- Gopkg.lock
- changelog/v0.18.38/use-secret-converter-in-glooctl.yaml
- projects/gloo/cli/pkg/helpers/clients.go
- projects/gloo/pkg/api/converters/kube/secretconverter.go
- projects/gloo/pkg/api/converters/kube/secretconverter_test.go
cc @ilackarms 
- Turns on secret converter in glooctl
- Additionally implements the gloo aws secret -> k8s aws secret logic, allowing us to flatten aws secret creds for mounting as env vars in pods
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1138
> Use secret converter in glooctl

- Gopkg.lock
- changelog/v0.18.41/uninstall-nonexistent-namespace.yaml
- projects/gloo/cli/pkg/cmd/install/uninstall.go
Assuming that these are all or nothing:
```GlooCrdNames = []string{
"gateways.gateway.solo.io.v2",
"proxies.gloo.solo.io",
"settings.gloo.solo.io",
"upstreams.gloo.solo.io",
"upstreamgroups.gloo.solo.io",
"virtualservices.gateway.solo.io",
"routetables.gateway.solo.io",
}
```
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/602
> Uninstall all nonexistent namespace

- changelog/v0.18.42/dynamic-user-id.yaml
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/1-gloo-deployment.yaml
- install/helm/gloo/templates/3-discovery-deployment.yaml
- install/helm/gloo/templates/5-gateway-deployment.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/values-gateway-template.yaml
Built the helm chart with setting `floatingUserId` to true, and installed into openshift. The pods were all running with dynamically-assigned user ids.
I also verified that the output of `helm template ......` does not contain any `runAsUser` settings when I turn on all of these `floatingUserId` options. AmEx's action to resolve this was to remove all those fields, so presumably this is the same effect as what they did manually.
```
~/go/src/github.com/solo-io/gloo > kubectl -n gloo-system get pods discovery-76d589d7cc-ssgwz gateway-v2-867f8fc88f-t2zqj gloo-d8dc8f9dc-rd7t5 -o json | jq '.items[].spec.containers[].securityContext.runAsUser'
1000160000
1000160000
1000160000
```
BOT NOTES: 
resolves https://github.com/solo-io/customers/issues/5
> Allow the cluster to dynamically assign user ids to containers

- changelog/v0.18.44/fix-ratelimit-translator-syncer.yaml
- projects/gloo/pkg/syncer/setup_syncer.go
only affects the newly added ratelimit config location (flattened on the settings object, outside of opaque extensions)
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1209
> Fix ratelimit (enterprise-only) translator syncer setup

- changelog/v0.18.44/ci-no-color-output.yaml
- cloudbuild.yaml
Currently the test steps of our CI builds output a lot of color codes:
```
Step #11 - "test": [1568747335] [1mPlugin Interface Suite[0m - 2/2 specs [32m•[0m[32m•[0m [32mSUCCESS![0m 1.648952ms PASS
Step #11 - "test": [1568747335] [1mAls Suite[0m - 6/6 specs [32m•[0m[32m•[0m[32m•[0m[32m•[0m[32m•[0m[32m•[0m [32mSUCCESS![0m 19.035596ms PASS
```
These are nice in a terminal that renders them, but in CI they make the output unreadable. Adding a `--noColor` flag to `ginkgo` should get rid of them.
> Remove hideous color codes from Ginkgo output

- changelog/v0.19.1/fix-pod-check.yaml
- projects/gloo/cli/pkg/cmd/check/root.go
glooctl pod check misses a bunch of the possible pod states. Fix that
BOT NOTES: 
resolves https://github.com/solo-io/solo-projects/issues/1121
> Make glooctl pod check more comprehensive

- changelog/v0.20.3/envoy-image-env-var.yaml
- test/services/envoy.go
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1311
> Fail early if the ENVOY_IMAGE_TAG env var is not set in end to end tests

- changelog/v0.20.3/bump-glooe-tag.yaml
- pkg/version/enterprise.go
This changes the default version of GlooE installed by the CLI to 0.20.0.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1272
> Bump default GlooE version to 0.20.1

- Gopkg.lock
- changelog/v0.20.3/fix-validation-test-flake.yaml
- install/helm/gloo/templates/1-gloo-deployment.yaml
- install/helm/gloo/templates/5-gateway-deployment.yaml
- install/test/helm_test.go
- projects/gateway/pkg/syncer/setup_syncer.go
- projects/gateway/pkg/validation/robust_client.go
- projects/gateway/pkg/validation/robust_client_test.go
- projects/gateway/pkg/validation/validator.go
- projects/gloo/pkg/translator/route_config.go
- test/kube2e/gateway/gateway_suite_test.go
- test/kube2e/gateway/gateway_test.go
* use blocking dial for grpc proxy validation server
* add readiness probe to gloo and gateway
* fix ch, add options for readiness probe
* use a client that retries the connection on an Unavailable grpc error
* use eventaully to handle test race with uds
* fmt
* subset mismatch converted to a warning
* Dep ensure & codegen
* fmt
* Merge branch 'fix-validation-test-flake' of github.com:solo-io/gloo into fix-validation-test-flake
* fix robust client retry logic
* fmt
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1322
> add readiness probe to gloo and gateway deployments (#1323)

- changelog/v0.20.6/fix-knative-manifest-parsing.yaml
- cloudbuild.yaml
- projects/gateway/pkg/validation/validator.go
- projects/gateway/pkg/validation/validator_test.go
2 fixes for validation:
- validator checks the hash of an updated object. if the hash has not changed (e.g. due to status update), the validator admits. **this would be improved if we used subresources for status**
- do not attempt to validate nil proxy (if no errors occurred but no listeners were created, proxy validation can panic)
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1369
resolves https://github.com/solo-io/gloo/issues/1368
> check hash in validator on update, skip validating nil proxy

- changelog/v0.20.7/process-custom-auth-configs.yaml
- projects/gloo/pkg/plugins/extauth/plugin.go
- projects/gloo/pkg/plugins/extauth/plugin_test.go
Process custom Ext Auth configuration on virtual hosts, routes, and weighted destinations. Plugin is still not active.
> Process custom auth configurations

- changelog/v0.20.3/sanitizer.yaml
- projects/gloo/pkg/syncer/envoy_translator_syncer.go
- projects/gloo/pkg/syncer/sanitizer/snapshot_sanitizer.go
- projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer.go
- projects/gloo/pkg/syncer/setup_syncer.go
- projects/gloo/pkg/syncer/translator_syncer.go
- projects/gloo/pkg/syncer/translator_syncer_test.go
i plan to add more "sanitizing" of xds snapshots to the gloo translator syncer.
currently, we have some sanitizing already going on: we remove all clusters from the snapshot who correspond to errored upstreams
this PR moves that behavior to an interface type we can extend
> Add sanitizer interface for sanitizing xds snapshot

- changelog/v0.20.7/bump-glooe-tag.yaml
- pkg/version/enterprise.go
The default version of GlooE installed by the CLI is now 0.20.3
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1386
> Bump default GlooE version installed by the CLI to 0.20.4

- Gopkg.lock
- Gopkg.toml
- changelog/v0.21.0/new-usage-client.yaml
- pkg/utils/setuputils/main_setup.go
- pkg/utils/usage/default_usage_reader.go
- pkg/utils/usage/instance_metadata.go
- projects/gloo/cli/cmd/main.go
- projects/gloo/pkg/setup/setup.go
- projects/metrics/pkg/metricsservice/metrics_handler.go
- projects/metrics/pkg/metricsservice/metrics_service_test.go
- projects/metrics/pkg/metricsservice/mocks/mock_storage.go
- projects/metrics/pkg/metricsservice/storage_client.go
- test/consulvaulte2e/consul_vault_test.go
The service is done being stood up in prod. Running this in minikube can successfully report usage to prod over SSL.
BOT NOTES: 
resolves https://github.com/solo-io/solo-projects/issues/1199
> Convert to new usage client

- changelog/v0.21.0/bump-glooe-tag.yaml
- pkg/version/enterprise.go
port of https://github.com/solo-io/gloo/pull/1387 to `feature-rc1`
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1386
> Bump default GlooE version installed by the CLI to 0.20.4 (#1387)

- Gopkg.lock
- Gopkg.toml
- changelog/v0.20.9/bump-go-utils.yaml
- projects/gateway/pkg/conversion/gateway.go
- projects/gateway/pkg/conversion/gateway_test.go
- projects/gateway/pkg/translator/translator_test.go
- projects/gloo/pkg/syncer/translator_syncer_test.go
- test/consulvaulte2e/consul_vault_test.go
- test/e2e/consul_test.go
- test/e2e/gateway_test.go
- test/e2e/happypath_test.go
- test/kube2e/gateway/gateway_test.go
- test/kube2e/gateway/robustness_test.go
Bump `go-utils` to the latest release to get the fix for the race condition in the gateway kube2e tests. This seems to have fixed flakes in these tests:
Also removed all references to the deprecated `translator.GatewayProxyName` constant.
> Bump go-utils

- .gitignore
- Makefile
- artifacts.yaml
- changelog/v0.21.0/push-tagged-helm-charts.yaml
Adds new make targets meant to be invoked locally that:
* build a tagged helm chart
* push tagged helm charts to a separate public helm repo
* download helm charts and sync from this new repo
Also adds:
* valet config to push tagged docker images
We need this so GlooE can depend on revisions of Gloo rather than just release tags.
Opted for a separate helm repo to prevent polluting the current helm repo.
The helm charts are versioned using the output from `git describe --tags`, which has the format `<last tag semver>-<#commits since last tag>-<short sha>`.
We can't run this in CI because we don't clone the repo as part of CI (we just start from a tarball)
I'm open to adding a git glone stage to our CI so we can upload helm charts to the tagged repo on every push if:
* we are ok with the …
> Add make targets for tagged helm charts, add valet config to push tagged docker images

- changelog/v0.20.9/fix-missing-matcher-panic.yaml
- projects/gateway/pkg/translator/http.go
- projects/gateway/pkg/translator/translator_test.go
- projects/gloo/pkg/translator/route_config.go
- projects/gloo/pkg/translator/translator_test.go
Check for nil matchers on routes. Added test to cover this case.
This PR does not need to be ported to `feature-rc` as the issue has already been solved there.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1438
> Avoid panicking on routes without matchers

- Makefile
- changelog/v0.21.0/assets-only-release.yaml
- ci/upload_github_release_assets.go
Support "asset-only" releases, which don't update homebrew formulas or fish food. Also updates release script to use the new `glooctl version` command now that `glooctl --version` has been removed.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1476
> Assets only release

- changelog/v0.20.3/fix-uds-ssl.yaml
- projects/gloo/pkg/plugins/kubernetes/uds_convert.go
- projects/gloo/pkg/plugins/kubernetes/uds_test.go
the change in #1461 was not picked up because the transition function for UDS ignores SSL config when comparing original/desired hash
do not ignore ssl config when comparing original/desired hash
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1485
> ssl does not update when uds reconciles

- changelog/v0.20.9/remove-orphaned-rbac-role.yaml
- install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
The Helm chart contained a `Role`/`ClusterRole` named `kube-crd-creator` which was unused. This role caused problems to users with limited privileges and effectively prevented them from installing Gloo in namespace-scoped mode.
This fix removes the `kube-crd-creator` resource from the Helm chart.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1491
> Remove orphaned RBAC role from chart

- Gopkg.lock
- Makefile
- changelog/v0.21.0/download-glooe-changelog.yaml
- cloudbuild.yaml
- docs/cmd/generate_changelog_doc.go
- pkg/version/enterprise.go
- projects/gloo/cli/pkg/cmd/install/install_suite_test.go
- projects/gloo/cli/pkg/cmd/install/install_test.go
cc @mitchdraft 
* Updates CI to download GlooE changelogs from publicly hosted bucket so Gloo docs generation can generate complete changelogs
* Fixes CI build step to set the expected and missing `GCLOUD_PROJECT_ID` env var
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1482
> Fix GlooE changelog generation during release

- Gopkg.lock
- changelog/v0.20.9/quiet-validation-logging.yaml
- projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
- projects/gloo/pkg/upstreams/kubernetes/conversions.go
tcp health check on validation webhook server causes Go's stdlib to log errors (which can be ignored)
use a debug logger. this will allow us to still inspect errors being logged if we need to (by setting log level to debug)
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1435
> use debug level logger for validation webhook errors

- changelog/v1.0.0-rc1/fix-docker-release-perms.yaml
- cloudbuild.yaml
tested with success here: https://console.cloud.google.com/cloud-build/builds/2000da81-c50b-40a6-a039-a6b7d7e3bd55?project=solo-public
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1516
> Fix docker permissions to push docs images during release

- docs/conf/conf.d/default.conf
Under the new hosting config, nginx is unable to interpolate the correct index filename.
This change uses the explicit filename generated by Hugo
> fix handling of docs index files

- README.md
- changelog/v0.20.11/fix-img-links.yaml
fixes broken image links now that we are serving docs from a new location
cc @mitchdraft
> Fix readme images

- changelog/v1.0.0-rc2/fix-docker-snippet-in-docs.yaml
- docs/content/dev/writing_auth_plugins/_index.md
- docs/content/gloo_routing/tls/client_tls.md
- docs/content/gloo_routing/tls/client_tls_service_annotations.md
- docs could not build because dockerfile snippet was interpreted as a hugo shortcode
- also fixes links that did not support product/version scoping
> Fix docs highlight

- .gitignore
- Makefile
- changelog/v1.0.0-rc2/consolidate-legacy-docs-mgmt.yaml
Include make targets for producing docs images from master/v0.20.x APIs that can be hosted at docs.solo.io/gloo/latest/
> Consolidate 0.20.x docs mgmt logic

- changelog/v0.20.12/dual-extauth-deployment.yaml
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
Allow the gateway-proxy pod to optionally receive both init containers to run and extra volumes to define through helm
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1537
> Allow envoy to receive initContainers and extra volume definitions through Helm

- changelog/v0.20.13/cli-fix-missing-matcher-panic.yaml
- projects/gloo/cli/pkg/printers/route.go
- projects/gloo/cli/pkg/printers/virtualservice.go
- projects/gloo/cli/pkg/printers/virtualservice_test.go
- projects/gloo/cli/pkg/surveyutils/route.go
- projects/gloo/pkg/utils/sort_routes.go
Avoid panicking on routes without matchers when running `glooctl get vs`.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1563
> Fix NPE on missing matchers in CLI

- changelog/v0.20.13/fix-handling-deprecated-ratelimit-settings.yaml
- projects/gloo/pkg/plugins/ratelimit/plugin.go
- projects/gloo/pkg/plugins/ratelimit/plugin_test.go
Handle the `rate_limit_before_auth` setting in its deprecated location. We currently correctly handle the flag in its new location (`spec.extensions.configs.rate-limit.rate_limit_before_auth`) but ignore it in the deprecated one (`spec.ratelimit_server.rate_limit_before_auth`).
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1572
> Handle rate_limit_before_auth setting in its deprecated location

- Gopkg.lock
- Gopkg.toml
- changelog/v1.0.0-rc2/bump-go-utils.yaml
Update go-utils to version v0.10.22 to get the new `HELM` and `UPGRADE` changelog entry types.
> Bump go-utils to get new changelog entry types

- changelog/v1.0.0-rc2/revamp-transformation-docs.yaml
- docs/content/gloo_routing/gateway_configuration/access_logging/_index.md
- docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/_index.md
- docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/add_headers_to_body/_index.md
- docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/change_response_status/_index.md
- docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/enrich_access_logs/_index.md
- docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/extract_query_params/_index.md
- docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/update_request_uri/_index.md
- docs/content/static/content/setup_postman_echo.md
Improve the existing documentation of Gloo's transformation features.
The new docs will be structured as a main page (describing the API and providing some simple example snippets) plus a series of tutorial pages, each exemplifying a use case for transformations:
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1565
> Revamp transformation docs

- Gopkg.lock
- Gopkg.toml
- changelog/v0.20.14/role-suffix.yaml
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
- install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
- install/helm/gloo/templates/_helpers.tpl
- install/test/rbac_test.go
- test/kube2e/gateway/gateway_suite_test.go
Allow RBAC cluster-scoped role names to receive custom suffixes. This enables, for example, blue/green deployments of Gloo to different namespaces within the same cluster. If you are performing an upgrade of Gloo from a version prior to this change, then you may have duplicate roles/role-bindings hanging around in your cluster. The ones created prior to this version can be safely cleaned up.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1459
> Allow role/role-binding names to take on unique suffixes

- changelog/v0.20.14/bump-glooe-tag.yaml
- pkg/version/enterprise.go
The default version of GlooE installed by the CLI is now 0.20.8.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1596
> CLI installs GlooE version 0.20.8 by default

- docs/content/advanced_configuration/rbac_configuration.md
The name of the field changed during code review feedback in the implementation PR but the docs didn't get updated.
> Fix docs after code review feedback

- changelog/v1.0.0-rc2/fix-plugin-race.yaml
- changelog/v1.0.0-rc3/fix-plugin-race.yaml
- projects/gloo/pkg/syncer/setup_syncer.go
- projects/gloo/pkg/translator/clusters.go
- projects/gloo/pkg/translator/http_filters.go
- projects/gloo/pkg/translator/listener.go
- projects/gloo/pkg/translator/route_config.go
- projects/gloo/pkg/translator/translator.go
- projects/gloo/pkg/translator/translator_test.go
- projects/gloo/pkg/translator/upstream_groups.go
- projects/gloo/pkg/validation/server_test.go
Gloo plugins are shared across calls to `Translate`. some plugins generate temporary state that is flushed at the start of the next translation loop.
Translation loops can now be called concurrently as a result of the proxy validation server.
initialize new plugins every translation by creating a "translationInstance" with a freshly constructed set of plugins whenever Translate is called
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1616
> fix potential plugin race

- changelog/v0.20.14/glooctl-uninstall-id.yaml
- docs/cli/glooctl_uninstall.md
- pkg/cliutil/install/kubernetes.go
- projects/gloo/cli/pkg/cmd/install/errors.go
- projects/gloo/cli/pkg/cmd/install/uninstall.go
- projects/gloo/cli/pkg/cmd/install/uninstall_test.go
- projects/gloo/cli/pkg/cmd/options/options.go
- projects/gloo/cli/pkg/flagutils/uninstall.go
Use the installation ID set by Helm to ensure that glooctl uninstalls only resources created for the instance of Gloo being uninstalled. It does this by attempting to read the "installationId" label from the gloo pod. If the label is not found, the uninstall will fail. You can choose to proceed by passing the new --force flag to "glooctl uninstall", which will attempt to perform an uninstall that may inadvertently delete cluster-scoped resources belonging to some other installation of Gloo.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1593
> Ensure glooctl deletes resources only for the appropriate installation

- changelog/v1.0.0-rc3/fix-transformation-docs-typo.yaml
- docs/content/gloo_routing/virtual_services/routes/routing_features/transformations/_index.md
Fix typo in transformation documentation main page.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1622
> Fix typo in transformation doc

- changelog/v1.0.0-rc2/role-suffix.yaml
- install/helm/gloo/templates/1-gloo-deployment.yaml
- install/helm/gloo/templates/10-ingress-deployment.yaml
- install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
- install/helm/gloo/templates/13-ingress-proxy-service.yaml
- install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
- install/helm/gloo/templates/16-clusteringress-proxy-service.yaml
- install/helm/gloo/templates/2-gloo-service.yaml
- install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
- install/helm/gloo/templates/28-knative-external-proxy-service.yaml
- install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
- install/helm/gloo/templates/3-discovery-deployment.yaml
- install/helm/gloo/templates/31-knative-internal-proxy-service.yaml
- install/helm/gloo/templates/5-gateway-deployment.yaml
- install/helm/gloo/templates/5-gateway-service.yaml
- install/helm/gloo/templates/6-access-logger-deployment.yaml
- install/helm/gloo/templates/6-access-logger-service.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/test/helm_test.go
- projects/gloo/cli/pkg/cmd/install/uninstall.go
- projects/gloo/cli/pkg/cmd/install/uninstall_test.go
Amended changelog for 1.0-rc2: 
This release changes the names of Gloo's ClusterRoles. By default, cluster-scoped roles will have the namespace of the associated Gloo installation appended to their name (i.e., the cluster-scoped role gloo-resource-reader created along with a Gloo installation to the gloo-system namespace will now become gloo-resource-reader-gloo-system). This may cause a problem during upgrades from Gloo <0.21.0 to Gloo >=0.21.0 for both open-source and enterprise Gloo, as the role ref in a ClusterRoleBinding is immutable. To resolve this, you can delete the existing ClusterRoleBindings with kubectl
> Make note of breaking change and remove installation ID from pod labels

- changelog/v0.21.1/minor-cleanup.yaml
- pkg/utils/setuputils/main_setup.go
- projects/gloo/pkg/plugins/ratelimit/plugin.go
Downgrade the log level from Error to Warn when gloo fails to report statistics, and DRY out the logic that determines what stage the rate limit plugin runs in
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1633
> Minor cleanup including downgrading a log line from error to warn and DRYing out some logic

- Gopkg.lock
- changelog/v1.0.0-rc3/fix-protobuf-display-links.yaml
- docs/content/advanced_configuration/consul_kv.md
- docs/content/advanced_configuration/multiple-gloo-installs.md
- docs/content/dev/_index.md
- docs/content/dev/example-proxy-controller.md
- docs/content/dev/writing-upstream-plugins.md
- docs/content/gloo_routing/gateway_configuration/access_logging/_index.md
- docs/content/gloo_routing/tcp_proxy.md
- docs/content/gloo_routing/validation/_index.md
- docs/content/gloo_routing/virtual_services/delegation/_index.md
- docs/content/gloo_routing/virtual_services/routes/matching_rules/_index.md
- docs/content/gloo_routing/virtual_services/routes/matching_rules/header_matching/_index.md
- docs/content/gloo_routing/virtual_services/routes/matching_rules/query_parameter_matching/_index.md
- docs/content/gloo_routing/virtual_services/routes/route_destinations/multiple_upstreams/multi_destination/_index.md
- docs/content/gloo_routing/virtual_services/routes/route_destinations/multiple_upstreams/subsets/_index.md
- docs/content/gloo_routing/virtual_services/routes/route_destinations/multiple_upstreams/upstream_groups/_index.md
- docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/grpc_to_rest/_index.md
- docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/rest_endpoint/_index.md
- docs/content/gloo_routing/virtual_services/routes/routing_features/append_remove_headers/_index.md
- docs/content/gloo_routing/virtual_services/routes/routing_features/prefix_rewrite/_index.md
- docs/content/gloo_routing/virtual_services/security/jwt/_index.md
- docs/content/installation/gateway/docker-compose-consul/_index.md
- docs/content/introduction/architecture.md
- docs/content/introduction/concepts.md
when docs were updated, some former markdown link syntax lingered, which produced broken links
here are some examples of how to use the protobuf shortcode to generate links: https://github.com/solo-io/hugo-theme-soloio#examples
BOT NOTES: 
resolves https://github.com/solo-io/solo-docs/issues/648
> Fix protobuf display links

- changelog/v1.0.0-rc3/knative-helm-uses-semver-compare.yml
- install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
- install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
- install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
- install/helm/gloo/templates/28-knative-external-proxy-service.yaml
- install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
- install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
- install/helm/gloo/templates/31-knative-internal-proxy-service.yaml
Improve the knative helm charts by swapping `semverCompare` in for `regexMatch`.
Before this PR, if you ran `glooctl install knative --install-knative-version 0.10.0`, you got knative 0.10.0 but a gloo system targeted at knative 0.7.0.
**Caveat:** Unfortunately, AFAICT this doesn't actually yield a working knative 0.10.0 system.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/1623
> knative helm charts compare semver

- changelog/v1.0.0-rc3/global-install-id.yaml
- docs/content/installation/gateway/kubernetes/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/_helpers.tpl
- install/helm/gloo/values-gateway-template.yaml
- install/helm/gloo/values-ingress-template.yaml
- install/helm/gloo/values-knative-template.yaml
- install/test/helm_test.go
- install/test/rbac_test.go
- install/test/svc_accnt_test.go
Move the Helm values field "installConfig.installationId" to "global.glooInstallationId" in order to better facilitate usage of the Gloo sub-chart in Gloo Enterprise
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1635
> Move the installationId Helm field to globals to make Gloo Helm chart easier to consume

- changelog/v1.0.0-rc3/add-enabled-flag-validation-certgenjob.yaml
- docs/content/installation/gateway/kubernetes/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/18-settings.yaml
- install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
- install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
- install/helm/gloo/templates/5-gateway-deployment.yaml
- install/helm/gloo/templates/5-gateway-service-account.yaml
- install/helm/gloo/templates/5-gateway-service.yaml
- install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
- install/helm/gloo/templates/6-access-logger-deployment.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/values-gateway-template.yaml
Add `enabled` to `.Values.gateway.validation` and `.Values.gateway.certGenJob` so users can disable the features without setting the root resource to nil.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1561
> Simpler disable of validation/certgenjob

- Gopkg.lock
- changelog/v1.0.0-rc3/fix-installation-links.yaml
- docs/content/gloo_routing/gateway_configuration/health_checks/_index.md
- docs/content/gloo_routing/virtual_services/security/_index.md
- docs/content/gloo_routing/virtual_services/security/apikey_auth/_index.md
- docs/content/gloo_routing/virtual_services/security/custom_auth/_index.md
- docs/content/gloo_routing/virtual_services/security/ldap/_index.md
- docs/content/installation/gateway/_index.md
api rename unearthed some old-format links that are now broken
fix links and update to use `protobuf` shortcode
> fix links - use protobuf

- changelog/v1.0.0-rc3/add-linkerd-helm-option.yaml
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/18-settings.yaml
- install/helm/gloo/values-gateway-template.yaml
- install/helm/gloo/values-knative-template.yaml
Adds a convenience option for Linkerd when deploying via. helm chart.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1651
> Linkerd Helm Chart Value

- changelog/v0.21.2/update-install-script.yaml
- projects/gloo/cli/install.sh
Update install script to honor `GLOO_VERSION` env var for desired version, if set. Also update to sort located releases in semver order so that if desired version is omitted, we try to download the largest release rather than the most recent release. (for example, we backport a fix and release a 0.x.x after 1.0.0 is already out).
> Update install script

- changelog/v0.21.3/bump-glooe-tag.yaml
- pkg/version/enterprise.go
Bump the default version of GlooE installed by the CLI to 0.21.0.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1725
> Bump the default version of GlooE installed by the CLI to 0.21.0

- Gopkg.lock
- changelog/v1.0.1/remove-gateway-url-shell-var.yaml
- docs/content/gloo_integrations/knative/_index.md
- docs/content/gloo_routing/virtual_services/routes/matching_rules/header_matching/_index.md
- docs/content/gloo_routing/virtual_services/routes/matching_rules/http_method_matching/_index.md
- docs/content/gloo_routing/virtual_services/routes/matching_rules/path_matching/_index.md
- docs/content/gloo_routing/virtual_services/routes/matching_rules/query_parameter_matching/_index.md
- docs/content/gloo_routing/virtual_services/routes/route_destinations/direct_response_action/_index.md
- docs/content/gloo_routing/virtual_services/routes/route_destinations/redirect_action/_index.md
- docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/discovered_upstream/_index.md
- docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/rest_endpoint/_index.md
- docs/content/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/static_upstream/_index.md
- docs/content/gloo_routing/virtual_services/security/apikey_auth/_index.md
- docs/content/gloo_routing/virtual_services/security/basic_auth/_index.md
- docs/content/gloo_routing/virtual_services/security/custom_auth/_index.md
- docs/content/gloo_routing/virtual_services/security/jwt/access_control.md
- docs/content/gloo_routing/virtual_services/security/jwt/claim_routing.md
- docs/content/gloo_routing/virtual_services/security/ldap/_index.md
- docs/content/gloo_routing/virtual_services/security/opa/_index.md
- docs/content/static/content/setup_notes
Remove the `GATEWAY_URL` shell variable from the docs and just use `$(glooctl proxy url)` where needed.
> Remove the GATEWAY_URL shell variable from the docs

- changelog/v1.0.1/reorder-messages-in-proto-files.yaml
- projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
- projects/gloo/api/v1/enterprise/options/jwt/jwt.proto
- projects/gloo/api/v1/enterprise/options/rbac/rbac.proto
- projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
- projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.go
- projects/gloo/pkg/api/v1/enterprise/options/rbac/rbac.pb.go
Re-order the messages in the security-related proto files so that higher-level messages appear at the top of the file. This will improve the experience of navigating to the protos. We currently link mostly to the messages that represent VirtualHost/Route options, which often are at the bottom of the proto files. This causes the browser to seemingly focus on unrelated messages when navigating to such messages.
> Re-order the messages in the security-related proto files

- docs/content/security/auth/_index.md
Added cross-reference to CORS doc from authentication page as some users were seeing authentication errors on OPTIONS requests and had not configured CORS correctly.
> Cross-referenced CORS and general grammer/format

- projects/gloo/cli/install.sh
This PR prints a clear message as to why the installation script has failed making the UX a little bit more user friendly.
EXAMPLE OUTPUT:
```
user@master01:~$ curl -sL https://run.solo.io/gloo/install | sh
sh: 6: python: not found
user@master01:~$ # Modified installer ->
user@master01:~$ ./install
Python is required to install glooctl
user@master01:~$ sudo apt-get install -y python
Reading package lists... Done
[ some time later]
Setting up python2.7 (2.7.11-7ubuntu1) ...
Setting up libpython-stdlib:amd64 (2.7.11-1) ...
Setting up python (2.7.11-1) ...
user@master01:~$ ./install
Attempting to download glooctl version v1.0.0-rc2
Downloading glooctl-linux-amd64...
```
This PR prints a clear message as to why the installation script has failed making the UX a little bit more user friendly.
> This adds a clean error when python is missing

- projects/gloo/cli/install.sh
port of https://github.com/solo-io/gloo/pull/1759
this is needed in the meantime until we rename `feature-rc1` to `master`, as our docs/CI link to the script in the master branch
> This adds a clean error when python is missing (#1759)

- docs/content/getting_started/_index.md
- docs/content/gloo_routing/tls/client_tls_service_annotations.md
- docs/content/gloo_routing/validation/_index.md
- docs/content/installation/gateway/_index.md
- docs/content/observability/tracing.md
- docs/content/upgrading/0.18.1.md
some of the headers have single `#` prefixes, which causes bad styling
fixes all unintentional matches to:
```
grep -e "^# " -r docs/content/
```
example of issue: https://docs.solo.io/gloo/latest/gloo_routing/tls/client_tls_service_annotations/
> Docs header size reduction

- changelog/v1.2.1/make-settings-hook.yaml
- install/helm/gloo/templates/18-settings.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
The template for the settings resource needs to be a Helm pre-install hook to prevent races during install. The hook annotation was accidentally removed with the `1.2.0` release; this change adds it back.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1838
> Fix helm race

- changelog/v1.2.2/remove-make-clean.yaml
- changelog/v1.2.3/remove-make-clean.yaml
- install/test/helm_suite_test.go
Do not delete to  `_output` directory during Helm chart unit tests.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1834
> Remove `make clean` invocation from helm tests

- changelog/v1.2.3/helm-namespace-fix.yaml
- install/test/helm_suite_test.go
- install/test/helm_test.go
- projects/gloo/cli/pkg/cmd/install/helm_client.go
Ensure that our usage of the Helm client libraries assigns a namespace to all resources, even those whose YAML definition does not specify a namespace. This is to fix the bug where observability resources can wind up in the default namespace set by the user's kube config; as of the time of writing, Prometheus's chart defines resources that are namespaced but do not have a namespace explicitly set on them.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1857
> Ensure that all namespaced resources are assigned a namespace

- changelog/v1.2.4/glooctl-version-warning-fix.yaml
- changelog/v1.2.5/glooctl-version-warning-fix.yaml
- projects/gloo/cli/pkg/prerun/version_warning.go
- projects/gloo/cli/pkg/prerun/version_warning_test.go
```
➜ TAGGED_VERSION=v1.0.0 make glooctl -B && curl -v $(./_output/glooctl proxy url)/status/201
GO111MODULE=on go build -ldflags="-X github.com/solo-io/gloo/pkg/version.Version=1.0.0" -gcflags=all="-N -l" -o /Users/grahamgoudeau/go/src/github.com/solo-io/gloo/_output/glooctl projects/gloo/cli/cmd/main.go
----------
glooctl binary version (1.0.0) differs from server components (v1.2.1) by at least a minor version.
Consider running:
./_output/glooctl upgrade --release=v1.2.1
----------
*   Trying 192.168.64.7...
* TCP_NODELAY set
* Connected to 192.168.64.7 (192.168.64.7) port 32555 (#0)
> GET /status/201 HTTP/1.1
> Host: 192.168.64.7:32555
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 201 Created
```
In the state described in the ticket (enterprise 1.0.0-rc3 deployed with OS gloo …
> Make glooctl version warning more intelligent

- changelog/v1.2.5/aws-discovery-fix.yaml
- projects/discovery/pkg/fds/syncer/discovery_syncer.go
- projects/discovery/pkg/fds/syncer/discovery_syncer_test.go
AWS function discovery is more painful after our change to make FDS run in Whitelist mode by default. This changes FDS so that, in Whitelist mode, AWS functions are discovered as if FDS is running in Blacklist mode.
Confirmed using valet that the petclinic demo works and the AWS functions are discovered after this change.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1878
> Make FDS run in Blacklist mode for AWS functions

- changelog/v1.2.8/direct-response-header-manipulation.yaml
- go.mod
- go.sum
- projects/gloo/pkg/translator/route_config.go
- projects/gloo/pkg/translator/translator_test.go
Currently Gloo skips the processing of route plugins on DirectResponseAction route actions. Envoy supports header manipulation on direct responses. This PR exposes that feature through Gloo.
This includes the ability to copy request headers to the direct response via the `%REQ(header-name)%` format specifier.
> Direct response header manipulation

- Makefile
- changelog/v1.2.9/fix-released-gloo-manifests.yaml
- projects/gloo/cli/pkg/cmd/install/installer.go
This change adds CRD resources back to the manifest files that are published as part of a Gloo release.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1877
> Fix release manifests

- Makefile
- changelog/v1.2.10/fix-manifest-release.yaml
- cloudbuild.yaml
- install/test/helm_suite_test.go
Fix manifest rendering step during release builds. Problem was that we were trying to render using the remote chart which had not been published yet (see [this build](https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=8d94d30b-6194-428b-8b47-329c768cc4cc)).
> Fix manifest release

- changelog/v1.2.11/remove-install-gateway-upgrade.yaml
- docs/content/cli/glooctl_install.md
- docs/content/cli/glooctl_install_gateway.md
- docs/content/cli/glooctl_install_gateway_enterprise.md
- docs/content/cli/glooctl_install_ingress.md
- docs/content/cli/glooctl_install_knative.md
- projects/gloo/cli/pkg/cmd/install/install_test.go
- projects/gloo/cli/pkg/cmd/options/options.go
- projects/gloo/cli/pkg/flagutils/install.go
The upgrade command has been depreciated, and should no longer be usable.
> Remove --upgrade flag from glooctl install gateway

- docs/content/installation/ingress/_index.md
- docs/content/installation/knative/_index.md
Docs should stop referencing the knative and ingress template yamls that have been consolidated into a single values.yaml file.
> Update install docs to prompt users to make helm override yamls

- changelog/v1.2.13/glooctl-in-cluster.yaml
- changelog/validation.yaml
- projects/gloo/cli/pkg/prerun/version_warning.go
Currently, glooctl install first checks for version compatibility. It looks in the gloo-system ns even if a different install namespace is specified. This means glooctl needs cluster roles to install gloo. This pr is a step away from that requirement
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1765
> remove cross-ns calls from glooctl installation

- CONTRIBUTING.md
- README.md
- changelog/v1.2.13/update-readme-solo-docs-refs.yaml
- docs/content/advanced_configuration/session_affinity.md
Fix some readme links and update old refs to deprecated solo-docs repo.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2050
> Update docs links

- changelog/v1.2.13/support-knative-annotations.yaml
- docs/content/installation/gateway/kubernetes/values.txt
- go.sum
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/10-ingress-deployment.yaml
- projects/ingress/pkg/setup/setup_syncer.go
- projects/knative/pkg/translator/translate.go
- projects/knative/pkg/translator/translator_syncer.go
- projects/knative/pkg/translator/translator_syncer_test.go
this PR adds support for knative's ingress annotation as described in #2040 
support is off by default but can be enabled via the helm chart (which sets an environment variable on the knative ingress controller)
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2040
> respect knative ingressclass annotation

- Gopkg.lock
- Gopkg.toml
- changelog/v1.2.13/dedupe-stats-config.yaml
- changelog/v1.2.13/placeholder.yaml
- changelog/v1.2.14/dep-bump.yaml
- changelog/v1.2.14/placeholder.yaml
- changelog/v1.2.15/placeholder.yaml
- changelog/validation.yaml
- docs/cmd/generate_changelog_doc.go
- go.mod
- go.sum
- projects/accesslogger/cmd/main.go
- projects/accesslogger/pkg/runner/run.go
- projects/discovery/cmd/main.go
- projects/gateway/cmd/main.go
- projects/gloo/cmd/main.go
* Relaxes semver validation in changelog validation
* Updates go-utils to handle `validation.yaml` living in the changelog directory
* Adds placeholder changelogs to ensure that the our changelog bot validation points us towards the next desired release tag.
We are skipping `v1.2.13` and `v1.2.14`, which were released off of master instead of this branch.
> Fix changelogs, relax semver changelog validation

- Makefile
- changelog/v1.3.2/determine_assets_only_release.yaml
Automatically determine whether or not a release should create PRs for our formulas, rather than hard-coding an `ASSETS_ONLY` variable into the makefile.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2084
> Automatically determine assets_only release value

- docs/content/contributing/_index.md
- docs/content/installation/gateway/docker-compose-consul/_index.md
- docs/content/installation/gateway/nomad/_index.md
Referring to issue #2135 
Removing references to the branch `feature-rc1` or the tag `v1.1.0` in the documentation.
> remove feature-rc1 and v1.1.0

- Makefile
- cloudbuild.yaml
- projects/gateway/pkg/validation/notification_channel.go
- projects/gateway/pkg/validation/validator.go
A bad merge resulted in a leftover reference to the  `github.com/solo-io/go-utils/errors` package, which does not exist anymore.
> Fix broken go-utils/errors import

- docs/content/observability/tracing.md
- docs/examples/session-affinity/sample_gloo_config/vs.yaml
- docs/install/sample_virtualservice.yaml
- projects/examples/services/sleeper/README.md
Fix occurrences of `matcher` (singular) in the docs.
> Fix occurrences of `matcher` attribute in docs

- changelog/v1.3.2/route-table-merging.yaml
- changelog/v1.3.3/public-route-table-selection-func.yaml
- projects/gateway/pkg/translator/route_converter.go
Also updated the changelog for the new route table selector feature to provide more details, hence the `skip-changelog`.
> Make Route Tables filtering function public

- Makefile
- changelog/v1.3.2/push-helm-chart-to-registry.yaml
- changelog/v1.3.2/push-images-all-builds.yaml
- changelog/v1.3.3/fix-glooctl-install.yaml
- install/helm/gloo/generate.go
- install/test/helm_suite_test.go
- pkg/version/linked.go
- projects/gloo/cli/pkg/cmd/install/install_test.go
- projects/gloo/cli/pkg/cmd/install/installer.go
- projects/gloo/pkg/plugins/wasm/mocks/mock_cache.go
- projects/metrics/pkg/metricsservice/mocks/mock_metrics_stream.go
Fix `glooctl install` command when `-f` flag is omitted to no longer error erroneously.
The problem was that in https://github.com/solo-io/gloo/pull/2075 we added https://github.com/solo-io/gloo/pull/2075/files#diff-89f8111040160d60e5a3daefca1edcc8R28-R35
`checkedoutAtTag` uses your git context to determine whether or not a build is a release build, rather than using the version linked into the binary. `glooctl install` checks whether or not it is itself a released version of `glooctl` to determine whether users need to use the `-f` flag. Thus, any invocation of `glooctl install` without a valid git context for Gloo would fail.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/508
> Fix install error on release versions of glooctl

- Makefile
- changelog/v1.3.3/fix-default-branch-detection.yaml
- projects/gloo/pkg/plugins/wasm/mocks/mock_cache.go
- projects/metrics/pkg/metricsservice/mocks/mock_metrics_stream.go
The problem with the previous version of this check was that in CI we check out a commit by its SHA (not by branch name) which puts the repo in a detached HEAD state, which in turn causes 
```make
CURRENT_BRANCH := $(shell git rev-parse --abbrev-ref HEAD)
```
to evaluate to `HEAD` instead of the branch name.
This caused `ASSETS_ONLY` to always be true:
```make
ASSETS_ONLY := true
ifeq ($(DEFAULT_BRANCH), $(CURRENT_BRANCH))
ASSETS_ONLY = false
endif
```
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2220
> Fix default branch detection

- changelog/v1.3.3/fix-hermetic-codegen.yaml
- pkg/utils/selectionutils/virtual_service.go
- projects/metrics/pkg/metricsservice/service.go
When we generate a mock file twice, we cause a race condition. Usually this isn't a problem, unless the different mockgen's have different import aliases, which causes the make code-check step in the cloudbuild.yaml to fail.
This removes the additional mockgen call in two places, which was causing non-hermetic codegen.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2239
> hermetic codegen

- changelog/v1.3.3/fix-hermetic-codegen.yaml
- pkg/utils/selectionutils/virtual_service.go
- projects/metrics/pkg/metricsservice/service.go
This reverts commit cacef98dcd94c4776398c57a938278e6327edec0.
The actual problem is that these deps aren't pinned: https://github.com/solo-io/gloo/blob/master/Makefile#L92-L93
> Revert "hermetic codegen (#2261)"

- changelog/v1.3.3/fix-certgen-domain.yaml
- jobs/pkg/certgen/gen_certs.go
potential bug for validation webhook server with clusters using non-default domain
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2288
> fix hard-coded cluster.local domain

- changelog/v1.3.3/helm-value-to-disable-k8s-dest.yaml
- docs/content/installation/gateway/kubernetes/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/18-settings.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
Gloo allows you to directly reference a Kubernetes service as a routing destination. To enable this feature, Gloo scans the cluster for Kubernetes services and creates a special type of in-memory Upstream to represent them.
If the cluster contains a lot of services and you do not restrict the namespaces Gloo is watching, this can result in significant overhead. If users do not plan on using this feature, they can now provide a helm value to turn it off.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2299
> Expose `disableKubernetesDestinations` setting as Helm chart value

- changelog/v1.2.16/fix-more-helm-hooks.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- projects/gloo/cli/pkg/cmd/install/installer_test.go
Port of #2287.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2212
> Remove unnecessary post-upgrade Helm hooks (port to 1.2.x)

- changelog/v1.3.3/fix-plugin-manifest-example.yaml
- docs/content/dev/writing_auth_plugins/_index.md
Example shows old format for plugin manifests.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2294
> Fix plugin manifest example in docs

- changelog/v1.2.16/allow-upgrade-settings-default-gw.yaml
- install/helm/gloo/templates/18-settings.yaml
- install/helm/gloo/templates/8-default-gateways.yaml
- install/test/helm_test.go
Our default settings and gateway resources are currently written only on installs. This change causes them to be created on upgrades as well. This way users can use `helm upgrade` to just update those settings.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2317
> Allow updating settings and default gateways when upgrading via Helm

- changelog/v1.3.4/fix-knative-internal-gateway.yaml
- cloudbuild.yaml
- projects/clusteringress/README.md
- projects/knative/README.md
- projects/knative/pkg/translator/translator_syncer.go
- projects/knative/pkg/translator/translator_syncer_test.go
this change adds all knative services to the `internal` proxy. this is based on the implicit Knative assumption that `External` ingresses will be available on the internal proxy
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2336
> knative: fix knative internal/external lb assumption

- changelog/v1.3.4/deflake-e2e-ci.yaml
- cloudbuild.yaml
- test/e2e/consul_test.go
- test/e2e/custom_auth_test.go
- test/e2e/route_transformation_test.go
Ran e2e tests in CI via `gcloud builds submit` with 10-20 consecutive successes
Fixes e2e test flakes by ensuring we cleanup Envoy after each test (we missed a case in the custom auth e2e tests). Locally running the e2e custom auth test followed by grpc_web was a guaranteed way to reproduce the grpc flake linked in this issue, and cleaning up Envoy fixes the grpc test to run properly. 
Also allows us to run the transformation tests on a Mac.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2245
> Fix flaky e2e tests

- changelog/v1.3.4/bump-solokit-resource-version-err-fixes.yaml
- go.mod
- go.sum
Picks up fixes to solo-kit's generated Reconciler and Reporter (v2), which is used in Gloo's proxy reconciler and gloo/gateway's status report writing logic.
In addition, this should help deflake other uses of these generated interfaces in our regression tests.
Earlier versions of the solo-kit code didn't properly handle resource version errors and retrying them (often only retrying once before giving up, without any backoff)
> Bump solo-kit version

- docs/content/advanced_configuration/fds_mode.md
FDS does not actually look at kubernetes services, only the discovered upstreams. Update the docs to reflect this behavior.
> Update FDS docs error

- changelog/v1.2.16/helm-value-to-disable-k8s-dest.yaml
- changelog/v1.2.18/helm-value-to-disable-k8s-dest.yaml
- docs/content/installation/gateway/kubernetes/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/18-settings.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
Gloo allows you to directly reference a Kubernetes service as a routing destination. To enable this feature, Gloo scans the cluster for Kubernetes services and creates a special type of in-memory Upstream to represent them.
If the cluster contains a lot of services and you do not restrict the namespaces Gloo is watching, this can result in significant overhead. If users do not plan on using this feature, they can now provide a helm value to turn it off.
Port of https://github.com/solo-io/gloo/pull/2302
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2299
> Port disable k8s dest fix

- changelog/v1.3.6/fix-grafana-average-request-time.yaml
- projects/gloo/pkg/plugins/grpc/plugin.go
- projects/gloo/pkg/plugins/plugin_interface.go
- projects/gloo/pkg/translator/translator_test.go
Fix `Less` functions for http filters (`StagedHttpFilterList`) and listener filters (`StagedListenerFilterList`) to handle case of 2 different filters with same name.
This should fix the grafana bug which was caused by the envoy_http_downstream_rq_time stats reloading exceedingly often.
(Also changed upstreamServices from unnecessary map to slice.)
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2185
> Lds reloads 2

- docs/content/installation/gateway/kubernetes/helm_chart_values.md
Some open source Helm values require an extra `gloo.` prefix when used with Gloo Enterprise. This change adds an info box to the Helm values page of our docs to alert the user of this discrepancy.
> Document prefix for GlooE helm chart values

- changelog/v1.3.6/fix-double-loadbalancer.yaml
- install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
- install/helm/gloo/templates/16-clusteringress-proxy-service.yaml
- install/helm/gloo/templates/18-settings.yaml
When using the Knative charts to install Gloo, two ingress proxies would be created if the knative version was > 1.9. This was because a regex identifying whether the version was > 1.7 contained a bug that made it match everything where the minor version contained any digit <8.
This PR removes the regex and uses the same `semverCompare` method used to identify versions above 1.7.
Fixes #2448
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2448
> Fix ingress proxy creation on Knative > 1.9

- changelog/v1.3.7/custom-gateway-proxy-svc-name.yaml
- docs/content/installation/gateway/kubernetes/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/test/helm_test.go
This is if you want to have your gateway-proxy's service name be different from the deploy/configmap/pod. I added a test for this as well.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2446
> Allow a custom name for the gateway-proxy service

- changelog/v1.3.7/fix-consul-docs.yaml
- docs/content/installation/gateway/docker-compose-consul/_index.md
- install/docker-compose-consul/data/gateways/gloo-system/gw-proxy.yaml
- install/docker-compose-consul/docker-compose.yaml
In Gloo 1.2.13 we removed the auto-creation of Gateway resources. This updates the Consul guide to reflect that change.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2439
> Fix Gloo on Consul tutorial for newer versions of Gloo

- docs/content/installation/gateway/kubernetes/_index.md
Already pushed to live docs, this was the change required to fix the 404 link
> Fix broken link

- Makefile
- changelog/v1.3.9/kind-improvements.yaml
- install/helm/gloo/generate.go
- install/test/helm_suite_test.go
- install/test/helm_test.go
- test/kube2e/gateway/gateway_suite_test.go
- test/services/envoy.go
changes to allow me to use kind with regression tests.
- no need to use pull policy always, now that we have unique tags for each commit (using always in kind requires pushing the images, which is otherwise not required in kind)
- fix the helm tests accordingly
- getEnvoyImageTag to use by default the tag from the Dockerfile. this allows me to run local e2e tests easier.
> Paper cuts

- changelog/v1.3.9/bump-go-utils.yaml
- go.mod
- go.sum
Update go-utils to version 0.14.1, which includes fixes to make our release asset logic more resilient to transient github failures.
> Harden github release asset retry logic

- changelog/v1.3.0/auth-endpoint-query-params.yaml
- changelog/v1.3.6/gloo-mtls.yaml
- changelog/v1.3.8/sds-envoy-helm-values.yaml
Some YAML code blocks are [rendering incorrectly](https://docs.solo.io/gloo/latest/changelog/open_source/) in our changelog docs. This change fixes the problematic entries.
> Fix changelog formatting errors

- docs/content/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
- projects/gloo/api/v1/settings.proto
- projects/gloo/pkg/api/v1/settings.pb.go
It was not immediately clear that our new consul dns resolution feature could be configured with non-consul dns servers.
This docs change clarifies that.
> Clarify consul dns docs

- docs/docs.toml
Regarding issue #2506 
This change to the docs.toml config will allow unsafe html to be processed by the markdown rendering engine. That appears to be what is preventing the children content lists from including the proper formatting and links.
> allow unsafe html

- changelog/v1.3.10/fix-filterchain-copying.yaml
- projects/gloo/pkg/plugins/hcm/plugin.go
- projects/gloo/pkg/plugins/tcp/plugin.go
- projects/gloo/pkg/translator/listener.go
Fix noisy logging on duplicate upgrade websocket config when using Gloo with SSL & SNI.
Harmless fix, as we were only side-affecting the upgrade configs in a dangerous way, but by resetting the list before appending in each loop (as we did to make this more code more defensive here: https://github.com/solo-io/gloo/pull/1990) there is no potential for error (despite these dangerous-looking logs).
Fixing this may prevent future bugs in the affected function and cleans up logging, which is nice.
We loop over filters here: https://github.com/solo-io/gloo/blob/v1.3.9/projects/gloo/pkg/plugins/hcm/plugin.go#L57
and modify them here: https://github.com/solo-io/gloo/blob/v1.3.9/projects/gloo/pkg/plugins/hcm/plugin.go#L68
but when we make new filter chains, we are reusing the same filter pointers: …
> Fix duplicate websocket upgrade configs noisy logging

- docs/content/gloo_routing/validation/invalid_route_replacement.md
- fix all gloo docs links (None of them currently work: https://docs.solo.io/gloo/latest/gloo_routing/validation/invalid_route_replacement/)
- remove extra parens, fix typo, make a link more specific
> fix route replacement gloo docs links

- docs/content/installation/_index.md
Right now the link labeled `recommended install for first-time users` on https://docs.solo.io/gloo/latest/installation goes to 404. This PR fixes it to go to https://docs.solo.io/gloo/latest/installation/gateway
> Fixed link from installation index to gateway

- changelog/v1.3.11/add-consul-appendix-dynamic-routing-docs.yaml
- docs/content/dev/example-proxy-controller.go
- docs/content/dev/example-proxy-controller.md
- example/proxycontroller/Dockerfile
- example/proxycontroller/Makefile
- example/proxycontroller/install/my-cool-proxy.yaml
- example/proxycontroller/install/proxycontroller.yaml
- example/proxycontroller/proxycontroller.go
- Expand on the proxy controller example to show how to route to auto-discovered consul services by passing the upstream name in the host header.
- Create a docker container and deploy yaml for the sample proxy controller
- Improve docs copy-pasteability
> Add appendix to show auto-routing to consul services

- changelog/v1.3.11/envoy-cve.yaml
- projects/envoyinit/cmd/Dockerfile.envoyinit
Envoy did a security release today: https://groups.google.com/forum/#!topic/envoy-announce/sVqmxy0un2s
Bump version of envoy-gloo to a version of envoy with the vulnerability fixed.
> envoy cve 3/3/2020

- Makefile
Lets a contributor specify one thing in the Makefile to change such that
building and pushing new images for personal use is easier
Add "clean-generated-code" target to Makefile which is required when
making changes to proto files, otherwise `make generated-code -B` target
fails with an exit code, and other targets such as `make gloo` will fail
too.
> Improve Makefile to make outside contributors lives easier

- changelog/v1.3.13/clarify-tls-docs.yaml
- docs/content/gloo_routing/tls/client_tls.md
- docs/content/gloo_routing/tls/server_tls.md
Clarifies some confusing information documented about TLS configuration in Gloo.
Also ensures that our example doesn't depend on the original virtual service's filter chain matcher to resolve the request. By using `--resolve` flag on `curl` we can ensure we send the proper SNI name with the request.
> Clarify confusing TLS docs

- changelog/v1.3.13/consul-e2e-osx-runnable.yaml
- test/e2e/cors_test.go
Update the consul e2e test to run locally on Macs. (still runs fine in CI on linux)
> Port consul runnable e2e osx

- .github/workflows/check-code-and-docs-gen.yaml
- changelog/v1.3.13/fix-go-1.14-compatibility.yaml
- cloudbuild-cache.yaml
- go.mod
- pkg/version/linked.go
- projects/gloo/pkg/api/v1/options/protocol_upgrade/protocol_upgrade.pb.go
Supersedes https://github.com/solo-io/gloo/pull/2570
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2532
> Upgrade to Go 1.14, and Go 1.14 compatibility changes

- changelog/v1.3.13/fix-typo-in-docs.yaml
- docs/content/gloo_integrations/cert_manager/_index.md
- docs/content/installation/preparation.md
- docs/content/security/auth/jwt/_index.md
Hi,
I noticed minor typos with the Kubernetes word across the documentation. This PR aims to fix all of them. That's a pretty small contribution but I thought it might be useful.
Thank you for maintaining Gloo. Keep up the great work.
> Fix Kubernetes typo in docs

- projects/gloo/cli/pkg/cmd/check/root.go
Fixes an incorrect message printed during `glooctl check`
> Fix `glooctl check` auth config message

- changelog/v1.3.16/glooctl-namespaced-rbac.yaml
- projects/gloo/cli/pkg/cmd/add/route.go
- projects/gloo/cli/pkg/cmd/check/root.go
- projects/gloo/cli/pkg/cmd/create/authconfig/authconfig.go
- projects/gloo/cli/pkg/cmd/create/upstream.go
- projects/gloo/cli/pkg/cmd/create/upstreamgroup.go
- projects/gloo/cli/pkg/cmd/create/virtualservice.go
- projects/gloo/cli/pkg/cmd/del/proxy.go
- projects/gloo/cli/pkg/cmd/del/upstream.go
- projects/gloo/cli/pkg/cmd/del/upstreamgroup.go
- projects/gloo/cli/pkg/cmd/del/virtualservice.go
- projects/gloo/cli/pkg/cmd/edit/route/options/options.go
- projects/gloo/cli/pkg/cmd/edit/settings/extauth.go
- projects/gloo/cli/pkg/cmd/edit/settings/ratelimit/custom_server_config.go
- projects/gloo/cli/pkg/cmd/edit/settings/ratelimit/ratelimit.go
- projects/gloo/cli/pkg/cmd/edit/upstream/root.go
- projects/gloo/cli/pkg/cmd/edit/virtualservice/custom_envoy_config.go
- projects/gloo/cli/pkg/cmd/edit/virtualservice/root.go
- projects/gloo/cli/pkg/cmd/get/root.go
- projects/gloo/cli/pkg/cmd/remove/route.go
- projects/gloo/cli/pkg/cmd/route/sort.go
- projects/gloo/cli/pkg/cmd/version/cmd.go
- projects/gloo/cli/pkg/cmd/version/version_test.go
- projects/gloo/cli/pkg/common/create.go
- projects/gloo/cli/pkg/common/get.go
- projects/gloo/cli/pkg/helpers/clients.go
- projects/gloo/cli/pkg/prerun/version_warning.go
- projects/gloo/cli/pkg/printers/virtualservice.go
- projects/gloo/cli/pkg/surveyutils/route.go
- projects/gloo/cli/pkg/surveyutils/upstreamgroup.go
- updates `glooctl` commands to work without cluster-scoped rbac
- updates `glooctl version` to report client version even if server version cannot be determined
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2375
> Fix glooctl to work without cluster-scoped permissions

- docs/content/guides/security/auth/opa/_index.md
Clarification on the `input` document available in OPA policies
> Add docs for opa input structure

- changelog/v1.4.0-beta1/update-versioning-to-beta-releases.yaml
- changelog/validation.yaml
This will enforce strict semver validation, as new features are only developed on master and are bundled together in quarterly releases.
This matches the versioning scheme we have already set forth with Gloo Enterprise, and closely mirrors the Envoy release strategy. (which of course we depend on)
> Strict semver validation

- changelog/v1.4.0-beta1/update-versioning-to-beta-releases.yaml
- changelog/validation.yaml
* Update changelog , cherrypick of https://github.com/solo-io/gloo/pull/2697
Had to redo this change because we undid it in https://github.com/solo-io/gloo/pull/2711 to fix a regression in 1.3.16, which allowed us to release the fix in 1.3.17 before preparing for 1.4.0-beta1
> Update changelog (#2697)

- docs/content/installation/platform_configuration/cluster_setup.md
This addresses issue #2696 
Added advice on how to configure a private GKE cluster to allow Gloo installation and creation of Virtual Services.
> Update with private GKE advisement

- docs/content/installation/platform_configuration/cluster_setup.md
The original private GKE doc had the wrong ports. Turns out it only needs 8443 for the admission control webhook. I have update the doc.
> Fix error on ports

- changelog/v1.3.21/fix-glooctl-kubectl-timeouts.yaml
- docs/content/operations/debugging_gloo/_index.md
- pkg/cliutil/uri.go
- projects/gloo/cli/pkg/cmd/gateway/dump.go
- projects/gloo/cli/pkg/cmd/gateway/logs.go
* fix glooctl kubectl timeouts
* mark glooctl proxy check setup error as warning
* still return errors when we can't set up a port-forward
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2771
> fix glooctl kubectl timeouts (#2790)

- changelog/v1.3.20/fix-proxy-garbage-collection.yaml
The changelog had an error with the default setting -- this fixes it so it will be rendered properly in the next update of ours docs
> Fix changelog accuracy

- docs/content/reference/gloo_port_reference.md
Adding a port reference document with the ports used by all pods and services in Gloo Gateway and Gloo Enterprise.
> Port reference document

- changelog/v1.4.0-beta7/fix-503-ratelimit-flakes.yaml
- test/e2e/ratelimit_test.go
Was able to reproduce locally after 65 attempts using `ENVOY_IMAGE_TAG=1.4.0-beta6 ginkgo -r -failFast -untilItFails -trace -compilers=2 test/e2e` while focused on `It("shouldn't rate limit"`. No longer able to reproduce.
This is due to an expected race in gloo between the upstreams and proxy being written to the gloo snapshot.
If the upstreams hit second, the eventually ok check may return ok before the proxy itself has valid upstream targets, which could result in `ConsistentlyNotRateLimiting` checks failing assertions before those assertions were ready to be made
logs from a run that flakes/fails would have contained:
```
{"level":"info","ts":1588079684.166445,"logger":"gloo.setup.v1.event_loop.envoyTranslatorSyncer","caller":"syncer/envoy_translator_syncer.go:77","msg":"begin sync …
```
> Fix 503 e2e flake

- changelog/v1.3.24/fix-503-ratelimit-flakes.yaml
- test/e2e/ratelimit_test.go
* Fix 503 e2e flake
backporting test flake fix from https://github.com/solo-io/gloo/pull/2896
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2895
> Fix 503 e2e flake (#2896)

- changelog/v1.4.0-beta8/fix-untar-mod-cache-flake.yaml
- cloudbuild.yaml
We have seen some flakes in CI where we have been unable to successfully download our go mod cache dependencies and untar them, which has failed CI runs.
Since the mod cache is just a speed optimization (we can download the dependencies later), we can opt to pass the cloudbuild step even if google has a server side error, or we hit download limits from the server.
a sample build where we hit the flake, and the step passes anyways, using these changes: https://console.cloud.google.com/cloud-build/builds/3c076ba6-0816-4965-8f5d-155b42b02571?project=solo-public
the idea came from: https://medium.com/@davidstanke/make-a-cloud-build-step-that-always-succeeds-9d23290a2f4e
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2894
> Fix untar mod cache flake

- docs/content/installation/_index.md
- docs/content/installation/gateway/_index.md
It appears that the tag `<div markdown=1>` is no longer respected by Hugo, so markdown included in HTML tables is not being rendered properly. I have updated two docs to use all HTML markup for the tables. The formatting available in markdown for tables doesn't really look right.
This resolves issue #2688
> Fix table formatting on setup

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/docs.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/pull_request_template.md
- changelog/v1.4.0-beta9/issue-and-pr-templates.yaml
Bringing back changes from https://github.com/solo-io/gloo/pull/1363 that got lost in the default branch swap during the Gloo 1.0 release several months ago.
Also adding a pr template to help direct devs who want to contribute to gloo
> Issue and pr templates

- changelog/v1.4.0-beta9/safer-upgrade-using-helm-3-2-0.yaml
- docs/content/operations/upgrading/1.3.0.md
This is a safer way for teams to upgrade to Gloo 1.3 from Gloo 1.2, leveraging helm 3's new feature to adopt previously existing resources into the chart. This allows us to skip deleting and recreating some resources to get them into the release (i.e., the settings and gateways).
While the documented workflows worked, they were easy to mess up, and could cause downtime if done improperly. This approach is also easier, just requires the newest release of helm.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2807
> upgrade to gloo 1.3 docs, leveraging helm 3.2 adoption of resources

- changelog/v1.4.0-beta9/host-rewrite-healthcheck.yaml
- projects/gloo/pkg/plugins/static/plugin.go
- projects/gloo/pkg/plugins/static/plugin_test.go
- test/e2e/gateway_test.go
When static upstreams with two or more hosts are converted to Envoy clusters, we will now add hostnames so that host headers for requests and healthchecks are set properly.
Users had a service behind each host that required the host header to be set to their own hostname.
Here is how I tested to check that our healthchecks and requests were having their host headers replaced properly:
Start up 2 services that run 'mendhak/http-https-echo', a docker image that will log and echo back all the information in the request that is sent to it:
```
kind: Deployment
apiVersion: apps/v1
metadata:
name: headers1
namespace: default
labels:
name: headers1
spec:
replicas: 1
selector:
matchLabels:
task: headers1
template:
metadata:
labels:
task: headers1
spec:
containers:
- name: log-and-echo-headers …
```
> Static upstream host header rewrite

- changelog/v1.4.0-beta9/fix-dev-portal-docs.yaml
- docs/content/guides/dev_portal/_index.md
Add `securityDefinitions` to OpenAPI spec in dev portal docs.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2963
> Fix dev portal docs

- changelog/v1.4.0-beta10/fix-auth-config-update.yaml
- projects/gloo/pkg/validation/server.go
- projects/gloo/pkg/validation/server_test.go
When AuthConfigs are updated, gloo resyncs, which should trigger a gateway resync as well. Previously, we weren't adding AuthConfigs into the hash that decided whether the gloo snapshot changed or not. That has been fixed here.
Users ran into this bug when deploying an auth config after a virtual service.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2920
> fix auth config update

- changelog/v1.4.0-beta11/solokit-upgrade.yaml
- go.mod
- go.sum
- projects/clusteringress/pkg/api/external/knative/cluster_ingress.sk.go
- projects/gateway/pkg/api/v1/gateway.sk.go
- projects/gateway/pkg/api/v1/route_table.sk.go
- projects/gateway/pkg/api/v1/virtual_service.sk.go
- projects/gloo/pkg/api/v1/artifact.sk.go
- projects/gloo/pkg/api/v1/endpoint.sk.go
- projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/auth_config.sk.go
- projects/gloo/pkg/api/v1/proxy.sk.go
- projects/gloo/pkg/api/v1/secret.sk.go
- projects/gloo/pkg/api/v1/settings.sk.go
- projects/gloo/pkg/api/v1/upstream.sk.go
- projects/gloo/pkg/api/v1/upstream_group.sk.go
- projects/ingress/pkg/api/v1/ingress.sk.go
- projects/ingress/pkg/api/v1/kube_service.sk.go
- projects/knative/pkg/api/external/knative/ingress.sk.go
This pulls in the fix in solo-kit that does not allow `Find` to accept resources without a namespace.
This bug was discovered with regard to upstreams while fixing https://github.com/solo-io/gloo/issues/2730.
> Find require ns

- changelog/v1.4.0-beta11/upgrade-the-upgrade-docs.yaml
- docs/content/operations/upgrading/0.18.1.md
- docs/content/operations/upgrading/1.0.0.md
- docs/content/operations/upgrading/faq.md
- docs/content/operations/upgrading/upgrade_steps.md
Polish the upgrade docs with our up to date recommendations for upgrading Gloo. In particular, this removes recommendations of `helm template | kubectl apply` \ `glooctl install --dry-run | kubectl apply`, as we don't recommend this as an upgrade path.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2902
> Upgrade the upgrade docs

- changelog/v1.4.0-beta11/log-wrong-upstream-port.yaml
- projects/gloo/pkg/plugins/kubernetes/eds.go
Gloo pod will now log a clear message when an upstream's port does not match that of its underlying kubernetes service.
This doesn't resolve the issue because it doesn't update the status on the upstream resource. We already have an issue (https://app.asana.com/0/1148785095952953/1161331415562787/f) to resolve this that we previously put on the back burner because it was more time consuming than anticipated.
> Wrong upstream port

- changelog/v1.4.0-beta11/add-helm-value-disable-vwh.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
- install/helm/gloo/values-template.yaml
Adds a helm values that allows users to disable the validating admission webhook while leaving the rest of validation enabled. This lets users leverage the exposed validation api without being forced to deploy the webhook, which some customers have been unable to do contractually.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3016
> Allow disable validation webhook

- changelog/v1.4.0-beta12/fix-deprecated-filter-name.yaml
- projects/gloo/pkg/plugins/extauth/plugin.go
Update deprecated 'envoy.ext_authz' field to 'envoy.filters.http.ext_authz'.
> update deprecated filter name

- changelog/v1.4.0-beta12/fix-valid-invalid-regression-test-flakes.yaml
- test/kube2e/gateway/gateway_test.go
Fix regression test flakes that occurred when we enabled validation before all invalid resources had been removed
We have hit flakes in CI related to this often lately, should ease dev experience greatly.
> Fix regression test flake with valid/invalid virtual services

- changelog/v1.3.28/fix-nodeport-value-bug
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
backport of https://github.com/solo-io/gloo/pull/3044
small helm fix for setting nodeport values in helm
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3015
> Fix nodeport helm chart bug (#3044)

- changelog/v1.4.0-beta12/fix-ingress-controller.yaml
- docs/content/guides/integrations/ingress/_index.md
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/10-ingress-deployment.yaml
- projects/ingress/api/v1/solo-kit.json
- projects/ingress/pkg/api/v1/translator_snapshot.sk.go
- projects/ingress/pkg/api/v1/translator_snapshot_emitter.sk.go
- projects/ingress/pkg/api/v1/translator_snapshot_simple_emitter.sk.go
- projects/ingress/pkg/setup/opts.go
- projects/ingress/pkg/setup/setup_syncer.go
- projects/ingress/pkg/status/status_syncer_test.go
- projects/ingress/pkg/translator/translate.go
- projects/ingress/pkg/translator/translate_test.go
- projects/ingress/pkg/translator/translator_syncer.go
this pr makes 3 changes to the `ingress` controller:
- fix a bug that cause ingress controller to stop processing ingresses when a config error is detected
- add support for Ingress objects which use named ports
- add support for customizing the Ingress class used by Gloo (via helm / env var) 
https://github.com/solo-io/gloo/issues/3051
https://github.com/solo-io/gloo/issues/3050
https://github.com/solo-io/gloo/issues/3047
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3051
resolves https://github.com/solo-io/gloo/issues/3050
resolves https://github.com/solo-io/gloo/issues/3047
> ingress class, named port, partial snapshot processing

- changelog/v1.4.0-beta12/supress-glooctl-usage.yaml
- projects/gloo/cli/pkg/cmd/get/root_test.go
- projects/gloo/cli/pkg/cmd/root.go
Use Cobra's `SilenceUsage` property to suppress the usage message when
an error has occurred. This allows the error to be found easier in the
output.
Added a check to the "should give clear error message" test to verify,
as this should no longer differ between builds based on flags changes.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2880
> Silence usage for glooctl with error

- docs/content/guides/dev/setting-up-dev-environment.md
Updating the setting up development environment guide to remove references to using `dep`. Also added clarity around required Linux tooling and MacOS tooling.
This is in reference to issue #2987
> Remove dep references from developer guide

- changelog/v1.4.0-beta12/add-loadbalancersourceranges.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/test/helm_test.go
- install/test/val_lb_source_ranges.yaml
Refer to [k8s docs](https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service) for loadBalancerSourceRanges feature.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2358
> Support LoadBalancerSourceRanges

- changelog/v1.4.0-beta13/fix-helm-docs-for-nodeport-svc.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
Update helm docs to accurately represent nodeport service setting
> Fix helm nodeport docs

- changelog/v1.4.0-beta14/fix-spaces-around-parameter-names.yaml
- docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/transformation/parameters.proto.sk.md
- projects/gloo/api/v1/options/transformation/parameters.proto
- projects/gloo/pkg/api/v1/options/transformation/parameters.pb.go
- projects/gloo/pkg/plugins/grpc/plugin_test.go
- projects/gloo/pkg/plugins/utils/transformation/extractors.go
The gRPC header extraction settings
parameters:
headers:
foo: '{ bar }'
would fail with
reason: "1 error occurred:\n\t* Route Error: ProcessingError. Reason: *grpc.plugin:
error processing parameter: { bar } is not valid syntax. {} braces must be
closed and variable names must satisfy regex ([\\-._[:alnum:]]+)\n\n"
With this change, it should pass and work the same as if it was '{bar}'.
❓If you find this acceptable, I'll happily add a changelog item. I could use a hint on where this is tested, so that I can add a case or two. 😃 
This is an alternative to the docs fix attempted in #3112.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3123
> plugins/utils/transformation: trim spaces around parameter names

- docs/content/guides/security/auth/extauth/oauth/_index.md
fix a minor typo in the oidc docs
`.well-known/open-configuration` -> `.well-known/openid-configuration`
> Fix minor typo in oidc docs

- docs/content/guides/security/auth/extauth/opa/_index.md
A small docs improvement that could be helpful.
When checking the docs, it's not perhaps not as clear as it could be that the OPA stuff works well without the OIDC module.
Related: #3009
> docs/extauth/opa: add link, and note for using without OIDC

- changelog/v1.4.0-beta15/fix-zipkin-docs-v2.yaml
- docs/content/guides/observability/tracing.md
Fixes our docs on tracing to use zipkin v2 endpoints with the v2 api
The current documented flow is broken
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3089
> Fix zipkin v2 docs

- changelog/v1.4.0-beta15/fix-helm-run-as-user.yaml
- install/helm/gloo/templates/1-gloo-deployment.yaml
- install/helm/gloo/templates/3-discovery-deployment.yaml
- install/helm/gloo/templates/5-gateway-deployment.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/test/helm_test.go
Setting this value currently only works via a values.yaml file, not using the --set arg. This PR fixes that & adds some tests.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3152
> Fix setting custom runAsUser during helm install via --set

- changelog/v1.4.0-beta15/reduce-gateway-proxy-default-privileges.yaml
- docs/content/reference/values.txt
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
Default to running as non-root and now giving privileges to bind to ports <1024 (we use 8080 and 8443 by default). 
There's already config here that users can override in their own values.yaml, if they need these privileges for any reason, but since our default setup doesn't need them we should run with as few privileges as possible.
> Run gateway-proxy with no root privileges by default

- docs/content/guides/integrations/datadog/_index.md
This is a minor update to the DataDog integration documentation that fixes the syntax used by some commands to extract data using `jq`.
This was found while running through the steps on a local cluster
> Update DataDog integration docs with corrected jq syntax

- changelog/v1.4.0-beta16/properly-namespace-rbac.yaml
- install/helm/gloo/templates/21-namespace-clusterrole-ingress.yaml
- install/helm/gloo/templates/22-namespace-clusterrole-knative.yaml
- install/helm/gloo/templates/24-namespace-clusterrolebinding-ingress.yaml
- install/helm/gloo/templates/25-namespace-clusterrolebinding-knative.yaml
- install/test/rbac_test.go
Properly suffix all cluster-scoped RBAC resources, including those only relevant to ingress- and knative-mode installations. This ensures that multi-tenant Gloo installations will not experience conflicts on those RBAC resources.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3103
> Properly namespace ingress- and knative-mode RBAC resources

- changelog/v1.4.0-beta17/fix-ingress-status.yaml
- install/helm/gloo/templates/21-namespace-clusterrole-ingress.yaml
- projects/ingress/pkg/api/ingress/resource_client.go
- projects/ingress/pkg/status/status_syncer_test.go
In ingress mode, Gloo attempts to update Ingress resources with
`status.loadBalancer` field. However, this update is silently ignored,
per [spec-and-status]. Fixing this temporary by making a call to
`UpdateStatus` after `Update`. A proper fix potentially should include
extending ingress client with a new method `WriteStatus`. Ingress
ClusterRole has been updated to support ops for `ingresses/status`
endpoint.
Also updating a test for `status_syncer.go`: the old test worked only in
Kubernetes clusters that do not update Service status with
LoadBalancerStatus. A fixed test verified with EKS and bare-metal
cluster to make sure both modes are supported.
Updating Ingress resource with `status.loadBalancer` is required for
`external-dns`. Specifically, for AWS EKS with no ELB listed in the …
> Fix for issue #2473

- changelog/v1.4.0-beta17/default-nonroot-volumes.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
Defaults mounted volumes to 10101 so that they can be used by unprivileged users.
This was preventing extauth sidecar from accessing a unix domain socket that was mounted and defaulting to root ownership.
> Use non-root filegroup when mounting volumes

- changelog/v1.5.0-beta1/brew-unstable-prs.yaml
- ci/upload_github_release_assets.go
- go.mod
- go.sum
Stop opening PRs to homebrew-core for non-stable versions, which is disallowed per https://docs.brew.sh/Acceptable-Formulae#stable-versions.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3178
> Stop opening PRs to homebrew-core for non-stable glooctl versions

- changelog/v1.5.0-beta1/update-dev-portal-install-docs.yaml
- changelog/v1.5.0-beta2/update-dev-portal-install-docs.yaml
- docs/content/guides/dev_portal/_index.md
Document developer portal install instructions in the [docs](https://docs.solo.io/gloo/latest/guides/dev_portal/#enabling-the-developer-portal-feature-in-gloo).
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3146
> Add `glooctl` install instructions to dev portal docs

- changelog/v1.5.0-beta1/improve-als-logs.yaml
- changelog/v1.5.0-beta2/improve-als-logs.yaml
- docs/content/guides/security/access_logging/_index.md
Add note to access logging docs that may have tripped up users trying to log headers in gRPC access logs.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3122
> Docs als headers to log

- changelog/v1.5.0-beta4/add-ingress-envoy-host-port-rule.yaml
- projects/ingress/pkg/translator/translate.go
- projects/ingress/pkg/translator/translate_test.go
Gloo in ingress mode should add two Envoy rules: first for the Ingress host, second for the Ingress port and port.
This fixes bug #3244
Gloo in ingress mode adds an Envoy rule that matches a host specified in
Ingress, but does not add a rule that matches a host and a port (80 or
443). This creates an issue for proxying GRPC services, because most of
the standard GRPC clients (grpcurl, Go, Python) use GRPC endpoint for
:authority header, if authority is not explicitly specified.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3244
> Ingress: add Envoy host with port rule

- changelog/v1.5.0-beta4/replace-invalid-routes-doc.yaml
- docs/content/operations/production_deployment/_index.md
Note replacing invalid routes on production deployment docs page, as this is common in prod deployments.
> Docs replacing invalid routes

- changelog/v1.4.2/add-ingress-envoy-host-port-rule.yaml
- projects/ingress/pkg/translator/translate.go
- projects/ingress/pkg/translator/translate_test.go
Gloo in ingress mode should add two Envoy rules: first for the Ingress host, second for the Ingress port and port.
This fixes bug #3244
Gloo in ingress mode adds an Envoy rule that matches a host specified in
Ingress, but does not add a rule that matches a host and a port (80 or
443). This creates an issue for proxying GRPC services, because most of
the standard GRPC clients (grpcurl, Go, Python) use GRPC endpoint for
:authority header, if authority is not explicitly specified.
> Backport: Ingress: add Envoy host with port rule

- changelog/v1.5.0-beta4/fix-enterprise-helm-install-command.yaml
- docs/content/installation/enterprise/_index.md
The enterprise helm install docs haven't been updated since helm 3's release, so it was not immediately clear to users that in this scenario the command was for helm 2 (instead of helm 3, like the rest of our docs).
This PR updates the command to work for helm 2 and 3
> Fix enterprise install docs

- changelog/v1.5.0-beta4/glooctl-debug-logs-text-file-output.yaml
- projects/gloo/cli/pkg/cmd/debug/debug.go
- projects/gloo/cli/pkg/cmd/debug/debug_test.go
This fixes a small bug in the glooctl debug command, in which the logs sub-command only respected the -f flag when --zip was also included. The command's functionality now matches the behavior specified in the docs by outputting logs to a text file when -f <filename> is included without --zip.
See https://github.com/solo-io/gloo/issues/3124
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3124
> Issue 3124 - make 'glooctl debug logs -f' actually save to file

- changelog/v1.5.0-beta4/opa-version-logging-doc.yaml
- docs/content/guides/security/auth/extauth/opa/_index.md
Update docs to note OPA version logging added for https://github.com/solo-io/gloo/issues/3136
> Log opa version docs

- changelog/v1.5.0-beta5/glooe-helm-upgrade-docs-correction.yaml
- docs/content/operations/upgrading/1.3.0.md
The apiserver-ui service's type was changed in the 1.4.0 upgrade. This change can't be automatically managed by helm, and causes attempts to upgrade GlooE via helm to fail. The easy solution is to delete the apiserver-ui service just before upgrading GlooE. This is safe because the apiserver-ui service just manages the GlooE dashboard, which can be briefly down with no major consequences.
https://github.com/solo-io/gloo/issues/3250
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3250
> I3250 helm upgrade docs fix

- changelog/v1.5.0-beta5/no-tls-inspector.yaml
- docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
- projects/gloo/api/v1/proxy.proto
- projects/gloo/pkg/plugins/registry/registry.go
- projects/gloo/pkg/plugins/tcp/plugin.go
- projects/gloo/pkg/plugins/tcp/plugin_test.go
- projects/gloo/pkg/plugins/tcp/tcp_suite_test.go
- test/kube2e/gateway/gateway_test.go
This PR fixes the bug which was causing the forward sni cluster name tcp proxy feature to not work properly.
When a ServerName match is present, envoy automatically adds the TlsInspector filter, which is how the SniCluster gets the cluster name to route too. However, with no Server Name match, this filter doesn't get appended and causes the routing to fail.
I ran into this bug while creating a TCP proxy with the forward sni cluster name host type, and an Ssl Config with no SniDomains.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3288
> Prepend TlsInspector Listener filter when no ServerName matches are present in Tcp Proxy

- changelog/v1.5.0-beta5/route-table-errors.yaml
- projects/gateway/pkg/translator/converter.go
- projects/gateway/pkg/translator/converter_test.go
- projects/gateway/pkg/translator/http.go
- projects/gateway/pkg/translator/route_table_selector_test.go
Properly validate `RouteTable` routes without matchers. Like with regular `VirtualService` routes, these routes will be assigned the default `/` prefix matcher. Consequently, the route is valid only if the parent route also has a `\` prefix matcher (either explicitly defined, or by default).
This also adds a change so that delegation cycle errors are reported on the offending `RouteTable`, not only on `VirtualServices` that use the table.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3291
> Improve checks on delegated routes

- changelog/v1.5.0-beta6/fix-gateway-extauth-overrides.yaml
- projects/gloo/pkg/plugins/extauth/filter.go
- projects/gloo/pkg/plugins/extauth/filter_test.go
- projects/gloo/pkg/plugins/extauth/plugin.go
- projects/gloo/pkg/plugins/extauth/plugin_test.go
Virtualhost, route, and weighted destination configuration is lower level, and if provided, intended to override higher level configuration.
This behavior works for extauth settings configured in Gloo `Settings`, our global settings store. In Gloo 1.4, we added support for listener-level configuration of the envoy extauth filter (e.g., allowing for multiple extauth servers, one for each listener). In the added listener-level config (exposed on the Gloo `Gateway` object), these lower-level overrides were not working.
Users ran into this bug trying to disable extauth on a route while inheriting configuration from gateway-level extauth.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3270
> Fix gateway-level extauth to allow it to be overriden by virtualhost, route, and weighted destination config

- changelog/v1.4.3/fix-gateway-extauth-overrides.yaml
- changelog/v1.5.0-beta6/fix-gateway-extauth-overrides.yaml
- projects/gloo/pkg/plugins/extauth/filter.go
- projects/gloo/pkg/plugins/extauth/filter_test.go
- projects/gloo/pkg/plugins/extauth/plugin.go
- projects/gloo/pkg/plugins/extauth/plugin_test.go
backport of https://github.com/solo-io/gloo/pull/3300
Virtualhost, route, and weighted destination configuration is lower level, and if provided, intended to override higher level configuration.
This behavior works for extauth settings configured in Gloo `Settings`, our global settings store. In Gloo 1.4, we added support for listener-level configuration of the envoy extauth filter (e.g., allowing for multiple extauth servers, one for each listener). In the added listener-level config (exposed on the Gloo `Gateway` object), these lower-level overrides were not working.
Users ran into this bug trying to disable extauth on a route while inheriting configuration from gateway-level extauth.
> Backport gw level fixes

- changelog/v1.5.0-beta8/vs-status.yaml
- projects/gateway/pkg/syncer/translator_syncer.go
- projects/gateway/pkg/syncer/translator_syncer_test.go
Use the proxy status when calculating if we need to update the status of a gateway resource. 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3115
> hash proxy status and not spec

- .github/pull_request_template.md
- BUILD.md
- Makefile
- changelog/v1.5.0-beta9/fix-go-tool-versioning.yaml
- ci/check-code-and-docs-gen.sh
- ci/tools.go
- docs/content/guides/dev/setting-up-dev-environment.md
- go.mod
- go.sum
Prior to this change, we were installing the `go` tools we require during builds by `go get`ting a specific version of executable packages, e.g.:
```
go get -v golang.org/x/tools/cmd/goimports@v0.0.0-20200423205358-59e73619c742
``` 
The problem with this approach is that it creates an alternative source of truth for go library versions (the main one being the `go.mod` file). When there is drift between the two, these commands can impose unintended version constraints, which would break our build process.
The solution is to have the `go.mod` file determine the versions of the `go` tools to install, as described [here](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module).
~~- [ ] I have made corresponding changes to the documentation~~ N/A
~~- [ ] I have …
> Use recommended way of pinning go tools

- changelog/v1.5.0-beta14/fix-glooctl-panic.yaml
- projects/gloo/cli/pkg/cmd/check/root.go
This change fixes a bug in glooctl check which caused a panic for users with virtual services that do not use extauth auth config refs.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3391
> fix panic by checking that the auth config ref is not nil

- changelog/v1.5.0-beta14/envoy-v3-minor-addition.yaml
- projects/gloo/hack/envoy.yaml
- projects/gloo/hack/run-gloo.sh
- test/services/envoy.go
One more set of changes I missed for the first section of the envoy v3 upgrade
> replace deprecated Cluster.hosts

- .github/workflows/regression-tests-and-codegen.yaml
- changelog/v1.5.0-beta14/setup-protoc.yaml
This is needed to use older versions of protoc, which now counts
v3.6.1. This will fix the broken github actions in CI.
> Use solo-io fork of setup-protoc

- .github/workflows/regression-tests-and-codegen.yaml
- changelog/v1.5.0-beta14/fix-glooctl-linux-federation-demo.yaml
- projects/gloo/cli/pkg/cmd/demo/federation.go
Fix glooctl linux federation demo. Previously, $managementPlane and $controlPlane were not defined in the script, so these commands fail to retrieve the IP address needed for cluster registration. This has been fixed.
BOT NOTES: 
resolves https://github.com/solo-io/gloo-fed/issues/239
> fix glooctl linux federation demo

- changelog/v1.4.7/validation-api-handles-lists.yaml
- projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
- projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook_test.go
backport of https://github.com/solo-io/gloo/pull/3434
This updates the gateway validation API to handle a list of gateway resources and validate them together against the current gateway snapshot (the gateway controller's view of the world).
Users wanted this feature to validate large change-sets against our validation API (that backs the validation webhook) before committing them to git (e.g., gitops approach)
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3261
> Validation API now handles list of gateway resources (#3434)

- changelog/v1.5.0-beta14/validation-api-handles-yaml.yaml
- go.mod
- projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
- projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook_test.go
- projects/gateway/pkg/syncer/setup_syncer.go
- projects/gateway/pkg/translator/opts.go
- test/services/gateway.go
Validation endpoint API now supports yaml encoding. e.g.:
```yaml
request:
kind:
group: gateway.solo.io
kind: VirtualService
version: v1
name: vs
namespace: namespace
object:
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
creationTimestamp: null
name: vs
namespace: namespace
spec:
virtualHost:
domains:
- '*'
routes:
- directResponseAction:
body: "Gloo and Envoy are configured correctly!\n\nDelete the 'vs Virtual Service to get started. \t\n"
status: 200
matchers:
- prefix: /
status: {}
oldObject: null
operation: CREATE
options: null
resource:
group: ""
resource: ""
version: ""
uid: "1234"
userInfo: {}
```
sent in body of request with `application/x-yaml` for the content-type header.
Users wanted this as a convenience since the config they are validating is already yaml.
BOT …
> Support yaml in the gateway validation API

- changelog/v1.5.0-beta14/graceful-shutdown.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
Add a set of helm options to support performing a "graceful shutdown" of envoy when gloo is sitting behind external loadbalancers that are outside of the Kubernetes context.
The main functionality is provided via a k8s `preStop` hook which will be called prior to the envoy pod being terminated. This hook will first call the envoy admin interface to explicitly begin failing healthchecks (that have been configured via the health check filter), and then sleep for a certain, customized amount of time.
This sleep period will allow for envoy to fail the healthchecks that the external loadbalancers are relying on, causing the envoy instance to be removed as a healthy endpoint, while still able to handle existing requests, etc.
For example, when using an AWS ALB with target groups of envoy …
> add graceful shutdown

- changelog/v1.5.0-beta14/validation-api-handle-dry-run.yaml
- projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
- projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook_test.go
- projects/gateway/pkg/validation/validator.go
- projects/gateway/pkg/validation/validator_test.go
The gateway validation API and webhook indicated that the API had no side-effects (see [here](https://github.com/solo-io/gloo/blob/v1.5.0-beta13/install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml#L25)), when in actuality, the API would modify its internal cache regardless of the dry-run value in the admission request.
This PR updates the validation API to handle dry-run requests and only modify the internal cache when necessary.
To accomplish this, a minor refactor was required and some logic was moved from the admission webhook code into the validator. The first commit (https://github.com/solo-io/gloo/commit/93992c5a2b3c24e5cd692e7ac89c06f3ed9ae600) only has the refactor, so reviewing that first and then the following commits may help the reviewer.
BOT NOTES: …
> Fix validation API to support dry run

- changelog/v1.4.8/validation-api-handle-dry-run.yaml
- projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
- projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook_test.go
- projects/gateway/pkg/validation/validator.go
- projects/gateway/pkg/validation/validator_test.go
backport of https://github.com/solo-io/gloo/pull/3455
The gateway validation API and webhook indicated that the API had no side-effects (see [here](https://github.com/solo-io/gloo/blob/v1.5.0-beta13/install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml#L25)), when in actuality, the API would modify its internal cache regardless of the dry-run value in the admission request.
This PR updates the validation API to handle dry-run requests and only modify the internal cache when necessary.
To accomplish this, a minor refactor was required and some logic was moved from the admission webhook code into the validator. The first commit (https://github.com/solo-io/gloo/commit/93992c5a2b3c24e5cd692e7ac89c06f3ed9ae600) only has the refactor, so reviewing that first and then the …
> Fix validation API to support dry run (#3455)

- changelog/v1.4.8/graceful-shutdown.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
backport of https://github.com/solo-io/gloo/pull/3435
Add a set of helm options to support performing a "graceful shutdown" of envoy when gloo is sitting behind external loadbalancers that are outside of the Kubernetes context.
The main functionality is provided via a k8s `preStop` hook which will be called prior to the envoy pod being terminated. This hook will first call the envoy admin interface to explicitly begin failing healthchecks (that have been configured via the health check filter), and then sleep for a certain, customized amount of time.
This sleep period will allow for envoy to fail the healthchecks that the external loadbalancers are relying on, causing the envoy instance to be removed as a healthy endpoint, while still able to handle existing requests, etc.
For example, …
> add graceful shutdown (#3435)

- changelog/v1.5.0-beta20/fix-demo.yaml
- projects/gloo/cli/pkg/cmd/demo/federation.go
Now that we have the `gateway_proxy.GATEWAY_PROXY_NAME.failover.enabled` helm value, we can use that in the gloo fed demo script.
It effectively replaces this operation:
```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
name: failover-gateway
namespace: gloo-system
labels:
app: gloo
spec:
bindAddress: "::"
bindPort: 15443
tcpGateway:
tcpHosts:
- name: failover
sslConfig:
secretRef:
name: failover-downstream
namespace: gloo-system
destination:
forwardSniClusterName: {}
---
apiVersion: v1
kind: Service
metadata:
labels:
app: gloo
gateway-proxy-id: gateway-proxy
gloo: gateway-proxy
name: failover
namespace: gloo-system
spec:
ports:
- name: failover
nodePort: 32000
port: 15443
protocol: TCP
targetPort: 15443
selector:
gateway-proxy: live
gateway-proxy-id: …
```
> Use failover.enabled helm value in gloo fed demo

- docs/content/introduction/architecture/deployment_arch.md
Documentation change to fix broken link and typo I found in reviewing deployment_arch doc
> fix deployment_arch doc broken link and typo

- docs/content/guides/traffic_management/listener_configuration/_index.md
Fixed https://docs.solo.io/gloo/latest/guides/traffic_management/listener_configuration/ to correct command blocks that didn't copy-paste properly, plus a yaml highlighting fix.
> fixed listener config code blocks to clarify and fix copy-paste errors

- .github/workflows/add-pr-label.yaml
- changelog/v1.5.0-beta21/add-pr-label-adder.yaml
adds GH action to add label titled "keep pr updated", which signals to bulldozer to keep our PRs up to date
> Enable bulldozer keep pr updated

- changelog/v1.5.0-beta21/knative-ingress-local-domains.yaml
- projects/clusteringress/pkg/translator/translate_test.go
- projects/knative/pkg/translator/translate.go
- projects/knative/pkg/translator/translate_test.go
Since Knative started expanding the cluster local domains by https://github.com/knative/serving/pull/9100, Gloo does not need to expand it anymore.
This patch stops to call `expandHosts()`.
> Use set to expand cluster local service domains for Knative

- changelog/v1.5.0-beta21/ingress-proxy-label.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
- install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
- install/helm/gloo/templates/13-ingress-proxy-service.yaml
- install/helm/gloo/values-template.yaml
- projects/ingress/pkg/setup/opts.go
- projects/ingress/pkg/setup/setup_syncer.go
Added a new Helm value for ingress proxy label. A unique value for the label is required if one wants to have several ingress proxy instances in the same cluster.
This fixes #3587.
When a user want to install more than one Gloo Ingress instance to the same cluster, they need to use a unique value for label "gloo" for ingress proxy Service.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3587
> Allow changing ingress proxy label

- .githooks/pre-commit
- .githooks/pre-commit-python.py
- changelog/v1.5.0-beta22/githook-mac-fix.yaml
- hook-test
Fixes a mac bug in the JWT githook introduced by the linux fix, and changes the git command used to get recent changes to the correct command.
> Githook fix

- changelog/v1.5.0-beta22/update-dev-portal-docs.yaml
- docs/content/guides/dev_portal/_index.md
Update the Dev Portal section of the Gloo docs to redirect users to the new [Dev Portal docs](https://docs.solo.io/dev-portal/latest).
> Update dev portal docs

- changelog/v1.4.13/ingress-proxy-label.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
- install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
- install/helm/gloo/templates/13-ingress-proxy-service.yaml
- install/helm/gloo/values-template.yaml
- projects/ingress/pkg/setup/opts.go
- projects/ingress/pkg/setup/setup_syncer.go
Added a new Helm value for ingress proxy label. A unique value for the label is required if one wants to have several ingress proxy instances in the same cluster.
This fixes #3587, backport of #3590.
When a user want to install more than one Gloo Ingress instance to the same cluster, they need to use a unique value for label "gloo" for ingress proxy Service.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3587
> Backport: Allow changing ingress proxy label

- changelog/v1.5.0-beta23/remove-dangling-comments.yaml
- install/helm/gloo/values-template.yaml
Realized that I forgot to remove the comments associated with the ratelimit value in my previous commit for this. Doing so now.
original PR: https://github.com/solo-io/gloo/pull/3539/files
Issue Link: https://github.com/solo-io/gloo/issues/3467
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3467
> Remove dangling ratelimit comments

- projects/gateway/pkg/validation/validator.go
Fix debug statement to use `Debugf`
Incorrect log function
> fix debugf statement in validator

- changelog/v1.5.0-beta25/istio-inject-fix.yaml
- docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
- projects/gloo/cli/pkg/cmd/istio/util.go
To fix https://github.com/solo-io/gloo/issues/3641, use only the Gloo OS pods (gateway, ingress, discovery) to determine Gloo OS version to be used in the SDS sidecar.
Users ran into this bug using `glooctl istio inject` with GlooE.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3641
resolves https://github.com/solo-io/gloo/issues/3640
> Fix glooctl istio inject for GlooE

- .github/workflows/regression-tests-and-codegen.yaml
- changelog/v1.5.0-beta26/istio-1-7-1-fix.yaml
- projects/gloo/cli/pkg/cmd/istio/enable_mtls.go
- projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.6.go
- projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7.go
Added ISTIO_META_CLUSTER_ID, which is now required by these versions.
Istio v1.6.9 and 1.7.1 were throwing errors when we tried to install them with the [glooctl Istio mTLS integration](https://docs.solo.io/gloo/latest/guides/integrations/service_mesh/gloo_istio_mtls/). Versions 1.6.8 and 1.7.0 were still working fine.
These new versions need "ISTIO_META_CLUSTER_ID" explicitly set, which is what this PR does.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3650
> Fix Istio 1.7.1+ and Istio 1.6.9+

- changelog/v1.5.0-beta26/route-basic-ratelimit-docs.yaml
- docs/content/guides/security/rate_limiting/simple/_index.md
Add docs for the route-level rate limiting feature added [here](https://github.com/solo-io/solo-projects/pull/1879).
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2517/
> Basic ratelimit docs - route-level rate limits

- docs/content/guides/integrations/datadog/_index.md
For all envoy logs to be captured and sent to datadog, the following update was required 
`ad.datadoghq.com/gateway-proxy.logs: '[{"source": "envoy", "service": "gloo","log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date","pattern" : "^\\[[0-9]{4}-[0-9]{2}-[0-9]{2}|{"}]}]' `
> Fix datadog integration annotation in doc

- changelog/v1.6.0-beta1/fix-glooctl-install-output.yaml
- projects/gloo/cli/pkg/cmd/install/installer.go
Fix misleading message in `glooctl install` output when the install namespace already exists.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3704
> Fix misleading message in `glooctl install` output

- install/nomad/demo-vagrant.sh
This PR updates the pinned Gloo versions running in the Nomad / Vagrant demo to `1.4.13`
Running the demo at `/install/nomad/demo-vagrant.sh`, I consistently ran into issues where the Nomad job specifications couldn't complete their placement of all of the Gloo tasks because `gateway-proxy` wouldn't stay healthy:
MAY be related to solo-io/gloo#2404
> fix: update Gloo image version in Nomad/Vagrant demo

- changelog/v1.6.0-beta1/invalid-rts.yaml
- install/helm/gloo/templates/18-settings.yaml
- install/test/helm_test.go
- test/kube2e/helm/helm_test.go
- test/kube2e/util.go
Fix helm chart to honor `.Values.settings.replaceInvalidRoutes` value.
> Fix helm chart to honor `.Values.settings.replaceInvalidRoutes` value.

- changelog/v1.5.1/invalid-rts.yaml
- install/helm/gloo/templates/18-settings.yaml
- install/test/helm_test.go
- test/kube2e/helm/helm_test.go
- test/kube2e/util.go
backport of (#3725)
Fix helm chart to honor `.Values.settings.replaceInvalidRoutes` value.
> Fix helm chart to honor `.Values.settings.replaceInvalidRoutes` value

- changelog/v1.6.0-beta2/unpin-curl.yaml
- ci/extended-docker/Dockerfile
unpin curl in extended docker image flow as base containers have differing requirements and can't all be satisfied by the same version
sample logs: https://console.cloud.google.com/cloud-build/builds/b4b7bdda-4e36-4f54-b918-35f7c9b16ce8;step=10?project=solo-public
note:
```
ERROR: unsatisfiable constraints:
curl-7.69.1-r1:
breaks: world[curl=7.67.0-r1]
```
> Unpin curl

- changelog/v1.6.0-beta3/homebrew-doc-update.yaml
- docs/content/installation/glooctl_setup.md
Update the glooctl install doc to remove tap reference for homebrew install. Reference issue: #3707 
The homebrew install now uses the native brew command instead of a tap.
> Homebrew update docs

- changelog/v1.6.0-beta4/helm-value-for-stats-prefix-rewrite.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
This PR adds a helm value for stats prefix rewrite
Currently it's hard-coded to `/stats/prometheus`. To integrate with
Datadog, or other monitoring system, we need to be able to change
the envoy stats endpoint.
I want to setup Datadog integration to monitor envoy as described in the docs https://docs.solo.io/gloo/latest/guides/integrations/datadog/. But there is a manual step to update the configmap.
I want to eliminate the manual step so that I can automate it.
fixes #3752 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3752
> Add helm value for stats prefix rewrite #3752

- changelog/v1.6.0-beta4/fix-bookstore-lock-oddity.yaml
- docs/examples/grpc-json-transcoding/bookstore/server.go
This fixes an instance of a RWMutex.Lock() followed by a RWMutex.RUnlock() which can cause a run-time error
This bug can be experienced while running the gRPC-JSON transcoding example from the recent 1.5 release if there is no active RLock() present
> Use Unlock in DeleteShelf Bookstore example to prevent runtime error

- SITE.md
- changelog/v1.6.0-beta4/remove-conflicting-doc-file.yaml
Remove conflicting top-level markdown document (SITE.md) claiming that documentation is not maintained in this repo 
When looking through GitHub repositories, my eye is usually first drawn to any top-level markdown files (README.md, CONTRIBUTING.md, BUILD.md, etc.) and SITE.md is one such file, although it appears to be outdated. Luckily the linked repository is well marked as deprecated and any reference in the README is using the proper doc directory in this repo, so it's a tiny problem.
> Remove conflicting doc file

- changelog/v1.6.0-beta4/fix-wrong-typed-sprintf.yaml
- pkg/utils/usage/usage_readers.go
Fix mismatched Sprintf verb in /pkg/utils/usage/usage_readers.go preventing the compilation of that file. The variable itself is a float64, but the Sprintf verb was for an integer. The "%.0f" verb was used in attempt to best replicate the written behavior.
While attempting to run `go test ./...` to lazily run all gloo tests at once, the following error would pollute the output, as the file would appear to not compile:
> ./usage_readers.go:61:28: Sprintf format %d has arg requestsCount of wrong type float64
> ./usage_readers.go:64:31: Sprintf format %d has arg connectionsCount of wrong type float64
I am unsure of what else this effects, however the closest test, /pkg/utils/utils_suite_test.go, passes both before and after the change.
> Fix mismatched Sprintf preventing compiles

- changelog/v1.6.0-beta4/helm-pass-image-pull-secret.yaml
- install/helm/gloo/templates/1-gloo-deployment.yaml
- install/helm/gloo/templates/10-ingress-deployment.yaml
- install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
- install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
- install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
- install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
- install/helm/gloo/templates/3-discovery-deployment.yaml
- install/helm/gloo/templates/5-gateway-deployment.yaml
- install/helm/gloo/templates/6-access-logger-deployment.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/templates/_helpers.tpl
- install/test/helm_test.go
Add possibility to pass imagePullSecrets section to all deployments
This bug fixes #3729
Users ran into this bug trying to pass own imagePullSecrets section to deployment
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3729
> helm: pass image pull secret to deployments

- docs/content/guides/integrations/service_mesh/gloo_app_mesh.md
The documentation mixed us-east-2 and us-west-2 and Oregon and Ohio.  This will correct that mix.  Please review to ensure that the change to the US-west-2 ELB is not impacting the intent of the documentation.
This addresses a documentation confusion around the use of us-west-2 and us-east-2 which does not directly make the documentation unusable but may confuse someone if they are not paying attention. 
There is no known bug report for this yet.
Users ran into this issue when reading the documentation. 
- [x ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [x ] I followed guidelines laid out in the Gloo [contribution guide](https://docs.solo.io/gloo/latest/contributing/)
> Correct use of us-east-2 and us-west-2

- docs/content/installation/enterprise/_index.md
- docs/content/installation/gateway/kubernetes/_index.md
- docs/content/installation/platform_configuration/cluster_setup.md
I was going through the kind installation process recently and ran across some broken links in the docs.  This PR fixes those.
> Fix broken kind links in gloo docs

- docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
Technically it works as-written because it gets routed to 127.0.0.1 ultimately, but we should fix it to make it less confusing.
> Fix docs typo in istio mTLS

- changelog/v1.6.0-beta5/helm-route-prefix-rewrite-to-ingressproxy-and-knativeproxy.yaml
- install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
- install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
- install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
- install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
- install/test/helm_test.go
Previous commit sets route prefix rewrite in gateway-proxy-envoy-config, but there are other places that should be changed too. This commit sets the value to the other places.
ref: #3752 #3759
I think the referred commit already cover the changelog for this. Do we need a new one?
> Set route prefix rewrite to ingress proxy and knative proxy configs

- docs/content/guides/integrations/aws/_index.md
AWS "specific annotaions" link [here](https://docs.solo.io/gloo/latest/guides/integrations/aws/) is broken because it no longer exists in latest k8s docs.  There is no exact equivalent of that page in latest docs.
This bug fixes the broken link by pointing at the most recent version of that page in k8s 1.17 docs.
> Fix broken AWS load balancer annotations link

- changelog/v1.6.0-beta9/docs-version-dropdown.yaml
- docs/Makefile
- docs/layouts/partials/versionnavigation.html
Add docs dropdowns for newer releases
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3402
> edit dropdown to include more versions

- changelog/v1.6.0-beta9/glooctl-check-fix-newlines.yaml
- projects/gloo/cli/pkg/cmd/check/gloo_stats.go
- projects/gloo/cli/pkg/cmd/check/root.go
Changed the deployments error message to use `Println` rather than `Printf`, for cleaner error messages.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2952
> Fix glooctl new lines on failed deployments check

- docs/content/guides/security/rate_limiting/crds/_index.md
Fix a typo in the rate limit docs
Ran into this debugging tests written based off the guide
> Fix docs typo

- docs/content/introduction/faq.md
This fixes the FAQ documentation guidance on how to assign a VirtualService to a specific Gateway when running multiple Gateways in parallel.
I ran into this erroneous documentation when setting up my own Gloo deployment with multiple Gateways, where I need to assign a subset of VirtualServices to one Gateway and a different subset to a different Gateway. The documentation changes have been verified in testing and were based on the [API reference](https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk/#httpgateway) docs.
> Fix incorrect virtualservice to gateway assignment faq guidance

- changelog/v1.6.0-beta10/invalid-vs-gateway.yaml
- projects/gloo/pkg/translator/listener.go
- projects/gloo/pkg/translator/translator_test.go
- test/e2e/gateway_test.go
- test/services/gateway.go
VS was being accepted when it had an invalid authconfig. This had the knock-on effect of the vs making it into the gateway, but since it was invalid, it invalidated the entire gateway.
This fix changes it so that the vs with the bad authconfig is itself marked invalid, does _not_ make it into the gateway, and does not block updates of the other, well-configured virtualservices.
Users ran into this when creating a virtualservice that pointed to an authconfig which didn't exist.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3538
> Missing authConfig should validate a VS, not a Gateway

- changelog/v1.6.0-beta10/istio-1-8.yaml
- docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
- projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7-1.8.go
- projects/gloo/cli/pkg/cmd/istio/sidecars/matcher.go
Add Istio 1.8.x support to Glooctl istio integrations
Istio 1.8.x is just about to be released to GA.
Istio sidecar configuration (args + env vars) from 1.7.x also works with 1.8.x with no changes required.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3855
> Add Istio 1.8.x support to glooctl integrations

- .github/workflows/regression-tests-and-codegen.yaml
- changelog/v1.6.0-beta11/update-kind.yaml
Update kind action
Fix for https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Update kind action

- changelog/v1.6.0-beta11/knative-doc-update.yaml
- docs/content/installation/knative/_index.md
Updating the Knative installation guide to include directions for clusters with an existing Knative installation. 
Resolves #1594.
> Update Knative doc for existing cluster

- changelog/v1.6.0-beta14/add-istio-clusterid-to-helm-chart.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
This PR adds the `ISTIO_META_CLUSTER_ID` environment variable with the default value of `Kubernetes` to the helm install when `istiosds.enabled` is true
Users previously added the environment variable retroactively after using the helm install, this now includes the env var in the helm install, similar to `glooctl istio inject`
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3881
> Add ISTIO_META_CLUSTER_ID to helm install

- changelog/v1.6.0-beta15/update-documentation-versions.yaml
- docs/active_versions.json
Update the release versions used in our documentation
We have updated documentation in previous releases. To make this visible to users, we need to update which deployed versions is used for our docs.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3896
resolves https://github.com/solo-io/gloo/issues/3900
> Update documentation versions

- docs/content/introduction/architecture/_index.md
Remove an obsolete reference to a one-time experimental feature called Istio-Based Route Rule Discovery. It is misleading to users.
> Remove reference to Istio-Based Route Rule Discovery

- changelog/v1.6.0-beta15/fix-multi-proxy-status.yaml
- projects/gateway/pkg/syncer/setup_syncer.go
- projects/gateway/pkg/syncer/translator_syncer.go
- projects/gateway/pkg/syncer/translator_syncer_test.go
In multi-proxy environments, resources that were invalid on one proxy (error or warning) but valid on another may have a status written of accepted, despite internally calculating (and logging) a warning. This PR fixes that, by ensuring that the map of status to write is updated internally.
It appears the code was written with the assumption that the `report` indexed from `allReports` was a pointer itself, when it was not.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3935
> Fix multi proxy status reporting

- changelog/v1.6.0-beta17/fix-enterprise-changelog-docs.yaml
- docs/cmd/changelogutils/changelog_utils.go
- docs/cmd/generate_changelog_doc.go
- docs/cmd/test/generate_changelog_doc_test.go
Currently, open source release notes only show up in the release version ordering of the enterprise changelogs. This PR adds the OS release notes to the chronological ordering of the enterprise releases (accessible if you choose "Chronological Order" on the enterprise changelogs page).
In addition, links to the open source docs of gloo from the enterprise docs are currently broken, this PR seeks to fix that.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3953
> Add Open source release notes to chronological ordering of enterprise changelog

- changelog/v1.6.0-beta18/fix-sed-ci.yaml
- ci/kind.sh
Fixes a subtle bug in our CI, where formatting on the previous line can interfere with our parsing of that log line - which we currently do to pull out the docker images built in this build run.
For example:
This currently works fine:
But if the previous line (493) has formatting, it causes a CI build issue:
> Fix sed CI flake

- .github/workflows/regression-tests-and-codegen.yaml
- changelog/v1.6.0-beta18/disable-community-docs-deploy.yaml
PR to fix current bug in CI preventing community users from passing codegen due to some sensitive enterprise-related docsgen permissions.
Users ran into this recently after we updated our docs CI.
You can see this PR's fix working in an example PR from a fork here - https://github.com/solo-io/gloo/pull/3969
> Docs CLI Fix (#3969)

- changelog/v1.6.0-beta18/helm-value-for-settings-extauth.yaml
- go.mod
- go.sum
- install/helm/gloo/templates/18-settings.yaml
- install/test/helm_test.go
Add helm values `.global.extensions.extAuth` to allow setting ext auth settings in the `Settings` k8s resource.
Previously users were using Kustomize or manually editing the resource after deployment.
- [] I have made corresponding changes to the documentation - **Note this depends on some changes to how we handle Enterprise vs open source helm values, out of scope for this PR**
Thank you to @eshepelyuk for getting us started with the contribution for this one.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/1892
> Helm extauth

- changelog/v1.6.0-beta18/fix-usptream-lambda-destination-validation.yaml
- projects/gloo/pkg/translator/clusters.go
- projects/gloo/pkg/translator/translator_test.go
fixes bug where route validation marks redirect and direct response route destinations as invalid.
Ran into this bug configuring a redirect or direct response action on a route
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3975
> Fix lambda route validation bug

- docs/content/guides/security/auth/extauth/oauth/dex/_index.md
- docs/content/guides/security/auth/extauth/oauth/google/_index.md
Now uses insecure cookie so that non-TLS localhost example works.
Before this exchange, users ran into issues following the tutorial because it was using http://localhost as the example, but the config was expecting secure cookies by default.
I've updated the Google and Dex examples. The [Okta Example](https://docs.solo.io/gloo-edge/1.6.0-beta14/guides/security/auth/extauth/oauth/okta/#secure-the-application-using-https) already walks the user through securing the app using https, so it did not need to be updated.
FIXES https://github.com/solo-io/gloo/issues/3980
> Update oauth example docs

- docs/content/guides/security/auth/extauth/oauth/_index.md
- docs/content/guides/security/auth/extauth/opa/_index.md
Docs-only change. Update any docs referencing the deprecates `oauth` syntax to instead use `oauth2` syntax.
When updating docs to include examples with insecure tokens enabled, some of the oauth examples were uploaded to oauth2. This PR updates all of the other examples across our docs to be the same oauth2 format.
> Update docs referencing oauth to use oauth2

- docs/content/guides/traffic_management/hello_world/_index.md
there is typo in virtualservice yaml example - spec: is missing
we ran into this by trying out gloo-ee with an demo app
> Update docs referencing hello world traffic management guide

- .github/workflows/add-pr-label.yaml
- changelog/v1.6.0-beta24/disable-community-pr-github-label.yaml
Do not append the `keep-pr-updated` to community pull requests
This work is done from a gloo fork to test the behavior for a community PR. If this is approved, I will open a pull request to the gloo master.
On a recent community PR, the `Add 'keep-pr-updated' Label` github action failed with:
```
Run christianvuerings/add-labels@v1
Add labels: keep pr updated to solo-io/gloo#4019
Error: Resource not accessible by integration
```
see the logs here:  (https://github.com/solo-io/gloo/runs/1599785332?check_suite_focus=true)
This modifies the action to not run for community pull requests.
> Don't add keep-pr-updated label if community PR

- changelog/v1.6.0-beta24/fix-csrf-shadow-enabled.yaml
- projects/gloo/pkg/plugins/csrf/plugin.go
Shadow Enabled mode rejects the request rather than just logging that the request triggered the CSRF filter. 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3898
> fix shadow translation

- changelog/v1.6.0-beta24/disable-rest-eds.yaml
- docs/content/reference/values.txt
- install/helm/gloo/templates/18-settings.yaml
- install/helm/gloo/values-template.yaml
- install/test/fixtures/settings/consul_config_upstream_discovery.yaml
- install/test/fixtures/settings/consul_config_values.yaml
- install/test/fixtures/settings/disable_kubernetes_destinations.yaml
- install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
- install/test/fixtures/settings/enable_default_credentials.yaml
- install/test/fixtures/settings/enable_rest_eds.yaml
- install/test/fixtures/settings/gateway_settings.yaml
- install/test/fixtures/settings/ratelimit_descriptors.yaml
- install/test/fixtures/settings/read_gateways_from_all_namespaces.yaml
- install/test/fixtures/settings/sts_discovery.yaml
- install/test/helm_test.go
- projects/gloo/pkg/xds/utils.go
Disable REST EDS server by default, which is no longer necessary now that upstream envoy has fixed https://github.com/envoyproxy/envoy/issues/13070
REST EDS was a workaround to avoid the bug in envoy, but we now depend on [envoy-gloo 1.17.0-rc3](https://github.com/solo-io/gloo/blob/c24a007d91165b08a04215a6a7d0f7a54e03245a/Makefile#L24) which itself depends on envoy https://github.com/solo-io/envoy-gloo/blob/master/bazel/repository_locations.bzl#L4 from commit [6be36debaf627925ebf5e22e84e7e066191b14d5](https://github.com/envoyproxy/envoy/tree/6be36debaf627925ebf5e22e84e7e066191b14d5)
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3805
> Disable rest eds

- changelog/v1.6.0-beta26/report-invalid-namespaces.yaml
- projects/gloo/pkg/plugins/kubernetes/plugin.go
- projects/gloo/pkg/plugins/kubernetes/plugin_test.go
- projects/gloo/pkg/plugins/kubernetes/uds.go
Adds a check in the kubernetes plugin to ensure that it actually found a non-nil ServiceLister from the call to `p.kubeCoreCache.NamespacedServiceLister(kube.Kube.ServiceNamespace)`, along with a test to ensure that it's working as expected. The code works, but it begs some questions about the solo-kit code behind this.
[The solo-kit lister functions](https://github.com/solo-io/solo-kit/blob/master/pkg/api/v1/clients/kube/cache/cache.go#L279) short circuit if they're scoped to all namespaces. When that's the case, the function creates and returns a new lister for any inputted namespace without any checks. This is why this error only occurred when gloo was namespace-restricted; it never reached line 283 of the above code otherwise. Do we want this behavior, or should we also see this error …
> report invalid namespaces

- changelog/v1.7.0-beta1/document-glooctl-upgrade.yaml
- docs/content/installation/glooctl_setup.md
Docs only update.
Documents existing `glooctl upgrade` functionality better, and explicitly explains `upgrade` can be used to go up _or down_ versions.
This is an improvement suggested in https://github.com/solo-io/gloo/issues/4037 . I'm not marking that issue as resolved yet, as there is another suggestion to add an alias for `glooctl upgrade` to make it clearer that it can be used to upgrade or downgrade. eg `glooctl set-version` or similar.
> Update glooctl docs for upgrades

- docs/content/installation/advanced_configuration/wasm.md
(Docs only change)
V0.3 of this wasm header is ABI 0_1_0, updating docs to use v0.5, as Gloo Edge 1.6.0 uses ABI 0_2_1
> Update docs to use newer example filter

- changelog/v1.7.0-beta2/additional-short-circuiting-validation.yaml
- projects/gateway/pkg/translator/http.go
- projects/gateway/pkg/translator/translator_test.go
Gloo Edge now proactively reports warnings on virtual services that have matchers that are short-circuited. To enable, update the Gloo `Settings` such that `spec.gateway.validation.warnRouteShortCircuiting=true`. The cases now additionally covered are:
- routes that have simple OR regex header matchers, ensuring each one of the OR'ed matchers can be reached
- the same logic, but with method matchers
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3334
> Additional route short-circuiting validation

- changelog/v1.7.0-beta7/validate-latest-docs-version.yaml
- docs/build-docs.sh
Adds validation to `build_docs.sh` to make sure that `latestVersion` is included in `activeVersions`.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4050
> Docs build validate latest

- changelog/v1.7.0-beta7/proxy-specific-config-dump-services.yaml
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/test/helm_test.go
This is a change to a template that only changes if you enable the `readConfigMulticluster` helm value. Instead of creating a default `gateway-proxy-config-dump-service`, create one service that is `[gateway-proxy-name]-config-dump-service` for each of the listed gatewayProxies in the helm chart. This allows us to address the edge case of having custom gateway proxies added by users.
> Add gateway-proxy-specific services

- changelog/v1.7.0-beta7/fix-leak-timer.yaml
- projects/gloo/pkg/plugins/consul/eds.go
Stop leaking memory for a timer in consul EDS.
We were calling `timer.Stop()` in a for loop rather than before it.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4112
> Consul timer leak

- changelog/v1.7.0-beta9/service-name-suffix-constant.yaml
- projects/gateway/pkg/defaults/gateway.go
If the readConfig and readConfigMulticluster helm values are enabled, gloo-fed will be able to query a service named: [gatewayProxyName]-config-dump-service. In case this changes, make the -config-dump-service suffix a constant used across both repos.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4173
> Add ConfigDumpServiceSuffix constant

- changelog/v1.7.0-beta9/update-k8s-19.yaml
Add DEPENDENCY_BUMP type to changelog for k8 1.19 upgrade.
> add dep bump to changelog for 1.19

- changelog/v1.7.0-beta10/docs-link-fix-datadog.yaml
- docs/content/guides/integrations/datadog/_index.md
Fix broken link to install guide in datadog docs
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4100
> Fix broken link in docs

- cloudbuild.yaml
- test/consulvaulte2e/consul_vault_test.go
- test/e2e/access_log_test.go
- test/e2e/aws_ec2_test.go
- test/e2e/aws_test.go
- test/e2e/buffer_test.go
- test/e2e/consul_test.go
- test/e2e/cors_test.go
- test/e2e/csrf_test.go
- test/e2e/custom_auth_test.go
- test/e2e/fault_injection_test.go
- test/e2e/gateway_test.go
- test/e2e/grpc_json_test.go
- test/e2e/grpc_plugin_test.go
- test/e2e/grpcweb_test.go
- test/e2e/gzip_test.go
- test/e2e/happypath_test.go
- test/e2e/health_checks_test.go
- test/e2e/ratelimit_test.go
- test/e2e/route_transformation_test.go
- test/e2e/staged_transformation_test.go
- test/e2e/util_test.go
- test/e2e/zipkin_test.go
- test/services/envoy.go
- test/services/gateway.go
This adds RunWithRoleAndRestXds to the envoy tests being run.
> Add Rest XDS to envoy tests

- changelog/v1.7.0-beta13/endpoint-discovery-flake-test.yaml
- test/e2e/gzip_test.go
Fix a flake in gzip e2e tests where requests sometimes were tested before new gateway config was written.
Example of this occurring in CI - https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=c0fe9d63-b901-4afc-954e-c29f62cf2a93&authuser=1
> Fix gzip flake

- docs/content/guides/traffic_management/_index.md
- docs/content/introduction/architecture/concepts.md
Remove obsolete references to AMQP support and refresh surrounding text w.r.t. NATS, XML/SOAP, OpenFaaS, Azure Functions.
> Remove obsolete references to AMQP support + others

- docs/content/guides/security/csrf/_index.md
Small documentation fix, in this context I'm pretty sure we're talking Firewall, not Framework
N/A
> Fix incorrect WAF acronym expansion

- docs/content/installation/gateway/kubernetes/_index.md
be explicit about using kubectl, and not use the alias `k`
This bug claifies documentation
> documentation change.  clarify, `k` -> `kubectl`

- docs/content/guides/traffic_management/destination_types/discovered_upstream/_index.md
Users noticed this guide was missing the step to enable FDS
> Fix docs example with FDS step skipped

- docs/cmd/generate_docs.go
Security scan docs missing versions because of semver error check
> Fix semver check for security scan versions

- changelog/v1.7.0-beta21/fix-replace-invalid-config-helm-values.yaml
- install/helm/gloo/templates/18-settings.yaml
- install/test/fixtures/settings/consul_config_upstream_discovery.yaml
- install/test/fixtures/settings/consul_config_values.yaml
- install/test/fixtures/settings/disable_kubernetes_destinations.yaml
- install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
- install/test/fixtures/settings/enable_default_credentials.yaml
- install/test/fixtures/settings/enable_rest_eds.yaml
- install/test/fixtures/settings/gateway_settings.yaml
- install/test/fixtures/settings/ratelimit_descriptors.yaml
- install/test/fixtures/settings/read_gateways_from_all_namespaces.yaml
- install/test/fixtures/settings/sts_discovery.yaml
- install/test/helm_test.go
InvalidConfigPolicy was incorrectly mapped in the settings template. Updated mapping and test.
Users ran into this bug: https://github.com/solo-io/gloo/issues/4321
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4321
> bug fix for settings invalidConfigPolicy helm value

- docs/content/guides/security/auth/extauth/oauth/dex/_index.md
- docs/content/installation/advanced_configuration/extauth_custom_ca.md
The Dex integration [guide](https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/oauth/dex/#install-dex) has a note with an embedded versioned_link_path that does not render properly and also contains an incorrect link.  This PR fixes that along with some other small editorial issues.
> fix extauth_custom_ca doc link

- changelog/v1.7.0-beta21/fix-helm-gateway-proxies-deep-merge.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/templates/8-default-gateways.yaml
- install/helm/gloo/templates/8-gateway-proxy-horizontal-pod-autoscaler.yaml
- install/helm/gloo/templates/8-gateway-proxy-pod-disruption-budget.yaml
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
- install/test/helm_suite_test.go
Adds on to the https://github.com/solo-io/gloo/pull/4182 PR to resolve issues related to not having default gateway proxy helm values merged into custom gateway probes.
There have been a few related issues (#3946, #3142, #4295)  opened where users were not seeing the default gateway proxy values included in custom gateway proxies. This uses helm `deepcopy` and `merge` to deep merge those values.
Helm 2 does not support `deepcopy` and causes tests failures. Since Helm 2 is not supported for this, that test renderer was also removed.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3142
> Fix helm gateway proxy merge

- changelog/v1.7.0-beta21/add-helm-gateway-proxy-tests.yaml
- install/test/helm_test.go
This adds helm tests that verifies that when there are multiple gateway proxies, the default proxy values are used and can be overwritten by values for the custom gateway proxies.
The PR with the code changes is https://github.com/solo-io/gloo/pull/4332 - this PR adds tests cases for those changes.
> Add tests for helm changes

- .github/workflows/update-solo-apis.yaml
> fix extra v in branch name

- projects/gloo/pkg/xds/envoy.go
Provide comments for future developers to understand why we are still serving v2 envoy config.
We decided that as long as the go-control-plane doesn't remove the v2 discovery code, we can continue to rely on it to serve ext-auth and rate-limit config. We created a github issue to track this tech debt, and this comment is being added to provide context to developers who don't understand why we are referencing a deprecated envoy API.
> Add comment around v2 xDS server

- changelog/v1.7.0-beta26/add-helm-log-level-env-variables.yaml
- docs/content/operations/debugging_gloo/_index.md
- go.mod
- go.sum
- install/helm/gloo/templates/1-gloo-deployment.yaml
- install/helm/gloo/templates/3-discovery-deployment.yaml
- install/helm/gloo/templates/5-gateway-deployment.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/test/helm_test.go
This change goes alongside https://github.com/solo-io/go-utils/pull/436 where we enable the stats server to set the log level by the `LOG_LEVEL` environment variable. This PR updates the Helm deployment templates to include that new environment variable that can be set in the values file.
I've tested that log level changes for the gloo resources and envoy components locally when the corresponding log level values are set.
Users have been asking for a way to declaratively define the log level for each Gloo & Envoy resource.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4090
> Helm log level env var

- test/kube2e/eds/eds_test.go
- test/kube2e/util.go
Upstream envoy has a bug, we might be hitting https://github.com/envoyproxy/envoy/issues/14598 on gRPC ADS
Update our test so we know when upstream has fixed the bug
> Improve test to know when we can go back to gRPC

- docs/content/guides/security/auth/jwt/claim_routing.md
A user gave us feedback that a code block [here](https://docs.solo.io/gloo-edge/master/guides/security/auth/jwt/claim_routing/#create-a-virtual-service) had a pipe "|" character that with our formatting looked like a "/" and caused him some pain.  This PR adds highlighting to the block in question to fix the formatting so it will look more like the pipe character [here](https://docs.solo.io/gloo-edge/latest/guides/security/auth/jwt/access_control/#secure-the-virtual-service).
> Tweak JWT claim routing doc to fix pipe character formatting

- Makefile
- changelog/v1.7.0-beta26/improve-rest-eds-perf.yaml
- go.mod
- go.sum
pick up the CPU improvements made in the REST EDS server from https://github.com/solo-io/solo-kit/pull/408 (profiles attached to that PR). additionally, bump envoy to 1.18
master should be tracking envoy 1.18
> Improve CPU & bump envoy dependency

- docs/content/guides/security/auth/extauth/oauth/auth0/_index.md
The recently added Auth0 integration doc has an error in one of the AuthConfigs that would cause the procedure to fail.  This PR fixes that error.
> Fix bad email reference in Auth0 doc

- .github/workflows/docs-gen.yaml
- .github/workflows/trivy-analysis.yaml
- changelog/v1.7.0-beta27/fix-workflow-name.yaml
The doc generation was not getting triggered on release because the workflow name did not match. This should now trigger the docs generation to also run on release after the trivy scan in complete.
> Fix workflow name for trivy scanner

- .github/workflows/trivy-analysis.yaml
- Makefile
- changelog/v1.6.15/backport-trivy-workflow.yaml
Currently the trivy scanner is not running on release for 1.6.x because the github workflow was never backported. 
Backports github workflow for running trivy scan of 1.6.x branch releases.
> Backport workflow for trivy scan 1.6

- .github/workflows/trivy-analysis.yaml
- Makefile
- changelog/v1.5.17/trigger-trivy-on-release.yaml
Updates the trivy doc generation directory and includes TAGGED_VERSION in the environment to set RELEASE=true and trigger uploading the generated docs.
> Trigger on release for trivy scan

- changelog/v1.7.0-beta30/add-rbl-warning.yaml
- changelog/v1.7.0-beta31/add-rbl-warning.yaml
- docs/content/guides/security/waf/_index.md
Using the `rbl` rule degrades envoy performance. Adds docs to warn against using rbl.
> Add modsecurity RBL warning to docs

- projects/gloo/cli/pkg/cmd/demo/federation.go
Adds `--with-gloo-fed=false` to fix installation script for gloo-fed demo.
> Fix gloo-fed demo script

- changelog/v1.7.0-beta32/doc-gen-format-fix-security-updates.yaml
- docs/cmd/securityscanutils/securityscan_utils.go
Fixes new line formatting in security scan doc generation.
> Fix doc gen formatting

- changelog/v1.7.0-rc2/docs-changes.yaml
- docs/content/installation/enterprise/_index.md
- docs/content/operations/upgrading/1.7.0.md
- docs/content/reference/gloo_port_reference.md
- docs/content/reference/helm_chart_values.md
- projects/gloo/cli/pkg/cmd/dashboard/root.go
Fix `glooctl ui` command for 1.7 (to use gloo fed UI) and update docs with some changes w.r.t. 1.7 upgrade
> Fix glooctl dashboard & small docs changes for 1.7

- docs/examples/grpc-passthrough-auth/pkg/auth/v3/auth.go
'i' before 'e' except after 'c' unless you leisurely deceive eight overweight heirs to forfeit their sovereign conceits
Completely minor typo in a log statement.
> fix: correct minor typo in auth.go

- changelog/v1.8.0-beta1/changelog-link-releases.yaml
- docs/cmd/changelogutils/changelog_utils.go
- docs/cmd/generate_docs.go
Adds links to releases on changelog version headers.
> add links to changelog version headers

- changelog/v1.7.0-rc3/fix-glooctl-test-flake.yaml
- test/kube2e/glooctl/glooctl_test.go
Fix a test flake
This slowed down development considerably
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4428
> Fix CI Test Flake: istio inject works on gateway-pod

- changelog/v1.6.19/tracing-provider-helm.yaml
- install/helm/gloo/templates/8-default-gateways.yaml
- install/test/helm_test.go
- install/test/values/val_tracing_provider_cluster.yaml
Backport of: https://github.com/solo-io/gloo/pull/4496
Allow tracing to be configured on gateways via Helm.
Envoy updated when tracing provider config is defined. Previously, it was at the bootstrap level, and then it was moved to the listener level. As part of https://github.com/solo-io/gloo/pull/3903, we removed the tracing config from the proxy config map. However, we didn't add the helm support to the gateway.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4494
> Helm support tracing on default gateway

- changelog/v1.8.0-beta3/fix-allow-warnings.yaml
- projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
- projects/gateway/pkg/validation/validator.go
- projects/gateway/pkg/validation/validator_test.go
Fix allowWarnings setting so it is honored when set to false (the default) in configuration validation API and admission webhook.
Also validated in cluster against [this](https://github.com/solo-io/gloo/issues/4466#issuecomment-812101643) use case to confirm it is fixed.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4466
> Fix allow warnings

- changelog/v1.8.0-beta4/fix-gateway-options.yaml
- install/helm/gloo/templates/8-default-gateways.yaml
- install/test/helm_test.go
Fixed bug where listener options were not able to be parsed.
> Fix gateways helmchart

- changelog/v1.8.0-beta5/fix-disable-gateway-corresponding-port.yaml
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/test/helm_test.go
Disabling http/s gateway should disable corresponding port
Several users have reported this.
Fixes: https://github.com/solo-io/gloo/issues/4578 and https://github.com/solo-io/gloo/issues/4286
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4578
> Disable gateway service port fix

- Makefile
- changelog/v1.8.0-beta5/upgrade-alpine.yaml
- docs/content/guides/security/tls/Dockerfile
- docs/examples/session-affinity/Dockerfile
- example/proxycontroller/Dockerfile
- jobs/certgen/cmd/Dockerfile
- projects/accesslogger/cmd/Dockerfile
- projects/discovery/cmd/Dockerfile
- projects/examples/services/sleeper/Dockerfile
- projects/gateway/cmd/Dockerfile
- projects/ingress/cmd/Dockerfile
- projects/sds/cmd/Dockerfile
Upgrade alpine refs to v3.13.4, and dump our envoy-gloo reference to a version that also uses this alpine version.
> alpine 3.13.4

- .github/workflows/regression-tests.yaml
- .gitignore
The old file blob only worked on junit results only one folder deep
> Fix testspace file glob

- .github/workflows/regression-tests.yaml
- .gitignore
Fix testspace file glob, needs quote escape
> Fix testspace file glob, needs quote escape

- .github/workflows/regression-tests.yaml
Per https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions the default condition is `success()` which doesn't run if previous steps failed. This means that job failures weren't getting uploaded to testspace. This fixes that.
> Always run testspace, even on failures

- Makefile
- changelog/v1.6.22/bump-envoy.yaml
Bumps envoy to pick up CVE fixes:
CVE-2021-28682: Remotely exploitable integer overflow via a very large grpc-timeout value causes undefined behavior.
CVE-2021-28683: Crash when peer sends a TLS Alert with an unknown code
CVE-2021-29258: Remotely exploitable crash in Envoy's HTTP2 Metadata, when an empty METADATA map is sent.
> Bump envoy 1.6

- Makefile
- changelog/v1.8.0-beta8/bump-envoy.yaml
Bumps envoy to pick up CVE fixes:
CVE-2021-28682: Remotely exploitable integer overflow via a very large grpc-timeout value causes undefined behavior.
CVE-2021-28683: Crash when peer sends a TLS Alert with an unknown code
CVE-2021-29258: Remotely exploitable crash in Envoy's HTTP2 Metadata, when an empty METADATA map is sent.
> Bump envoy 1.18

- Makefile
- changelog/v1.7.2/bump-envoy.yaml
Bumps envoy to pick up CVE fixes:
CVE-2021-28682: Remotely exploitable integer overflow via a very large grpc-timeout value causes undefined behavior.
CVE-2021-28683: Crash when peer sends a TLS Alert with an unknown code
CVE-2021-29258: Remotely exploitable crash in Envoy's HTTP2 Metadata, when an empty METADATA map is sent.
> Bump envoy 1.7

- changelog/v1.8.0-beta9/wasm-sdk-bump-doc-notice.yaml
- docs/content/installation/advanced_configuration/wasm.md
Update docs to reflect change to C++ WASM filters now requiring upgrade to proxy-wasm-cpp-sdk-b2e6b0759d34d760e527dadca413a285614f9e99 due to a breaking change introduced by https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/133.
> Add notice to wasm docs

- changelog/v1.7.3/fix-istio-mtls-sds-alpn.yaml
- projects/gloo/pkg/utils/ssl.go
Backport for: https://github.com/solo-io/gloo/pull/4647
> Fix: Istio mTLS not working in permissive mode (1.7)

- changelog/v1.8.0-beta12/fix-istio-meta-cluster-id-typo.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
fix typo with istioMetaClusterId helm value
Resolves: https://github.com/solo-io/gloo/issues/4667
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4667
> fix typo with istioMetaClusterId helm value

- changelog/v1.8.0-beta12/docs-remove-helm2.yaml
- docs/content/guides/observability/prometheus/metrics.md
- docs/content/installation/advanced_configuration/gloo-readonly-ui.md
- docs/content/installation/advanced_configuration/multiple-gloo-installs.md
- docs/content/installation/enterprise/_index.md
- docs/content/installation/gateway/kubernetes/_index.md
- docs/content/operations/upgrading/upgrade_steps.md
Helm 2 has been deprecated and there will be no further Helm v2 releases (even for security patches). Gloo 1.8 uses `deepCopy` functionality that is only supported in Helm 3.
> Remove helm2 references from 1.8 docs

- changelog/v1.8.0-beta12/logging-docs-small-fixes.yaml
- docs/content/guides/traffic_management/request_processing/transformations/change_response_status/_index.md
- projects/gloo/pkg/translator/listener.go
- projects/gloo/pkg/translator/translator_test.go
- description: Add note to docs about potential way to crash envoy
- Improve format of logging error message to be clearer to users
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4675
resolves https://github.com/solo-io/gloo/issues/4668
> Small changes: Improve logging clarity and add warning to transformation docs

- changelog/v1.8.0-beta12/configmap-remove-trailing-whitespace.yaml
- install/helm/gloo/templates/1-gloo-deployment.yaml
- install/helm/gloo/templates/10-ingress-deployment.yaml
- install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
- install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
- install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
- install/helm/gloo/templates/3-discovery-deployment.yaml
- install/helm/gloo/templates/5-gateway-deployment.yaml
- install/helm/gloo/templates/6-access-logger-deployment.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
- install/helm/gloo/templates/_helpers.tpl
Remove trailing whitespace from helm templates.
This bug fixes https://github.com/solo-io/gloo/issues/4645
Trailing whitespace was causing our gateway-proxy-envoy-config configmap to be non-human readable (relevant kubernetes bug: https://github.com/kubernetes/kubernetes/issues/36222#issuecomment-426587162).  Tests and/or lint checks to be added in follow-up PR to ensure this doesn't happen again moving forward.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4645
> Remove trailing whitespace from helm templates.

- changelog/v1.8.0-beta12/tracing-customtags-envvar-literal.yaml
- docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/tracing/tracing.proto.sk.md
- docs/data/ProtoMap.yaml
- projects/gloo/api/v1/options/tracing/tracing.proto
- projects/gloo/pkg/api/v1/options/tracing/tracing.pb.equal.go
- projects/gloo/pkg/api/v1/options/tracing/tracing.pb.go
- projects/gloo/pkg/api/v1/options/tracing/tracing.pb.hash.go
- projects/gloo/pkg/plugins/tracing/plugin.go
- projects/gloo/pkg/plugins/tracing/plugin_test.go
Adding the possibility to add tracing custom tags based on environment variables and fixed literals in addition to request headers.
A mentioned in https://github.com/solo-io/gloo/issues/4699, it would be great to be able to add custom tags for tracing spans based on other sources then request headers - especially from environment variables. In combination with the K8s Downward API this would allow to add Kubernetes Information (Node Name, Namespace Name, Pod Name, ...) to a tracing span. E.g. according to the OpenTelemetry Specification.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4699
> Expose envoy custom tags via environment variable & literal

- changelog/v1.8.0-beta12/fix-env-var-log-level.yaml
- docs/content/reference/values.txt
- go.mod
- go.sum
- install/helm/gloo/generate/values.go
This PR bumps the go-utils version so that it included a fix in which we initialize the log config/logger when an environment variable is used to set the stats server log level. This was tested locally with a gloo image that pulled in these changes.
Also there are a few small docs updates.
1.7 introduced the ability to set a pod's log level via an env variable. However, we weren't initializing the logger in that case so logs were not being produced.
> Fix logger

- docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk.md
- projects/gateway/api/v1/virtual_service.proto
- projects/gateway/pkg/api/v1/virtual_service.pb.go
Comments on the `DelegateAction` protobuf message were referencing a non-existing `single` field instead of the intended `ref` one.
> Fix field name in delegate action API documentation

- changelog/v1.8.0-beta12/bump-jwt-go.yaml
- docs/content/static/content/osa_provided.md
- example/proxycontroller/Dockerfile
- go.mod
- go.sum
- jobs/certgen/cmd/Dockerfile
- projects/accesslogger/cmd/Dockerfile
- projects/discovery/cmd/Dockerfile
- projects/examples/services/sleeper/Dockerfile
- projects/gateway/cmd/Dockerfile
- projects/ingress/cmd/Dockerfile
- projects/sds/cmd/Dockerfile
- test/e2e/aws_test.go
jwt-go for CVE-2020-26160 and alpine for CVE-2021-30139
The fix for this cve is on the v4-preview1 release, it looks like there hasn't been much activity and jwt-go isn't maintained actively (see: dgrijalva/jwt-go#426). If we can't expect updates, we might want consider to migrate to a different jwt library (https://github.com/solo-io/gloo/issues/4722)
> bump alpine and jwt-go

- changelog/v1.8.0-beta12/docker-compose-file-docs.yaml
- docs/content/installation/gateway/development/docker-compose-file/_index.md
- docs/content/installation/glooctl_setup.md
- install/docker-compose-file/.gitignore
- install/docker-compose-file/data/config/gateways/gloo-system/gateway-proxy.yaml
- install/docker-compose-file/data/config/virtualservices/gloo-system/default.yaml
- install/docker-compose-file/data/envoy-config.yaml
- install/docker-compose-file/docker-compose.yaml
Update the docker-compose-file docs to work with Gloo Edge 1.7+
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4692
> update docker-compose-file docs to work with 1.7

- Makefile
- changelog/v1.5.22/bump-envoy-gloo.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
- install/helm/gloo/values-template.yaml
- install/test/fixtures.go
- install/test/helm_test.go
This change pulls in the latest envou-gloo changes which address the Envoy CVE (https://github.com/envoyproxy/envoy/security/advisories/GHSA-4987-27fx-x6cf). We also had to bump the version of `go-control-plane` so that we can get the latest envoy API changes so that we can expose the hcm option that is needed to configure the fix for this CVE
See envoy CVE-2021-29492 (https://github.com/envoyproxy/envoy/security/advisories/GHSA-4987-27fx-x6cf)
> Upgrade envoy and add helm value

- changelog/v1.8.0-beta12/fix-install-script-python.yaml
- projects/gloo/cli/install.sh
Add checks to the `glooctl` install script for alternative python executables (e.g. `python3`, `python2`)
This is done in a somewhat verbose way as no bash-isms are allowed since [we are using `sh` explicitly](https://github.com/solo-io/gloo/blob/master/projects/gloo/cli/install.sh#L1).
The install script was breaking on systems like Ubuntu where e.g. the default `python` installation is `python3`.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2877
> check for alternative python executables

- docs/content/operations/upgrading/1.8.0.md
Add a document to outline how to upgrade to Gloo Edge 1.8.x
The validation schema work (glooOS: https://github.com/solo-io/gloo/pull/4757, glooEE: https://github.com/solo-io/solo-projects/pull/2346) requires that CRDs be defined with camelCase fields instead of snake_case. We need to outline this so that when users upgrade to 1.8.x they do not run into issues.
> Docs: Add 1.8.x upgrade steps

- changelog/v1.6.0-beta24/add-gzip-buffer.yaml
- changelog/v1.6.27/revert-adding-buffer-config-default.yaml
- projects/gloo/pkg/plugins/buffer/plugin.go
- projects/gloo/pkg/plugins/buffer/plugin_test.go
- test/e2e/buffer_test.go
Reverts: https://github.com/solo-io/gloo/pull/4015 
The buffer filter will need to be configured on the gateway level to be able to do BufferPerRoute on the route or vh.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4000
> Revert buffer filter behavior

- .github/workflows/docs-gen.yaml
- changelog/v1.8.0-beta20/fix-docgen-community-users.yaml
- docs/build-docs.sh
Fix docsgen CI for community users.
Docgen was not working for community users, because it was attempting to checkout a commit that existed in a forked repository. This reverts the old behavior for community users, of using master as the latest commit, instead of the head SHA of the pull request.
```
logs from CI...
+ getContentForVersion 1.7.10 master
+ version=1.7.10
+ latestMasterTag=master
```
```
logs from CI...
+ generateSiteForVersion 1.6.29 6a45fc0b538528f6c5cb75f9633ed767687d90e1
+ version=1.6.29
+ latestMasterTag=6a45fc0b538528f6c5cb75f9633ed767687d90e1
```
> Fix docsgen for community users

- changelog/v1.8.0-beta20/envoy-bootstrap-v3.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/test/helm_test.go
- test/services/envoy.go
Specify the API version to load the bootstrap envoy configuration as. Since we were not specifying it before, envoy loaded the bootstrap as v2.
From https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-bootstrap-version: 
```
The API version to load the bootstrap as. The value should be a single integer, e.g. to parse the bootstrap configuration as V3, specify --bootstrap-version 3. If unset, Envoy will attempt to load the bootstrap as the previous API version and upgrade it to the latest. If that fails, Envoy will attempt to load the configuration as the latest version.
```
> Envoy bootstrap v3

- changelog/v1.8.0-beta20/fix-disable-default-gatewayProxy.yaml
- install/helm/gloo/templates/8-default-gateways.yaml
- install/test/helm_test.go
When installing a custom gateway proxy, always get the value for "disabled" from the custom spec rather than the default.
Currently the custom settings are merged with the default settings when installing a non-default gateway. However this means that disabling the default gateway effectively disables any custom gateways that do not have `disabled: false` explicitly set.
Users ran into this bug when trying to install a proxy other than the default when the default was disabled. 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4696
> Fix disabling default gateway #4696

- changelog/v1.8.0-beta20/bump-istio-proxy-to-195.yaml
- docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/test/helm_test.go
Bump istio proxy from 1.9.4 to 1.9.5 for CVE fixes
Resolves: https://github.com/solo-io/gloo/issues/4846
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4846
> bump istio proxy version to 1.9.5 for use during injection

- changelog/v1.7.12/backport-istio-support-changes.yaml
- docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/test/helm_test.go
- projects/gloo/cli/pkg/cmd/istio/inject.go
- projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7-1.8-1.9-1.10.go
- projects/gloo/cli/pkg/cmd/istio/sidecars/matcher.go
- projects/gloo/cli/pkg/cmd/istio/uninject.go
Back port istio 1.9.x and 1.10.x support changes
Resolves: https://github.com/solo-io/gloo/issues/4883, https://github.com/solo-io/gloo/issues/4884
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4884
resolves https://github.com/solo-io/gloo/issues/4883
> Back port istio 1.9.x and 1.10.x support changes

- changelog/v1.6.8-patch2/fix-transport-api-version.yaml
- projects/gloo/pkg/plugins/extauth/config_generator.go
- projects/gloo/pkg/plugins/extauth/config_generator_test.go
This is a special Gloo release for enterprise to depend on in an enterprise stub release. The feature backported here depends on extauth features in the v3 api.
Gloo 1.6 supports both v2 and v3 transport API versions, so changing the version here is safe.
Ran enterprise tests against this change, this fixed the broken backported tests / behaviors.
> Fix transport api version

- docs/content/guides/integrations/cert_manager/_index.md
documentation: updating apiVersion: cert-manager.io to v1 from v1alpha2
> updating apiVersion cert-manager.io to v1 from v1alpha2

- changelog/v1.8.0-beta23/fix-sec-scan.yaml
- docs/cmd/securityscanutils/securityscan_utils.go
Fixing quick typo. Needs to be backported to atleast 1.7 to show on 1.7 docs.
> Fix security scan docs for gloo-ee-envoy-wrapper

- changelog/v1.9.0-beta1/doc-reorg-links-to-main-apis.yaml
- docs/content/reference/api/_index.md
A simplified view of our main APIs in the API Reference.
Using this part of the doc on a daily basis, I really want to have shortcuts to VS Options and Route Options.
It will look like this:
with the CSS of course! I was not able to have the CSS when specifying a `DocsVersion` in `Solo.yaml`
> simplify and reorganize links to main APIs

- docs/content/guides/traffic_management/request_processing/transformations/_index.md
The current transformation doc [here](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/transformations/) does not highlight that the `regex` attribute is required for any `extractor` to work. This PR fixes that omission.
> Add required regex attribute for extractors to Transformation doc

- changelog/v1.9.0-beta1/extauth-opa-doc-fix.yaml
- docs/content/guides/security/auth/extauth/opa/_index.md
Modified YAML values for dex-config to be parseable.
This bug fixes doc issue #4946 
Helm 3 fails to parse the current YAML.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4946
> Fixed dex-values config

- changelog/v1.9.0-beta1/proxy-service-extra-annotations.yaml
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/test/helm_test.go
Ensure that gateway proxy service annotations are not mixed between the default and custom gateway proxies
Recently, we introduced a deep-merge operation on the Helm dictionary values, to reuse the defaults in .Values.gatewayProxies.gatewayProxy with additional gateway proxies. This enabled customers to avoid manually specifying all the values when running multiple gateway proxies, which is especially problematic during upgrades, as the expected helm values may have changed.
However, this also merges service annotations, which should be distinct per gateway proxy. Therefore, we unset the service annotations of the default gateway proxy copy, that we use to merge with additional gateway proxies.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4914
> Do not mix extraAnnotations for gw-proxy service resources

- .github/workflows/regression-tests.yaml
- Makefile
- changelog/v1.9.0-beta3/prevent-localhost-external-name.yaml
- ci/deploy-to-kind-cluster.sh
- projects/ingress/pkg/status/status_syncer.go
- projects/ingress/pkg/status/status_syncer_test.go
- test/kube2e/README.md
Removes the possibility of using localhost in ExternalNames as endpoints
I also updated the README for our regression tests to make local development (and testing) easier.
> Remove the possibility of using 'localhost' in KubeService ExternalName

- .github/workflows/trivy-analysis-scheduled.yaml
- changelog/v1.9.0-beta3/temporary-fix-security-scan.yaml
- go.mod
- go.sum
Currently, our security scans miss some versions. This is because they scan once a week and run on the latest master, v1.8.x, v1.7.x, v1.6.x, etc branches. This means that if we were to release v1.8.1 and v1.8.2 in the same week, a security scan would only run for release v1.8.2. This is not ideal, and as a temporary solution, this PR allows us to specify which versions that need to be scanned directly from the github action.
1. Navigate to the trivy schedule security scan GH action: https://github.com/solo-io/gloo/actions/workflows/trivy-analysis-scheduled.yaml
2. Click `Run Workflow`, and specify the version under "Gloo Version" , e.g. v1.7.8. If you leave Gloo Version empty, it will run the security scan on the master, v1.8.x, v1.7.x, etc branches as we do weekly.
BOT NOTES: 
resolves …
> Specify Gloo versions to be scanned in security scan

- .github/workflows/docs-gen.yaml
I haven't tested it, but I think the names accidentally diverged.
If I understand correctly, this will result in the Docs getting re-published whenever a security scan is run, as originally intended, and which I'm suspicious hasn't been happening.
> Publish docs after security scan

- .github/workflows/docs-gen.yaml
- changelog/v1.9.0-beta3/skip-enterprise-docs-gen-community-pr.yaml
- docs/cmd/generate_docs.go
- Skip enterprise docs generation during the `docs-gen` GH workflow on community PRs.
- CI was failing on community PRs during the "Generate versioned docs site" step of the docs-gen workflow, because enterprise docs generation required the presence of a Github access token with access to the solo-projects repository.
> Skip enterprise docs generation on community PRs

- .github/workflows/docs-gen-preview.yaml
- changelog/v1.9.0-beta3/skip-enterprise-docs-gen-preview-community-pr.yaml
- Skip enterprise docs generation on community PRs during the docs-gen-preview workflow.
- Leverages the `SKIP_ENTERPRISE_DOCS_GENERATION` environment variables exposed in https://github.com/solo-io/gloo/pull/4987
> Skip enterprise docs gen on community PRs during docs-gen-preview

- docs/content/installation/gateway/development/docker-compose-file/_index.md
- install/docker-compose-file/docker-compose.yaml
- install/docker-compose-file/prepare-directories.sh
Adress https://github.com/solo-io/gloo/issues/4971
Bumping from 1.7 w/o the proper folder structure available throws `fatal`
```
{"level":"fatal","ts":"2021-07-06T14:40:02.692Z","logger":"gateway","caller":"setuputils/main_setup.go:88","msg":"error in setup: starting snapshot watch: initial VirtualHostOption list: reading namespace dir: open /data/config/virtualhostoptions/gloo-system: no such file or directory","version":"1.8.0","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gloo/pkg/utils/setuputils/main_setup.go:88\ngithub.com/solo-io/gloo/projects/gateway/pkg/setup.Main\n\t/workspace/gloo/projects/gateway/pkg/setup/setup.go:13\nmain.main\n\t/workspace/gloo/projects/gateway/cmd/main.go:11\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
```
``` …
```
> Update docker-compose.yaml to reflect v1.8 config changes

- docs/content/guides/security/rate_limiting/simple/_index.md
A user was confused about the source of the user id that drives authorized request rate limiting and had to guess at the right answer. Adding a note in the docs to clarify.
> Add rate limiting UserID source note to docs

- docs/content/guides/traffic_management/request_processing/transformations/_index.md
- docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
- install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
- install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
- install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
- install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
- install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
- install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
- install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
- install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml
- projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
- projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
Make it more clear to customers / engineers that extractor `regex` needs to match the _entire_ source in order to work.
Issue here for more context: https://github.com/solo-io/gloo/issues/5000
> Add extractor regex note to docs

- changelog/v1.9.0-beta6/fix-glooctl-dashboard-cmd.yaml
- changelog/v1.9.0-beta6/schema-int64-and-descriptions.yaml
- projects/gloo/cli/pkg/cmd/dashboard/root.go
Fixing glooctl dashboard cmd 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5010
> fixing dashboard cmd

- changelog/v1.9.0-beta6/fix-regression-flakes.yaml
- projects/gateway/pkg/reconciler/proxy_reconciler.go
- projects/gateway/pkg/reconciler/proxy_reconciler_test.go
- test/helpers/input_resources.go
- test/helpers/kube_objects.go
- test/kube2e/gateway/gateway_suite_test.go
- test/kube2e/gateway/gateway_test.go
- test/kube2e/gateway/robustness_test.go
- test/kube2e/util.go
- Fixed logic in our proxy reconciler, which allowed invalid virtual hosts to be added to a proxy twice. 
- Add some utility methods for our Kube2e tests, to make it easier for developers to add logic around waiting for resources to be accepted and cleaned up
- Fix test pollution that did lead to flakes
- Fix robustness_test, which was written in a way that relied on the exact bug that this PR fixes, to be present
- Fix disable_transformation_test (https://github.com/solo-io/gloo/issues/4900) which would flake occasionally, and did during the development of this PR 
Example logs: https://console.cloud.google.com/cloud-build/builds/a13c32e3-fddf-4263-b28a-e931933d9f87;step=14?project=solo-public
This test flake was due to a bug in our proxy_reconciler. We incorrectly were duplicating …
> Ensure invalid virtual hosts are not duplicated on proxy

- changelog/v1.7.14/fix-regression-flakes.yaml
- projects/gateway/pkg/reconciler/proxy_reconciler.go
- projects/gateway/pkg/reconciler/proxy_reconciler_test.go
- test/kube2e/gateway/robustness_test.go
Partial backport of: https://github.com/solo-io/gloo/pull/5033 (Only included bug fix, since there were merge conflicts)
Fixed logic in our proxy reconciler, which allowed invalid virtual hosts to be added to a proxy twice. 
Example logs: https://console.cloud.google.com/cloud-build/builds/a13c32e3-fddf-4263-b28a-e931933d9f87;step=14?project=solo-public
This test flake was due to a bug in our proxy_reconciler. We incorrectly were duplicating virtual hosts on the proxy object. The proxy only transitioned in certain situations (depending on metadata of the object) which is why this didn't occur more frequently. However, when it did happen, it caused this flaking test.
I added a unit test to verify the change that I made fixes the problem. 
I also added a comment to the code so that future …
> Ensure invalid virtual hosts are not duplicated on proxy (1.7)

- changelog/v1.6.32/fix-regression-flakes.yaml
- go.sum
- projects/gateway/pkg/reconciler/proxy_reconciler.go
- projects/gateway/pkg/reconciler/proxy_reconciler_test.go
- test/kube2e/gateway/robustness_test.go
Partial backport of: https://github.com/solo-io/gloo/pull/5033 (Only included bug fix, since there were merge conflicts)
Fixed logic in our proxy reconciler, which allowed invalid virtual hosts to be added to a proxy twice. 
Example logs: https://console.cloud.google.com/cloud-build/builds/a13c32e3-fddf-4263-b28a-e931933d9f87;step=14?project=solo-public
This test flake was due to a bug in our proxy_reconciler. We incorrectly were duplicating virtual hosts on the proxy object. The proxy only transitioned in certain situations (depending on metadata of the object) which is why this didn't occur more frequently. However, when it did happen, it caused this flaking test.
I added a unit test to verify the change that I made fixes the problem. 
I also added a comment to the code so that future …
> Ensure invalid virtual hosts are not duplicated on proxy (1.6)

- docs/content/guides/observability/_index.md
- docs/content/guides/observability/grafana/deployment/_index.md
- docs/content/guides/observability/prometheus/_index.md
- docs/content/operations/production_deployment/_index.md
- docs/content/reference/helm_chart_values/enterprise_helm_chart_values.md
Fixes https://github.com/solo-io/gloo/issues/4991
There are some default values like `persistentVolumeSize=16GB +RetentionTime=15d` that are not suitable for production. In general, users should be warned that they must provide their own production-ready instance of prometheus/grafana, or fine-tune the helm chart for production usage.
Recently, there have been several customers reporting weird issues that resulted in 'no disk space' in observability pods. A clearer documentation could mitigate these kind of scenarios.
> issue-4491-doc

- docs/content/guides/security/auth/extauth/passthrough_auth/_index.md
Fix link in passthrough auth [doc](https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/passthrough_auth/#creating-an-authentication-service) to point to correct example in github.
> Fix passthrough auth example repo link

- changelog/v1.9.0-beta7/windows-server-installer-fix.yaml
- docs/content/getting_started/_index.md
- docs/content/installation/glooctl_setup.md
- projects/clusteringress/README.md
- projects/gloo/cli/install.ps1
- projects/knative/README.md
Fix the glooctl windows install and docs to work more consistently on windows server 64bit
Update docs
Add change log
Fix implementation from: https://github.com/solo-io/gloo/pull/5086
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5062
> fix glooctl windows installer - 64 bit window server

- changelog/v1.9.0-beta7/helm-fix-proxy-service-annotations.yaml
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
Fixes the incorrect service annotation being rendered for gateway proxies. I've tried adding some unit tests to reproduce, but cannot get a failing test case... This occurs with helm version `v3.5.4`
Fixes https://github.com/solo-io/gloo/issues/4914
The following values.yaml results in the incorrect annotations being added to `gatewayProxyPublic`
```yaml
gloo:
gatewayProxies:
gatewayProxy:
disabled: true
gatewayProxyPublic:
disabled: false
gatewayProxyInternal:
disabled: false
service:
extraAnnotations:
a: b
```
```yaml
apiVersion: v1
kind: Service
metadata:
labels:
app: gloo
gloo: gateway-proxy
gateway-proxy-id: gateway-proxy-internal
name: gateway-proxy-internal
namespace: default
annotations:
a: "b"
prometheus.io/path: "/metrics"
prometheus.io/port: "8081"
prometheus.io/scrape: "true" …
```
> fix: helm: gateway proxy service annotations

- changelog/v1.6.34/fix-npe-consul.yaml
- projects/gloo/pkg/plugins/consul/subsets.go
Fix NPE backport
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5112
> Npe fix 1.6

- projects/gloo/cli/pkg/cmd/istio/inject.go
- projects/gloo/cli/pkg/cmd/istio/uninject.go
This fixes two dropped `err` variables in the `istio` cmd.
> fix: cmd/istio dropped errors

- changelog/v1.7.17/fix-npe-consul.yaml
- projects/gloo/pkg/plugins/consul/subsets.go
backport of https://github.com/solo-io/gloo/pull/5110
Fix a potential NPE in translation loop.
Unit tests should come in a follow up. Want to release 1.6.32 and other versions with a fix now.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5112
> Fix NPE (#5110)

- changelog/v1.7.17/proxy-protocol-listener-filter.yaml
- projects/gloo/pkg/plugins/proxyprotocol/plugin.go
- projects/gloo/pkg/plugins/proxyprotocol/plugin_test.go
- projects/gloo/pkg/plugins/proxyprotocol/proxyprotocol_suite_test.go
- projects/gloo/pkg/plugins/registry/registry.go
- projects/gloo/pkg/plugins/tcp/plugin.go
- projects/gloo/pkg/translator/listener.go
- test/e2e/proxy_protocol_test.go
Backport of: https://github.com/solo-io/gloo/pull/5117
Support PROXY Protocol listener filter and ensure it is executed before the TLS inspector listener filter.
https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/proxy_protocol.html
We previously relied on a now deprecated Envoy flag, `use_proxy_proto` defined on the Listener FilterChain: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#config-listener-v3-filterchain. 
Using the deprecated flag, the PROXY protocol listener filter is appended to the filter chain. However, we need the PROXY protocol listener filter to be executed before the TLS inspector filter. Since the PROXY protocol adds bytes to the beginning of the connection, the SNI will not be parsed …
> Support PROXY Protocol listener filter (1.7)

- changelog/v1.8.6/proxy-protocol-listener-filter.yaml
- projects/gloo/pkg/plugins/proxyprotocol/plugin.go
- projects/gloo/pkg/plugins/proxyprotocol/plugin_test.go
- projects/gloo/pkg/plugins/proxyprotocol/proxyprotocol_suite_test.go
- projects/gloo/pkg/plugins/registry/registry.go
- projects/gloo/pkg/plugins/tcp/plugin.go
- projects/gloo/pkg/translator/listener.go
- test/e2e/proxy_protocol_test.go
Backport of: https://github.com/solo-io/gloo/pull/5117
Support PROXY Protocol listener filter and ensure it is executed before the TLS inspector listener filter.
https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/proxy_protocol.html
We previously relied on a now deprecated Envoy flag, `use_proxy_proto` defined on the Listener FilterChain: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#config-listener-v3-filterchain. 
Using the deprecated flag, the PROXY protocol listener filter is appended to the filter chain. However, we need the PROXY protocol listener filter to be executed before the TLS inspector filter. Since the PROXY protocol adds bytes to the beginning of the connection, the SNI will not be parsed …
> Support PROXY Protocol listener filter (1.8)

- .github/workflows/regression-tests-and-codegen.yaml
- changelog/v1.7.8-patch2/proxy-protocol-listener-filter.yaml
- ci/kind.sh
- projects/gloo/cli/pkg/cmd/demo/federation.go
- projects/gloo/pkg/plugins/proxyprotocol/plugin.go
- projects/gloo/pkg/plugins/proxyprotocol/plugin_test.go
- projects/gloo/pkg/plugins/proxyprotocol/proxyprotocol_suite_test.go
- projects/gloo/pkg/plugins/registry/registry.go
- projects/gloo/pkg/plugins/tcp/plugin.go
- projects/gloo/pkg/translator/listener.go
- test/e2e/proxy_protocol_test.go
Backport of: https://github.com/solo-io/gloo/pull/5117 (PROXY protocol) and https://github.com/solo-io/gloo/pull/5092 (Fix CI)
Support PROXY Protocol listener filter and ensure it is executed before the TLS inspector listener filter.
https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/proxy_protocol.html
We previously relied on a now deprecated Envoy flag, `use_proxy_proto` defined on the Listener FilterChain: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#config-listener-v3-filterchain. 
Using the deprecated flag, the PROXY protocol listener filter is appended to the filter chain. However, we need the PROXY protocol listener filter to be executed before the TLS inspector filter. Since the PROXY protocol …
> Support PROXY Protocol listener filter (1.7 patch)

- ci/deploy-to-kind-cluster.sh
- test/kube2e/README.md
- Update the kube2e README:
- Clarify need for semver on versions
- Condense docker exec command
- Update setup script with valid default version
Changes made while progressing through the README myself
> Test readme cleanup

- docs/content/guides/traffic_management/destination_types/aws_lambda/eks-service-accounts.md
A user was confused by the obsolete "beta" language in [this doc](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/aws_lambda/eks-service-accounts/). This PR cleans that up.
> Remove confusing beta comments from Lambda / EKS ServiceAccount doc

- docs/content/guides/observability/prometheus/metrics.md
For https://github.com/solo-io/gloo/issues/5171, the tab wasn't closed so I think that none of the content on the rest of the page was rendering, which caused the broken link.
- N/A I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
> Fix tab to fix link

- .github/CODEOWNERS
Previously left off the front half of `@solo-io/solo-docs`. This fixes the CODEOWNERS file to properly autotag docs team for changes to files in /docs/ directory.
- NA I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- NA I have commented my code, particularly in hard-to-understand areas
- NA I have made corresponding changes to the documentation
- NA I have added tests that prove my fix is effective or that my feature works
>  Fix docs team name in codeowners

- Makefile
- changelog/v1.6.37/update-envoy-dependency.yaml
Update envoy-gloo to 1.17.4-patch1 for CVE-2021-32777, CVE-2021-32779, CVE-2021-32781, and CVE-2021-32778.
> [Gloo 1.6: Envoy 1.17] Update envoy dependency

- changelog/v1.9.0-beta15/fix-onewaytls-npe.yaml
- projects/gateway/pkg/translator/http.go
NPE in gateway when gateway defines oneWayTls but virtualservice does not have an sslConfig
Resolves: https://github.com/solo-io/gloo/issues/5262
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5262
> oneway tls npe fix

- changelog/v1.8.12/fix-onewaytls-npe.yaml
- projects/gateway/pkg/translator/http.go
NPE in gateway when gateway defines oneWayTls but virtualservice does not have an sslConfig
Backport to resolve: https://github.com/solo-io/gloo/issues/5262
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5262
> backport to 1.8.x - oneway tls npe fix

- changelog/v1.8.16/upgrade-docs-backport.yaml
- docs/content/operations/upgrading/1.8.0.md
Backport the 1.8 upgrade docs from master to 1.8.
There is information present in master (https://docs.solo.io/gloo-edge/master/operations/upgrading/1.8.0/) that is not present in the 1.8 ("latest") version (https://docs.solo.io/gloo-edge/latest/operations/upgrading/1.8.0/).
> Backport 1.8 upgrade docs

- projects/gloo/pkg/plugins/utils/update_upstream_spec.go
Copy ignoreHealthOnHostRemoval
Fix a bug identified here: https://github.com/solo-io/gloo/pull/5325#pullrequestreview-755606311
> update_upstream_spec includes ignoreHealthOnHostRemoval

- .github/workflows/do-not-submit.yaml
- changelog/v1.9.0-beta19/do-not-submit.yaml
- ci/do-not-submit.sh
- ci/tools.go
Add a CI check which fails when `// DO_NOT_SUBMIT` is found in *.go files that were modified in a PR.
Example failure: https://github.com/solo-io/gloo/runs/3654089442?check_suite_focus=true
> Add CI check for DO_NOT_SUBMIT comments in go files.

- Makefile
- changelog/v1.9.0-beta20/gcr-push-fix.yaml
The -extended part of the tag was missing when we retagged images from quay to gcr.
> Fix the tags for -extended gcr images

- changelog/v1.9.0-rc2/fix-glooctl-check-gloo-fed.yaml
- projects/gloo/cli/pkg/cmd/check/gloo_instances.go
Use the existence of the gloo-fed deployment to determine whether Gloo Fed is installed, since the lack of gloo instances doesn't necessarily mean Gloo Fed isn't installed - only means no clusters with gloo instances on them have been registered.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5386
> fix the glooctl gloo fed check to use deployment

- docs/content/reference/helm_chart_values/enterprise_helm_chart_values.md
- docs/content/reference/helm_chart_values/open_source_helm_chart_values.md
Fix to move the enterprise helm prefix warning to the correct reference page.
> Docs: Move helm prefix warning

- docs/content/reference/helm_chart_values/enterprise_helm_chart_values.md
- docs/content/reference/helm_chart_values/open_source_helm_chart_values.md
* Docs: Move helm prefix warning
Fix to move the helm prefix warning to the correct page.
> Backport: Docs: Move helm prefix warning (#5397)

- changelog/v1.6.38/upgrade-protobuf-dep.yaml
- go.mod
- go.sum
Upgrade protobuf dependency to fix known CVE.
An upgrade to the trivy version we use in CI has identified a CVE (https://docs.solo.io/gloo-edge/latest/reference/security-updates/open_source/)
> Upgrade dependencies to fix vulnerabilities found in security scan (1.6)

- changelog/v1.8.18/upgrade-protobuf-dep.yaml
- docs/content/static/content/osa_provided.md
- go.mod
- go.sum
Upgrade protobuf dependency to fix known CVE.
An upgrade to the trivy version we use in CI has identified a CVE (https://docs.solo.io/gloo-edge/latest/reference/security-updates/open_source/)
> Upgrade dependencies to fix vulnerabilities found in security scan (1.8)

- changelog/v1.7.23/nodeselector-override.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/test/helm_test.go
Backport of #5421
Added helm logic to preserve initial custom GatewayConfig spec after the mergeOverwrite call which did not previously exist on this version
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5286
> Node selector overwrite (#5421)

- docs/content/guides/integrations/aws/_index.md
Clarify HTTPS to HTTP routing when TLS offloading is on the NLB
> doc - clarify HTTPS to HTTP routing when TLS offloading is on the NLB

- changelog/v1.8.20/bump-solo-kit.yaml
- changelog/v1.9.0-beta19/remove-ownerref-mapping-for-uds.yaml
- go.mod
- go.sum
- projects/clusteringress/api/external/knative/cluster_ingress.go
- projects/gloo/api/external/solo/ratelimit/rate_limit_config.go
- projects/gloo/pkg/api/converters/kube/api_key_secret.go
- projects/gloo/pkg/api/converters/kube/artifact_converter.go
- projects/gloo/pkg/api/converters/kube/secretconverter.go
- projects/gloo/pkg/plugins/kubernetes/uds_convert.go
- projects/ingress/pkg/api/ingress/resource_client.go
- projects/ingress/pkg/api/service/resource_client.go
- projects/knative/api/external/knative/ingress.go
- test/e2e/gateway_test.go
- test/e2e/happypath_test.go
Bump solo-kit dependency to v0.20.4, which includes at recent backport of https://github.com/solo-io/solo-kit/pull/446 to v0.20.x. This is being done with the intention of introducing the fix for solo-io/gloo#4790 to Gloo EE v1.8.x
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4790
> v1.8.x: bump solo-kit dependency to v0.20.4

- changelog/v1.10.0-beta6/gateway-proxy-envoy-clusters.yaml
- install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
- install/test/fixtures.go
Expose the envoy admin clusters endpoint if readConfig is true. It will be used by the UI to display cluster info.
> expose envoy clusters endpoint

- changelog/v1.10.0-beta6/bump-security-deps.yaml
- go.mod
- go.sum
Bump minor versions of dependencies per trivy scan results
> go.mod: Indirect dependencies updated per trivy scans

- changelog/v1.9.2/bump-security-deps.yaml
- go.mod
- go.sum
Bump minor versions of dependencies per trivy scan results
> 1.9.x go.mod: Indirect dependencies updated per trivy scans

- docs/content/guides/observability/prometheus/_index.md
A `port-forward` command in [this](https://docs.solo.io/gloo-edge/latest/guides/observability/prometheus/) doc does not indicate the default `gloo-system` namespace and thus fails for users with the most common configuration.
> Fix Envoy port-forward in prometheus docs

- docs/content/guides/security/waf/_index.md
The current [WAF](https://docs.solo.io/gloo-edge/latest/guides/security/waf/) docs point to an obsolete [ModSecurity home page](https://www.modsecurity.org/). This PR replaces it with the [current home](https://github.com/SpiderLabs/ModSecurity) of its OSS community.
> fix obsolete modsec link in waf doc

- test/kube2e/gloo-mtls/gloo_mtls_suite_test.go
- test/kube2e/util.go
If the `glooctl check` fails in our e2e tests, we don't know why. This will provide a more descriptive error with the glooctl check error message.
> Glooctl check eventually healthy gives more descriptive error

- changelog/v1.10.0-rc5/add-license-env-var.yaml
- changelog/v1.11.0-beta3/add-license-env-var.yaml
- docs/content/operations/upgrading/1.10.0.md
- install/helm/gloo/templates/1-gloo-deployment.yaml
- install/helm/gloo/templates/3-discovery-deployment.yaml
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5751
> (Backport 1.10.x) - Add GLOO_LICENSE_KEY env var to gloo and discovery pods.

- changelog/v1.11.0-beta3/upstream-template-config-casing.yaml
- docs/content/guides/traffic_management/destination_types/discovered_upstream/discovered-upstream-configuration.md
- projects/gloo/pkg/plugins/kubernetes/uds_convert_test.go
https://github.com/solo-io/gloo/pull/5452 introduced the ability to configure discovered upstreams via annotations on the service corresponding to the discovered upstream. Since the introduction of this feature, there have been some questions about the form that this configuration should take.
- The documentation introduced around this feature suggests that users use `snake_case` field names to configure discovered upstreams, i.e.:
- `gloo.solo.io/upstream_config: '{"initial_stream_window_size": 2048}'`
- This is not ideal UX, as our documentation provides these values in `camelCase`
- `camelCase` configuration is also valid -- this PR proposes that we center this configuration format in our documentation.
- e.g.: `gloo.solo.io/upstream_config: '{"initialStreamWindowSize": 2048}'`
> Discovered Upstream Annotation Config Casing Clarification

- docs/content/operations/upgrading/1.10.0.md
* add upgrade notice for graphql schema
* Update docs/content/operations/upgrading/1.10.0.md
Co-authored-by: Sam Heilbron <SamHeilbron@gmail.com>
* fix shell script for upgrading
* small change
* Apply suggestions from code review
Co-authored-by: Art <artberger@users.noreply.github.com>
Co-authored-by: Sam Heilbron <SamHeilbron@gmail.com>
* commit to show diff
* Revert "commit to show diff"
This reverts commit 413c0ac7f05ef65d16b59dd2826d0ded8e4d5dc4.
Co-authored-by: Sam Heilbron <SamHeilbron@gmail.com>
Co-authored-by: Art <artberger@users.noreply.github.com>
Users ran into this bug doing ... \ …
> (docs backport) add upgrade notice for graphql schema (#5772)

- changelog/v1.11.0-beta4/prepare-directories.sh.yaml
- docs/content/installation/gateway/development/docker-compose-file/_index.md
- install/docker-compose-consul/docker-compose.yaml
- install/docker-compose-file/docker-compose.yaml
- install/docker-compose-file/prepare-directories.sh
Address #5777
Running 1.10.0 is throwing `fatal` errors due to a missing folder
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5777
> Update docker-compose.yaml to reflect v1.10 config change

- changelog/v1.11.0-beta4/hybrid-gateway-panic.yaml
- docs/content/operations/upgrading/1.10.0.md
- projects/gloo/pkg/plugins/plugin_interface.go
- projects/gloo/pkg/plugins/registry/registry.go
- projects/gloo/pkg/translator/clusters.go
- projects/gloo/pkg/translator/endpoints.go
- projects/gloo/pkg/translator/filter_chain.go
- projects/gloo/pkg/translator/listener_subsystem.go
- projects/gloo/pkg/translator/route_config.go
- projects/gloo/pkg/translator/translator.go
- projects/gloo/pkg/translator/translator_test.go
Ensure that invalid configuration defined on a HybridListener does not cause the translation loop to panic
Our CI pipeline failed: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=2ae522e9-cca1-4d87-9257-36deb08a1258
During the generation of the FilterChain, we convert a user defined SslConfig, into the definition for a FilterChainMatch. If the SslConfig is invalid (for example, an invalid secret reference) we should catch the error, write it to a report, skip the config and continue processing.
We do this for HttpListeners: https://github.com/solo-io/gloo/blob/fccf272cb170ba4f1531013bacaa915d98e2e99d/projects/gloo/pkg/translator/filter_chain.go#L99
However, we did not do this for HybridListeners: https://github.com/solo-io/gloo/blob/fccf272cb170ba4f1531013bacaa915d9 …
> Resolve HybridListener marshal panic

- changelog/v1.11.0-beta4/docs-fix.yaml
- docs/content/installation/glooctl_setup.md
Raised in Slack: https://solo-io-corp.slack.com/archives/CHJV572TG/p1642410193030100
The static reuse files don't work in a file that is already being reused itself.
- N/A I opened a draft PR or added the work in progress label if my PR is not ready for review
> Doc fix for reuse files

- projects/gloo/api/external/envoy/config/filter/http/gzip/v2/gzip.proto
Cue has issues parsing the `CompressionLevel.Enum` field in gzip.proto. Prefixing with the parent message name i.e. `Gzip.CompressionLevel.Enum` makes cue happy.
Needed in a dependent project to generate validation schemas using skv2.
> prefix enum field with Gzip

- changelog/v1.10.4/hotfix-docs-gen.yaml
- docs/Makefile
- docs/build-docs.sh
- docs/content/reference/security-updates/enterprise/_index.md
- docs/content/reference/security-updates/open_source/_index.md
- docs/split-file-by-delimiter.sh
When running CI, we've found that our vulnerability reports are too large to process.  This PR splits the reports into smaller sections, as well as renders said sections individually
> backport(feat(docs)): split vulnerabillity scans to render in smaller chunks

- changelog/v1.11.0-beta7/opaque-header-secrets.yaml
- projects/gloo/pkg/api/converters/kube/header_secret.go
- projects/gloo/pkg/api/converters/kube/header_secret_test.go
- projects/gloo/pkg/api/converters/kube/secretconverter.go
Allow header secrets to be Opaque.
> Allow header secrets to be of type Opaque.

- changelog/v1.8.25/hotfix-docs-gen.yaml
- docs/Makefile
- docs/build-docs.sh
- docs/content/reference/security-updates/enterprise/_index.md
- docs/content/reference/security-updates/open_source/_index.md
- docs/split-file-by-delimiter.sh
When running CI, we've found that our vulnerability reports are too large to process.  This PR splits the reports into smaller sections, as well as renders said sections individually
> feat(docs): split vulnerabillity scans to render in smaller chunks

- changelog/v1.9.8/affinity-pdb-documentation.yaml
- docs/content/operations/production_deployment/_index.md
Document Helm configuration of PDB and affinity/anti-affinity rules for ExtAuth and RateLimit
Support for this functionality was added to Gloo Edge Enterprise with https://github.com/solo-io/solo-projects/pull/2946
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5648
> Document Helm configuration of PDB and affinity/anti-affinity rules

- changelog/v1.10.5/5578-orphaned-gateway.yaml
- changelog/v1.10.5/opaque-header-secrets.yaml
- projects/gateway/pkg/reconciler/proxy_reconciler.go
- projects/gateway/pkg/syncer/translator_syncer.go
- projects/gateway/pkg/syncer/translator_syncer_integration_test.go
- projects/gateway/pkg/syncer/translator_syncer_test.go
- test/kube2e/gateway/gateway_test.go
backport of https://github.com/solo-io/gloo/commit/638755e32ee48bf98b7a63290219089689a4d766 to `v1.10.x`.
Beyond the backport, this also transfers the sorting logic implemented in https://github.com/solo-io/gloo/pull/5844/files#diff-120aa64c2663421cad34855e6614b279b92bb76b47816fb9172a4bc1e5a237a1R196-R207
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5578
resolves https://github.com/solo-io/gloo/issues/5323
> backport(fix(gateway)): allow error clearing for gateways without children

- changelog/v1.11.0-beta9/fix-helm-indentation-https-gw.yaml
- install/helm/gloo/templates/8-default-gateways.yaml
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5874
> Fix indentation for custom HTTPS Gateway settings

- changelog/v1.11.0-beta9/certgen-preupgrade.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
This new feature can be used to support upgrading Gloo with mTLS enabled if Gloo was initially installed without mTLS.
Relevant open issues:
1. https://github.com/solo-io/gloo/issues/4638
2. https://github.com/solo-io/gloo/issues/5855
Users needed this feature to so on upgrade the certgen job will run also on pre-upgrade hook if the secret doesn't exist.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4638
> Enable to add 'pre-upgrade' hook to Certgen Job

- changelog/v1.10.6/certgen-preupgrade.yaml
- changelog/v1.10.7/certgen-preupgrade.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
This was added in the 1.11 branch and is low risk and useful enough to backport to 1.10.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4638
> Backport change to allow running certgen job on upgrade

- changelog/v1.11.0-beta11/graphql-fed-cluster-reg.yaml
- projects/gloo/cli/pkg/cmd/federation/register/root.go
We need this to be able to read/list graphqlschemas when Gloo Fed is enabled.
> add graphql to fed clusterrole

- changelog/v1.11.0-beta11/glooctl-check-fix.yaml
- projects/gloo/cli/pkg/cmd/check/root.go
- projects/gloo/cli/pkg/helpers/clients.go
Prevent glooctl check from producing stackdumps by removing usages of `Must`.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5061
> Avoid stackdumps in glooctl check

- changelog/v1.10.8/glooctl-check-fix.yaml
- changelog/v1.11.0-beta11/glooctl-check-fix.yaml
- projects/gloo/cli/pkg/cmd/check/root.go
- projects/gloo/cli/pkg/helpers/clients.go
Prevent glooctl check from producing stackdumps by removing usages of Must.
v1.10.x backport of https://github.com/solo-io/gloo/pull/5907
> Avoid stackdumps in glooctl check (v1.10.x backport)

- changelog/v1.11.0-beta12/fix-regex-route-short-circuiting.yaml
- projects/gateway/pkg/translator/http_translator.go
- projects/gateway/pkg/translator/http_translator_test.go
Fix a typo that was resulting in regex route short-circuiting being reported when it shouldn't have been.
See the linked issue for context.
> fix regex route short circuiting check

- changelog/v1.10.11/docs-backport2.yaml
- docs/content/reference/support.md
Backport changes to 1.10.
See Slack: https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1646173086108269\?thread_ts\=1646172727.815669\&cid\=CEDCS8TAP
- N/A I opened a draft PR or added the work in progress label if my PR is not ready for review
> Backport doc updates to 1.10.x

- changelog/v1.11.0-beta17/disable-default-gateways.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/8-default-gateways.yaml
- install/helm/gloo/values-template.yaml
- install/test/helm_test.go
Allow users to disable the default gateways, which can be helpful for users who configure the validation webhook to strict failures (i.e. `gloo.gateway.validation.failurePolicy: Fail`) so validation works on installation and upgrades. Once the gateway pod is running and healthy, the user can then apply the default gateways.
In addition to unit tests, validated locally with the following helm values:
```yaml
cat << EOF > values.yaml
gloo:
gateway:
validation:
allowWarnings: false
alwaysAcceptResources: false
failurePolicy: Fail
gatewayProxies:
gatewayProxy:
gatewaySettings:
enabled: false
EOF
```
then build a new chart with `TAGGED_VERSION=v1.9.0 make build-test-chart -B` and validate the installation is successful via `glooctl install gateway --values values.yaml -f _test/gloo-1.9.0.tgz` …
> Make default gateways disable-able

- install/helm/README.md
Broken link in README updated - points to docs for installation options.
Reading about the Helm Chart.
https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
(❓~Is this required for docs changes?~ Thanks changelog-bot ✅)
> Update broken link to Gloo Edge installation opts

- Makefile
- changelog/v1.11.0-beta18/improve-release-times.yaml
Disable tests on release builds to improve ci times and reliability
> Disable tests on release builds to improve ci times and reliability

- Makefile
- changelog/v1.10.13/improve-ci-releases-times.yaml
backport of https://github.com/solo-io/gloo/pull/6030
> Run tests releases only 1.10

- Makefile
- changelog/v1.8.26/improve-ci-times.yaml
backport of https://github.com/solo-io/gloo/pull/6030
> Run tests releases only 1.8

- Makefile
- changelog/v1.9.10/improve-ci-release-times.yaml
backport of https://github.com/solo-io/gloo/pull/6030
> Run tests releases only 1.9

- changelog/v1.11.0-beta18/helm-fix-discovery-service.yaml
- install/helm/gloo/templates/3-discovery-service.yaml
Fix indent in helm template
The issue was introduced in https://github.com/solo-io/gloo/pull/6001
> Fix indent in discovery service template

- .github/workflows/notify-on-regression-failure-list.json
- .github/workflows/regression-tests.yaml
- changelog/v1.10.14/notify-on-failure.yaml
* ci(regression-tests): added opt-in slack notify-on-failure step
* enabled bewebi
* enabled ben-taussig-solo, kdorosh
* enabled inFocus7, mkazin
* enabled elcasteel
* enabled `sam-heilbron`
> ci(regression-tests): added opt-in slack notify-on-failure step (#6024)

- changelog/v1.11.0-beta19/docker-compose-repair.yaml
- install/docker-compose-file/prepare-directories.sh
Modified the filesystem prep script referenced in [this guide](https://docs.solo.io/gloo-edge/master/installation/gateway/development/docker-compose-file/).  It stopped being functional after `v1.10.7`, as it expects a `config/httpgateways/gloo-system` directory to exist.  This allows the `gateway` container to spin up correctly
> feat(docker-compose) add missing setup directory

- Makefile
- changelog/v1.11.0-beta19/bump-envoy.yaml
- changelog/v1.11.0-beta20/bump-envoy.yaml
Bump envoy-gloo to support aws sts fixes.
Intermittent 403s in aws sts filter was tracked down to race condition with upstream functionality working as expected. This envoy-gloo version has a workaround.
> makefile: Upgrade envoy-gloo version for aws fixes

- Makefile
- changelog/v1.10.17/docker-compose-repair.yaml
- install/docker-compose-file/docker-compose.yaml
- install/docker-compose-file/prepare-directories.sh
* bump envoy version
* repair missing setup directory to docker-compose script
related https://github.com/solo-io/gloo/issues/5980
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5980
> 10/feat(docker-compose): repair docker-compose launch script

- changelog/v1.11.0-beta21/fix-annotation-config-merge-annotation.yaml
- docs/content/guides/traffic_management/destination_types/discovered_upstream/discovered-upstream-configuration.md
- projects/gloo/pkg/plugins/kubernetes/serviceconverter/general_annotation_converter.go
Pr #6036 introduces the ability to deep merge discovered upstream config provided via annotation with default upstream configuration. [The annotation used to enable the feature in the initial implementation](https://github.com/solo-io/gloo/pull/6036/files#diff-d5cb4efdfb5e21818b5d7ddb469244d2bf54dba8a791263f3c1adc54c4f7ca61R15) is not a valid k8s annotation (only 1 `/` is allowed). This PR changes the name of the annotation from  `gloo.solo.io/upstream_config/deep_merge` to `gloo.solo.io/upstream_config.deep_merge`, allowing users to configure this feature in the way that the PR initially intended.
Specifically, attempting to apply the service below resulted in the following error:
```
apiVersion: v1
kind: Service
metadata:
name: httpbin
labels:
app: httpbin
annotations: …
```
> Rename DeepMergeAnnotationPrefix to be a valid Annotation

- .github/workflows/trivy-analysis-scheduled.yaml
setup-gcloud will be updating the branch name from master to main in
a future release. Even though GitHub will establish redirects, this
will break any GitHub Actions workflows that pin to master. This PR
updates your GitHub Actions workflows to pin to v0, which is the
recommended best practice.
> Pin setup-gcloud to v0 instead of master

- docs/content/guides/security/auth/extauth/opa/_index.md
* Fix the comparison operators in OPA document [here](https://docs.solo.io/gloo-edge/master/guides/security/auth/extauth/opa).
* Remove an obsolete version reference.
> OPA fix comparison operators and remove obsolete version reference

- changelog/v1.10.18/initialize-valid-config-metric.yaml
- projects/gateway/pkg/validation/validator.go
- projects/gateway/pkg/validation/validator_test.go
v1.10.x backport of https://github.com/solo-io/gloo/pull/6132
Initialize the `validation_gateway_solo_io_valid_config` metric when the gateway pod starts up.
`validation_gateway_solo_io_valid_config` will not appear on the gateway pod's `/metrics` endpoint until a value is assigned to it. This PR initializes the metric based on the first snapshot that the gateway pod receives after starting. Previously, the metric would not have been initialized until a resource was applied and validated by the webhook.
> (v1.10.x) Initialize the validation_gateway_solo_io_valid_config metric

- changelog/v1.8.27/initialize-valid-config-metric.yaml
- projects/gateway/pkg/validation/validator.go
- projects/gateway/pkg/validation/validator_test.go
v1.8.x backport of https://github.com/solo-io/gloo/pull/6132
Initialize the `validation_gateway_solo_io_valid_config` metric when the gateway pod starts up.
`validation_gateway_solo_io_valid_config` will not appear on the gateway pod's `/metrics` endpoint until a value is assigned to it. This PR initializes the metric based on the first snapshot that the gateway pod receives after starting. Previously, the metric would not have been initialized until a resource was applied and validated by the webhook.
> (v1.8.x) Initialize the validation_gateway_solo_io_valid_config metric

- changelog/v1.11.0-rc2/initialize-valid-config-metric.yaml
- changelog/v1.9.11/initialize-valid-config-metric.yaml
- projects/gateway/pkg/validation/validator.go
- projects/gateway/pkg/validation/validator_test.go
v1.9.x backport of https://github.com/solo-io/gloo/pull/6132
Initialize the `validation_gateway_solo_io_valid_config` metric when the gateway pod starts up.
`validation_gateway_solo_io_valid_config` will not appear on the gateway pod's `/metrics` endpoint until a value is assigned to it. This PR initializes the metric based on the first snapshot that the gateway pod receives after starting. Previously, the metric would not have been initialized until a resource was applied and validated by the webhook.
> (v1.9.x) Initialize the validation_gateway_solo_io_valid_config metric

- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/test/helm_test.go
Include app=gloo label on all services and deployments
The dynamically generated dashboards for the upstreams has app=gloo defined for some panels. Without this label, the metrics will not appear properly on the dashboard.
Slack context: https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1648154147487449
> Include app=gloo label on gateway proxy services

- changelog/v1.10.18/less-strict-ssl-validation.yaml
- projects/gloo/pkg/utils/ssl.go
- projects/gloo/pkg/utils/ssl_test.go
related https://github.com/solo-io/gloo/issues/6021
Avoid validating `certChain` and `privateKey` when _only_ a `rootCa` is present
Per [Gloo's Upstream TLS docs](https://docs.solo.io/gloo-edge/latest/guides/security/tls/client_tls/#trusted-mode), users should be able to provide _only_ a rootCa file (as in `glooctl create secret tls --rootca=...`).  However, the [current validation method](https://github.com/solo-io/gloo/commit/ee2e1115631e36a6b6136101f5d330dde810be74) in `ResolveCommonSslConfig` is overly restrictive, enforcing `tls.X509KeyPair` checks against empty files, even if said empty files aren't meant to be used.
> 10/fix(ssl.go): prevent isValidSslKeyPair with only rootCa

- changelog/v1.11.0-rc3/less-strict-ssl-validation.yaml
- projects/gloo/pkg/utils/ssl.go
- projects/gloo/pkg/utils/ssl_test.go
related https://github.com/solo-io/gloo/issues/6021
Avoid validating `certChain` and `privateKey` when _only_ a `rootCa` is present
Per [Gloo's Upstream TLS docs](https://docs.solo.io/gloo-edge/latest/guides/security/tls/client_tls/#trusted-mode), users should be able to provide _only_ a rootCa file (as in `glooctl create secret tls --rootca=...`).  However, the [current validation method](https://github.com/solo-io/gloo/commit/ee2e1115631e36a6b6136101f5d330dde810be74) in `ResolveCommonSslConfig` is overly restrictive, enforcing `tls.X509KeyPair` checks against empty files, even if said empty files aren't meant to be used.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6021
> master/fix(ssl.go): prevent isValidSslKeyPair with only rootCa

- CONTRIBUTING.md
Updating CONTRIBUTING.md.
- Updated the label shown for work-in-progress tickets to `work in progress`.
- Removed `make update-deps` from the "Useful make commands" subsection, since it's been removed/replaced since [this commit](https://github.com/solo-io/gloo/commit/f2f718dd8e30c740b46a0fca1feecd584264a79e)
- Might worth to instead replace with `make install-go-tools`.
- Updated `make build-kind-chart` from the "Useful make commands" subsection, since it's been removed since [this commit](https://github.com/solo-io/gloo/commit/5fc8480eba37446516c8f291c2d66c840fc96724). It's now `make build-test-chart`
While starting to work in contributions these small nits threw me off a bit, so best to keep them updated for any future contributor.
> Small CONTRIBUTING.md updates to better match Gloo's current state

- changelog/v1.11.0-rc5/docs-debug.yaml
- docs/Makefile
(temporary) github action update to docs gen.  Debugging `cat` to trace security-scan generation issue
> CI(docs): cat out security utils file

- changelog/v1.11.0-rc7/regex-rewrite-engine.yaml
- pkg/utils/regexutils/regex.go
- pkg/utils/regexutils/regex_test.go
We have documents showing how to setup regex rewrites without requiring engine.
We stopped allowing this behavior but will once more respect this.
It makes sense to not require the engine as envoy has moved away from interacting with the engine (only field on it is now deprecated). It does raise questions as to whether there needs to be more regex validation on the control plane prior to translation but this minimally fixes the issue seen in 1.11.0-rc5/rc6 of gloo
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5448
> utils/regexutils: Re-allow nil engine types in regex.

- changelog/v1.12.0-beta1/helm-fix-discovery-empty-subjects.yaml
- install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
Corrects syntax of empty `subjects` array in helm chart when two role bindings' only subject is `discovery` which is removed due to Discovery being disabled
This change does not manifest in existing unit tests for this issue and is not testable. Debugging the Golang unit test showed the `makeRoleBindingFromUnstructured(resource).Subjects` field contains an empty array both before and after the change.
For the following manual tests I used a policy file named `values-discovery_disabled.yaml` which disables discovery as follows:
```
gloo:
deployment:
image:
repository: gloo
tag: $VERSION
gatewayProxies:
gatewayProxy:
service:
type: NodePort
httpPort: 31500
httpsPort: 32500
httpNodePort: 31500
httpsNodePort: 32500
discovery:
enabled: false
global:
image:
registry: $IMAGE_REPO
pullPolicy: …
```
> Disabled discovery empty subjects fix

- changelog/v1.10.20/helm-fix-discovery-empty-subjects.yaml
- install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
* Adding else clause in case discovery is disabled, because it fails if not empty list.
* Follow-up to contribution by vladimir-cmd
- add else statement to a second empty subjects array
- add changelog
Co-authored-by: Vladimir Bundalo <vbundalo@repay.com>
> [1.10.x] Disabled discovery empty subjects fix (#6249)

- changelog/v1.11.1/helm-fix-discovery-empty-subjects.yaml
- install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
* Adding else clause in case discovery is disabled, because it fails if not empty list.
* Follow-up to contribution by vladimir-cmd
- add else statement to a second empty subjects array
- add changelog
Co-authored-by: Vladimir Bundalo <vbundalo@repay.com>
> [1.11.x] Disabled discovery empty subjects fix (#6249)

- changelog/v1.12.0-beta2/glooctl-upgrade-windows-fix.yaml
- projects/gloo/cli/pkg/cmd/upgrade/cmd.go
fix issue with glooctl upgrade on windows not finding assets
Fixes https://github.com/solo-io/gloo/issues/6255
> fix issue with glooctl upgrade on windows

- changelog/v1.12.0-beta2/robust-client-panic.yaml
- projects/gateway/pkg/validation/robust_client.go
- projects/gateway/pkg/validation/robust_client_test.go
Ensure that the gateway validation client is never set to nil
We encountered this bug in tests that would occasionally panic, however the bug itself could impact customers
I wrote a test first, and add that as the first commit. If you checkout just that test (no other changes) it will panic in the way that we noticed in some e2e tests. If you then checkout my fix and re-run the same test, it will pass.
I believe this issue arises because we have a local variable for clientReinstantiateError and a class variable for constructorClient. This means that we can ensure that on a clientReinstantiateError we do not retry, but we do set the client to nil which could be picked up on the subsequent request.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6237
> Resolve panic in gateway validation client

- changelog/v1.12.0-beta3/setup-syncer-data-race.yaml
- test/kube2e/gloo/setup_syncer_test.go
Resolve a data race that occurs in our setup syncer test
I think this data race is due to our tests and not due to our implementation. Per https://github.com/kubernetes/kubernetes/pull/89019#issuecomment-600278461, we do setup schemes at construction time, as we should. Moreover, this flake has only occurred in this specific test. If this were a bug in our Gloo code, I would have expected to see it fail in other tests.
> Resolve data race in setup syncer test

- .github/workflows/README.md
I added a reminder about not merging solo-apis PRs to the readme in github actions. We were discussing this in slack and this readme seems like a good place to ensure it is found in the future.
> Add line about draft PRs to github actions readme

- changelog/v1.12.0-beta4/gzip-early.yaml
- projects/gloo/pkg/plugins/gzip/plugin.go
- projects/gloo/pkg/plugins/gzip/plugin_test.go
Currently, the gzip compression filter runs before the transformation filter on the response path (gzip does not run on the request path). This can result in corrupt data when the transformation filter modifies the gzip blob. To fix this, we now run gzip after transformation on the response path. This means that we need to configure gzip to run *before* transformation on the request path (even though gzip isn't actually used on the request path). Since the earliest stage that the transformation filter can run is the [stage after the FaultStage](https://github.com/solo-io/gloo/blob/081423f6837f7c6ad4be4ac8f4eaf5e98b074beb/projects/gloo/pkg/plugins/transformation/plugin.go#L44), gzip needs to run during the FaultStage.
> Run gzip compression after transformation

- changelog/v1.10.21/doc-fix-links.yaml
- docs/content/guides/graphql/getting_started.md
Backport of https://github.com/solo-io/gloo/pull/6323/files
> Backport: Docs: Fix GraphQL links 1.10.x

- changelog/v1.12.0-beta5/fix-proxy-deployment-override.yaml
- changelog/v1.12.0-beta6/fix-proxy-deployment-override.yaml
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/test/helm_test.go
This change fixes a helm template so the envoySidecarResources value is used when generating the gateway proxy deployment.
The Helm template had been incorrectly using sdsResources.
> Fixed template to correctly use envoySidecarResources for istio-proxy

- changelog/v1.12.0-beta7/docs-link-fix.yaml
- docs/content/installation/gateway/kubernetes/_index.md
On the latest Firefox the link for "Helm Chart Hooks" goes to `https://helm.sh/docs/topics/charts_hooks/),` with the parenthesis and comma at the end. This should resolve that as well as make the format more in-line with the rest of the page.
https://docs.solo.io/gloo-edge/latest/installation/gateway/kubernetes/#installing-gloo-edge-on-kubernetes
Affects Chrome 102, Firefox 100, and Edge 100. This closes #6372.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6372
> Use link syntax to avoid ambiguous linking behavior

- changelog/v1.12.0-beta8/fix-certgen-upgrade.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/test/helm_test.go
- jobs/pkg/kube/secret.go
- jobs/pkg/kube/secret_test.go
- jobs/pkg/run/run.go
- test/kube2e/knative/knative_manual_tls_test.go
- Make sure the gateway certgen job runs on upgrade, since we now reinstall the validation webhook on upgrade and it needs the caBundle field to be populated by the certgen job.
- Fix a bug in the certgen job where if we don't create a new Secret (because the existing one is still valid), we were still setting a newly generated caBundle on the validation webhook (which was not attached to any persisted secret)
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6384
> Fix certgen upgrade

- changelog/v1.12.0-beta9/fix-translator-syncer-flake.yaml
- projects/gateway/pkg/syncer/translator_syncer_test.go
Revert a previous change that removed the Eventually when waiting for status to update
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6388
> fix translator syncer test flake

- changelog/v1.12.0-beta9/staged-transformation-flake.yaml
- test/e2e/staged_transformation_test.go
The test sets up an upstream and some additional configuration and expects to get a 403 when all the config is propagated. The previous readiness check also succeeded on 503 which would sometimes happen before the config was finished propagating (I think as a result of config from a previous test). In this change the test looks for a 403. 
Running with `untilItFails` locally, it would fail after <7 runs before the fix and did not fail after 15 runs after the fix.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6356
> Test flake fixes

- changelog/v1.12.0-beta10/remove-cors-default-filter.yaml
- changelog/v1.12.0-beta10/unused-filters-followup.yaml
- projects/gateway/pkg/utils/metrics/metrics.go
- projects/gloo/cli/pkg/cmd/install/util.go
- projects/gloo/pkg/plugins/cors/plugin.go
- projects/gloo/pkg/plugins/csrf/plugin.go
- projects/gloo/pkg/plugins/csrf/plugin_test.go
- projects/gloo/pkg/plugins/faultinjection/plugin.go
- projects/gloo/pkg/plugins/grpcweb/plugin.go
- projects/gloo/pkg/plugins/registry/registry_test.go
- projects/gloo/pkg/plugins/transformation/plugin.go
- CORS filter respects the `removeUnusedFilters` setting
- GrpcWeb filter respects the `removeUnusedFilters` setting
- `removeUnusedFilters` setting applied per HttpListener, instead of globally per plugin
As part of [some previous work](https://github.com/solo-io/gloo/issues/5651), we enable the ability to not load empty http filters into the filter chain. This behavior is opt-in, using the `removeUnusedFilters` flag in the Settings CR. We extended this work to apply the behavior to the CORS filter as well.
The GrpcWeb filter has a per HttpListener configuration. If that config is true, the filter is generated. If that config is not present, we fallback to a Settings `disableGrpcWeb`. This setting, if it wasn't defined would fallback to false. I changed the fallback to instead respect …
> RemoveUnusedFilters evaluated per HttpListener

- changelog/v1.12.0-beta11/fix-cleanup-job.yaml
- docs/content/guides/dev/example-proxy-controller.md
- install/helm/gloo/templates/5-gateway-cleanup-job.yaml
- install/helm/gloo/templates/_helpers.tpl
- install/test/helm_test.go
- projects/gloo/pkg/syncer/setup/proxy_cleanup.go
- projects/gloo/pkg/syncer/setup/proxy_cleanup_test.go
- test/kube2e/helm/helm_test.go
- Fix missing permissions and syntax error in the Job that cleans up custom resources during helm uninstall.
- Rename `created-by` to `created_by` for consistency, as we already use `created_by` elsewhere in code.
> fix cleanup job

- changelog/v1.12.0-beta12/robustness_test_fix.yaml
- test/kube2e/gateway/robustness_test.go
In the robustness test, wrap creating a new virtual service in `Eventually`. We already have a check to see that all the old virtual services have been deleted but we don't confirm that the Proxy has been updated. I think an `Eventually` here will help ensure that we've reached a consistent state before adding a new Virtual Service.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6430
> Fix for robustness test flake

- changelog/v1.12.0-beta13/istio-ip-routing.yaml
- install/helm/gloo/templates/1-gloo-deployment.yaml
- projects/gloo/pkg/plugins/kubernetes/eds.go
- projects/gloo/pkg/plugins/kubernetes/eds_test.go
This change includes support for setting endpoints based on service ip addresses rather than dns names, which is required for integration with Istio.
This required breaking up a large and complicated function which was making code changes difficult. 
This is phase two of the work required to prepare Edge for full Istio integration (see s-p 3461)
It follows the work done in #6196 , utilizing the helm value established there to enable this code change.
This was tested manually by repeating the method described in the earlier work to enable injection ([see here](https://github.com/solo-io/gloo/pull/6312#issuecomment-1098467998)), along with steps [described here](https://github.com/murphye/demo-gloo-edge-istio) to generate an error from the petstore sevice when strict mTLS is enabled .
A …
> Istio compat - use kub service ip for upstreams

- changelog/v1.12.0-beta13/retries-grpc-stream.yaml
- test/e2e/access_log_test.go
> test: Try retrying on access log streaming for unready upstreams

- changelog/v1.12.0-beta13/ctl-install-error-str.yaml
- projects/gloo/cli/pkg/cmd/install/installer.go
Update glooctl install to have more consistent error messages that indicate the --file option
> gloo/cli/cmd/install: Update the error message on enterprise install

- changelog/v1.12.0-beta15/set-based-proxy-label-selection.yaml
- go.mod
- go.sum
- projects/clusteringress/pkg/translator/translator_syncer.go
- projects/gateway/pkg/reconciler/proxy_reconciler.go
- projects/gateway/pkg/reconciler/proxy_reconciler_test.go
- projects/gateway/pkg/syncer/translator_syncer.go
- projects/ingress/pkg/translator/translator_syncer.go
- test/kube2e/gateway/gateway_test.go
Reconcile proxies using labels that follow the current naming convention, and the previous naming convention.
Gloo maintains an internal CR, known as a [Proxy](https://github.com/solo-io/gloo/blob/e5df9c889c00a4756fc468432160732706554257/projects/gloo/api/v1/proxy.proto#L30). We identify these Proxies with [unique labels](https://github.com/solo-io/gloo/blob/bc380b36d42fdad7c83ab8dc4f055258b326aeac/projects/gateway/pkg/syncer/translator_syncer.go#L49). We rely on these labels to both read Proxies (to know which to reconcile) and write Proxies (to know which to reconcile on the next iteration). Recently we changed these labels on Proxies, which means that after an upgrade from a version with the old label, to a version with the new label, the Proxy controller will attempt to reconcile the …
> Reconcile Proxies using both new and old labels

- changelog/v1.10.25/set-based-proxy-label-selection.yaml
- go.mod
- go.sum
- projects/clusteringress/pkg/translator/translator_syncer.go
- projects/gateway/pkg/reconciler/proxy_reconciler.go
- projects/gateway/pkg/reconciler/proxy_reconciler_test.go
- projects/gateway/pkg/syncer/translator_syncer.go
- projects/ingress/pkg/translator/translator_syncer.go
- test/kube2e/gateway/gateway_test.go
Backport of: https://github.com/solo-io/gloo/pull/6461
Reconcile proxies using labels that follow the current naming convention, and the previous naming convention.
Gloo maintains an internal CR, known as a [Proxy](https://github.com/solo-io/gloo/blob/e5df9c889c00a4756fc468432160732706554257/projects/gloo/api/v1/proxy.proto#L30). We identify these Proxies with [unique labels](https://github.com/solo-io/gloo/blob/bc380b36d42fdad7c83ab8dc4f055258b326aeac/projects/gateway/pkg/syncer/translator_syncer.go#L49). We rely on these labels to both read Proxies (to know which to reconcile) and write Proxies (to know which to reconcile on the next iteration). Recently we changed these labels on Proxies, which means that after an upgrade from a version with the old label, to a version with the new …
> [1.10] Reconcile Proxies using both new and old labels

- changelog/v1.9.15/set-based-proxy-selection.yaml
- go.mod
- go.sum
- projects/clusteringress/pkg/translator/translator_syncer.go
- projects/gateway/pkg/reconciler/proxy_reconciler.go
- projects/gateway/pkg/reconciler/proxy_reconciler_test.go
- projects/gateway/pkg/syncer/translator_syncer.go
- projects/ingress/pkg/translator/translator_syncer.go
- test/kube2e/gateway/gateway_test.go
Backport of: https://github.com/solo-io/gloo/pull/6461
Reconcile proxies using labels that follow the current naming convention, and the previous naming convention.
Gloo maintains an internal CR, known as a [Proxy](https://github.com/solo-io/gloo/blob/e5df9c889c00a4756fc468432160732706554257/projects/gloo/api/v1/proxy.proto#L30). We identify these Proxies with [unique labels](https://github.com/solo-io/gloo/blob/bc380b36d42fdad7c83ab8dc4f055258b326aeac/projects/gateway/pkg/syncer/translator_syncer.go#L49). We rely on these labels to both read Proxies (to know which to reconcile) and write Proxies (to know which to reconcile on the next iteration). Recently we changed these labels on Proxies, which means that after an upgrade from a version with the old label, to a version with the new …
> [1.9] Reconcile Proxies using both new and old labels

- changelog/v1.12.0-beta17/docs-canary copy.yaml
- docs/content/guides/traffic_management/destination_selection/header_matching/_index.md
Adds a note about prefix matching as a requirement (and restriction that no hyphens can be in the path) when using header matchers to the header matcher doc.
Users ran into this bug when trying to apply header matchers in a virtual service without a prefix matcher, and then again when they specified a `-` in the prefix matcher  path.
> Docs: Add note about prefix matching to header matcher doc

- changelog/v1.10.26/doc-backport.yaml
- docs/content/guides/observability/tracing.md
- docs/content/operations/upgrading/1.10.0.md
- docs/content/operations/upgrading/canary.md
Backports tracing and canary CRD upgrade docs.
- N/A I opened a draft PR or added the work in progress label if my PR is not ready for review
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5466
resolves https://github.com/solo-io/gloo/pull/6502
> Doc backport to 1.10.x

- changelog/v1.11.13/doc-backport.yaml
- docs/content/guides/observability/tracing.md
- docs/content/operations/upgrading/canary.md
- docs/content/operations/upgrading/v1.10.md
- docs/content/operations/upgrading/v1.11.md
Backports tracing and canary CRD upgrade docs.
- N/A I opened a draft PR or added the work in progress label if my PR is not ready for review
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5466
resolves https://github.com/solo-io/gloo/pull/6502
> Doc backport to 1.11.x

- changelog/v1.12.0-beta17/custom-proxy-namespace.yaml
- docs/content/reference/values.txt
- install/helm/gloo/generate/values.go
- install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
- install/helm/gloo/templates/8-default-gateways.yaml
- install/helm/gloo/templates/8-gateway-proxy-horizontal-pod-autoscaler.yaml
- install/helm/gloo/templates/8-gateway-proxy-pod-disruption-budget.yaml
- install/helm/gloo/templates/8-gateway-proxy-service-account.yaml
- install/helm/gloo/templates/8-gateway-proxy-service.yaml
- install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
- install/test/fixtures.go
- install/test/fixtures/envoy_config/bootstrap_extensions.yaml
- install/test/fixtures/envoy_config/custom_static_bootstrap.yaml
- install/test/fixtures/envoy_config/overload_manager.yaml
- install/test/fixtures/envoy_config/static_clusters.yaml
- test/kube2e/helm/helm_test.go
Allows setting the namespace of amy named proxy (gatewayProxies.NAME) using a new 
Draft notes:
* This change does not create any of the specified non-control-plane namespaces. These must  be created manually.
This change allows Gloo Edge to be deployed in a more customized configuration. This is required when integrating proxies into Gloo Mesh Workspaces which use namespaces for isolation.
Testing was done manually, verifying that XDS configuration reached proxies in both gloo-system and a custom  namespace.
Configuration used in testing (based on the [multi-gw deployment guide](https://github.com/solo-io/gloo/blob/master/docs/content/installation/advanced_configuration/multi-gw-deployment.md))
```
gatewayProxies:
publicGw: # Proxy name for public access (Internet facing)
disabled: false …
```
> Install gateway-proxy in separate namespace from Gloo Edge Control Plane

- .github/workflows/issue_board.yaml
The action that we're using is expecting one string with a comma separated list embedded in it rather than a list of strings.
> Pass issue labels as a single string

- changelog/v1.12.0-beta24/helm-certgen-hooks.yaml
- install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
- install/test/helm_test.go
After enabling cergen pre-upgrade,  the serviceaccount,clusterrole and clusterrolebinding might be missing if originally installed prior to v1.5.1 so it should be created when upgrading as well.
https://github.com/solo-io/gloo/issues/6578
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6578
> pre-upgrade helm hook for certgen rbac resources

- changelog/v1.11.16/gloo-fed-panic.yaml
- install/test/helm_suite_test.go
- projects/gloo/cli/pkg/cmd/check/root.go
- projects/gloo/cli/pkg/cmd/federation/register/register.go
- projects/gloo/cli/pkg/cmd/install/helm_client.go
- projects/gloo/cli/pkg/cmd/install/installer.go
- projects/gloo/cli/pkg/cmd/install/installer_test.go
- projects/gloo/cli/pkg/cmd/install/mocks/mock_helm_client.go
- projects/gloo/cli/pkg/cmd/version/clients.go
- projects/gloo/cli/pkg/cmd/version/cmd.go
- projects/gloo/cli/pkg/prerun/version_warning.go
- test/kube2e/helm/helm_test.go
* fix(glooctl): apply CRDs to cluster prior to register
* install CRDs IFF not found on remote
* attempt to _exactly_ preserve earlier NewKube.Get functionality
* repaired badly copy/pasted error message
* lowercased error messages
> 11 | fix(glooctl): apply CRDs to cluster prior to register (#6565)

- changelog/v1.9.17/gloo-fed-panic.yaml
- install/test/helm_suite_test.go
- projects/gloo/cli/pkg/cmd/federation/register/register.go
- projects/gloo/cli/pkg/cmd/install/helm_client.go
- projects/gloo/cli/pkg/cmd/install/installer.go
- projects/gloo/cli/pkg/cmd/install/installer_test.go
- projects/gloo/cli/pkg/cmd/install/mocks/mock_helm_client.go
- projects/gloo/cli/pkg/cmd/version/clients.go
- projects/gloo/cli/pkg/cmd/version/cmd.go
- projects/gloo/cli/pkg/prerun/version_warning.go
- test/kube2e/helm/helm_test.go
* fix(glooctl): apply CRDs to cluster prior to register
* install CRDs IFF not found on remote
* attempt to _exactly_ preserve earlier NewKube.Get functionality
* repaired badly copy/pasted error message
* lowercased error messages
> 9 | fix(glooctl): apply CRDs to cluster prior to register (#6565)

- changelog/v1.10.28/gloo-fed-panic.yaml
- install/test/helm_suite_test.go
- projects/gloo/cli/pkg/cmd/federation/register/register.go
- projects/gloo/cli/pkg/cmd/install/helm_client.go
- projects/gloo/cli/pkg/cmd/install/installer.go
- projects/gloo/cli/pkg/cmd/install/installer_test.go
- projects/gloo/cli/pkg/cmd/install/mocks/mock_helm_client.go
- projects/gloo/cli/pkg/cmd/version/clients.go
- projects/gloo/cli/pkg/cmd/version/cmd.go
- projects/gloo/cli/pkg/prerun/version_warning.go
- test/kube2e/helm/helm_test.go
* fix(glooctl): apply CRDs to cluster prior to register
* install CRDs IFF not found on remote
* attempt to _exactly_ preserve earlier NewKube.Get functionality
* repaired badly copy/pasted error message
* lowercased error messages
> 10 | fix(glooctl): apply CRDs to cluster prior to register (#6565)

- changelog/v1.11.16/add-v3-clusters.yaml
- go.mod
- go.sum
Adding V3 clusters
[passing tests](https://github.com/solo-io/gloo/pull/6595)
V3 clusters need to be ordered in Envoy requests.
> V3 clusters

- changelog/v1.8.30/ordering-of-envoy-requests.yaml
- go.mod
- go.sum
- projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/ext_auth_discovery_service_xds.sk.go
- projects/gloo/pkg/api/v1/enterprise/rate_limit_discovery_service_xds.sk.go
- projects/gloo/pkg/syncer/envoy_translator_syncer.go
- projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer.go
- projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer_test.go
- projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer.go
- projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer_test.go
- projects/gloo/pkg/syncer/setup/setup_syncer.go
- projects/gloo/pkg/syncer/translator_syncer_test.go
- projects/gloo/pkg/translator/translator_test.go
- projects/gloo/pkg/xds/envoy_server_v3.go
- projects/gloo/pkg/xds/envoy_snapshot.go
- projects/gloo/pkg/xds/envoy_snapshot_test.go
- projects/gloo/pkg/xds/gloo_xds_server.go
Add Envoy Ordering
Rotating secrets on Gloo Upstreams causes `no healthy upstream` response from Envoy.
> v1.8.x-Envoy ordering

- changelog/v1.11.17/grpcmaxvalidationbyte-refresh.yaml
- projects/gloo/pkg/syncer/setup/setup_syncer.go
- test/kube2e/gloo/setup_syncer_test.go
On settings update we check if grpc servers need a kick
Right now we only do it if the addr changes but we also need to set anything else that is passed in as a grpc opt. In this case the validation bytes.
Users were confused when the settings change was not reflected in the validation server's behavior
> [1.11] setup/settings: Update to allow for validationServerGrpcMaxSizeBytes to take effect without manual kick
